(define-module (crates-io mp ar mpart-async) #:use-module (crates-io))

(define-public crate-mpart-async-0.1.0 (c (n "mpart-async") (v "0.1.0") (d (list (d (n "bytes") (r "^0.4.6") (d #t) (k 0)) (d (n "failure") (r "^0.1.1") (d #t) (k 0)) (d (n "futures") (r "^0.1.21") (d #t) (k 0)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "rand") (r "^0.4") (d #t) (k 0)))) (h "03kzwc0hw77j0xki672823apbr45mffh85fxcphc6w1k8c17ggaf")))

(define-public crate-mpart-async-0.2.0 (c (n "mpart-async") (v "0.2.0") (d (list (d (n "bytes") (r "^0.4.6") (d #t) (k 0)) (d (n "failure") (r "^0.1.1") (d #t) (k 0)) (d (n "futures") (r "^0.1.21") (d #t) (k 0)) (d (n "hyper") (r "^0.12") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "rand") (r "^0.5") (d #t) (k 0)) (d (n "tokio") (r "^0.1.11") (o #t) (d #t) (k 0)) (d (n "tokio") (r "^0.1.11") (d #t) (k 2)))) (h "0q77kfqbcp7rpfhf0840rdb5b2rmxyrrrhqb3ykg3l9fljcgbgqg") (f (quote (("filestream" "tokio") ("default" "filestream"))))))

(define-public crate-mpart-async-0.2.1 (c (n "mpart-async") (v "0.2.1") (d (list (d (n "bytes") (r "^0.4.6") (d #t) (k 0)) (d (n "failure") (r "^0.1.1") (d #t) (k 0)) (d (n "futures") (r "^0.1.21") (d #t) (k 0)) (d (n "hyper") (r "^0.12") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "rand") (r "^0.5") (d #t) (k 0)) (d (n "tokio") (r "^0.1.11") (d #t) (k 2)) (d (n "tokio-codec") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "tokio-fs") (r "^0.1.3") (o #t) (d #t) (k 0)))) (h "1l4wwbqwkkyzjlyklpm9mxh48g5axvhfzfkfd3a79niml8v9rz5m") (f (quote (("filestream" "tokio-codec" "tokio-fs") ("default" "filestream"))))))

(define-public crate-mpart-async-0.3.0 (c (n "mpart-async") (v "0.3.0") (d (list (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "failure") (r "^0.1.1") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "hyper") (r "^0.13") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "tokio") (r "^0.2.10") (f (quote ("fs" "rt-threaded" "macros" "stream"))) (o #t) (d #t) (k 0)) (d (n "tokio-util") (r "^0.2") (f (quote ("codec"))) (o #t) (d #t) (k 0)))) (h "1h6phl3w8bhsf6k6cc5h63ifqgn56zarsxni230acwfa3az0vn2z") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.4.0 (c (n "mpart-async") (v "0.4.0") (d (list (d (n "anyhow") (r "^1.0.26") (d #t) (k 0)) (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^0.2.0") (d #t) (k 0)) (d (n "httparse") (r "^1.3.4") (d #t) (k 0)) (d (n "hyper") (r "^0.13") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2.10") (f (quote ("fs" "rt-threaded" "macros" "stream"))) (o #t) (d #t) (k 0)) (d (n "tokio-util") (r "^0.2") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "twoway") (r "^0.2.1") (d #t) (k 0)) (d (n "warp") (r "^0.2.2") (d #t) (k 2)))) (h "127bpahpc6kzvrzbf0df0wnnbb02b738fabvls0q33fh5xwmajr0") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.4.1 (c (n "mpart-async") (v "0.4.1") (d (list (d (n "anyhow") (r "^1.0.26") (d #t) (k 0)) (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^0.2.0") (d #t) (k 0)) (d (n "httparse") (r "^1.3.4") (d #t) (k 0)) (d (n "hyper") (r "^0.13") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2.10") (f (quote ("fs" "rt-threaded" "macros" "stream"))) (o #t) (d #t) (k 0)) (d (n "tokio-util") (r "^0.2") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "twoway") (r "^0.2.1") (d #t) (k 0)) (d (n "warp") (r "^0.2.2") (d #t) (k 2)))) (h "03wx0lm1l46ah7l0cyvs99c8xqrfmlg3055kcjisxnkzm3xqycza") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.4.2 (c (n "mpart-async") (v "0.4.2") (d (list (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "futures-core") (r "^0.3") (d #t) (k 0)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^0.2.0") (d #t) (k 0)) (d (n "httparse") (r "^1.3.4") (d #t) (k 0)) (d (n "hyper") (r "^0.13") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "pin-project") (r "^0.4.22") (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 2)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2") (f (quote ("fs" "stream"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^0.2") (f (quote ("rt-threaded" "macros"))) (d #t) (k 2)) (d (n "tokio-util") (r "^0.3") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "twoway") (r "^0.2.1") (d #t) (k 0)) (d (n "warp") (r "^0.2.2") (d #t) (k 2)))) (h "1kk8b1v4sjy8jgqprib29jzq11vjy0zzy34r9gx350andcpv61sy") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.5.0 (c (n "mpart-async") (v "0.5.0") (d (list (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "futures-core") (r "^0.3") (d #t) (k 0)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^0.2.0") (d #t) (k 0)) (d (n "httparse") (r "^1.3.4") (d #t) (k 0)) (d (n "hyper") (r "^0.14") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "pin-project") (r "^1.0") (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 2)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("fs"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("rt-multi-thread" "macros"))) (d #t) (k 2)) (d (n "tokio-stream") (r "^0.1") (d #t) (k 2)) (d (n "tokio-util") (r "^0.6") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "twoway") (r "^0.2.1") (d #t) (k 0)) (d (n "warp") (r "^0.3") (d #t) (k 2)))) (h "0rxllv62x3n4gxzv3qymc8g89cawcc18jq91lvkcffc4gpm2znvp") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.6.0 (c (n "mpart-async") (v "0.6.0") (d (list (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "futures-core") (r "^0.3") (d #t) (k 0)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^0.2.0") (d #t) (k 0)) (d (n "httparse") (r "^1.6.0") (d #t) (k 0)) (d (n "hyper") (r "^0.14") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "memchr") (r "^2.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "percent-encoding") (r "^2.1.0") (d #t) (k 0)) (d (n "pin-project-lite") (r "^0.2") (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 2)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("fs"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("rt-multi-thread" "macros"))) (d #t) (k 2)) (d (n "tokio-stream") (r "^0.1") (d #t) (k 2)) (d (n "tokio-util") (r "^0.6") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "warp") (r "^0.3") (d #t) (k 2)))) (h "1z5ffwi1nvmwl5p4zly1cs24vrbw0prs1w2fj65fbvwcy9mbcvlk") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.6.1 (c (n "mpart-async") (v "0.6.1") (d (list (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "futures-core") (r "^0.3") (d #t) (k 0)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^0.2.0") (d #t) (k 0)) (d (n "httparse") (r "^1.6.0") (d #t) (k 0)) (d (n "hyper") (r "^0.14") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "memchr") (r "^2.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "percent-encoding") (r "^2.1.0") (d #t) (k 0)) (d (n "pin-project-lite") (r "^0.2") (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 2)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("fs"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("rt-multi-thread" "macros"))) (d #t) (k 2)) (d (n "tokio-stream") (r "^0.1") (d #t) (k 2)) (d (n "tokio-util") (r "^0.6") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "warp") (r "^0.3") (d #t) (k 2)))) (h "0r0qb71nmywfywbyra9fhyxjlbsqcxdcx9bvpl0j8pflb4isp9ky") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

(define-public crate-mpart-async-0.7.0 (c (n "mpart-async") (v "0.7.0") (d (list (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "futures-core") (r "^0.3") (d #t) (k 0)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "headers") (r "^0.3.2") (d #t) (k 2)) (d (n "http") (r "^1.0.0") (d #t) (k 0)) (d (n "httparse") (r "^1.6.0") (d #t) (k 0)) (d (n "hyper") (r "^0.14") (d #t) (k 2)) (d (n "log") (r "^0.4.1") (d #t) (k 0)) (d (n "memchr") (r "^2.4.1") (d #t) (k 0)) (d (n "mime") (r "^0.3.16") (d #t) (k 2)) (d (n "mime_guess") (r "^2.0.1") (o #t) (d #t) (k 0)) (d (n "percent-encoding") (r "^2.1.0") (d #t) (k 0)) (d (n "pin-project-lite") (r "^0.2") (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 2)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("fs"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("rt-multi-thread" "macros"))) (d #t) (k 2)) (d (n "tokio-stream") (r "^0.1") (d #t) (k 2)) (d (n "tokio-util") (r "^0.7.8") (f (quote ("codec"))) (o #t) (d #t) (k 0)) (d (n "warp") (r "^0.3") (d #t) (k 2)))) (h "16qdskidpswx7ddmabvvn9dnnhf58b61kzvdqr75sp1jcf6fpggr") (f (quote (("filestream" "tokio" "tokio-util" "mime_guess") ("default" "filestream"))))))

