(define-module (crates-io ru st rust-cli-pomodoro) #:use-module (crates-io))

(define-public crate-rust-cli-pomodoro-1.0.0 (c (n "rust-cli-pomodoro") (v "1.0.0") (d (list (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.0") (d #t) (k 0)) (d (n "clap") (r "^2.33.3") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (d #t) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.4") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.130") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.5.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "145nrwf151rr1pzm4yhn0gb2hp9by2590grkl07fdpzp5da9x6wq") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.1.0 (c (n "rust-cli-pomodoro") (v "1.1.0") (d (list (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.0") (d #t) (k 0)) (d (n "clap") (r "^2.33.3") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (d #t) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.4") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.130") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.5.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "1cnipxx1d1ihid7pbniik7nx908xwzx8bc61mwzfiibhghw2lkc4") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.1.1 (c (n "rust-cli-pomodoro") (v "1.1.1") (d (list (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.0") (d #t) (k 0)) (d (n "clap") (r "^2.33.3") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (d #t) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.4") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.130") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.5.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "0am9ag5yh30d5bc8v8bkpp8cxwib015f8yna8wkyiz80r11rrzff") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.2.0-beta.0 (c (n "rust-cli-pomodoro") (v "1.2.0-beta.0") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.0") (d #t) (k 0)) (d (n "clap") (r "^3.1.10") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (d #t) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.4") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.137") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.5.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.18.1") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "07pgsi2k06j4pq5d2q0ggdb6wkcnr0wf19z0wwj4qwajhdd1fsdw") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.2.0 (c (n "rust-cli-pomodoro") (v "1.2.0") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.0") (d #t) (k 0)) (d (n "clap") (r "^3.1.10") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (d #t) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.4") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.137") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.5.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.18.1") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "027hvlagrqw09gyzc0yzr5y7iwk4shgcsg2n4l7a0qz1fsz7igsb") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.3.0 (c (n "rust-cli-pomodoro") (v "1.3.0") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.0") (d #t) (k 0)) (d (n "clap") (r "^3.1.10") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.4") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.137") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.5.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.18.1") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "1rw33s2fnxl3d8w25l16ihnrimhcixc9sjkzlc57xs0aj6vmiyvc") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.3.1 (c (n "rust-cli-pomodoro") (v "1.3.1") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.1") (d #t) (k 0)) (d (n "clap") (r "^3.2.8") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.0") (d #t) (k 0)) (d (n "gluesql") (r "^0.10.2") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.0") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.8") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.137") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.59") (d #t) (k 0)) (d (n "tabled") (r "^0.7.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "0827g05j1x35ps8hqd4nhhg2rdsrhf62hn56ppa2hrkmy7j09hqx") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.3.2 (c (n "rust-cli-pomodoro") (v "1.3.2") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^3.2.22") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.8.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "08lscavwiwnz0af09s5h8q8d9bvc2vy2qyqnz89ix4xs507y8h7i") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.3.3 (c (n "rust-cli-pomodoro") (v "1.3.3") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^3.2.22") (d #t) (k 0)) (d (n "clap_complete") (r "^3.2.2") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.8.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "03ybr6xw4mqmlv5jaz9khymlaa2j13qhvqlzp90jmsa0aimqb9w8") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.3.4 (c (n "rust-cli-pomodoro") (v "1.3.4") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^3.2.22") (d #t) (k 0)) (d (n "clap_complete") (r "^3.2.2") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.8.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "0lnxh834b0isxp2xqdxijrhbf4q60b27ls8c2k1nblk73w5183ml") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.4.0 (c (n "rust-cli-pomodoro") (v "1.4.0") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^4.1.10") (d #t) (k 0)) (d (n "clap_complete") (r "^4.1.5") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.10.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "15jj7r0c8axi60fxg2wc17ij7zlifracdwhxnib456an5k6x73dc") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.4.1 (c (n "rust-cli-pomodoro") (v "1.4.1") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^4.1.10") (d #t) (k 0)) (d (n "clap_complete") (r "^4.1.5") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.10.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "1xnpqxs2a63y7p45ws47nnd85x0zrhvzm3ww0mzf7i0y0jpmq3nc") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.4.2 (c (n "rust-cli-pomodoro") (v "1.4.2") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^4.1.10") (d #t) (k 0)) (d (n "clap_complete") (r "^4.1.5") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.10.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "0df5w2fbc7hghzf9rjy5n30m4ypz9gh8f8jyzs9zb1nwdlg1n675") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.4.3 (c (n "rust-cli-pomodoro") (v "1.4.3") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^4.1.10") (d #t) (k 0)) (d (n "clap_complete") (r "^4.1.5") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.10.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "0xk75lz5wr5p4qw8mjfzr6bjip2jyb906v5pxcp8sivs050yb2ai") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.4.4 (c (n "rust-cli-pomodoro") (v "1.4.4") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^4.1.10") (d #t) (k 0)) (d (n "clap_complete") (r "^4.1.5") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.10.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "0xr9m0v01j91gqa3xjyihwz7b84a202az5i8x43hlyk02zhizpnx") (r "1.59")))

(define-public crate-rust-cli-pomodoro-1.4.5 (c (n "rust-cli-pomodoro") (v "1.4.5") (d (list (d (n "bincode") (r "^2.0.0-rc.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "chrono") (r "^0.4.22") (d #t) (k 0)) (d (n "chrono-tz") (r "^0.6.3") (d #t) (k 0)) (d (n "clap") (r "^4.1.10") (d #t) (k 0)) (d (n "clap_complete") (r "^4.1.5") (d #t) (k 0)) (d (n "colored") (r "^2") (d #t) (k 0)) (d (n "env_logger") (r "^0.9.1") (d #t) (k 0)) (d (n "gluesql") (r "^0.13.1") (f (quote ("memory-storage"))) (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "notify-rust") (r "^4.5.10") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (f (quote ("json"))) (d #t) (k 0)) (d (n "rustyline") (r "^11.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.144") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.85") (d #t) (k 0)) (d (n "tabled") (r "^0.10.0") (f (quote ("color"))) (d #t) (k 0)) (d (n "tokio") (r "^1.19.2") (f (quote ("macros" "rt-multi-thread" "time" "sync"))) (d #t) (k 0)))) (h "078ydzalf4h6gc9gmrzz1cyzn8032d4965q24s56m4adb8fsra8n") (r "1.59")))

