(define-module (crates-io ru st rust-htslib) #:use-module (crates-io))

(define-public crate-rust-htslib-0.3.0 (c (n "rust-htslib") (v "0.3.0") (d (list (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "0911w497232cxcyc8353k6a9587l9lwh23shdd5mjr4jh93vmz2w")))

(define-public crate-rust-htslib-0.3.1 (c (n "rust-htslib") (v "0.3.1") (d (list (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "0x445l0fmjfz3psxsn2nc4b2f6fgzaxifv06sffhdqp1s0hrgyfg")))

(define-public crate-rust-htslib-0.4.0 (c (n "rust-htslib") (v "0.4.0") (d (list (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "0yjil7qailfg695wkd228192wk52jhbj1m6c4rh14sq4w7rhzj1x")))

(define-public crate-rust-htslib-0.4.1 (c (n "rust-htslib") (v "0.4.1") (d (list (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "1r5x3l14qgvc6bb5qf3pq7axim46d2na582jvjpkl9600rg54m3s")))

(define-public crate-rust-htslib-0.4.2 (c (n "rust-htslib") (v "0.4.2") (d (list (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "0sjd0fxdhzhfjry0ghk4g8vw322l7p440cnh678r4vw4h9pysj7d")))

(define-public crate-rust-htslib-0.4.3 (c (n "rust-htslib") (v "0.4.3") (d (list (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "1c47slnr23v5myckrqz89abz8r97czbbddxipsx8xh89jabqw8gr")))

(define-public crate-rust-htslib-0.5.0 (c (n "rust-htslib") (v "0.5.0") (d (list (d (n "itertools") (r ">= 0.4.1") (d #t) (k 0)) (d (n "libc") (r ">= 0.1.10") (d #t) (k 0)) (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "0hwzjmz1yjmnf0caqsa0w8ry02d7lmf2l06xi1ymwck3xjwsjh4h")))

(define-public crate-rust-htslib-0.5.1 (c (n "rust-htslib") (v "0.5.1") (d (list (d (n "itertools") (r ">= 0.4.1") (d #t) (k 0)) (d (n "libc") (r ">= 0.1.10") (d #t) (k 0)) (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "1sfa9xszsj7ssm5xdzz60nzqj1vgs4qz0bcfd8mcwi4pkccjwmma")))

(define-public crate-rust-htslib-0.5.2 (c (n "rust-htslib") (v "0.5.2") (d (list (d (n "itertools") (r ">= 0.4.1") (d #t) (k 0)) (d (n "libc") (r ">= 0.2.2") (d #t) (k 0)) (d (n "tempdir") (r "*") (d #t) (k 2)))) (h "1lbvwh3smymsalx4rz5gi1likg3cmw45ajqkkn1dazssy425cddg")))

(define-public crate-rust-htslib-0.6.0 (c (n "rust-htslib") (v "0.6.0") (d (list (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "14hfmj1jx5j49b1rckhr748d1bqkcqlzj5cihgcmq8w35q2kmwmy")))

(define-public crate-rust-htslib-0.6.1 (c (n "rust-htslib") (v "0.6.1") (d (list (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "15simww41yvmi24x1229sjl173gbfj5hqkh14vav90qp2z1564mj")))

(define-public crate-rust-htslib-0.6.2 (c (n "rust-htslib") (v "0.6.2") (d (list (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "1whl6fdblnk1n6qk0hwwr9ywphd759fyri5iih84zs8wyrx6nhkl")))

(define-public crate-rust-htslib-0.7.0 (c (n "rust-htslib") (v "0.7.0") (d (list (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "1k03lq83jqx0p7isapmx1r26nkb09fzfysj45zminb0lj0x667v9")))

(define-public crate-rust-htslib-0.8.0 (c (n "rust-htslib") (v "0.8.0") (d (list (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "quick-error") (r "1.1.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "0qkixr1x5qs40vgxb715wjxjb4kxhxldxwx7xs230nkv03swbfyh")))

(define-public crate-rust-htslib-0.8.1 (c (n "rust-htslib") (v "0.8.1") (d (list (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "quick-error") (r "1.1.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "16fhjhdhigcb6c0kkfwvqfmh6cm5i1w72d20j3gaf97cjhaj8vd2")))

(define-public crate-rust-htslib-0.9.0 (c (n "rust-htslib") (v "0.9.0") (d (list (d (n "custom_derive") (r "0.1.*") (d #t) (k 0)) (d (n "ieee754") (r "^0.1") (d #t) (k 0)) (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "lazy_static") (r "0.1.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "newtype_derive") (r "0.1.*") (d #t) (k 0)) (d (n "quick-error") (r "1.1.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)))) (h "0vdnan1z168j9gkdypahf134dd7k2adfgdzwba97pr4vpq1sbla8")))

(define-public crate-rust-htslib-0.10.0 (c (n "rust-htslib") (v "0.10.0") (d (list (d (n "custom_derive") (r "0.1.*") (d #t) (k 0)) (d (n "ieee754") (r "^0.1") (d #t) (k 0)) (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "lazy_static") (r "0.1.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "newtype_derive") (r "0.1.*") (d #t) (k 0)) (d (n "quick-error") (r "1.1.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)) (d (n "url") (r "1.2.*") (d #t) (k 0)))) (h "0vf9fba6w0jk8vs2093nij94z4diljdjzmbh76ynzcqy3f1153ia")))

(define-public crate-rust-htslib-0.11.0 (c (n "rust-htslib") (v "0.11.0") (d (list (d (n "bitflags") (r "0.8.*") (d #t) (k 0)) (d (n "custom_derive") (r "0.1.*") (d #t) (k 0)) (d (n "ieee754") (r "^0.1") (d #t) (k 0)) (d (n "itertools") (r "0.4.*") (d #t) (k 0)) (d (n "lazy_static") (r "0.1.*") (d #t) (k 0)) (d (n "libc") (r "0.2.*") (d #t) (k 0)) (d (n "newtype_derive") (r "0.1.*") (d #t) (k 0)) (d (n "quick-error") (r "1.1.*") (d #t) (k 0)) (d (n "tempdir") (r "0.3.*") (d #t) (k 2)) (d (n "url") (r "1.2.*") (d #t) (k 0)))) (h "029s40lng74na3vzs8yxpxp0nnp1scq849jc9ag4xwwhpn5mxr0f")))

(define-public crate-rust-htslib-0.12.0 (c (n "rust-htslib") (v "0.12.0") (d (list (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "1yydzn2ppisyy2k3jalzyczawvdqah1rrhqspbjcgyk9gmbyn41r")))

(define-public crate-rust-htslib-0.12.1 (c (n "rust-htslib") (v "0.12.1") (d (list (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "1cywvn3rn0h3d4ay3i2jx8s1f7kfbgx0xwi8y2qmynv0z0hbpqda")))

(define-public crate-rust-htslib-0.13.0 (c (n "rust-htslib") (v "0.13.0") (d (list (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "03yql79nkys550dwkax9mz78k2wa6li9a8dc4svf71wim59grg82")))

(define-public crate-rust-htslib-0.14.0 (c (n "rust-htslib") (v "0.14.0") (d (list (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0xan30wky29nh8n3qgj50f7gw29xdiwl80r0kbzkfs3av0yxam75")))

(define-public crate-rust-htslib-0.15.0 (c (n "rust-htslib") (v "0.15.0") (d (list (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0kniq8b0fag09agizkdr4zm3aszvgvzsz8w4w6mi7xlgmpy3yljk")))

(define-public crate-rust-htslib-0.16.0 (c (n "rust-htslib") (v "0.16.0") (d (list (d (n "bindgen") (r "^0.32.1") (d #t) (k 1)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "190lqmnhgl9ill6qywf1ip7clvxwyfvq6xrbnbag6mk70lr38qnl")))

(define-public crate-rust-htslib-0.17.0 (c (n "rust-htslib") (v "0.17.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.32.1") (d #t) (k 1)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "00y847v1brhjikilx79daqjsshi1xknjxhs6d2wqflxlix5fmlph") (f (quote (("default"))))))

(define-public crate-rust-htslib-0.18.0 (c (n "rust-htslib") (v "0.18.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.35.0") (d #t) (k 1)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^0.2") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0zlg5nlfpy3lbj98ly6myxcynd8qpjqn662dza6m8ciwchphw300") (f (quote (("default"))))))

(define-public crate-rust-htslib-0.19.0 (c (n "rust-htslib") (v "0.19.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.36") (d #t) (k 1)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^0.2") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0832bk0sb0d9jqnnyrkxz71b6rja1kv0g6rb1slbzpknin0wlrff") (f (quote (("default"))))))

(define-public crate-rust-htslib-0.19.1 (c (n "rust-htslib") (v "0.19.1") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.36") (d #t) (k 1)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^0.2") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0drfdmjdn1qknks4bpx20a930qjyqymgscwf5pwv3vww0mqd2if1") (f (quote (("default"))))))

(define-public crate-rust-htslib-0.20.0 (c (n "rust-htslib") (v "0.20.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.36") (d #t) (k 1)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "1i068249qw17x2i1hhrdrihhhf5kcwdri7cr0mvd57b0i6yyw0pp") (f (quote (("default"))))))

(define-public crate-rust-htslib-0.21.0 (c (n "rust-htslib") (v "0.21.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.36") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.1.1") (d #t) (k 0)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0fy8gnl00qy4d2mkxy9pr3y7r4la4abi7qrbzxbacxw351imp4qr") (f (quote (("lzma") ("default" "bzip2" "lzma") ("bzip2"))))))

(define-public crate-rust-htslib-0.22.0 (c (n "rust-htslib") (v "0.22.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r "^0.36") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.1.1") (d #t) (k 0)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "bzip2-sys") (r "^0.1.6") (o #t) (d #t) (k 0)) (d (n "cc") (r "^1.0") (d #t) (k 1)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "lzma-sys") (r "^0.1.10") (o #t) (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "1phxad7hgc5njg8wza6z7jia6ljak2lr5h0h7imf23jaw4s92v50") (f (quote (("lzma" "lzma-sys") ("default" "bzip2" "lzma") ("bzip2" "bzip2-sys"))))))

(define-public crate-rust-htslib-0.23.0 (c (n "rust-htslib") (v "0.23.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r ">= 0.37") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.5.1") (d #t) (k 0)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "bzip2-sys") (r "^0.1.7") (o #t) (d #t) (k 0)) (d (n "cc") (r "^1.0") (d #t) (k 1)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "lzma-sys") (r "^0.1.10") (o #t) (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "056zxpcl8nwvjdk3w7qr9q3iycvab9g5q5l30ik2p2mhsxb61y1n") (f (quote (("lzma" "lzma-sys") ("default" "bzip2" "lzma") ("bzip2" "bzip2-sys"))))))

(define-public crate-rust-htslib-0.24.0 (c (n "rust-htslib") (v "0.24.0") (d (list (d (n "bincode") (r "^1.0") (d #t) (k 2)) (d (n "bindgen") (r ">= 0.37") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.5.1") (d #t) (k 0)) (d (n "bitflags") (r "^0.9") (d #t) (k 0)) (d (n "bzip2-sys") (r "^0.1.7") (o #t) (d #t) (k 0)) (d (n "cc") (r "^1.0") (d #t) (k 1)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.0") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "linear-map") (r "^1.2.0") (d #t) (k 0)) (d (n "lzma-sys") (r "^0.1.10") (o #t) (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.5.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^1.4") (d #t) (k 0)))) (h "0yjq9r4nky12i1vky7wlk2ixjvmvqjbm8gzp2dnp53z1ssq76dsm") (f (quote (("lzma" "lzma-sys") ("default" "bzip2" "lzma") ("bzip2" "bzip2-sys"))))))

(define-public crate-rust-htslib-0.25.0 (c (n "rust-htslib") (v "0.25.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bindgen") (r "^0.51.0") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.5.1") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "bzip2-sys") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "cc") (r "^1.0") (d #t) (k 1)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.1") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "lzma-sys") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r "^0.5") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1vfm37rqyhmr5bv52pc9r7175439d5vxmhww216w65rv8z7z42s8") (f (quote (("lzma" "lzma-sys") ("default" "bzip2" "lzma") ("bzip2" "bzip2-sys"))))))

(define-public crate-rust-htslib-0.26.0 (c (n "rust-htslib") (v "0.26.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bindgen") (r "^0.51.0") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.5.1") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "bzip2-sys") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "cc") (r "^1.0") (d #t) (k 1)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.1") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "lzma-sys") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r "^0.5") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0jm5z36jks26nal63n9q5pb1rv2qyhra88x6rsn7xgbgff51qfhc") (f (quote (("lzma" "lzma-sys") ("default" "bzip2" "lzma") ("bzip2" "bzip2-sys"))))))

(define-public crate-rust-htslib-0.26.1 (c (n "rust-htslib") (v "0.26.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bindgen") (r "^0.51.0") (d #t) (k 1)) (d (n "bio-types") (r ">= 0.5.1") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "bzip2-sys") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "cc") (r "^1.0") (d #t) (k 1)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "fs-utils") (r "^1.1") (d #t) (k 1)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "lzma-sys") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r "^0.5") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1bkxndfw3bqc95a8lng1bckyjr90xihs4jqp5q6zm7rg2s02z8lp") (f (quote (("lzma" "lzma-sys") ("default" "bzip2" "lzma") ("bzip2" "bzip2-sys"))))))

(define-public crate-rust-htslib-0.27.0 (c (n "rust-htslib") (v "0.27.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">= 0.5.1") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.10") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde_base") (r "^1") (o #t) (d #t) (k 0) (p "serde")) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r ">= 0.5.0, <= 0.6.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0hqj0d7k6sc76n13b18h5sgj2xkxma78cn1bhhjx5p596g6ydirs") (f (quote (("serde" "serde_base" "serde_bytes") ("openssl" "hts-sys/openssl") ("lzma" "hts-sys/lzma") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2"))))))

(define-public crate-rust-htslib-0.28.0 (c (n "rust-htslib") (v "0.28.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">= 0.6") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.10") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde_base") (r "^1") (o #t) (d #t) (k 0) (p "serde")) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r ">= 0.5.0, <= 0.6.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1y6h6frmbn86lk9ccf7mnsqjn5lgxx3rhnq57z478gdm06yn5ns8") (f (quote (("serde" "serde_base" "serde_bytes") ("openssl" "hts-sys/openssl") ("lzma" "hts-sys/lzma") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2"))))))

(define-public crate-rust-htslib-0.29.0 (c (n "rust-htslib") (v "0.29.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">= 0.6") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.10") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde_base") (r "^1") (o #t) (d #t) (k 0) (p "serde")) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r ">= 0.5.0, <= 0.6.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1kzw5y8i4y7rjy0z172imq9wpd4vg4x4qnmr5833zq8hvy154f01") (f (quote (("serde" "serde_base" "serde_bytes") ("openssl" "hts-sys/openssl") ("lzma" "hts-sys/lzma") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2"))))))

(define-public crate-rust-htslib-0.30.0 (c (n "rust-htslib") (v "0.30.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">= 0.6") (d #t) (k 0)) (d (n "bitflags") (r "^1.2") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.10") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde_base") (r "^1") (o #t) (d #t) (k 0) (p "serde")) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "snafu") (r ">= 0.5.0, <= 0.6.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1d4ci50v75dx8c87wqn35nl9wa6qp7d50c6kg6zm4k77xvm4psp0") (f (quote (("serde" "serde_base" "serde_bytes") ("openssl" "hts-sys/openssl") ("lzma" "hts-sys/lzma") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2"))))))

(define-public crate-rust-htslib-0.31.0 (c (n "rust-htslib") (v "0.31.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.10.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde_base") (r "^1") (o #t) (d #t) (k 0) (p "serde")) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1zhb1h0639vqs710ij5bbg05xrznky17agcy0xr5233dw4dzsrpn") (f (quote (("static" "hts-sys/static") ("serde" "serde_base" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.32.0 (c (n "rust-htslib") (v "0.32.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.10.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde_base") (r "^1") (o #t) (d #t) (k 0) (p "serde")) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempdir") (r "^0.3") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "11d1rf3s8f0gglc98g8pvm5q6nij5na1had0p6mln847xxsnik5h") (f (quote (("static" "hts-sys/static") ("serde" "serde_base" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.33.0 (c (n "rust-htslib") (v "0.33.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.11.0") (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0apd2vlbmb02jqc8l8zm4sfd21gh3civp3jab1vbnnkr9za0sa1h") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.34.0 (c (n "rust-htslib") (v "0.34.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "hts-sys") (r "^1.11.0") (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0dbvj5rblqh0linlz01zzsa11zd8mldn0m0wmmp9ncffxchrf5ix") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.35.0 (c (n "rust-htslib") (v "0.35.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derefable") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^1.11.0") (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "13v2sgh99pq35hjcy3y9h1y9b02c1kdncxbpiqpwy5wj5il74240") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.35.1 (c (n "rust-htslib") (v "0.35.1") (d (list (d (n "bincode") (r ">=1.2.0, <2.0.0") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6.0") (d #t) (k 0)) (d (n "custom_derive") (r ">=0.1.0, <0.2.0") (d #t) (k 0)) (d (n "derefable") (r ">=0.1.0, <0.2.0") (d #t) (k 0)) (d (n "derive-new") (r ">=0.5.0, <0.6.0") (d #t) (k 0)) (d (n "hts-sys") (r ">=1.11.0-fix1, <2.0.0") (k 0)) (d (n "ieee754") (r ">=0.2.0, <0.3.0") (d #t) (k 0)) (d (n "lazy_static") (r ">=1.4.0, <2.0.0") (d #t) (k 0)) (d (n "libc") (r ">=0.2.0, <0.3.0") (d #t) (k 0)) (d (n "linear-map") (r ">=1.2.0, <2.0.0") (d #t) (k 0)) (d (n "newtype_derive") (r ">=0.1.0, <0.2.0") (d #t) (k 0)) (d (n "pretty_assertions") (r ">=0.6.0, <0.7.0") (d #t) (k 2)) (d (n "regex") (r ">=1.3.0, <2.0.0") (d #t) (k 0)) (d (n "serde") (r ">=1.0.0, <2.0.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r ">=0.11.0, <0.12.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r ">=1.0.0, <2.0.0") (d #t) (k 2)) (d (n "tempfile") (r ">=3.1.0, <4.0.0") (d #t) (k 2)) (d (n "thiserror") (r ">=1.0.0, <2.0.0") (d #t) (k 0)) (d (n "url") (r ">=2.1.0, <3.0.0") (d #t) (k 0)))) (h "153krz9lj2v5ajqh1rvipkv3dy5yzriy70mbar43gr1ydnpncrfd") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.35.2 (c (n "rust-htslib") (v "0.35.2") (d (list (d (n "bincode") (r ">=1.2.0, <2.0.0") (d #t) (k 2)) (d (n "bio-types") (r ">=0.6.0") (d #t) (k 0)) (d (n "custom_derive") (r ">=0.1.0, <0.2.0") (d #t) (k 0)) (d (n "derefable") (r ">=0.1.0, <0.2.0") (d #t) (k 0)) (d (n "derive-new") (r ">=0.5.0, <0.6.0") (d #t) (k 0)) (d (n "hts-sys") (r ">=1.11.1-fix1, <2.0.0") (k 0)) (d (n "ieee754") (r ">=0.2.0, <0.3.0") (d #t) (k 0)) (d (n "lazy_static") (r ">=1.4.0, <2.0.0") (d #t) (k 0)) (d (n "libc") (r ">=0.2.0, <0.3.0") (d #t) (k 0)) (d (n "linear-map") (r ">=1.2.0, <2.0.0") (d #t) (k 0)) (d (n "newtype_derive") (r ">=0.1.0, <0.2.0") (d #t) (k 0)) (d (n "pretty_assertions") (r ">=0.6.0, <0.7.0") (d #t) (k 2)) (d (n "regex") (r ">=1.3.0, <2.0.0") (d #t) (k 0)) (d (n "serde") (r ">=1.0.0, <2.0.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r ">=0.11.0, <0.12.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r ">=1.0.0, <2.0.0") (d #t) (k 2)) (d (n "tempfile") (r ">=3.1.0, <4.0.0") (d #t) (k 2)) (d (n "thiserror") (r ">=1.0.0, <2.0.0") (d #t) (k 0)) (d (n "url") (r ">=2.1.0, <3.0.0") (d #t) (k 0)))) (h "0if931g1s92jficigck6nvdjh4p8xwn0jl2k6hf13y8fpls8w8rj") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.36.0 (c (n "rust-htslib") (v "0.36.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derefable") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^1.11.1-fix1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "strum_macros") (r "^0.20") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1nbv00vpzf6siwjx24mv763azb9c3kav19b62gsg9shdk3vyblmn") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.37.0 (c (n "rust-htslib") (v "0.37.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^1.11.1-fix1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0blhcrkljfg9wv1hqzicinfy8w5z2ygpk6sdck7lx7jx9flwz7jy") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.38.2 (c (n "rust-htslib") (v "0.38.2") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "070sihnvyiyqcw8yjkdl8hvav598bsw36m722phgd2b394k6djia") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.39.5 (c (n "rust-htslib") (v "0.39.5") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0lwf22acf6zn9znqd9irc9ny7msya8macvvsdgasqndz9lrzg7i3") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.40.2 (c (n "rust-htslib") (v "0.40.2") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1m08935ijvxaq6pjmzhkimc6isb3qm7h1sza1012vwk99vzdwwqb") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.41.1 (c (n "rust-htslib") (v "0.41.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "11lkkxw9ijmvi25zs1pg9hcp8agrwd3h7n33rk6vbnli4zh6j76b") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.42.0 (c (n "rust-htslib") (v "0.42.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1m1xxaw98y59zjqd1zpzws30awpl5p86l0v0qsychdqwrkpl7ivf") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.43.0 (c (n "rust-htslib") (v "0.43.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1mlbr992vr8sw9y152skry6x1wcbgqmm3k7ypzjrvgjb3xaf3w8s") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.43.1 (c (n "rust-htslib") (v "0.43.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.0.3") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1x8bsym3gvkawc9f3grk04h6vacsdq7dgxn37j4zm49by801i22k") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.44.0 (c (n "rust-htslib") (v "0.44.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.1.1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1rcixchbjsmzz0c32ispik2lq0s4dhjkzykccppbfnzka6drwj0b") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.44.1 (c (n "rust-htslib") (v "0.44.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.1.1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "0ry4q2sjwa4blmwk40hnh02qj8ypygz5x43q4pia8r6fkzrb0zkw") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.45.0 (c (n "rust-htslib") (v "0.45.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.1.1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "1y02b2gw9yapb6ypapvk59c3x3bish6jzgjqyyppqvsgmj291ady") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.46.0 (c (n "rust-htslib") (v "0.46.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.1.1") (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r ">=1.1.15") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "13lnc33n5699v9cg1bgnfflfapfi9la9k37zfnpb9gh18v5gkimf") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

(define-public crate-rust-htslib-0.47.0 (c (n "rust-htslib") (v "0.47.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 2)) (d (n "bio-types") (r ">=0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "custom_derive") (r "^0.1") (d #t) (k 0)) (d (n "derive-new") (r "^0.5") (d #t) (k 0)) (d (n "hts-sys") (r "^2.1.4") (f (quote ("bindgen"))) (k 0)) (d (n "ieee754") (r "^0.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "libz-sys") (r ">=1.1.15") (d #t) (k 0)) (d (n "linear-map") (r "^1.2") (d #t) (k 0)) (d (n "newtype_derive") (r "^0.1") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6") (d #t) (k 2)) (d (n "regex") (r "^1.3") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 2)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "url") (r "^2.1") (d #t) (k 0)))) (h "10i4s30y6phigs5aa50iw1kyhq713wzw1ibg5hlbngp701l7kwa1") (f (quote (("static" "hts-sys/static") ("serde_feature" "serde" "serde_bytes" "bio-types/serde") ("s3" "hts-sys/s3") ("lzma" "hts-sys/lzma") ("libdeflate" "hts-sys/libdeflate") ("gcs" "hts-sys/gcs") ("default" "bzip2" "lzma" "curl") ("curl" "hts-sys/curl") ("bzip2" "hts-sys/bzip2") ("bindgen" "hts-sys/bindgen"))))))

