(define-module (crates-io ro ck rocket_cors) #:use-module (crates-io))

(define-public crate-rocket_cors-0.0.1 (c (n "rocket_cors") (v "0.0.1") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "1k6d820izq8gfpm2chaibk7jhl1bp0n2sly1si9xlk51jk3ac9c6") (y #t)))

(define-public crate-rocket_cors-0.1.0 (c (n "rocket_cors") (v "0.1.0") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "1vdgnqdd8794mg8pva5l2d276ryn9hl1mg295pwy8zy7paflrg6d") (y #t)))

(define-public crate-rocket_cors-0.1.1 (c (n "rocket_cors") (v "0.1.1") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "04niqvxfqn9ddxnismc1423m791wkzd62nqir40a87hp1jj2pi5y") (y #t)))

(define-public crate-rocket_cors-0.1.2 (c (n "rocket_cors") (v "0.1.2") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "1bpnscdjmd6w5y2bhrqhykp6a57h6jkn0wchkbqmn9ycpsr0hs2v") (y #t)))

(define-public crate-rocket_cors-0.1.3 (c (n "rocket_cors") (v "0.1.3") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "1m2viz1fq690mhb1lp82ci4n1z0nm3pl0xhywdzybf2aqp1lq14v") (y #t)))

(define-public crate-rocket_cors-0.1.4 (c (n "rocket_cors") (v "0.1.4") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "1khr2m4w8q0dn4ssxzy272gdrqwssb2im3mxxvbfazlfbzjdnfw7")))

(define-public crate-rocket_cors-0.2.0 (c (n "rocket_cors") (v "0.2.0") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "00dhaik83rw0yx93nrwmbpfwjsfmsnsa8b1pa0wmsxywizs8za3w")))

(define-public crate-rocket_cors-0.2.1 (c (n "rocket_cors") (v "0.2.1") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 1)) (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "version_check") (r "^0.1") (d #t) (k 1)))) (h "0rb8658nqai5ky3samp5d5qln5a6bqvzx306v64kwd7g9x0zjx5w") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.2.2 (c (n "rocket_cors") (v "0.2.2") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3.6") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "027m46z0bwxwk18y91kw3ckcalhw3infap5q5hxdy9pn91c3z1k7") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.2.3 (c (n "rocket_cors") (v "0.2.3") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3.6") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "0zhg3dbvcx86ixrp8w659j03iy3f627aks6d6z2hwg8mn6igk3mg") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.3.0 (c (n "rocket_cors") (v "0.3.0") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.3.15") (d #t) (k 0)) (d (n "rocket_codegen") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "1vlfjzpzrylp9v7nhq5w3mgfjlriq9na4kwcm1i8whjxbqwxi4v8") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.4.0-rc.1 (c (n "rocket_cors") (v "0.4.0-rc.1") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.4.0-rc.1") (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "1zrw5c6hd8qmpkbazfj79gl1vq7d5x1bwvnvk0lxp2fm62936a16") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization")))) (y #t)))

(define-public crate-rocket_cors-0.4.0-rc.2 (c (n "rocket_cors") (v "0.4.0-rc.2") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.4.0-rc.1") (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "0l0mbkgr4d1s997wkq6inyj0can9zy64a7v9sf971q64nk4y8dr2") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization")))) (y #t)))

(define-public crate-rocket_cors-0.4.0-rc.3 (c (n "rocket_cors") (v "0.4.0-rc.3") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.4.0-rc.2") (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "19ah5bj0xv7awljfilipx0mclpwl13hyx6dpcjrcazzxfdysdm0k") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization")))) (y #t)))

(define-public crate-rocket_cors-0.4.0 (c (n "rocket_cors") (v "0.4.0") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "rocket") (r "^0.4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.5.1") (d #t) (k 0)) (d (n "url_serde") (r "^0.2.0") (o #t) (d #t) (k 0)))) (h "06yf9pigslzd0w6gi90h6d805alvhrfn11c052hg8cfj3s5xxbfq") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde" "url_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.5.0-beta-1 (c (n "rocket_cors") (v "0.5.0-beta-1") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "regex") (r "^1.1") (d #t) (k 0)) (d (n "rocket") (r "^0.4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.7.2") (d #t) (k 0)))) (h "01f0b6nm9f0gbapyjxgidnh5g12a3cansg2dc0jz6ljdrplf9rrk") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.5.0 (c (n "rocket_cors") (v "0.5.0") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "regex") (r "^1.1") (d #t) (k 0)) (d (n "rocket") (r "^0.4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.7.2") (d #t) (k 0)))) (h "0hcz0r8hf1jgp7pbmd2vdj0gzc4b5zn6jqb024k42j1h7bnavhjw") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.5.1 (c (n "rocket_cors") (v "0.5.1") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.3") (d #t) (k 0)) (d (n "regex") (r "^1.1") (d #t) (k 0)) (d (n "rocket") (r "^0.4.2") (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^1.7.2") (d #t) (k 0)))) (h "04sfdksfkszg7hw7h12mdgd35s9wfyvqs9klmll7j2ssp869c2i7") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.5.2 (c (n "rocket_cors") (v "0.5.2") (d (list (d (n "hyper") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "regex") (r "^1.1") (d #t) (k 0)) (d (n "rocket") (r "^0.4.2") (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.1.0") (d #t) (k 0)))) (h "0xhh4y3c7kc5xa19rbw7q138waz073z0aa920v5d0233qinnj87a") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.6.0-alpha1 (c (n "rocket_cors") (v "0.6.0-alpha1") (d (list (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "regex") (r "^1.1") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0-rc.1") (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.0") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.1.0") (d #t) (k 0)))) (h "14s72mwmc61qr47xgzlrhdclgk24i01v0kxx72zvpnmmrp4s4niz") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.6.0-alpha2 (c (n "rocket_cors") (v "0.6.0-alpha2") (d (list (d (n "http") (r "^0.2") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "regex") (r "^1.7.2") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0-rc.3") (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.6") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.3.1") (d #t) (k 0)))) (h "1l6bl95bgmg78y4f3f9w4rrkx1l2lgmlli0f1rflvqsjgys729xi") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.6.0-alpha3 (c (n "rocket_cors") (v "0.6.0-alpha3") (d (list (d (n "http") (r "^0.2") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "regex") (r "^1.7.2") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0-rc.4") (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.6") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.3.1") (d #t) (k 0)))) (h "0nskqmn3vyl6dx3qqy4bj5wq3qzrdp9pxbkr4xax9jig61jxcpgg") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization"))))))

(define-public crate-rocket_cors-0.6.0 (c (n "rocket_cors") (v "0.6.0") (d (list (d (n "http") (r "^0.2") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "regex") (r "^1.7.2") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0") (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "unicase") (r "^2.6") (d #t) (k 0)) (d (n "unicase_serde") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.3.1") (d #t) (k 0)))) (h "0sdah6kjppwmcb3jxxf0gxxl31n7hqxvl7d4db4lz39zz0fkmb6g") (f (quote (("serialization" "serde" "serde_derive" "unicase_serde") ("default" "serialization")))) (r "1.69")))

