(define-module (crates-io ro ck rocket-jwt-new) #:use-module (crates-io))

(define-public crate-rocket-jwt-new-0.5.2 (c (n "rocket-jwt-new") (v "0.5.2") (d (list (d (n "jsonwebtoken") (r "^8") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "syn") (r "^1") (d #t) (k 0)) (d (n "trybuild") (r "^1.0") (d #t) (k 2)) (d (n "version_check") (r "^0.9") (d #t) (k 1)) (d (n "yansi") (r "^0.5") (d #t) (k 1)))) (h "1hlkk9vfapa3585s7lwg4zd6f3hr08qgg2bmld258f7a3x3rszc2") (r "1.56")))

(define-public crate-rocket-jwt-new-0.5.3 (c (n "rocket-jwt-new") (v "0.5.3") (d (list (d (n "jsonwebtoken") (r "^8") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "syn") (r "^1") (d #t) (k 0)) (d (n "trybuild") (r "^1.0") (d #t) (k 2)) (d (n "version_check") (r "^0.9") (d #t) (k 1)) (d (n "yansi") (r "^0.5") (d #t) (k 1)))) (h "1f4bqr533fkhgj03v2kfdl7xq3q05jhdw676nmlyj85vcycjkwbc") (r "1.56")))

(define-public crate-rocket-jwt-new-0.5.4 (c (n "rocket-jwt-new") (v "0.5.4") (d (list (d (n "jsonwebtoken") (r "^8") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "syn") (r "^1") (d #t) (k 0)) (d (n "trybuild") (r "^1.0") (d #t) (k 2)) (d (n "version_check") (r "^0.9") (d #t) (k 1)) (d (n "yansi") (r "^0.5") (d #t) (k 1)))) (h "1pn38djcnhxfxb21njybh8bxw314698db8ylm5arqahz8z2iddra") (r "1.56")))

(define-public crate-rocket-jwt-new-0.5.5 (c (n "rocket-jwt-new") (v "0.5.5") (d (list (d (n "jsonwebtoken") (r "^8") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "syn") (r "^1") (d #t) (k 0)) (d (n "trybuild") (r "^1.0") (d #t) (k 2)) (d (n "version_check") (r "^0.9") (d #t) (k 1)) (d (n "yansi") (r "^0.5") (d #t) (k 1)))) (h "1hybrmzzyhrykjfzfxzcl9ds2g3b2m8h3nxg8p0g467dn4g5c5sw") (r "1.56")))

(define-public crate-rocket-jwt-new-0.6.0 (c (n "rocket-jwt-new") (v "0.6.0") (d (list (d (n "jsonwebtoken") (r "^8") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "rocket") (r "^0.5.0") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "syn") (r "^1") (d #t) (k 0)) (d (n "trybuild") (r "^1.0") (d #t) (k 2)) (d (n "version_check") (r "^0.9") (d #t) (k 1)) (d (n "yansi") (r "^0.5") (d #t) (k 1)))) (h "0ankrdr4wgj0rwwxqc2bwspws2jbhfhrslginm9ddxz1gb8sqbpp") (r "1.56")))

