(define-module (crates-io se cr secret-toolkit-viewing-key) #:use-module (crates-io))

(define-public crate-secret-toolkit-viewing-key-0.3.0 (c (n "secret-toolkit-viewing-key") (v "0.3.0") (d (list (d (n "base64") (r "^0.11.0") (d #t) (k 0)) (d (n "cosmwasm-std") (r "^0.10") (d #t) (k 0) (p "secret-cosmwasm-std")) (d (n "cosmwasm-storage") (r "^0.10") (d #t) (k 0) (p "secret-cosmwasm-storage")) (d (n "schemars") (r "^0.7") (d #t) (k 0)) (d (n "secret-toolkit-crypto") (r "^0.3") (f (quote ("hash" "rand"))) (k 0)) (d (n "secret-toolkit-utils") (r "^0.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "subtle") (r "^2.2.3") (k 0)))) (h "18ag6v9hp79daq576k2qpd2rdnyx6cn7hb0x64zw0pmkfy57m5xp")))

(define-public crate-secret-toolkit-viewing-key-0.6.0 (c (n "secret-toolkit-viewing-key") (v "0.6.0") (d (list (d (n "base64") (r "^0.11.0") (d #t) (k 0)) (d (n "cosmwasm-std") (r "^1.0.0") (d #t) (k 0) (p "secret-cosmwasm-std")) (d (n "cosmwasm-storage") (r "^1.0.0") (d #t) (k 0) (p "secret-cosmwasm-storage")) (d (n "schemars") (r "^0.7") (d #t) (k 0)) (d (n "secret-toolkit-crypto") (r "^0.6") (f (quote ("hash" "rand"))) (k 0)) (d (n "secret-toolkit-utils") (r "^0.6") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "subtle") (r "^2.2.3") (k 0)))) (h "1yayg92g0mp9i742lwh8z1m5c93q67y0hi8kissiq5vnlf5x15sb")))

(define-public crate-secret-toolkit-viewing-key-0.7.0 (c (n "secret-toolkit-viewing-key") (v "0.7.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "cosmwasm-std") (r "^1.0.0") (d #t) (k 0) (p "secret-cosmwasm-std")) (d (n "cosmwasm-storage") (r "^1.0.0") (d #t) (k 0) (p "secret-cosmwasm-storage")) (d (n "schemars") (r "^0.8.11") (d #t) (k 0)) (d (n "secret-toolkit-crypto") (r "^0.7") (f (quote ("hash" "rand"))) (d #t) (k 0)) (d (n "secret-toolkit-utils") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "subtle") (r "^2.2.3") (k 0)))) (h "1f46f36qlmzzs4786wvwsah5z4nmmw4fipqcy7jfh6sjcfwa8mdm")))

(define-public crate-secret-toolkit-viewing-key-0.9.0 (c (n "secret-toolkit-viewing-key") (v "0.9.0") (d (list (d (n "base64") (r "^0.21.0") (d #t) (k 0)) (d (n "cosmwasm-std") (r "^1.1.10") (f (quote ("random"))) (d #t) (k 0) (p "secret-cosmwasm-std")) (d (n "cosmwasm-storage") (r "^1.1.10") (d #t) (k 0) (p "secret-cosmwasm-storage")) (d (n "schemars") (r "^0.8.11") (d #t) (k 0)) (d (n "secret-toolkit-crypto") (r "^0.9") (f (quote ("hash" "rand"))) (d #t) (k 0)) (d (n "secret-toolkit-utils") (r "^0.9") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "subtle") (r "^2.2.3") (k 0)))) (h "0pr7wycmwgpvaw60xg1k35vdym60cr9capy6yf9cq390lzsnb4sz")))

(define-public crate-secret-toolkit-viewing-key-0.10.0 (c (n "secret-toolkit-viewing-key") (v "0.10.0") (d (list (d (n "base64") (r "^0.21.0") (d #t) (k 0)) (d (n "cosmwasm-std") (r "^1.1.11") (f (quote ("random"))) (d #t) (k 0) (p "secret-cosmwasm-std")) (d (n "cosmwasm-storage") (r "^1.1.11") (d #t) (k 0) (p "secret-cosmwasm-storage")) (d (n "schemars") (r "^0.8.11") (d #t) (k 0)) (d (n "secret-toolkit-crypto") (r "^0.10.0") (f (quote ("hash" "rand"))) (d #t) (k 0)) (d (n "secret-toolkit-utils") (r "^0.10.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "subtle") (r "^2.2.3") (k 0)))) (h "08g917nlcp6xglxpiwc276a310g4wzk31yhjlqsjgcd9kyva129d")))

