(define-module (crates-io ge ng gengo) #:use-module (crates-io))

(define-public crate-gengo-0.1.0 (c (n "gengo") (v "0.1.0") (d (list (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "05ngzssfznjxir2x7cqvyvxdf3jvh297k7nxnsf5ppdmljpwysw3")))

(define-public crate-gengo-0.1.2 (c (n "gengo") (v "0.1.2") (d (list (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0dahmcwagb1nw35zmkbzkp64a46rfhm7dw9pii4lki09bs7d9qxw")))

(define-public crate-gengo-0.1.3 (c (n "gengo") (v "0.1.3") (d (list (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18.1") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1jm7zmd993fxy09rh5xsnjn8qyfm4xqbz1kc31nrcd9fi58k3kjj")))

(define-public crate-gengo-0.1.5 (c (n "gengo") (v "0.1.5") (d (list (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18.1") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "13mcm3av1mb9sgrj6d4ksf7qgyyxicp73xqf9g829r6m5f1wx4gx")))

(define-public crate-gengo-0.2.0 (c (n "gengo") (v "0.2.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1s4iq2ry3gqfqxiyrvczjk8iwpa4f8mj9v0hwpnnhmcq6m5z7rbc")))

(define-public crate-gengo-0.2.1 (c (n "gengo") (v "0.2.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0ddhk7n6f4galybzp0xknv7s8hly3l9lxi0v3ksprxivx30ipr0x")))

(define-public crate-gengo-0.3.0 (c (n "gengo") (v "0.3.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1j6gf34ymix0lhqmcgas159j59gczn929yywa7cw9y1pwq232znx")))

(define-public crate-gengo-0.3.1 (c (n "gengo") (v "0.3.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0qjxv3r43z2mvp6syp8fihvxpp8dww2iycfv1ws6z5530f2i3gia")))

(define-public crate-gengo-0.3.2 (c (n "gengo") (v "0.3.2") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "04qy31qc65gd6aq2831cb7l63f9zz343x9xvxm3b3s6dzzf4j3mz")))

(define-public crate-gengo-0.3.3 (c (n "gengo") (v "0.3.3") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (d #t) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0srf5wjzk0wshgkiv7sp8az9pi1nfm891j8xrrs0f0cgyhs78q1k")))

(define-public crate-gengo-0.3.4 (c (n "gengo") (v "0.3.4") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1vwblxmp74kqis69lm82sf7ir22kh04aj8kligh831lldi2j319w")))

(define-public crate-gengo-0.3.5 (c (n "gengo") (v "0.3.5") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0a16s0dkvhc59yywhk68wxbqfn7s95baapm3pc96s29axh3lqbar")))

(define-public crate-gengo-0.3.6 (c (n "gengo") (v "0.3.6") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "07k19dz01jg1qi54bvwa61pbrpnnk8asppq7q2lp7ppxdb5f55jc")))

(define-public crate-gengo-0.4.0 (c (n "gengo") (v "0.4.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "064f4ibmivsxdjja6q0hc3b7c81ayxcdd2g7y86jjxph0brsy12v")))

(define-public crate-gengo-0.4.1 (c (n "gengo") (v "0.4.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "git2") (r "^0.17") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "13jj2nsms2plca1kgqzcwdngc6dzsjckkgyyngsx598kbiiba2wi")))

(define-public crate-gengo-0.5.0 (c (n "gengo") (v "0.5.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.52") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0c9d6b7yhkav2gdpkaylqrj038hcd5aw7qr4hf9m6mkidzv1h0sy") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.5.1 (c (n "gengo") (v "0.5.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.52") (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1frcs8hzw4k69rqlfygk2ydcdalfqjraalavf0h54cw20r6lcchf") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.5.2 (c (n "gengo") (v "0.5.2") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.53") (f (quote ("index" "attributes" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0x328ixlxasmhy1hzvvll9x0aygamx0i6yp80p20h0mcn40a1r4g") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.6.0 (c (n "gengo") (v "0.6.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.53") (f (quote ("index" "attributes" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "05p7z0x5n8jn0zlgcm241i9x28hzggsm7p1j99ygd48ghs7qdwc8") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.7.0 (c (n "gengo") (v "0.7.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.54.1") (f (quote ("index" "attributes" "revision" "parallel"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1wijvsc268pq4k2hfycl4nvbsjvv4lr3c5vbzcjn1flbs8h6q4p1") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.7.1 (c (n "gengo") (v "0.7.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.54.1") (f (quote ("index" "attributes" "revision" "parallel"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1lq94zglf5d7w64a8kk4dx4kxn9f162n0d60d5sbqbl50xfgvlzf") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.8.0 (c (n "gengo") (v "0.8.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.54.1") (f (quote ("index" "attributes" "revision" "parallel"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1i5zccv8c436cwg7pzpj6d6n1j0b6pgd6wmy4jbnwp7275hbgzbd") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.8.1 (c (n "gengo") (v "0.8.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.54.1, <0.56") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "0ask6ai7dq7277p2wc9z8dlcg7yhdsjsfmd2nw1h9vbqifz1mi6w") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.8.2 (c (n "gengo") (v "0.8.2") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.54.1, <0.56") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "08v3s5hf6j7vmczq6sqy7lbcg922y9xwbzdsrixfr0wcsmbp61mf") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.9.0 (c (n "gengo") (v "0.9.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.54.1, <0.56") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1kcy58iqzvn2yjl3d3ln86xpkz5rhmwj1wynd2mnml4jgnjmaywg") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.9.1 (c (n "gengo") (v "0.9.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r "^0.56") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r "^3") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1qdb5f8l39psmkif8g7d3hal0iayxplm9x7a5i9v1ax31jiq0pnd") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.10.0 (c (n "gengo") (v "0.10.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.56, <=0.57") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r ">=3, <=4") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1wwqvkwlzhr57sav1fdzy63q3pgawkh0a2ah6px0rjv9s10di6gh") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.10.1 (c (n "gengo") (v "0.10.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.56, <=0.57") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("rayon" "serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "owo-colors") (r ">=3, <=4") (o #t) (d #t) (k 0)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)))) (h "1lfc18g55mn2amfsxh00f23cnv9bps6x4c17g60r5x336yls4bgv") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.11.0 (c (n "gengo") (v "0.11.0") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.56, <=0.57") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("rayon" "serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 2)) (d (n "owo-colors") (r ">=3, <=4") (o #t) (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 1)) (d (n "proc-macro2") (r "^1") (d #t) (k 1)) (d (n "quote") (r "^1") (d #t) (k 1)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 2)) (d (n "syn") (r "^2") (d #t) (k 1)))) (h "1xsy6xc0mlzsqzfzpr9an9zjq92rm1gflmqxzafakn7dkk344gn0") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.11.1 (c (n "gengo") (v "0.11.1") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.56, <=0.61") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("rayon" "serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 2)) (d (n "owo-colors") (r ">=3, <=4") (o #t) (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 1)) (d (n "proc-macro2") (r "^1") (d #t) (k 1)) (d (n "quote") (r "^1") (d #t) (k 1)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.18") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 2)) (d (n "syn") (r "^2") (d #t) (k 1)))) (h "1b7a2par2xwf04br65myfvzdfdhvbxp7c4r7dmca4ak4h2cnkqyv") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.11.2 (c (n "gengo") (v "0.11.2") (d (list (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "gix") (r ">=0.56, <=0.62") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("rayon" "serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 2)) (d (n "owo-colors") (r ">=3, <=4") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 1)) (d (n "quote") (r "^1") (d #t) (k 1)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.19") (d #t) (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 2)))) (h "1icvlbbpq9fflcc6b259m7s2dx44v9pyxxq22q65bbz2zlz0ymqs") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

(define-public crate-gengo-0.11.3 (c (n "gengo") (v "0.11.3") (d (list (d (n "criterion") (r "^0.5") (f (quote ("rayon" "cargo_bench_support"))) (k 2)) (d (n "gix") (r ">=0.56, <=0.63") (f (quote ("attributes" "index" "parallel" "revision"))) (k 0)) (d (n "glob") (r "^0.3") (d #t) (k 0)) (d (n "ignore") (r "^0.4") (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("rayon" "serde"))) (d #t) (k 0)) (d (n "indexmap") (r "^2") (f (quote ("serde"))) (d #t) (k 1)) (d (n "insta") (r "^1") (d #t) (k 2)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 2)) (d (n "owo-colors") (r ">=3, <=4") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 1)) (d (n "quote") (r "^1") (d #t) (k 1)) (d (n "rayon") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "rstest") (r "^0.19") (k 2)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 1)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 2)))) (h "0xncp860nk6cfjgph819xnrrnqf3pb777yh7f5bpa6cvqkw15m7h") (f (quote (("max-performance-safe" "gix/max-performance-safe") ("max-performance" "gix/max-performance") ("default" "max-performance-safe"))))))

