(define-module (crates-io in fe infer_schema_macros) #:use-module (crates-io))

(define-public crate-infer_schema_macros-0.99.0 (c (n "infer_schema_macros") (v "0.99.0") (d (list (d (n "clippy") (r "= 0.0.162") (o #t) (d #t) (k 0)) (d (n "diesel") (r "^0.99.0") (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "^0.99.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "1x3z51ilp3mprlzgz48k7bhvlh9d1g6pmzlhw5b8pblm2cj6yn1i") (f (quote (("sqlite" "diesel/sqlite" "infer_schema_internals/sqlite") ("postgres" "diesel/postgres" "infer_schema_internals/postgres") ("mysql" "diesel/mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.0.0-beta1 (c (n "infer_schema_macros") (v "1.0.0-beta1") (d (list (d (n "clippy") (r "= 0.0.174") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "^1.0.0-beta1") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "0xw6362nhj6353bm9ckik5vwb983m2068sdfdx5247zh4yn4fx7f") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.0.0-rc1 (c (n "infer_schema_macros") (v "1.0.0-rc1") (d (list (d (n "clippy") (r "= 0.0.174") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "^1.0.0-rc1") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "0lxrh9n4dx3lzqlb7la0ar82sm2j2jcd9xq8flgazydkhclyj1da") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.0.0 (c (n "infer_schema_macros") (v "1.0.0") (d (list (d (n "clippy") (r "= 0.0.174") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "^1.0.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "1bm66mcaqrwhl0xpasxjx7d252hxiv5ayqlxwn9dplhwi851k2pv") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.1.0 (c (n "infer_schema_macros") (v "1.1.0") (d (list (d (n "clippy") (r "= 0.0.174") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "^1.1.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "02zxndgyhqg1pfr1hgz5bpnf6sr8mmimqhwbfn460rbrnp85dk0z") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.0.1 (c (n "infer_schema_macros") (v "1.0.1") (d (list (d (n "clippy") (r "= 0.0.174") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "~1.0.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "0q9jl4lv1fgg0bygda1vaf6k7idkg9kdf0a82s7rbz6z96sx4apb") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.1.2 (c (n "infer_schema_macros") (v "1.1.2") (d (list (d (n "clippy") (r "= 0.0.174") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "~1.1.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "0k9vgixx952f1dbym70zzw9jb2ima7psl2j2w0dl3wcj19bdbwla") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.2.0 (c (n "infer_schema_macros") (v "1.2.0") (d (list (d (n "clippy") (r "= 0.0.185") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "~1.2.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "1zm4rmjffpfmklrbk06bxdg4m4acr02xwcpz6jfz3khbjv2df2xz") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.3.0 (c (n "infer_schema_macros") (v "1.3.0") (d (list (d (n "clippy") (r "= 0.0.195") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "~1.3.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "16dmd79hpxm4y13cyi6d7vpxnj17w13zjmly4pv80nf2g90a1513") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

(define-public crate-infer_schema_macros-1.4.0 (c (n "infer_schema_macros") (v "1.4.0") (d (list (d (n "clippy") (r "= 0.0.195") (o #t) (d #t) (k 0)) (d (n "dotenv") (r ">= 0.8, < 0.11") (o #t) (k 0)) (d (n "infer_schema_internals") (r "~1.4.0") (k 0)) (d (n "quote") (r "^0.3.12") (d #t) (k 0)) (d (n "syn") (r "^0.11.4") (f (quote ("aster"))) (d #t) (k 0)) (d (n "tempdir") (r "^0.3.4") (d #t) (k 2)))) (h "1ilab1vhccdx1wziv5dqxrlyddl8w8dlbsnfi5cn96ggf6s6gdh7") (f (quote (("sqlite" "infer_schema_internals/sqlite") ("postgres" "infer_schema_internals/postgres") ("mysql" "infer_schema_internals/mysql") ("lint" "clippy") ("default" "dotenv"))))))

