(define-module (crates-io cg lu cglue-gen) #:use-module (crates-io))

(define-public crate-cglue-gen-0.0.0 (c (n "cglue-gen") (v "0.0.0") (h "0b7600z5r3pg1nlg42wjk7ad1b3zmin9408ymah2xrm5clzf3g66") (y #t)))

(define-public crate-cglue-gen-0.1.0 (c (n "cglue-gen") (v "0.1.0") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1jrzp4q8iw1iqdvdhj061qj629lkyz4mdixwgazdakmvqz5gb043") (f (quote (("no_empty_retwrap") ("default"))))))

(define-public crate-cglue-gen-0.1.1 (c (n "cglue-gen") (v "0.1.1") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "19p62ys6482axihgrznj3ldqbs0wsxjp6nbw6fbbm6826k2d7mns") (f (quote (("no_empty_retwrap") ("default")))) (y #t)))

(define-public crate-cglue-gen-0.1.2 (c (n "cglue-gen") (v "0.1.2") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "16x11bl8c767nvny5s3p9zvwjmgw6ccwg7mjwi2nvh78zprzaap1") (f (quote (("no_empty_retwrap") ("default"))))))

(define-public crate-cglue-gen-0.1.3 (c (n "cglue-gen") (v "0.1.3") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0cjjc8jgl8c7s94adhsjlgcwsbc67d5arzjw3z1z4zh9gi8n0hrb") (f (quote (("no_empty_retwrap") ("default"))))))

(define-public crate-cglue-gen-0.1.4 (c (n "cglue-gen") (v "0.1.4") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0d15rdyk5yfki8lgk888pzric88158ldy0xdr5a2a28ii3cxclmb") (f (quote (("no_empty_retwrap") ("default"))))))

(define-public crate-cglue-gen-0.2.0 (c (n "cglue-gen") (v "0.2.0") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1s4fcakj51yhspz3qrkwz30hmky2ca6jh26f5b1aii4ih3rydxws") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.1 (c (n "cglue-gen") (v "0.2.1") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1m0wyc0xmn43s9w8zdk8w08m2l3fhg371d39vrl2wsq7bx5bzkjc") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.2 (c (n "cglue-gen") (v "0.2.2") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0kybwl20bfv9wxw26cd8911h4z2wyaijdi3kbahzgmgxvqpqqcgq") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.3 (c (n "cglue-gen") (v "0.2.3") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1hg7xzvjrf1vnxklmbcm7xz8hhbsxb2c86ym6lmp5m063fmsz4w6") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.4 (c (n "cglue-gen") (v "0.2.4") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0r6wxlihikq1hixywas6kswddbfjyxkcdv513vrc7w2wfg8b2ibd") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.5 (c (n "cglue-gen") (v "0.2.5") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r ">=1.1.3") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1c67z6jxncq2nh7b7k6q05sk0fii9z6fn28vysl8in5iq822ymy4") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.6 (c (n "cglue-gen") (v "0.2.6") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r ">=1.1.3") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1hgf2551kaxk688izrgsy4wm6k1niig0sk79sd6mbdjf2wkas36m") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default")))) (y #t)))

(define-public crate-cglue-gen-0.2.7 (c (n "cglue-gen") (v "0.2.7") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r ">=1.1.3") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1s7w5z22sd7apc1bwsdkgcbnlxyabz869yzaysgg5gkngsd5a4zp") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.8 (c (n "cglue-gen") (v "0.2.8") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r ">=1.1.3") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0q28ihfnkqb26b6rqqlydg98mf4kdm2vksr6k74s0knm1iwinfxv") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

(define-public crate-cglue-gen-0.2.9 (c (n "cglue-gen") (v "0.2.9") (d (list (d (n "itertools") (r "^0.10") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "proc-macro-crate") (r ">=1.1.3") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1n3ifgvvjdm01kmlw5k3qjzjbz0n4lwg8jmpjvnkj1dpdz23l489") (f (quote (("unstable") ("rust_void") ("layout_checks") ("default"))))))

