(define-module (crates-io be vy bevy_eventwork) #:use-module (crates-io))

(define-public crate-bevy_eventwork-0.6.0 (c (n "bevy_eventwork") (v "0.6.0") (d (list (d (n "async-channel") (r "^1.6.1") (d #t) (k 0)) (d (n "async-trait") (r "^0.1.52") (d #t) (k 0)) (d (n "bevy") (r "^0.6.1") (k 0)) (d (n "bevy") (r "^0.6") (d #t) (k 2)) (d (n "bincode") (r "^1.3.2") (d #t) (k 0)) (d (n "dashmap") (r "^4.0.2") (d #t) (k 0)) (d (n "derive_more") (r "^0.99.13") (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.24") (d #t) (k 0)))) (h "1x1d7j41jibr0np4kwlvdzsd1ywm4sqwbwf2nm6xfq2x1m3bby35")))

(define-public crate-bevy_eventwork-0.6.1 (c (n "bevy_eventwork") (v "0.6.1") (d (list (d (n "async-channel") (r "^1.6.1") (d #t) (k 0)) (d (n "async-net") (r "^1.6.1") (d #t) (k 0)) (d (n "async-trait") (r "^0.1.52") (d #t) (k 0)) (d (n "bevy") (r "^0.6.1") (k 0)) (d (n "bevy") (r "^0.6") (d #t) (k 2)) (d (n "bincode") (r "^1.3.2") (d #t) (k 0)) (d (n "dashmap") (r "^4.0.2") (d #t) (k 0)) (d (n "derive_more") (r "^0.99.13") (d #t) (k 0)) (d (n "futures-lite") (r "^1.12.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.24") (d #t) (k 0)))) (h "0czi9x6rvfnq46zs63ksyd3d1j2gjkjpvqwgv0dqcsfgp4k8gvb3") (f (quote (("tcp") ("default" "tcp"))))))

(define-public crate-bevy_eventwork-0.6.2 (c (n "bevy_eventwork") (v "0.6.2") (d (list (d (n "async-channel") (r "^1.6.1") (d #t) (k 0)) (d (n "async-net") (r "^1.6.1") (d #t) (k 0)) (d (n "async-trait") (r "^0.1.52") (d #t) (k 0)) (d (n "bevy") (r "^0.6.1") (k 0)) (d (n "bevy") (r "^0.6") (d #t) (k 2)) (d (n "bincode") (r "^1.3.2") (d #t) (k 0)) (d (n "dashmap") (r "^4.0.2") (d #t) (k 0)) (d (n "derive_more") (r "^0.99.13") (d #t) (k 0)) (d (n "futures-lite") (r "^1.12.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.24") (d #t) (k 0)))) (h "156ycl6sjq45i2jcsc0d71p7dhzvfs58vc4r5d76wlxfcfzb2mhh") (f (quote (("tcp") ("default" "tcp"))))))

(define-public crate-bevy_eventwork-0.7.0 (c (n "bevy_eventwork") (v "0.7.0") (d (list (d (n "async-channel") (r "^1.6.1") (d #t) (k 0)) (d (n "async-net") (r "^1.6.1") (d #t) (k 0)) (d (n "async-trait") (r "^0.1.52") (d #t) (k 0)) (d (n "bevy") (r ">0.6") (k 0)) (d (n "bevy") (r ">0.6") (d #t) (k 2)) (d (n "bincode") (r "^1.3.2") (d #t) (k 0)) (d (n "dashmap") (r "^4.0.2") (d #t) (k 0)) (d (n "derive_more") (r "^0.99.13") (d #t) (k 0)) (d (n "futures-lite") (r "^1.12.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.24") (d #t) (k 0)))) (h "1kn2cpd4jbk6np5yp6g9h7ymhgsw6ikqhq9rkg8v41d0bk7dlkpb") (f (quote (("tcp") ("default" "tcp"))))))

(define-public crate-bevy_eventwork-0.7.1 (c (n "bevy_eventwork") (v "0.7.1") (d (list (d (n "async-channel") (r "^1.6.1") (d #t) (k 0)) (d (n "async-net") (r "^1.6.1") (o #t) (d #t) (k 0)) (d (n "async-trait") (r "^0.1.52") (d #t) (k 0)) (d (n "bevy") (r ">0.6") (k 0)) (d (n "bevy") (r ">0.6") (d #t) (k 2)) (d (n "bincode") (r "^1.3.2") (d #t) (k 0)) (d (n "dashmap") (r "^4.0.2") (d #t) (k 0)) (d (n "futures-lite") (r "^1.12.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (f (quote ("derive"))) (d #t) (k 0)))) (h "0ghbzri6mk3m34j8v8ik07rx1wsqhxsihid8smqiv9rpnq1yi2aw") (f (quote (("tcp" "async-net") ("default" "tcp"))))))

(define-public crate-bevy_eventwork-0.7.2 (c (n "bevy_eventwork") (v "0.7.2") (d (list (d (n "async-channel") (r "^1.6.1") (d #t) (k 0)) (d (n "async-net") (r "^1.6.1") (o #t) (d #t) (k 0)) (d (n "async-trait") (r "^0.1.52") (d #t) (k 0)) (d (n "bevy") (r ">0.6") (k 0)) (d (n "bevy") (r ">0.6") (d #t) (k 2)) (d (n "bincode") (r "^1.3.2") (d #t) (k 0)) (d (n "dashmap") (r "^4.0.2") (d #t) (k 0)) (d (n "futures-lite") (r "^1.12.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (f (quote ("derive"))) (d #t) (k 0)))) (h "10xfr67k54ad42vqqczy29xqg7rwqkiibzhbagyvb9m2gi429x87") (f (quote (("tcp" "async-net") ("default" "tcp"))))))

(define-public crate-bevy_eventwork-0.8.0 (c (n "bevy_eventwork") (v "0.8.0") (d (list (d (n "async-channel") (r "^2.0.0") (d #t) (k 0)) (d (n "async-net") (r "^2.0.0") (o #t) (d #t) (k 0)) (d (n "async-trait") (r "^0.1.74") (d #t) (k 0)) (d (n "bevy") (r "^0.13.0") (f (quote ("multi-threaded"))) (k 0)) (d (n "bevy") (r "^0.13.0") (f (quote ("default_font"))) (d #t) (k 2)) (d (n "bincode") (r "^1.3.3") (d #t) (k 0)) (d (n "dashmap") (r "^5.5.3") (d #t) (k 0)) (d (n "futures-lite") (r "^2.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.190") (f (quote ("derive"))) (d #t) (k 0)))) (h "177mbvdy3jrs2gwgiyr2ja7j0q1fyxmnvkkhs8xhbz299l3jqzhm") (f (quote (("tcp" "async-net") ("default" "tcp"))))))

