(define-module (crates-io gh -c gh-config) #:use-module (crates-io))

(define-public crate-gh-config-0.1.0 (c (n "gh-config") (v "0.1.0") (d (list (d (n "dirs") (r "^4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0s303cq03ckpw4a62m2w2ra0b4b3hnydm33rp0x7bphlzrsnswig")))

(define-public crate-gh-config-0.1.1 (c (n "gh-config") (v "0.1.1") (d (list (d (n "dirs") (r "^4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0wbdgi082621dybkcp38dfacg5rq7ldpr1k4s1gqj6zz5biiwvf8")))

(define-public crate-gh-config-0.2.0 (c (n "gh-config") (v "0.2.0") (d (list (d (n "anyhow") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "clap") (r "^3.2") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "180a5xnbl5rhskl7lbsisaars7rn7j0nw39iqvh3qkxj0g2fmi05") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json")))) (y #t)))

(define-public crate-gh-config-0.2.1 (c (n "gh-config") (v "0.2.1") (d (list (d (n "anyhow") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "clap") (r "^3.2") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "08p8d7fxyygr41pkcf5ig7hv6nw6y50jvdgf07ay41k7dh0zblwm") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json"))))))

(define-public crate-gh-config-0.2.2 (c (n "gh-config") (v "0.2.2") (d (list (d (n "anyhow") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "base64") (r "^0.21.0") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "clap") (r "^4.4") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^5.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "secret-service") (r "^3.0") (f (quote ("rt-async-io-crypto-rust"))) (d #t) (t "cfg(target_os = \"linux\")") (k 0)) (d (n "security-framework") (r "^2.8") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "windows") (r "^0.46.0") (f (quote ("Win32_Foundation" "Win32_Security_Credentials"))) (d #t) (t "cfg(target_os = \"windows\")") (k 0)))) (h "1qk97p6znh4xd5842dd6wbmxggn5d4cm0wmnhjqf1gw3bnn29yg6") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json"))))))

(define-public crate-gh-config-0.3.0 (c (n "gh-config") (v "0.3.0") (d (list (d (n "anyhow") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "base64") (r "^0.21.4") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "clap") (r "^4.4") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^5.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "secret-service") (r "^3.0") (f (quote ("rt-async-io-crypto-rust"))) (d #t) (t "cfg(target_os = \"linux\")") (k 0)) (d (n "security-framework") (r "^2.9") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "windows") (r "^0.51.1") (f (quote ("Win32_Foundation" "Win32_Security_Credentials"))) (d #t) (t "cfg(target_os = \"windows\")") (k 0)))) (h "12l3xc21zw2sp8qlxm6b7lrvsgxrr3kjl9xzh7d7q8mnswbd4wsi") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json"))))))

(define-public crate-gh-config-0.3.1 (c (n "gh-config") (v "0.3.1") (d (list (d (n "anyhow") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "base64") (r "^0.21.5") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "clap") (r "^4.4") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^5.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "secret-service") (r "^3.0") (f (quote ("rt-async-io-crypto-rust"))) (d #t) (t "cfg(target_os = \"linux\")") (k 0)) (d (n "security-framework") (r "^2.9") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "windows") (r "^0.52.0") (f (quote ("Win32_Foundation" "Win32_Security_Credentials"))) (d #t) (t "cfg(target_os = \"windows\")") (k 0)))) (h "12b7vmq9armjmw4x2s7vgcb051c7m7jldi60n4mzwba6kc3fr0yl") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json"))))))

(define-public crate-gh-config-0.3.2 (c (n "gh-config") (v "0.3.2") (d (list (d (n "anyhow") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "base64") (r "^0.22.0") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "clap") (r "^4.5") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^5.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "secret-service") (r "^3.0") (f (quote ("rt-async-io-crypto-rust"))) (d #t) (t "cfg(target_os = \"linux\")") (k 0)) (d (n "security-framework") (r "^2.9") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)) (d (n "windows") (r "^0.54.0") (f (quote ("Win32_Foundation" "Win32_Security_Credentials"))) (d #t) (t "cfg(target_os = \"windows\")") (k 0)))) (h "07w5gwr5f0lgmxzpnc4vm1l1dmyyvb1aaxvdbs9nwvmxy7wynf30") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json"))))))

(define-public crate-gh-config-0.4.0 (c (n "gh-config") (v "0.4.0") (d (list (d (n "anyhow") (r "^1.0.86") (o #t) (d #t) (k 0)) (d (n "base64") (r "^0.22.1") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "clap") (r "^4.5.4") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "dirs") (r "^5.0.1") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "secret-service") (r "^3.0.1") (f (quote ("rt-async-io-crypto-rust"))) (d #t) (t "cfg(target_os = \"linux\")") (k 0)) (d (n "security-framework") (r "^2.11") (d #t) (t "cfg(target_os = \"macos\")") (k 0)) (d (n "serde") (r "^1.0.202") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.117") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.61") (d #t) (k 0)) (d (n "windows") (r "^0.56.0") (f (quote ("Win32_Foundation" "Win32_Security_Credentials"))) (d #t) (t "cfg(target_os = \"windows\")") (k 0)))) (h "09jjh808gddvadg2an6n55zb3adj60ppk2r5avhsygv4pjz1aicq") (f (quote (("default") ("cli" "anyhow" "clap" "serde_json"))))))

