(define-module (crates-io ft d- ftd-rt) #:use-module (crates-io))

(define-public crate-ftd-rt-0.1.0 (c (n "ftd-rt") (v "0.1.0") (d (list (d (n "console_error_panic_hook") (r "^0.1.6") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.74") (f (quote ("serde-serialize"))) (o #t) (d #t) (k 0)) (d (n "web-sys") (r "^0.3.51") (f (quote ("Document" "Element" "HtmlElement" "Node" "Window"))) (o #t) (d #t) (k 0)))) (h "1ggqmq07shxsv4rmg4qxgpgm7psbhkp37aarvy6vlv3z4rd1ilg9") (f (quote (("wasm" "console_error_panic_hook" "wasm-bindgen" "web-sys") ("default"))))))

(define-public crate-ftd-rt-0.1.1 (c (n "ftd-rt") (v "0.1.1") (d (list (d (n "console_error_panic_hook") (r "^0.1.6") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.74") (f (quote ("serde-serialize"))) (o #t) (d #t) (k 0)) (d (n "web-sys") (r "^0.3.51") (f (quote ("Document" "Element" "HtmlElement" "Node" "Window"))) (o #t) (d #t) (k 0)))) (h "1fkrskvk3k7yznhnwy3x6pirkafhbfy6if031dwabzabj8avrp92") (f (quote (("wasm" "console_error_panic_hook" "wasm-bindgen" "web-sys") ("realm") ("default" "realm"))))))

(define-public crate-ftd-rt-0.1.2 (c (n "ftd-rt") (v "0.1.2") (d (list (d (n "console_error_panic_hook") (r "^0.1.6") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.74") (f (quote ("serde-serialize"))) (o #t) (d #t) (k 0)) (d (n "web-sys") (r "^0.3.51") (f (quote ("Document" "Element" "HtmlElement" "Node" "Window"))) (o #t) (d #t) (k 0)))) (h "03c5lvc746jlvxk1467j0z82cg4gaiij9bkdf241bwmcah3lasds") (f (quote (("wasm" "console_error_panic_hook" "wasm-bindgen" "web-sys") ("realm") ("default" "realm"))))))

(define-public crate-ftd-rt-0.1.4 (c (n "ftd-rt") (v "0.1.4") (d (list (d (n "console_error_panic_hook") (r "^0.1.6") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.74") (f (quote ("serde-serialize"))) (o #t) (d #t) (k 0)) (d (n "web-sys") (r "^0.3.51") (f (quote ("Document" "Element" "HtmlElement" "Node" "Window"))) (o #t) (d #t) (k 0)))) (h "101g6ss38iqvs4z0zarzn5m6mqha6a660xndchspnwypl2d9wk90") (f (quote (("wasm" "console_error_panic_hook" "wasm-bindgen" "web-sys") ("realm") ("default" "realm"))))))

(define-public crate-ftd-rt-0.1.5 (c (n "ftd-rt") (v "0.1.5") (d (list (d (n "console_error_panic_hook") (r "^0.1.6") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.74") (f (quote ("serde-serialize"))) (o #t) (d #t) (k 0)) (d (n "web-sys") (r "^0.3.51") (f (quote ("Document" "Element" "HtmlElement" "Node" "Window"))) (o #t) (d #t) (k 0)))) (h "13y4c2drx16h6xk85fmj113rxn0mnadlkh305f5xq3r7zamkf1mm") (f (quote (("wasm" "console_error_panic_hook" "wasm-bindgen" "web-sys") ("realm") ("default" "realm"))))))

