(define-module (crates-io em pt empty_type_derive) #:use-module (crates-io))

(define-public crate-empty_type_derive-0.1.0 (c (n "empty_type_derive") (v "0.1.0") (d (list (d (n "empty_type_traits") (r "^0.1.0") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1.0") (f (quote ("full"))) (d #t) (k 0)))) (h "1gqnwbwg3wwdnqi3lprmafaccr97143fnnn9prfvvljx7mnmfc5n") (s 2) (e (quote (("serde" "dep:serde" "serde/derive" "empty_type_traits/serde"))))))

(define-public crate-empty_type_derive-0.2.0 (c (n "empty_type_derive") (v "0.2.0") (d (list (d (n "empty_type") (r "^0.2.0") (d #t) (k 0) (p "empty_type_traits")) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1mk3fjynwn6dzp6wplxybv9wc721gj9sr99x4h236j0ybfd9ps6z") (s 2) (e (quote (("serde" "dep:serde" "serde/derive" "empty_type/serde"))))))

(define-public crate-empty_type_derive-0.2.1 (c (n "empty_type_derive") (v "0.2.1") (d (list (d (n "empty_type") (r "^0.2.1") (d #t) (k 0) (p "empty_type_traits")) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "1in487h8s2k07rp56zkwnmyph5z91vr0268g7rww2ggxbzar1dis") (s 2) (e (quote (("serde" "dep:serde" "serde/derive" "empty_type/serde"))))))

(define-public crate-empty_type_derive-0.2.2 (c (n "empty_type_derive") (v "0.2.2") (d (list (d (n "empty_type") (r "^0.2.1") (d #t) (k 0) (p "empty_type_traits")) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0xf5k67hj0x846d23w86z4abr0hr6xvfcd9b7f6zivxds0dy3l05") (s 2) (e (quote (("serde" "dep:serde" "serde/derive" "empty_type/serde"))))))

(define-public crate-empty_type_derive-0.2.3 (c (n "empty_type_derive") (v "0.2.3") (d (list (d (n "empty_type") (r "^0.2.1") (d #t) (k 0) (p "empty_type_traits")) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits"))) (d #t) (k 0)))) (h "0dckxvm94jvavhqa0gw37rpnvpfac6yqjqw80fcx5zxn7al1479x") (s 2) (e (quote (("serde" "dep:serde" "serde/derive" "empty_type/serde"))))))

