(define-module (crates-io de fa default-net) #:use-module (crates-io))

(define-public crate-default-net-0.1.0 (c (n "default-net") (v "0.1.0") (d (list (d (n "pnet") (r "^0.26") (d #t) (k 0)))) (h "0dbcd2bknvbc2vhwb8k2a2cs80a17cfap53gj55sk51wnaprm5n5") (y #t)))

(define-public crate-default-net-0.1.1 (c (n "default-net") (v "0.1.1") (d (list (d (n "pnet") (r "^0.26") (d #t) (k 0)))) (h "08rgpz60pv4xkdfqjdpbcrcdy5wrjkkxyvz2jgqr0iclf4d2w71d") (y #t)))

(define-public crate-default-net-0.2.0 (c (n "default-net") (v "0.2.0") (d (list (d (n "pnet") (r "^0.26") (d #t) (t "cfg(target_os = \"windows\")") (k 0)) (d (n "pnet") (r "^0.27") (d #t) (t "cfg(not(windows))") (k 0)))) (h "1y3596fj4g0f1infs919pvzjiwhm7di9wf71qvd40vmg593v3hpv") (y #t)))

(define-public crate-default-net-0.2.1 (c (n "default-net") (v "0.2.1") (d (list (d (n "pnet") (r "^0.26") (d #t) (k 0)))) (h "015bcj6maf84hnc9a7ang6yqzl87ck37kfn77b5fk59zgpk0c0mz") (y #t)))

(define-public crate-default-net-0.3.0 (c (n "default-net") (v "0.3.0") (d (list (d (n "pnet") (r "^0.28") (d #t) (k 0)) (d (n "winapi") (r "^0.3.8") (f (quote ("std"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0rw4m6v1f2fnq62x72560qxpzyybfndlmg71x4k3k9k2wwaibakc") (y #t)))

(define-public crate-default-net-0.4.0 (c (n "default-net") (v "0.4.0") (d (list (d (n "pnet") (r "^0.28") (d #t) (k 0)) (d (n "winapi") (r "^0.3.9") (f (quote ("std"))) (d #t) (t "cfg(windows)") (k 0)))) (h "103m0b1h7rb99vxnn77rwwii595xs46nq9yg89d8g0crqx8rprhv") (y #t)))

(define-public crate-default-net-0.5.0 (c (n "default-net") (v "0.5.0") (d (list (d (n "pnet_datalink") (r "^0.28") (d #t) (k 0)) (d (n "pnet_packet") (r "^0.28") (d #t) (k 0)) (d (n "winapi") (r "^0.3.9") (f (quote ("std"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0hfl6kkzdhpalmn5jmmni15q18k8n4fbdsfc0920w0fpx1dzr8k1")))

(define-public crate-default-net-0.6.0 (c (n "default-net") (v "0.6.0") (d (list (d (n "pnet_datalink") (r "^0.28") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "pnet_packet") (r "^0.28") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "windows") (r "^0.29.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1lr0l7fq3x6w81j1jb77m48yh2p0ni5z33xp8ynwb6s5n42xhxjy")))

(define-public crate-default-net-0.7.0 (c (n "default-net") (v "0.7.0") (d (list (d (n "libc") (r "^0.2") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "windows") (r "^0.29.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1n1xa33biy3dy6c0c2blg8am3df67gl0f86hqsngdmg9qrj7srla")))

(define-public crate-default-net-0.8.0 (c (n "default-net") (v "0.8.0") (d (list (d (n "libc") (r "^0.2") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "windows") (r "^0.29.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper"))) (d #t) (t "cfg(windows)") (k 0)))) (h "01sw8i11ydg2ckdnc4crfyfxwwb5mdfd720sgvvi520f1fk2yqxi")))

(define-public crate-default-net-0.8.1 (c (n "default-net") (v "0.8.1") (d (list (d (n "libc") (r "^0.2") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "windows") (r "^0.29.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1pn09ad3ls4agaq6y07aj2mrqf4qrmxrx3g8bcmddvyn3kwzkvlq")))

(define-public crate-default-net-0.8.2 (c (n "default-net") (v "0.8.2") (d (list (d (n "libc") (r "^0.2") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "windows") (r "^0.29.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper"))) (d #t) (t "cfg(windows)") (k 0)))) (h "15rzxpglgv9c3841h07vbqdkvs2kj3d43w91mqyvpps7s9j2bh5l")))

(define-public crate-default-net-0.9.0 (c (n "default-net") (v "0.9.0") (d (list (d (n "libc") (r "^0.2") (d #t) (t "cfg(not(windows))") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.29.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0byn6qkm4ylnk02v7liyn94rzpp1g9fcqwdbd4k5xh7n8p3gn0cv")))

(define-public crate-default-net-0.10.0 (c (n "default-net") (v "0.10.0") (d (list (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.30.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "13y0ymwh9mnlgmyldkyr8qsg1cd6psg0fpafpl79rmmw89q0a5cd")))

(define-public crate-default-net-0.11.0 (c (n "default-net") (v "0.11.0") (d (list (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.30.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0imn9lqra4hcx2nl6ji2n7yhv25n0jxv6lanr0ifg90b3d3hvrq5")))

(define-public crate-default-net-0.12.0 (c (n "default-net") (v "0.12.0") (d (list (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.30.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0qrs0vy6x0dys9fhf0493srp3xjw6xvaddfqgm539yq63vnlkqql")))

(define-public crate-default-net-0.13.0 (c (n "default-net") (v "0.13.0") (d (list (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.32.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0hz0x6yz48n1a0qnr62qw0p1msdln2fciq0p8bxxxhi4m9x4y1cv")))

(define-public crate-default-net-0.13.1 (c (n "default-net") (v "0.13.1") (d (list (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.32.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0lddbvpafd4dr5576brh2wj21n441a8k6ag4vxg9dk12p8pypk8j")))

(define-public crate-default-net-0.14.0 (c (n "default-net") (v "0.14.0") (d (list (d (n "dlopen2") (r "^0.4") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.5") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.15") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.32.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1jf4n53qibqs2kw0279pk49s3673gadp89c9m4lm50dvdg68vvqj")))

(define-public crate-default-net-0.14.1 (c (n "default-net") (v "0.14.1") (d (list (d (n "dlopen2") (r "^0.4") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.5") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.15") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.32.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock"))) (d #t) (t "cfg(windows)") (k 0)))) (h "00z0hjh8rqxablp4kgvrh3v1v9bn7rdx355jsvx9jr6mmr1qp2d4")))

(define-public crate-default-net-0.15.0 (c (n "default-net") (v "0.15.0") (d (list (d (n "dlopen2") (r "^0.4") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.5") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.15") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.0") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1ffnvs24slw2p0l2k6v2pw3g1gixmyqyljc8wzisk0lvgb658qmh")))

(define-public crate-default-net-0.16.0 (c (n "default-net") (v "0.16.0") (d (list (d (n "dlopen2") (r "^0.4") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.5") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.15") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0agpxdlvg7sn2s8jaim1x60fjp5pdw8bw56acnaiplz1xy333f2k") (y #t)))

(define-public crate-default-net-0.16.1 (c (n "default-net") (v "0.16.1") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "11qn6j5iknrc6hk060661s2rr8a0y9gxw80fz2xvl63lw8g40ixf") (y #t)))

(define-public crate-default-net-0.16.2 (c (n "default-net") (v "0.16.2") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "037k0p8gxx0yg2s19b91jcl1f0fgj6dwrxr42cxgc4c59c0m7rfg")))

(define-public crate-default-net-0.17.0 (c (n "default-net") (v "0.17.0") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "09jm32s4pj2f7bfxpr1j0pdmws1bk39sw8k5hlk5ri00fwzvklfm")))

(define-public crate-default-net-0.18.0 (c (n "default-net") (v "0.18.0") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0f2hjmsginwf7d1anr23nj73g9c56jj65zhbayy61nazyi2fczi6")))

(define-public crate-default-net-0.19.0 (c (n "default-net") (v "0.19.0") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1qmqvzgkw9qzwysy3la55smanhqgvp17733qwx4cwd798hkllza0") (s 2) (e (quote (("serde" "dep:serde"))))))

(define-public crate-default-net-0.20.0 (c (n "default-net") (v "0.20.0") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1gq53vraf4igaagvv5a4znxkhvfz3kmjjbpxcr68byi79bc2k93v") (s 2) (e (quote (("serde" "dep:serde"))))))

(define-public crate-default-net-0.21.0 (c (n "default-net") (v "0.21.0") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "1sskiryld57f2l7qanvrlh5rfv0gdp969p34mn33qv9lv1v7bp45") (s 2) (e (quote (("serde" "dep:serde"))))))

(define-public crate-default-net-0.22.0 (c (n "default-net") (v "0.22.0") (d (list (d (n "dlopen2") (r "^0.5") (t "cfg(target_os = \"android\")") (k 0)) (d (n "libc") (r "^0.2") (d #t) (k 0)) (d (n "memalloc") (r "^0.1.0") (d #t) (t "cfg(windows)") (k 0)) (d (n "netlink-packet-core") (r "^0.7") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-packet-route") (r "^0.17") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "netlink-sys") (r "^0.8") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "once_cell") (r "^1") (d #t) (t "cfg(target_os = \"android\")") (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 2)) (d (n "system-configuration") (r "^0.5.1") (d #t) (t "cfg(any(target_os = \"macos\", target_os = \"ios\"))") (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Foundation" "Win32_NetworkManagement_IpHelper" "Win32_Networking_WinSock" "Win32_NetworkManagement_Ndis"))) (d #t) (t "cfg(windows)") (k 0)))) (h "0rnafc5z04wbr4qzsqkmv761xjlssqbcbcqdn54lsd88m5lnanhc") (s 2) (e (quote (("serde" "dep:serde"))))))

