(define-module (crates-io ap pl apply-license) #:use-module (crates-io))

(define-public crate-apply-license-0.1.0 (c (n "apply-license") (v "0.1.0") (d (list (d (n "cargo_metadata") (r "^0.5") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "clap") (r "^2") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "handlebars") (r "^0.32") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "structopt") (r "^0.2") (d #t) (k 0)) (d (n "toml") (r "^0.4") (d #t) (k 0)) (d (n "toml_edit") (r "^0.1") (d #t) (k 0)))) (h "0rapagiq8xbpbrvv8f3q8h7wcb7ayhjiv8xpz02fyh0a9zxn3a53")))

(define-public crate-apply-license-0.2.0 (c (n "apply-license") (v "0.2.0") (d (list (d (n "cargo_metadata") (r "^0.5") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "clap") (r "^2") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "handlebars") (r "^0.32") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "structopt") (r "^0.2") (d #t) (k 0)) (d (n "toml") (r "^0.4") (d #t) (k 0)) (d (n "toml_edit") (r "^0.1") (d #t) (k 0)))) (h "0i9m1hx9pnybba6nrv6692x5czxyvgvvdw6k3pmp9pgb471rn3gs")))

(define-public crate-apply-license-0.3.0 (c (n "apply-license") (v "0.3.0") (d (list (d (n "anyhow") (r "^1.0.55") (d #t) (k 0)) (d (n "assert_cmd") (r "^2.0.4") (d #t) (k 2)) (d (n "cargo_metadata") (r "^0.14.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "clap") (r "^3.1.5") (f (quote ("derive"))) (d #t) (k 0)) (d (n "handlebars") (r "^4.2.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.10.0") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "tempfile") (r "^3.3.0") (d #t) (k 2)) (d (n "toml_edit") (r "^0.13.4") (f (quote ("easy"))) (d #t) (k 0)))) (h "0d2s92bx7x9fd0a3ywif3w2n6h2xdqki86s4z3ijsm7pv2k82gi3")))

(define-public crate-apply-license-0.3.1 (c (n "apply-license") (v "0.3.1") (d (list (d (n "anyhow") (r "^1.0.55") (d #t) (k 0)) (d (n "assert_cmd") (r "^2.0.4") (d #t) (k 2)) (d (n "cargo_metadata") (r "^0.14.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "clap") (r "^3.1.5") (f (quote ("derive"))) (d #t) (k 0)) (d (n "handlebars") (r "^4.2.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.10.0") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "tempfile") (r "^3.3.0") (d #t) (k 2)) (d (n "toml_edit") (r "^0.13.4") (f (quote ("easy"))) (d #t) (k 0)))) (h "1wh1p9vcq46g7p8smnqz16gr4g5vzrwb0lli2sva95xap7fjlgrj")))

