(define-module (crates-io so da sodaq_one) #:use-module (crates-io))

(define-public crate-sodaq_one-0.1.1 (c (n "sodaq_one") (v "0.1.1") (d (list (d (n "atsamd-hal") (r "~0.4") (k 0)) (d (n "cortex-m") (r "~0.5") (d #t) (k 0)) (d (n "cortex-m-rt") (r "~0.6") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "~0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "~0.2") (d #t) (k 0)) (d (n "nb") (r "~0.1") (d #t) (k 0)) (d (n "panic-halt") (r "~0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "~0.5") (d #t) (k 2)))) (h "0411x4wlgmraiiqmc19hw8s72aygcycix1z46qsj87vj3pyl4p01") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g18a-rt") ("default" "rt" "atsamd-hal/samd21g18a"))))))

(define-public crate-sodaq_one-0.2.0 (c (n "sodaq_one") (v "0.2.0") (d (list (d (n "atsamd-hal") (r "~0.5") (k 0)) (d (n "cortex-m") (r "~0.5") (d #t) (k 0)) (d (n "cortex-m-rt") (r "~0.6") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "~0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "~0.2") (d #t) (k 0)) (d (n "nb") (r "~0.1") (d #t) (k 0)) (d (n "panic-halt") (r "~0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "~0.5") (d #t) (k 2)))) (h "19zzsk14mcgyaxs3cndxnw2nikzzbfnv98qmna438p98r6lmbzql") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g18a-rt") ("default" "rt" "atsamd-hal/samd21g18a"))))))

(define-public crate-sodaq_one-0.3.0 (c (n "sodaq_one") (v "0.3.0") (d (list (d (n "atsamd-hal") (r "~0.6") (k 0)) (d (n "cortex-m") (r "~0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "~0.6") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "~0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "~0.2") (d #t) (k 0)) (d (n "nb") (r "~0.1") (d #t) (k 0)) (d (n "panic-halt") (r "~0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "~0.5") (d #t) (k 2)))) (h "0jjl8vkkmrka6zy7pghy96pw5wg56xffn3qba4vh3vb4cww3f8bs") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g18a-rt") ("default" "rt" "atsamd-hal/samd21g18a"))))))

(define-public crate-sodaq_one-0.4.0 (c (n "sodaq_one") (v "0.4.0") (d (list (d (n "atsamd-hal") (r "~0.7") (k 0)) (d (n "cortex-m") (r "~0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "~0.6") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "~0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "~0.2") (d #t) (k 0)) (d (n "nb") (r "~0.1") (d #t) (k 0)) (d (n "panic-halt") (r "~0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "~0.5") (d #t) (k 2)))) (h "0j7hfcjirrawsi4msvgq7r422ha1cchda6gm6hakd7is08b65fl8") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g18a-rt") ("default" "rt" "atsamd-hal/samd21g18a"))))))

(define-public crate-sodaq_one-0.5.0 (c (n "sodaq_one") (v "0.5.0") (d (list (d (n "atsamd-hal") (r "~0.8") (k 0)) (d (n "cortex-m") (r "~0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "~0.6") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "~0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "~0.2") (d #t) (k 0)) (d (n "nb") (r "~0.1") (d #t) (k 0)) (d (n "panic-halt") (r "~0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "~0.5") (d #t) (k 2)))) (h "148j56mlq46ff3a1g51jkv073b0b3x513hcpfxfmkx0zxnwplb24") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g18a-rt") ("default" "rt" "atsamd-hal/samd21g18a"))))))

(define-public crate-sodaq_one-0.6.0 (c (n "sodaq_one") (v "0.6.0") (d (list (d (n "atsamd-hal") (r "~0.9") (k 0)) (d (n "cortex-m") (r "~0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "~0.6.12") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "~0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "~0.2.3") (d #t) (k 0)) (d (n "nb") (r "~0.1") (d #t) (k 0)) (d (n "panic-halt") (r "~0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "~0.5") (d #t) (k 2)))) (h "04i4jv8xggw3lykzqzpmz5g3p44f13n15jnspfmmi4ia84zsbmnx") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g18a-rt") ("default" "rt" "atsamd-hal/samd21g18a"))))))

(define-public crate-sodaq_one-0.6.1 (c (n "sodaq_one") (v "0.6.1") (d (list (d (n "atsamd-hal") (r "^0.10") (k 0)) (d (n "cortex-m") (r "^0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "^0.6.12") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "^0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "^0.2.3") (d #t) (k 0)) (d (n "nb") (r "^0.1") (d #t) (k 0)) (d (n "panic-halt") (r "^0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "^0.5") (d #t) (k 2)))) (h "0zpp5xb9qj9ni5dy7ml8wdb76lr9ag8y479k29hhnj5z9m2haypz") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g-rt") ("default" "rt" "atsamd-hal/samd21g"))))))

(define-public crate-sodaq_one-0.7.0 (c (n "sodaq_one") (v "0.7.0") (d (list (d (n "atsamd-hal") (r "^0.11") (k 0)) (d (n "cortex-m") (r "^0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "^0.6.12") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "^0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "^0.2.3") (d #t) (k 0)) (d (n "nb") (r "^0.1") (d #t) (k 0)) (d (n "panic-halt") (r "^0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "^0.5") (d #t) (k 2)))) (h "081yy2vznkc2cn033v2w9h40xkc5xarmsgs4087aw8f0772jq7xi") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g-rt") ("default" "rt" "atsamd-hal/samd21g"))))))

(define-public crate-sodaq_one-0.8.0 (c (n "sodaq_one") (v "0.8.0") (d (list (d (n "atsamd-hal") (r "^0.12") (k 0)) (d (n "cortex-m") (r "^0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "^0.6.12") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "^0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "^0.2.3") (d #t) (k 0)) (d (n "nb") (r "^0.1") (d #t) (k 0)) (d (n "panic-halt") (r "^0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "^0.5") (d #t) (k 2)))) (h "1wsrqxf5bnzj3hj7k6m6dqz66wkg8cxp497n7cf5fyqqrs8cr2b4") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g-rt") ("default" "rt" "atsamd-hal/samd21g"))))))

(define-public crate-sodaq_one-0.9.0 (c (n "sodaq_one") (v "0.9.0") (d (list (d (n "atsamd-hal") (r "^0.13") (k 0)) (d (n "cortex-m") (r "^0.6") (d #t) (k 0)) (d (n "cortex-m-rt") (r "^0.6.12") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "^0.3") (d #t) (k 2)) (d (n "embedded-hal") (r "^0.2.3") (d #t) (k 0)) (d (n "nb") (r "^0.1") (d #t) (k 0)) (d (n "panic-halt") (r "^0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "^0.5") (d #t) (k 2)))) (h "1vpk243cfahc4k3vny6dqghamcaskqrmcdrahwgklgc1vxyc1khj") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g-rt") ("default" "rt" "atsamd-hal/samd21g"))))))

(define-public crate-sodaq_one-0.10.0 (c (n "sodaq_one") (v "0.10.0") (d (list (d (n "atsamd-hal") (r "^0.14") (k 0)) (d (n "cortex-m-rt") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "cortex-m-semihosting") (r "^0.3") (d #t) (k 2)) (d (n "panic-halt") (r "^0.2") (d #t) (k 2)) (d (n "panic-semihosting") (r "^0.5") (d #t) (k 2)))) (h "0xv8dpi4c18rw458sc53axcm790068p99yx6x3wqvpkd27y1svdd") (f (quote (("use_semihosting") ("use_rtt" "atsamd-hal/use_rtt") ("unproven" "atsamd-hal/unproven") ("rt" "cortex-m-rt" "atsamd-hal/samd21g-rt") ("default" "rt" "atsamd-hal/samd21g"))))))

