(define-module (crates-io js on json-syntax) #:use-module (crates-io))

(define-public crate-json-syntax-0.1.0 (c (n "json-syntax") (v "0.1.0") (d (list (d (n "decoded-char") (r "^0.1.0") (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.1.0") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.5.2") (d #t) (k 0)) (d (n "smallstr") (r "^0.3.0") (d #t) (k 0)) (d (n "smallvec") (r "^1.9.0") (d #t) (k 0)))) (h "00j13k3w77lc2wwgpmsl2rgbbrz000jd7w5xz4k8qyn19n2fy2va") (y #t)))

(define-public crate-json-syntax-0.2.0 (c (n "json-syntax") (v "0.2.0") (d (list (d (n "decoded-char") (r "^0.1.0") (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.1.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.6.0") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3.0") (d #t) (k 0)) (d (n "smallvec") (r "^1.9.0") (d #t) (k 0)))) (h "1pmbcv0pkkl3j1cigl1nvmcddcjd7af2lwmijaibif9scmkbd6c2") (y #t)))

(define-public crate-json-syntax-0.3.0 (c (n "json-syntax") (v "0.3.0") (d (list (d (n "decoded-char") (r "^0.1.0") (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.2.0") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3.0") (d #t) (k 0)) (d (n "smallvec") (r "^1.9.0") (d #t) (k 0)))) (h "1grbdwsb9svwmvyvg3kr24z4s0fng6fvdrnjzjrcj5wyjy5l7akh") (y #t)))

(define-public crate-json-syntax-0.3.1 (c (n "json-syntax") (v "0.3.1") (d (list (d (n "decoded-char") (r "^0.1.0") (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.2.0") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3.0") (d #t) (k 0)) (d (n "smallvec") (r "^1.9.0") (d #t) (k 0)))) (h "002lawgil06w5jqvfhpyyxcvhf08gr19amz0g7lnmppnwmhyhzhs") (y #t)))

(define-public crate-json-syntax-0.4.0 (c (n "json-syntax") (v "0.4.0") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0rrc215v7l0p4jkzfansy83d0rnqghydxj0ipf8y28w4c71aplrw") (y #t)))

(define-public crate-json-syntax-0.5.0 (c (n "json-syntax") (v "0.5.0") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "11r0ch3s1cc2srx4zxg7vn8gr324amx0w7x6cd13fp00lmwj93aw") (y #t)))

(define-public crate-json-syntax-0.5.1 (c (n "json-syntax") (v "0.5.1") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1rpaxyyv8ib2va1s225k0h9s74p3d1b6xhlwfqxv6cs49p16mpkv") (y #t)))

(define-public crate-json-syntax-0.5.2 (c (n "json-syntax") (v "0.5.2") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1hhrxf4ym8wzns8bhwxhv3lcrgy7clsjm82ahazgw3xk233qnckq") (y #t)))

(define-public crate-json-syntax-0.5.3 (c (n "json-syntax") (v "0.5.3") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0vqjxqjibj8fq9dax9vyaz42bb8cnwd3vmvsr5wpyyyz0352jqq1") (y #t)))

(define-public crate-json-syntax-0.5.4 (c (n "json-syntax") (v "0.5.4") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "04c1g6siy487c1ccja6p5bhwadyam9l9li944jm0xg0yc4zm6izv") (y #t)))

(define-public crate-json-syntax-0.6.0 (c (n "json-syntax") (v "0.6.0") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "142ylljrv56h8m1c9v7gklphjr8rj89f13zx819r0m550irgmsxj") (y #t)))

(define-public crate-json-syntax-0.6.1 (c (n "json-syntax") (v "0.6.1") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0h9pj6mz8wwmn6pr9qjhgnr3zhclzh656ngrzihy7xc2ichgcm39") (y #t)))

(define-public crate-json-syntax-0.6.2 (c (n "json-syntax") (v "0.6.2") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "114n72hyrjafdfg8rlv51ahl24k3rhyb9j5cv7wj797gfr57dmha") (y #t)))

(define-public crate-json-syntax-0.6.3 (c (n "json-syntax") (v "0.6.3") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1n8mlbrgyh7awi94gklb48zx9wv69j2wb9zlps704nx54hpmqrsn") (y #t)))

(define-public crate-json-syntax-0.6.5 (c (n "json-syntax") (v "0.6.5") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0kngi63i2zgbzngbj7yy5q3jp0gk5ims6s949gb1qg5swqynrnyg") (y #t)))

(define-public crate-json-syntax-0.6.6 (c (n "json-syntax") (v "0.6.6") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "08i3kc47s5nam7ills3swskbcwgm63xw2dvl6j07qln9jhbsh7xa") (y #t)))

(define-public crate-json-syntax-0.6.7 (c (n "json-syntax") (v "0.6.7") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.3.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "04zj8s9fklh4lqrsvzybmsqjqglfdqgd735z28ywrk3hpglri32p") (y #t)))

(define-public crate-json-syntax-0.7.0 (c (n "json-syntax") (v "0.7.0") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0kz3k4245n6zd4glgpd8d371viqx0fbrai4cw8576424nvpn2w8x") (y #t)))

(define-public crate-json-syntax-0.7.1 (c (n "json-syntax") (v "0.7.1") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0i4a54f07rr62xfp4ph655m40v2qv8cg710a1rxkjlcqb7jp45aq") (y #t)))

(define-public crate-json-syntax-0.8.0 (c (n "json-syntax") (v "0.8.0") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "07hxy6ckb4mwcj6gzdw60spdlppzjnj5kqpjicv2r0zb552329w6") (y #t)))

(define-public crate-json-syntax-0.8.1 (c (n "json-syntax") (v "0.8.1") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0lc36knxvwv4pk9dyxjjmpvsbm7n5n0gwcg1d9bhwvp3pc8ckz22") (y #t)))

(define-public crate-json-syntax-0.8.2 (c (n "json-syntax") (v "0.8.2") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "009wqjclp5pr5nf861ylmi45qifh14m5nmz8aac748085x2l4li2") (y #t)))

(define-public crate-json-syntax-0.8.3 (c (n "json-syntax") (v "0.8.3") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0lhlzhbrfzrc7cz48z52sagj842g9r8bzvrpxxlidi3h1k19hxim") (y #t)))

(define-public crate-json-syntax-0.8.4 (c (n "json-syntax") (v "0.8.4") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0768hyasqyxgmrzapgpvflmsia4cpk3g9ricsvy0nxh096s01i10") (y #t)))

(define-public crate-json-syntax-0.8.5 (c (n "json-syntax") (v "0.8.5") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "10ssmwpljqj2ch1dsn767sk9nwnlsxbk5lq9y5h8yc23zsnn4wva")))

(define-public crate-json-syntax-0.8.6 (c (n "json-syntax") (v "0.8.6") (d (list (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "01mjndldc2hmpvkzjhvgyvgql45v34px8hivmi1xq0jvi5ja55k4")))

(define-public crate-json-syntax-0.8.7 (c (n "json-syntax") (v "0.8.7") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "12l6cmkdi4k06gnc1lxd4h7wc8s29gyz7zlyr7c5s59ksl1cdhp7")))

(define-public crate-json-syntax-0.8.8 (c (n "json-syntax") (v "0.8.8") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0fmvbx2ish7fsjjg5vp1vnblcy357qn9kxbwwmycbh1vpa794n35")))

(define-public crate-json-syntax-0.8.9 (c (n "json-syntax") (v "0.8.9") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0p64862c327w72wrnzazmgaqips7xm6mpk2kjjyn2ikf4jf0n427")))

(define-public crate-json-syntax-0.8.10 (c (n "json-syntax") (v "0.8.10") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0xiqlr9jzsc0splvvi2jndy31jd4ay8kq5yrxzki67ilrf7ic0jg")))

(define-public crate-json-syntax-0.8.11 (c (n "json-syntax") (v "0.8.11") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "14s0a6dm8scbj31qjy9bzwk6gs4wj1f2cs77pyahcfh445hc8w6q")))

(define-public crate-json-syntax-0.8.12 (c (n "json-syntax") (v "0.8.12") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1g9ncf186al182c8jy93d4w9pi7mjsx5mh5wxx8piw5sam3q2277")))

(define-public crate-json-syntax-0.8.13 (c (n "json-syntax") (v "0.8.13") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.5.1") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0f86vrf7bdf1gvjx63ill9kji4gzbrz6zcia4p097a0ms7fqn49s")))

(define-public crate-json-syntax-0.8.14 (c (n "json-syntax") (v "0.8.14") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.1") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0yxli767fhia20argw6wgmpslfxfb5vsrrm57mpfbibsj92kz6hr")))

(define-public crate-json-syntax-0.8.15 (c (n "json-syntax") (v "0.8.15") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.2") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0673a4d41cmr51n5n62r5la1p765yynqyr5wbhv21wxn66fbcplz") (f (quote (("canonicalize" "ryu-js" "json-number/canonical"))))))

(define-public crate-json-syntax-0.8.16 (c (n "json-syntax") (v "0.8.16") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.3") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1z11dm2zmr2ghmqlpvggb44l3f9pgh1m8gixarjrg50dacbyzx9g") (f (quote (("canonicalize" "ryu-js" "json-number/canonical"))))))

(define-public crate-json-syntax-0.8.17 (c (n "json-syntax") (v "0.8.17") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.3") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0zmzxwazirmpcb5mk3763snn659bdq8p4dk7jhs82v85ji3mqp1n") (f (quote (("canonicalize" "ryu-js" "json-number/canonical"))))))

(define-public crate-json-syntax-0.8.18 (c (n "json-syntax") (v "0.8.18") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.3") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "19c6zzz5pxhyx9mf4d5wh1gn1s576aczjxbrxxkic303d3732bkr") (f (quote (("canonicalize" "ryu-js" "json-number/canonical"))))))

(define-public crate-json-syntax-0.9.0 (c (n "json-syntax") (v "0.9.0") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.5") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0vwwrbn1adbkxns65xxgvck4kslk7d2n76479kijd57xjp91gf3c") (f (quote (("default" "serde_json") ("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.9.1 (c (n "json-syntax") (v "0.9.1") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.5") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1yrdrjwfm75xfcmz7hnv7pgrhdb5kkcd9d3kj529b5viq73p6d2f") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.9.2 (c (n "json-syntax") (v "0.9.2") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.5") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0fikm68bmfhbwqrg8iidpawbc5zj8lgk1vn9wn0hjiwji2w2cchz") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.9.3 (c (n "json-syntax") (v "0.9.3") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.5") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1qgb97x5rx4mgm7d32jdh9y9zf81y18ca94060cm580028w7z9h4") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.9.4 (c (n "json-syntax") (v "0.9.4") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.5") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "07vyz8brj8sj53kdsav4q3pz252xdmli4pnz8d4fd1c2kpc3w15r") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.9.5 (c (n "json-syntax") (v "0.9.5") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.5") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1fq26vq0fdccc65l84i8c1857qh6nzjr4msvfpj517ij03wrkb94") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.9.6 (c (n "json-syntax") (v "0.9.6") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.6") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.7.3") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1k5iz72p1qnp4gybad5v2cz53f3ijkxgksxx0b0hqcpyw1blabwz") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.10.0 (c (n "json-syntax") (v "0.10.0") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.6") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0vkp83sjycvd24xfvm7i2nhq06dqpddbrq525zc60ya6w237ajhy") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.11.0 (c (n "json-syntax") (v "0.11.0") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.6") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1anm3jsjingfprj196kvg7knvn0d0s76c622rr6w9wkd4by6d2gl") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (y #t) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.11.1 (c (n "json-syntax") (v "0.11.1") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.6") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "05ivbvky6v95xj27ffymhjjjkwzxjvnvbnm2gah5b1bb18gdc3k8") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.11.2 (c (n "json-syntax") (v "0.11.2") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.6") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1aqg7cr4n300njxk8d6jswapiydnh3nzhgwfi66wacmb3z39lpqp") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde"))))))

(define-public crate-json-syntax-0.11.3 (c (n "json-syntax") (v "0.11.3") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.6") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1a01l26395lpkl3lrxv98chxw68br9008zy6lc36vzfp94nprmh4") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.11.4 (c (n "json-syntax") (v "0.11.4") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0fx6dh93likpx149397khg9ynsjpc97n6czlx7whrwxvshv8x9wh") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.11.5 (c (n "json-syntax") (v "0.11.5") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "11c6hmiyxg25p2l9m5s55kz12d87332av6bil3s218lkvr64y31z") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.11.6 (c (n "json-syntax") (v "0.11.6") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "0pqz6hj0jw0whs3pm6kzi25qyzq26hca4ssln1av6zarag0xcqlv") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.11.7 (c (n "json-syntax") (v "0.11.7") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)))) (h "1clb8w92vlqh7niivg6v9fgmss86dh9vdfazbxisndmbadckak5p") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.12.0 (c (n "json-syntax") (v "0.12.0") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)) (d (n "utf8-decode") (r "^1.0.1") (d #t) (k 0)))) (h "1ixh8fmiygh802b96qjalv4rrgdqycicdjprc86cnv6xcrw5rin1") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.12.1 (c (n "json-syntax") (v "0.12.1") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)) (d (n "utf8-decode") (r "^1.0.1") (d #t) (k 0)))) (h "04r5f572v7gn5s1l5cr6x324m86zrncdc8v75hfidrr2skhsk824") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.12.2 (c (n "json-syntax") (v "0.12.2") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)) (d (n "utf8-decode") (r "^1.0.1") (d #t) (k 0)))) (h "0xx8a0cy5mnaqjs1h4kz5gqrw967cmnspxw72i8ajnyir31f0dfp") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde"))))))

(define-public crate-json-syntax-0.12.3 (c (n "json-syntax") (v "0.12.3") (d (list (d (n "contextual") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "decoded-char") (r "^0.1") (d #t) (k 0)) (d (n "hashbrown") (r "^0.12.1") (f (quote ("raw"))) (d #t) (k 0)) (d (n "indexmap") (r "^1.9.1") (d #t) (k 0)) (d (n "json-number") (r "^0.4.8") (f (quote ("smallnumberbuf"))) (d #t) (k 0)) (d (n "locspan") (r "^0.8.2") (d #t) (k 0)) (d (n "locspan-derive") (r "^0.6") (d #t) (k 0)) (d (n "ryu-js") (r "^0.2.2") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1.0") (o #t) (d #t) (k 0)) (d (n "smallstr") (r "^0.3") (d #t) (k 0)) (d (n "smallvec") (r "^1.9") (d #t) (k 0)) (d (n "utf8-decode") (r "^1.0.1") (d #t) (k 0)))) (h "19f6hdlbgskkvhdya8dfzgd2wj7qbna8yizbip0yqirp6r3m9r5v") (f (quote (("canonicalize" "ryu-js" "json-number/canonical")))) (s 2) (e (quote (("serde_json" "dep:serde_json" "json-number/serde_json") ("serde" "dep:serde" "json-number/serde" "smallstr/serde")))) (r "1.71.0")))

