(define-module (crates-io js on json-rpc2) #:use-module (crates-io))

(define-public crate-json-rpc2-0.1.0 (c (n "json-rpc2") (v "0.1.0") (d (list (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "1myv7lm6iss97a4vcrpipxnfapaq55ia056fdmnrd8097im629jz")))

(define-public crate-json-rpc2-0.2.0 (c (n "json-rpc2") (v "0.2.0") (d (list (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "0mlwrqa9b43lmfbyavdm8l1w8i5kc60m27mnclqc1b2lxn7v8qld")))

(define-public crate-json-rpc2-0.3.0 (c (n "json-rpc2") (v "0.3.0") (d (list (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "0lkjrjs34mj8nzfiss5wr42jzbzws139a205c82v37i5w52bq0lp")))

(define-public crate-json-rpc2-0.4.0 (c (n "json-rpc2") (v "0.4.0") (d (list (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "05wxggwnf4bbs785nmr1cznn2yhl53x9jmx6jq49iaaqpriz8jsw")))

(define-public crate-json-rpc2-0.5.0 (c (n "json-rpc2") (v "0.5.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0c8m7lp20sdi4mfsgg41glr51z5yzjgvacg059wlx3498idks2k5") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.5.1 (c (n "json-rpc2") (v "0.5.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1ia13ssjznplz03bp61f6bga5xr0wb1knhhlxwc16pwiiffg3sp3") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.5.2 (c (n "json-rpc2") (v "0.5.2") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1vjg5z92g3h7bkqi4093wp2b0n1889nhmzvkl0zgjgg12151j2xk") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.5.3 (c (n "json-rpc2") (v "0.5.3") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1dmk4m5gjgykn3szw6j8arxqlw6iiyq12ddxc5zqmcn210ldnb5x") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.6.0 (c (n "json-rpc2") (v "0.6.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0ggp6x1k3fwzh53kcvgb7mks0p9vbrxk6cbfp0dc40lbs6frj95g") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.6.1 (c (n "json-rpc2") (v "0.6.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "01yz7ylnissdrril2m2mhhmapdc2pbcl8jj62chppilj626x4l3r") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.6.2 (c (n "json-rpc2") (v "0.6.2") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "16bsj5wajij96hi528bwqfbpi166xvisp82zdmg89ia0hj7x7iya") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.7.0 (c (n "json-rpc2") (v "0.7.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "12wcsypfra5q7wsl5px3z2wdm80jv4gbispliww148hhk106zhvl") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.7.1 (c (n "json-rpc2") (v "0.7.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1ls7xz4hz6df4f5x5p2bk2slpsfchz1fjbj28vncy5sdfdifcbzk") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.7.2 (c (n "json-rpc2") (v "0.7.2") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1il8pyyjvg20pfz1yiisi8zjja8x75l50srdab2vr6cvb7saxwzd") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.7.3 (c (n "json-rpc2") (v "0.7.3") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1ff27w7xp426x89l221mbsg9zh32k9bvsdx4fjznwdc6l3lhxi1r") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.8.0 (c (n "json-rpc2") (v "0.8.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1lmv39rxw19mjnz9ph5hsg4vk8bvx3nna614fbq0y9ly1pj774dd") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.8.1 (c (n "json-rpc2") (v "0.8.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "187r8ih10bkz0k673a725cbpcc5j03kzm1nn48hzl3rwip11y8r6") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.8.2 (c (n "json-rpc2") (v "0.8.2") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "08597xi7rzvsmpd2i5mx1s06vgnvl9jjn2b7l8s1c8s96ggpc4ig") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.9.0 (c (n "json-rpc2") (v "0.9.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0v6xh6lncajahh7lb2r9by2vxa8dwpnbi925phh8kqi41li7dkhk") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.9.1 (c (n "json-rpc2") (v "0.9.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "09wcipxrl7j5bmkpgbap18dzhid4x1csvy6lddj1z9q3dgjbflyk") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.9.2 (c (n "json-rpc2") (v "0.9.2") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "084skldh2zl7zv5yfn66p808fxk1njl5l3sqdpk8pz31jsiwi7dm") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.9.3 (c (n "json-rpc2") (v "0.9.3") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1pjpglrb525iix0x21r6i676yywas2crzwq804lzqx2zbvxbvflq") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.9.4 (c (n "json-rpc2") (v "0.9.4") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0lghc8hzzdkg1iyxzrh52zjvjd53qv3lvbkd73byql8h1mv6zcxr") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.9.5 (c (n "json-rpc2") (v "0.9.5") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0n7pq5l4ydjxb0ncyll5pfcj9f83l1whfkzcjbxrp84210dxhval") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.10.0 (c (n "json-rpc2") (v "0.10.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0vhcj376bmwqn70kk2a1dlc1h566875d6sj5gglqxcv66dhz6s1a") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.10.1 (c (n "json-rpc2") (v "0.10.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1997y419dwna31x5qk03nam97h9djdfws5v7g4s5q4xdgxqrzd3q") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.10.2 (c (n "json-rpc2") (v "0.10.2") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0mknj2j1jcdm1fribzah3bg79d85472dbp4izxng7ahzpnyv97g8") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.10.3 (c (n "json-rpc2") (v "0.10.3") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1f99zmpz0lgkz5lxk657ri8kaf0313pzmlb6ashz4h7nh29mzg92") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.10.4 (c (n "json-rpc2") (v "0.10.4") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "15gr3nm6irfmxr7q5ifxj3n0hjf3d4ycbn8pkc16rjg6dl1gc7ls") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.10.5 (c (n "json-rpc2") (v "0.10.5") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1l6scczhmxkxw5sc42i55hlhz8l1pxfp2z7aj0jc6r4r0866na81") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.11.0 (c (n "json-rpc2") (v "0.11.0") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "0cc6q63n9y37kpg0dqqnml0d3z9afvl6capmm1x835v4hwwnjb7j") (f (quote (("async" "async-trait"))))))

(define-public crate-json-rpc2-0.11.1 (c (n "json-rpc2") (v "0.11.1") (d (list (d (n "async-trait") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("full"))) (d #t) (k 2)))) (h "1sj99lxgzz7kcrdkr9mb2j4jjna5l01drxqnplik4j6ywj93yhwz") (f (quote (("async" "async-trait"))))))

