(define-module (crates-io #{3}# l llm) #:use-module (crates-io))

(define-public crate-llm-0.1.0 (c (n "llm") (v "0.1.0") (h "0jijyiq84mrg688d3cv7crb66xv2gqsbi76ffc2mzi8lf87ijpzi") (y #t)))

(define-public crate-llm-0.1.0-rc1 (c (n "llm") (v "0.1.0-rc1") (d (list (d (n "llm-base") (r "^0.1.0-rc1") (d #t) (k 0)) (d (n "llm-bloom") (r "^0.1.0-rc1") (o #t) (d #t) (k 0)) (d (n "llm-gpt2") (r "^0.1.0-rc1") (o #t) (d #t) (k 0)) (d (n "llm-gptj") (r "^0.1.0-rc1") (o #t) (d #t) (k 0)) (d (n "llm-llama") (r "^0.1.0-rc1") (f (quote ("convert"))) (o #t) (d #t) (k 0)) (d (n "llm-neox") (r "^0.1.0-rc1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.5") (d #t) (k 2)))) (h "1iibgn01an56wkfa759bsm5x9b4a87sigjmij2bwd9271wnvh5pz") (f (quote (("default" "llama" "gpt2" "gptj" "bloom" "neox")))) (s 2) (e (quote (("neox" "dep:llm-neox") ("llama" "dep:llm-llama") ("gptj" "dep:llm-gptj") ("gpt2" "dep:llm-gpt2") ("bloom" "dep:llm-bloom"))))))

(define-public crate-llm-0.1.0-rc2 (c (n "llm") (v "0.1.0-rc2") (d (list (d (n "llm-base") (r "^0.1.0-rc2") (d #t) (k 0)) (d (n "llm-bloom") (r "^0.1.0-rc2") (o #t) (d #t) (k 0)) (d (n "llm-gpt2") (r "^0.1.0-rc2") (o #t) (d #t) (k 0)) (d (n "llm-gptj") (r "^0.1.0-rc2") (o #t) (d #t) (k 0)) (d (n "llm-llama") (r "^0.1.0-rc2") (f (quote ("convert"))) (o #t) (d #t) (k 0)) (d (n "llm-neox") (r "^0.1.0-rc2") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.5") (d #t) (k 2)))) (h "03m3k1402jfn2nm3gmcn1y9ka4rl7myzbw4y7azw2rs8i126icjs") (f (quote (("default" "llama" "gpt2" "gptj" "bloom" "neox")))) (s 2) (e (quote (("neox" "dep:llm-neox") ("llama" "dep:llm-llama") ("gptj" "dep:llm-gptj") ("gpt2" "dep:llm-gpt2") ("bloom" "dep:llm-bloom"))))))

(define-public crate-llm-0.1.0-rc3 (c (n "llm") (v "0.1.0-rc3") (d (list (d (n "llm-base") (r "^0.1.0-rc3") (d #t) (k 0)) (d (n "llm-bloom") (r "^0.1.0-rc3") (o #t) (d #t) (k 0)) (d (n "llm-gpt2") (r "^0.1.0-rc3") (o #t) (d #t) (k 0)) (d (n "llm-gptj") (r "^0.1.0-rc3") (o #t) (d #t) (k 0)) (d (n "llm-llama") (r "^0.1.0-rc3") (f (quote ("convert"))) (o #t) (d #t) (k 0)) (d (n "llm-neox") (r "^0.1.0-rc3") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.5") (d #t) (k 2)))) (h "1g9xz172v30qyiy5z4f2nx59pa3xf2r311sps874dxjddizym3y3") (f (quote (("default" "llama" "gpt2" "gptj" "bloom" "neox")))) (s 2) (e (quote (("neox" "dep:llm-neox") ("llama" "dep:llm-llama") ("gptj" "dep:llm-gptj") ("gpt2" "dep:llm-gpt2") ("bloom" "dep:llm-bloom"))))))

(define-public crate-llm-0.1.0-rc4 (c (n "llm") (v "0.1.0-rc4") (d (list (d (n "llm-base") (r "^0.1.0-rc4") (d #t) (k 0)) (d (n "llm-bloom") (r "^0.1.0-rc4") (o #t) (d #t) (k 0)) (d (n "llm-gpt2") (r "^0.1.0-rc4") (o #t) (d #t) (k 0)) (d (n "llm-gptj") (r "^0.1.0-rc4") (o #t) (d #t) (k 0)) (d (n "llm-llama") (r "^0.1.0-rc4") (f (quote ("convert"))) (o #t) (d #t) (k 0)) (d (n "llm-neox") (r "^0.1.0-rc4") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.5") (d #t) (k 2)))) (h "0giqx1psxh937nf436373xsnwss4plwdrhpn0cjisqlbm7wzgiyw") (f (quote (("default" "llama" "gpt2" "gptj" "bloom" "neox")))) (s 2) (e (quote (("neox" "dep:llm-neox") ("llama" "dep:llm-llama") ("gptj" "dep:llm-gptj") ("gpt2" "dep:llm-gpt2") ("bloom" "dep:llm-bloom"))))))

(define-public crate-llm-0.1.1 (c (n "llm") (v "0.1.1") (d (list (d (n "llm-base") (r "^0.1.1") (d #t) (k 0)) (d (n "llm-bloom") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "llm-gpt2") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "llm-gptj") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "llm-llama") (r "^0.1.1") (f (quote ("convert"))) (o #t) (d #t) (k 0)) (d (n "llm-neox") (r "^0.1.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.5") (d #t) (k 2)))) (h "0bx41dp5wglmvlcwgjl0q2kyidlg4srfkffhxz3ln5nd0gbz7w9f") (f (quote (("default" "llama" "gpt2" "gptj" "bloom" "neox")))) (s 2) (e (quote (("neox" "dep:llm-neox") ("llama" "dep:llm-llama") ("gptj" "dep:llm-gptj") ("gpt2" "dep:llm-gpt2") ("bloom" "dep:llm-bloom"))))))

