(define-module (crates-io mo ck mockers_codegen) #:use-module (crates-io))

(define-public crate-mockers_codegen-0.5.1 (c (n "mockers_codegen") (v "0.5.1") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.21.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.21.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.44.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.44.0") (o #t) (d #t) (k 0)))) (h "1civqaw4c17rn6dynmj06bp89iwvhl5z1qp6h307vz3x4vyy7szh") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default"))))))

(define-public crate-mockers_codegen-0.5.2 (c (n "mockers_codegen") (v "0.5.2") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.21.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.21.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.44.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.44.0") (o #t) (d #t) (k 0)))) (h "0mpfhrc6aic87ccimq3xym9kxax8l1f8a64bdklilfk0lyimknzv") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default"))))))

(define-public crate-mockers_codegen-0.5.3 (c (n "mockers_codegen") (v "0.5.3") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.21.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.21.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.44.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.44.0") (o #t) (d #t) (k 0)))) (h "0kbjvyb82m4iv7qy23gxvi4ygvsvfvhqmd5dl5qx1f6kmwnnznjg") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default"))))))

(define-public crate-mockers_codegen-0.5.4 (c (n "mockers_codegen") (v "0.5.4") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.27.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.27.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.51.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.51.0") (o #t) (d #t) (k 0)))) (h "0lcl11knly5xicp52wxdwmk2vvx1mwg3hqd540gkm1w6ddyqp9li") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.5 (c (n "mockers_codegen") (v "0.5.5") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.27.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.27.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.51.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.51.0") (o #t) (d #t) (k 0)))) (h "1sl1nf36mlnwpsjhn30d6c3h2810y8ia5xd9hcnilvw432a4fv17") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.6 (c (n "mockers_codegen") (v "0.5.6") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.28.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.28.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.52.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.52.0") (o #t) (d #t) (k 0)))) (h "093ak4yr5rswk765jzlvd63lnxcnq6b2ahznq0mg6h6hyyz9va3h") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.7 (c (n "mockers_codegen") (v "0.5.7") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.28.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.28.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.52.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.52.0") (o #t) (d #t) (k 0)))) (h "0ghflljvy5x6wzhj9qpj7fzfx59xf86qqb4z61bcvxxljy9qf78g") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.8 (c (n "mockers_codegen") (v "0.5.8") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.28.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.28.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.52.0") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.52.0") (o #t) (d #t) (k 0)))) (h "0533hvl8h30hpyi96kc9fsplgnb9kx8g03j8vqqyyhq0arbm806i") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.9 (c (n "mockers_codegen") (v "0.5.9") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "1bblhapjag66g7jrdph40rx07fm683ibjn32psr77spj5hlbmh8f") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.10 (c (n "mockers_codegen") (v "0.5.10") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "0cqr3ba591l8r7y7nw18w2bwsy42rzx0x6r84ybjqn2wc5z8fl4v") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.5.11 (c (n "mockers_codegen") (v "0.5.11") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "1z5b68l3hzmy3v3wad78a19x3sgyldqaa5ljzwspmyi5930ixxd5") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.6.0 (c (n "mockers_codegen") (v "0.6.0") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "08i677372q7x500maq18fciy34achcav0igmhq0kx9hnky833pxc") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.6.1 (c (n "mockers_codegen") (v "0.6.1") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "18w3mzwa80dw5fl6882796ba17x49n7y3x96w92ghp3kjgkd56hx") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.6.2 (c (n "mockers_codegen") (v "0.6.2") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "0yxx0b07dzfyqss2sjinw34kpl8ylzl1i67zv5j97mb541ixpz2g") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.6.3 (c (n "mockers_codegen") (v "0.6.3") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "01n3dvvk0sznz7i51m0819dhn402kkrwxvzy3rf46m8cnjkg4w0v") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.7.0 (c (n "mockers_codegen") (v "0.7.0") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "171iwrnanycmkjilwjhdb8bb3ysskipp43vhw9110gc0c5r712gq") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.7.1 (c (n "mockers_codegen") (v "0.7.1") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "021l2jgwj3jyn431aaa2mkp6sycvj6zrf6pc7agjx8w104dgkbhp") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.8.0 (c (n "mockers_codegen") (v "0.8.0") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "1c9wp5zi7782wbn4nd9dc259dh81yix61bdlcn3wzdwdbpg5n90a") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.9.0 (c (n "mockers_codegen") (v "0.9.0") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "1r9gmy8cirmvija9yzwzrlhr0xv2abc2dmbcbrkvr24d5glzxcm7") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.9.1 (c (n "mockers_codegen") (v "0.9.1") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "02nw0ws6jz1xwl83g506gr3rdg96hvlrn3hk3d3vwaxfrc0hy40b") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.9.2 (c (n "mockers_codegen") (v "0.9.2") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)) (d (n "quasi") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 0)) (d (n "quasi_codegen") (r "^0.32.0") (f (quote ("with-syntex"))) (o #t) (d #t) (k 1)) (d (n "syntex") (r "^0.58.1") (o #t) (d #t) (k 0)) (d (n "syntex_syntax") (r "^0.58.1") (o #t) (d #t) (k 0)))) (h "0f5yaw30jk9238y22fark5gv6wbf7sm3166z7pl6plw1y97zpjqa") (f (quote (("with-syntex" "syntex" "syntex_syntax" "quasi" "quasi_codegen") ("default") ("debug"))))))

(define-public crate-mockers_codegen-0.9.3 (c (n "mockers_codegen") (v "0.9.3") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)))) (h "030bmf2csaq0b6ykvmmv9ywsyq7xvf52fmfncgss5apd0ckbjm77") (f (quote (("default") ("debug"))))))

(define-public crate-mockers_codegen-0.9.4 (c (n "mockers_codegen") (v "0.9.4") (d (list (d (n "itertools") (r "^0.4.13") (d #t) (k 0)))) (h "15yqq6sngyic89j4j29689l9jgdsfs1aywqdlhqnp9z3k9ls9qzm") (f (quote (("default") ("debug"))))))

