(define-module (crates-io an ch anchor-attribute-access-control) #:use-module (crates-io))

(define-public crate-anchor-attribute-access-control-0.0.0-alpha.0 (c (n "anchor-attribute-access-control") (v "0.0.0-alpha.0") (d (list (d (n "anchor-syn") (r "^0.0.0-alpha.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "=1.0.57") (f (quote ("full"))) (d #t) (k 0)))) (h "14h67n751y98x2v14vx629whqrcxqp00a5k7sizx374i4512rv62")))

(define-public crate-anchor-attribute-access-control-0.1.0 (c (n "anchor-attribute-access-control") (v "0.1.0") (d (list (d (n "anchor-syn") (r "^0.1.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "=1.0.57") (f (quote ("full"))) (d #t) (k 0)))) (h "0hzpnfsbj3536rwjphln9q67bsv8vn2rs6chv379dw1xyqhjhbr5")))

(define-public crate-anchor-attribute-access-control-0.2.0 (c (n "anchor-attribute-access-control") (v "0.2.0") (d (list (d (n "anchor-syn") (r "^0.2.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "=1.0.57") (f (quote ("full"))) (d #t) (k 0)))) (h "1ls635b44qm0pn99bcnj5f1yg5q81qxdp4nvv2hm6dzmhsndz0la")))

(define-public crate-anchor-attribute-access-control-0.2.1 (c (n "anchor-attribute-access-control") (v "0.2.1") (d (list (d (n "anchor-syn") (r "^0.2.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "=1.0.57") (f (quote ("full"))) (d #t) (k 0)))) (h "0p3miyzlv36kklwvjllm6yih2risj6z8znnf94yvb89mxfnp6s27")))

(define-public crate-anchor-attribute-access-control-0.3.0 (c (n "anchor-attribute-access-control") (v "0.3.0") (d (list (d (n "anchor-syn") (r "^0.3.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "=1.0.57") (f (quote ("full"))) (d #t) (k 0)))) (h "07jwgq1a17ccrwn97awdn1brl4caxsdnpks5bmxsqcfns1mg35yz")))

(define-public crate-anchor-attribute-access-control-0.4.0 (c (n "anchor-attribute-access-control") (v "0.4.0") (d (list (d (n "anchor-syn") (r "^0.4.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1p7xfxkrr7zw3sk2j5j53s6maxpcca182ahzcmd4l2g8662xpkzm")))

(define-public crate-anchor-attribute-access-control-0.4.1 (c (n "anchor-attribute-access-control") (v "0.4.1") (d (list (d (n "anchor-syn") (r "^0.4.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1wzj55srrhd0blgbp9c3y9s13pj6r2rzvyl4d9xkmbv6rc5hhwbl")))

(define-public crate-anchor-attribute-access-control-0.4.2 (c (n "anchor-attribute-access-control") (v "0.4.2") (d (list (d (n "anchor-syn") (r "^0.4.2") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1i5j5p5n06llk5fcc519bw8hjkp067l2iqydbj0zasln4hmjn52q")))

(define-public crate-anchor-attribute-access-control-0.4.3 (c (n "anchor-attribute-access-control") (v "0.4.3") (d (list (d (n "anchor-syn") (r "^0.4.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0cp9ri3d5r77x7ml6lqq10yirjxxki2f7f7wwgzg3gvnf7lp5ayq")))

(define-public crate-anchor-attribute-access-control-0.4.4 (c (n "anchor-attribute-access-control") (v "0.4.4") (d (list (d (n "anchor-syn") (r "^0.4.4") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1q3jsbr39r2lgpk5nw3cc5a5zwpmnz69gfzb3l6zr2mn8h3dvh8b")))

(define-public crate-anchor-attribute-access-control-0.4.5 (c (n "anchor-attribute-access-control") (v "0.4.5") (d (list (d (n "anchor-syn") (r "^0.4.5") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "13xspzs3gvvfngwmb5klx5g65swv677w291220n5p4cqnsc3nxdm")))

(define-public crate-anchor-attribute-access-control-0.5.0 (c (n "anchor-attribute-access-control") (v "0.5.0") (d (list (d (n "anchor-syn") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1z405bxpn23ihn7bx9i5zmjm2nppaaqdnx1fk5pmqf2khyxfh84c") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.6.0 (c (n "anchor-attribute-access-control") (v "0.6.0") (d (list (d (n "anchor-syn") (r "^0.6.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1h578cp4w1xl0acy13qqbxj7bg95636cdar0y84xkmmin0dl6ry0") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.7.0 (c (n "anchor-attribute-access-control") (v "0.7.0") (d (list (d (n "anchor-syn") (r "^0.7.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1bh5xmql8hw5564rps4hm4mflpck3l9a56a7bja3aida9sqsb9ar") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.8.0 (c (n "anchor-attribute-access-control") (v "0.8.0") (d (list (d (n "anchor-syn") (r "^0.8.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0csx78lbcidlcx6g6gyfrlm9nf6ismmifp4ja749nw0cqhidlib6") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.9.0 (c (n "anchor-attribute-access-control") (v "0.9.0") (d (list (d (n "anchor-syn") (r "^0.9.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "196vg53p914r8nj2dlsal34gbbghac3gl5sfpvxjv7pj8qk8z7j7") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.10.0 (c (n "anchor-attribute-access-control") (v "0.10.0") (d (list (d (n "anchor-syn") (r "^0.10.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1md322nqwh0dn0i9fgmix6l06k69g5g5i1lmrjgxrb530waad0pq") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.11.0 (c (n "anchor-attribute-access-control") (v "0.11.0") (d (list (d (n "anchor-syn") (r "^0.11.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "01d7zm13fzk5ra0zbhsmybm2hyrm6xd1vm0m8zf4lrxa8ia1gfaq") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.11.1 (c (n "anchor-attribute-access-control") (v "0.11.1") (d (list (d (n "anchor-syn") (r "^0.11.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0bhnwy4yhpgdd8zqv5l7an9v34y2130ni17kz36l30s0wj1bi9jf") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.12.0 (c (n "anchor-attribute-access-control") (v "0.12.0") (d (list (d (n "anchor-syn") (r "^0.12.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0bza1qj06lsp05c4a3z47xkr4zymvrwj8in5b8mx5hsl3xl4z5mf") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.13.0 (c (n "anchor-attribute-access-control") (v "0.13.0") (d (list (d (n "anchor-syn") (r "^0.13.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1psz4s6knad80dj91yqllvq3yq85c4h1ldqgc2c9qs454b5c8zii") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.13.1 (c (n "anchor-attribute-access-control") (v "0.13.1") (d (list (d (n "anchor-syn") (r "^0.13.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "00fk23drlq8ygzpzm86gj8gnczp4qnd7scfvbcrlgkijd3xvr49c") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.13.2 (c (n "anchor-attribute-access-control") (v "0.13.2") (d (list (d (n "anchor-syn") (r "^0.13.2") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0wq415mpx622jvgrwj4scwrx56j5kd415fhr88l9p2pdigf6mfim") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.14.0 (c (n "anchor-attribute-access-control") (v "0.14.0") (d (list (d (n "anchor-syn") (r "^0.14.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0dwjj4jywbg05qk2l0zkipk73z5ds52r5abgb3jdk6gbsvrpw6np") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.15.0 (c (n "anchor-attribute-access-control") (v "0.15.0") (d (list (d (n "anchor-syn") (r "^0.15.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1zd2s38h9vzw1cc0ij4j2q1174l6k3pplx12lgv3xgvn48wqk86v") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.16.0 (c (n "anchor-attribute-access-control") (v "0.16.0") (d (list (d (n "anchor-syn") (r "^0.16.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "017481q67605imxzgc8mvqrw48xllbbbwxs8qw8v0i8dkrklgidh") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.16.1 (c (n "anchor-attribute-access-control") (v "0.16.1") (d (list (d (n "anchor-syn") (r "^0.16.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "08rsm33qzyjs0id20js3y1fqwrv7nwmx9qdmgwbwwcnjlma7pzx4") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.16.2 (c (n "anchor-attribute-access-control") (v "0.16.2") (d (list (d (n "anchor-syn") (r "^0.16.2") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "17gh6panjj30lzsn1rw0cn1r2wxyhw5nl1mlx2ibrsma4s9i9ll6") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.17.0 (c (n "anchor-attribute-access-control") (v "0.17.0") (d (list (d (n "anchor-syn") (r "^0.17.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0f4ik4yxad4ih358jsm6cz4ffmmxx5bsi1lm76y4jvp1zmxvk2kv") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.18.0 (c (n "anchor-attribute-access-control") (v "0.18.0") (d (list (d (n "anchor-syn") (r "^0.18.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1gab65g8lr0pnf8jdfk0zv8kzjkrdswivx3xsi34381wqnws9dlw") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.18.2 (c (n "anchor-attribute-access-control") (v "0.18.2") (d (list (d (n "anchor-syn") (r "^0.18.2") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1rsc7hp0fsmc95lm50xwim1rb41r9vn9xhs7wsr4n0xas3c3zr8k") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.19.0 (c (n "anchor-attribute-access-control") (v "0.19.0") (d (list (d (n "anchor-syn") (r "^0.19.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "05apzgyrqdsr6dzd158aqbgc3z7kl05mlri44jh2n57w0scigkw6") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.20.0 (c (n "anchor-attribute-access-control") (v "0.20.0") (d (list (d (n "anchor-syn") (r "^0.20.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1vb9pjpgbhffwf97zs8np8pjlcncfa721p0zqd75jvdy9v98zpv8") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.20.1 (c (n "anchor-attribute-access-control") (v "0.20.1") (d (list (d (n "anchor-syn") (r "^0.20.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0sv2xgxdkagsw11zca05m2acybd8dya5yv7valkj2a9zc4x48p0h") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.21.0 (c (n "anchor-attribute-access-control") (v "0.21.0") (d (list (d (n "anchor-syn") (r "^0.21.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "06qrv81vivxfpb0dvb08bdc5b6f9rfazw9k0s7mrzqy6c4a76ww5") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.22.0 (c (n "anchor-attribute-access-control") (v "0.22.0") (d (list (d (n "anchor-syn") (r "^0.22.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0xdaylykc74l0s3vv0sdc9b2i4ppqvd0bbj0k378h8kmk1wwjw7d") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.22.1 (c (n "anchor-attribute-access-control") (v "0.22.1") (d (list (d (n "anchor-syn") (r "^0.22.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0j1zbxh9k7g0nkrwccr3ih810f1cb94xw9hi6kd5wbp73jfwqigv") (f (quote (("anchor-debug" "anchor-syn/anchor-debug"))))))

(define-public crate-anchor-attribute-access-control-0.23.0 (c (n "anchor-attribute-access-control") (v "0.23.0") (d (list (d (n "anchor-syn") (r "^0.23.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0bs1jgn5byh15m99dwq6zgia6y3cckvqr54fj06vnp58d9ipx4gv") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.56")))

(define-public crate-anchor-attribute-access-control-0.24.0 (c (n "anchor-attribute-access-control") (v "0.24.0") (d (list (d (n "anchor-syn") (r "^0.24.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0klpnijgaqws4mbswa8myi8vpv3wg13nwgclwbp3ad7kxmjsmag0") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.56")))

(define-public crate-anchor-attribute-access-control-0.24.1 (c (n "anchor-attribute-access-control") (v "0.24.1") (d (list (d (n "anchor-syn") (r "^0.24.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1hynl01y7fxxwhpkqzn6rrlfpn06jywyvnlifiy349cngdh7dgnm") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.56")))

(define-public crate-anchor-attribute-access-control-0.24.2 (c (n "anchor-attribute-access-control") (v "0.24.2") (d (list (d (n "anchor-syn") (r "^0.24.2") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "14ax9jpfkfr5mbzr4z58qp20i9yk4xmphfvfpfarvb5lnq2mvdx9") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.56")))

(define-public crate-anchor-attribute-access-control-0.25.0 (c (n "anchor-attribute-access-control") (v "0.25.0") (d (list (d (n "anchor-syn") (r "^0.25.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "0kwlmwqm5sm39p8j2npnbvfjn0l6j5bcy7276kag83zm32ayxxkh") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.56")))

(define-public crate-anchor-attribute-access-control-0.26.0 (c (n "anchor-attribute-access-control") (v "0.26.0") (d (list (d (n "anchor-syn") (r "^0.26.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "069kwmlkax4dq5xwzp9c0kqrvb9j3qf0lv3iq3i3vgl12dg56zfg") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.59")))

(define-public crate-anchor-attribute-access-control-0.27.0 (c (n "anchor-attribute-access-control") (v "0.27.0") (d (list (d (n "anchor-syn") (r "^0.27.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.32") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.0") (d #t) (k 0)) (d (n "syn") (r "^1.0.60") (f (quote ("full"))) (d #t) (k 0)))) (h "1pfpyr5lb4vmm3n7qjcjyw2bz78w82xhs7dn56fh66ri7d0ilpid") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.60")))

(define-public crate-anchor-attribute-access-control-0.28.0 (c (n "anchor-attribute-access-control") (v "0.28.0") (d (list (d (n "anchor-syn") (r "^0.28.0") (d #t) (k 0)) (d (n "anyhow") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1wmlxvvs0pq5zmsg9rm9zimkbgn2lfdkfs68hxzidsmbf9dvx9gs") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.60")))

(define-public crate-anchor-attribute-access-control-0.29.0 (c (n "anchor-attribute-access-control") (v "0.29.0") (d (list (d (n "anchor-syn") (r "^0.29.0") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0gha7s1gsf3znv5mhiz158ghi9m57dijx2ms4lcn4lsgs3qikxp5") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.60")))

(define-public crate-anchor-attribute-access-control-0.30.0 (c (n "anchor-attribute-access-control") (v "0.30.0") (d (list (d (n "anchor-syn") (r "^0.30.0") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "09m9vi019n5fjfaq3k16qzb0m7gd9vvw13n0bn41g8xkf7hnhwyx") (f (quote (("anchor-debug" "anchor-syn/anchor-debug")))) (r "1.60")))

