(define-module (crates-io ic e_ ice_core) #:use-module (crates-io))

(define-public crate-ice_core-0.3.2 (c (n "ice_core") (v "0.3.2") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.1") (d #t) (k 0)) (d (n "cervus") (r "^0.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "etag") (r "^0.2") (d #t) (k 0)) (d (n "futures") (r "^0.1") (d #t) (k 0)) (d (n "hyper") (r "^0.11") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "sequence_trie") (r "^0.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tera") (r "^0.10") (d #t) (k 0)) (d (n "tokio-core") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "uuid") (r "^0.4") (f (quote ("v4"))) (d #t) (k 0)))) (h "00qc993gxqfm1bmixpchh3ngqyw7hphbflwiy16xjpnymaia5di2")))

(define-public crate-ice_core-0.3.3 (c (n "ice_core") (v "0.3.3") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.1") (d #t) (k 0)) (d (n "cervus") (r "^0.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "etag") (r "^0.2") (d #t) (k 0)) (d (n "futures") (r "^0.1") (d #t) (k 0)) (d (n "hyper") (r "^0.11") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "net2") (r "^0.2") (d #t) (k 0)) (d (n "num_cpus") (r "^1.6") (d #t) (k 0)) (d (n "sequence_trie") (r "^0.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tera") (r "^0.10") (d #t) (k 0)) (d (n "tokio-core") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "uuid") (r "^0.4") (f (quote ("v4"))) (d #t) (k 0)))) (h "13v5gxhrknxig16839pcgb5yanyzizr5igwclf6jmq9vjdvjaspn")))

(define-public crate-ice_core-0.3.9 (c (n "ice_core") (v "0.3.9") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.1") (d #t) (k 0)) (d (n "cervus") (r "^0.3") (o #t) (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "etag") (r "^0.2") (d #t) (k 0)) (d (n "futures") (r "^0.1") (d #t) (k 0)) (d (n "hyper") (r "^0.11") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "net2") (r "^0.2") (d #t) (k 0)) (d (n "num_cpus") (r "^1.6") (d #t) (k 0)) (d (n "sequence_trie") (r "^0.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tera") (r "^0.10") (d #t) (k 0)) (d (n "tokio-core") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "uuid") (r "^0.4") (f (quote ("v4"))) (d #t) (k 0)))) (h "0w50dha6spshrlyl105x37r1b74fpphdzpsfmzk09n1606npyn2s") (f (quote (("use_cervus" "cervus"))))))

(define-public crate-ice_core-0.3.10 (c (n "ice_core") (v "0.3.10") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.1") (d #t) (k 0)) (d (n "cervus") (r "^0.3") (o #t) (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "etag") (r "^0.2") (d #t) (k 0)) (d (n "futures") (r "^0.1") (d #t) (k 0)) (d (n "hyper") (r "^0.11") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "net2") (r "^0.2") (d #t) (k 0)) (d (n "num_cpus") (r "^1.6") (d #t) (k 0)) (d (n "sequence_trie") (r "^0.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tera") (r "^0.10") (d #t) (k 0)) (d (n "tokio-core") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "url") (r "^1.5") (d #t) (k 0)) (d (n "uuid") (r "^0.4") (f (quote ("v4"))) (d #t) (k 0)))) (h "10vvnhm01nmp5f6pxgp80q58wyl8gh5jlvy9p140agj85zz0fjr5") (f (quote (("use_cervus" "cervus"))))))

(define-public crate-ice_core-0.4.0-alpha.4 (c (n "ice_core") (v "0.4.0-alpha.4") (d (list (d (n "ansi_term") (r "^0.9") (d #t) (k 0)) (d (n "byteorder") (r "^1.1") (d #t) (k 0)) (d (n "cervus") (r "^0.3") (o #t) (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "etag") (r "^0.2") (d #t) (k 0)) (d (n "futures") (r "^0.1") (d #t) (k 0)) (d (n "hyper") (r "^0.11") (d #t) (k 0)) (d (n "lazy_static") (r "^0.2") (d #t) (k 0)) (d (n "mime_guess") (r "^2.0.0-alpha.2") (d #t) (k 0)) (d (n "net2") (r "^0.2") (d #t) (k 0)) (d (n "num_cpus") (r "^1.6") (d #t) (k 0)) (d (n "r2d2") (r "^0.7") (d #t) (k 0)) (d (n "r2d2_redis") (r "^0.6") (d #t) (k 0)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "redis") (r "^0.8") (d #t) (k 0)) (d (n "sequence_trie") (r "^0.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tarpc") (r "^0.9") (d #t) (k 0)) (d (n "tarpc-plugins") (r "^0.2") (d #t) (k 0)) (d (n "tera") (r "^0.10") (d #t) (k 0)) (d (n "threadpool") (r "^1.6") (d #t) (k 0)) (d (n "tokio-core") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "url") (r "^1.5") (d #t) (k 0)) (d (n "uuid") (r "^0.4") (f (quote ("v4"))) (d #t) (k 0)))) (h "1gqjj4k5dwpyhwvdf00ks0f9s6lcq751kyn47lj9dzcrbvz7wf77") (f (quote (("use_cervus" "cervus"))))))

(define-public crate-ice_core-0.5.0 (c (n "ice_core") (v "0.5.0") (d (list (d (n "ansi_term") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.1.20") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.7") (d #t) (k 0)) (d (n "slab") (r "^0.4") (d #t) (k 0)) (d (n "tokio") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "wasm-core") (r "^0.2.9") (f (quote ("jit" "trans"))) (d #t) (k 0)))) (h "1vskllhz8f9gi4ibz2p8ydsbfdyfy0b2d0gpyv8wb8wq9rdq2rgv")))

(define-public crate-ice_core-0.5.1 (c (n "ice_core") (v "0.5.1") (d (list (d (n "ansi_term") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.1.20") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.7") (d #t) (k 0)) (d (n "slab") (r "^0.4") (d #t) (k 0)) (d (n "tokio") (r "^0.1") (d #t) (k 0)) (d (n "tokio-io") (r "^0.1") (d #t) (k 0)) (d (n "wasm-core") (r "^0.2.9") (f (quote ("jit" "trans"))) (d #t) (k 0)))) (h "1qa59rgknqnngrg9zxbxbpm417vk5hsdra001mbscwi5h70gn49x")))

