(define-module (crates-io eg ui egui_glow_tao) #:use-module (crates-io))

(define-public crate-egui_glow_tao-0.19.0 (c (n "egui_glow_tao") (v "0.19.0") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.19.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.19.0") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.11") (d #t) (k 0)) (d (n "glutin") (r "^0.29.1") (d #t) (k 2) (p "glutin_tao")) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.13") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "tracing") (r "^0.1") (f (quote ("std"))) (k 0)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "00zhvlhacfh1cni1xqgd60448w3l68r296bcg78mp1h75da5mcb4") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("screen_reader" "egui-winit?/screen_reader") ("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.61")))

(define-public crate-egui_glow_tao-0.19.1 (c (n "egui_glow_tao") (v "0.19.1") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.19.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.19.0") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.11") (d #t) (k 0)) (d (n "glutin") (r "^0.29.1") (d #t) (k 2) (p "glutin_tao")) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.13") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "tracing") (r "^0.1") (f (quote ("std"))) (k 0)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "1l6if5vi4jsacvb1qadw4a5i1bfg1660gpga136fprs82gwbmrs5") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("screen_reader" "egui-winit?/screen_reader") ("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.61")))

(define-public crate-egui_glow_tao-0.20.0 (c (n "egui_glow_tao") (v "0.20.0") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.19.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.20.0") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.11") (d #t) (k 0)) (d (n "glutin") (r "^0.30.0") (d #t) (k 2) (p "glutin_tao")) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.13") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "tracing") (r "^0.1") (f (quote ("std"))) (k 0)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "1jmjx72xf869779l8gxllfgw84jzadgk6faxbx8fmh7vnzgbzv17") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("screen_reader" "egui-winit?/screen_reader") ("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.61")))

(define-public crate-egui_glow_tao-0.20.1 (c (n "egui_glow_tao") (v "0.20.1") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.19.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.20.1") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.11") (d #t) (k 0)) (d (n "glutin") (r "^0.30.1") (d #t) (k 2) (p "glutin_tao")) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.13") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "tracing") (r "^0.1") (f (quote ("std"))) (k 0)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "1i2rdgfnaaj8gf8ky07s4jyh6z9w3qccpzaj41m45xi968l1w58l") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("screen_reader" "egui-winit?/screen_reader") ("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.61")))

(define-public crate-egui_glow_tao-0.21.0 (c (n "egui_glow_tao") (v "0.21.0") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.19.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.21.0") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.11") (d #t) (k 0)) (d (n "glutin") (r "^0.31.0") (d #t) (k 2) (p "glutin_tao")) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.13") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "tracing") (r "^0.1") (f (quote ("std"))) (k 0)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "1hbllc0m338vdrhfav0bb32gklncxdv0qxqlcgdyjg55dna7lv1w") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("screen_reader" "egui-winit?/screen_reader") ("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.61")))

(define-public crate-egui_glow_tao-0.22.0 (c (n "egui_glow_tao") (v "0.22.0") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.19.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.22.0") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.11") (d #t) (k 0)) (d (n "glutin") (r "^0.32.0") (d #t) (k 2) (p "glutin_tao")) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.13") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "tracing") (r "^0.1") (f (quote ("std"))) (k 0)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "0gjdilhpla567vnr40sanq9svhnc6s03df5m16xr2b5hpji7ivgn") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("screen_reader" "egui-winit?/screen_reader") ("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.61")))

(define-public crate-egui_glow_tao-0.23.0 (c (n "egui_glow_tao") (v "0.23.0") (d (list (d (n "bytemuck") (r "^1.7") (d #t) (k 0)) (d (n "document-features") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "egui") (r "^0.22.0") (f (quote ("bytemuck"))) (k 0)) (d (n "egui-winit") (r "^0.23.0") (o #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0) (p "egui-tao")) (d (n "glow") (r "^0.12") (d #t) (k 0)) (d (n "glutin") (r "^0.30") (d #t) (k 2)) (d (n "glutin-winit") (r "^0.33.0") (d #t) (k 2) (p "glutin_tao")) (d (n "log") (r "^0.4") (f (quote ("std"))) (d #t) (k 0)) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "puffin") (r "^0.15") (o #t) (d #t) (t "cfg(not(target_arch = \"wasm32\"))") (k 0)) (d (n "raw-window-handle") (r "^0.5.0") (d #t) (k 2)) (d (n "wasm-bindgen") (r "^0.2") (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)) (d (n "web-sys") (r "^0.3") (f (quote ("console"))) (d #t) (t "cfg(target_arch = \"wasm32\")") (k 0)))) (h "0bc1ycq0dkw8rfk0bww7h9qvmjblpmfdjyj1x8lsy8aws6640qsk") (f (quote (("winit" "egui-winit") ("default")))) (s 2) (e (quote (("puffin" "dep:puffin" "egui-winit?/puffin") ("links" "egui-winit?/links") ("clipboard" "egui-winit?/clipboard")))) (r "1.65")))

