(define-module (crates-io se rd serde_avro_derive_macros) #:use-module (crates-io))

(define-public crate-serde_avro_derive_macros-0.1.0 (c (n "serde_avro_derive_macros") (v "0.1.0") (d (list (d (n "darling") (r "^0.20") (d #t) (k 0)) (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2") (f (quote ("visit" "visit-mut" "extra-traits"))) (d #t) (k 0)))) (h "1ba71hpb27shscxpgyzyg0h29p9v0cv9nyps7brmr3s47l5a6h12")))

(define-public crate-serde_avro_derive_macros-0.1.1 (c (n "serde_avro_derive_macros") (v "0.1.1") (d (list (d (n "darling") (r "^0.20") (d #t) (k 0)) (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde_avro_derive") (r "^0.1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2") (f (quote ("visit" "visit-mut" "extra-traits"))) (d #t) (k 0)))) (h "0aamsspqj3q6g8kj58migckvdv761sdvzgldc6nn4n1f5cpyp44d")))

(define-public crate-serde_avro_derive_macros-0.1.2 (c (n "serde_avro_derive_macros") (v "0.1.2") (d (list (d (n "darling") (r "^0.20") (d #t) (k 0)) (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde_avro_derive") (r "^0.1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2") (f (quote ("visit" "visit-mut" "extra-traits"))) (d #t) (k 0)))) (h "1fnkw5iy7z68rj1b92j7yigad2b4fx6i7sjab2rdxm4xpabxk1p8")))

(define-public crate-serde_avro_derive_macros-0.2.0 (c (n "serde_avro_derive_macros") (v "0.2.0") (d (list (d (n "darling") (r "^0.20") (d #t) (k 0)) (d (n "heck") (r "^0.5") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde_avro_derive") (r "^0.1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2") (f (quote ("visit" "visit-mut" "extra-traits"))) (d #t) (k 0)))) (h "1ypf26diijxj88r20gsxs85ls3jmp02x344l8zy2cfs1fdn7p7rr")))

(define-public crate-serde_avro_derive_macros-0.2.1 (c (n "serde_avro_derive_macros") (v "0.2.1") (d (list (d (n "darling") (r "^0.20") (d #t) (k 0)) (d (n "heck") (r "^0.5") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde_avro_derive") (r "^0.2") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2") (f (quote ("visit" "visit-mut" "extra-traits"))) (d #t) (k 0)))) (h "0l3ksjrvhk76ni8g426lv6jdcxrwqvppxnf9m24319wsc38g9pxa")))

(define-public crate-serde_avro_derive_macros-0.2.2 (c (n "serde_avro_derive_macros") (v "0.2.2") (d (list (d (n "darling") (r "^0.20") (d #t) (k 0)) (d (n "heck") (r "^0.5") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 2)) (d (n "serde_avro_derive") (r "^0.2") (d #t) (k 2)) (d (n "serde_derive") (r "^1") (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2") (f (quote ("visit" "visit-mut" "extra-traits"))) (d #t) (k 0)))) (h "0vhbv1k9dklzi6xclkmz06wma86azlnfjzn0cgrijaqggnxrw8iq")))

