(define-module (crates-io bo re bore-cli) #:use-module (crates-io))

(define-public crate-bore-cli-0.1.0 (c (n "bore-cli") (v "0.1.0") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "1j3xcg6qk4z7y9j0kdy24hjbbw0aqqsw8rk6cz2z6ksyis3nr1fi")))

(define-public crate-bore-cli-0.1.1 (c (n "bore-cli") (v "0.1.1") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "09bjqjd1qcj2hrx6hb4azjk1n21yphj0yyc2agk98p2lnqf36ywf")))

(define-public crate-bore-cli-0.2.0 (c (n "bore-cli") (v "0.2.0") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "14p2backqk1jndqsbyrvsi4sgdrk45n8sli8y8fp4fpqk743bp3n")))

(define-public crate-bore-cli-0.2.1 (c (n "bore-cli") (v "0.2.1") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "0ra1llwz2ah806a0mhma08kzh3q0hhnjndiws1920l1y106p92pf")))

(define-public crate-bore-cli-0.2.2 (c (n "bore-cli") (v "0.2.2") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "0sd82lccb89a65c4rj6znkq1id6k4436abkf31fk0c22hy2mvxz4") (y #t)))

(define-public crate-bore-cli-0.2.3 (c (n "bore-cli") (v "0.2.3") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "1ax3lvgv97zhb82fl88yrpyfgwc2q6qcgjl4ql7xc4xq1vrqxx1v")))

(define-public crate-bore-cli-0.3.0 (c (n "bore-cli") (v "0.3.0") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive" "env"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("rt-multi-thread" "io-util" "macros" "net" "time"))) (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("sync"))) (d #t) (k 2)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "0g82aj4gsijw1m26x1893gn6cy8nidz44nf7pi9bmlqqzqdm3c24")))

(define-public crate-bore-cli-0.4.0 (c (n "bore-cli") (v "0.4.0") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^3.1.8") (f (quote ("derive" "env"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "futures-util") (r "^0.3.21") (f (quote ("sink"))) (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("rt-multi-thread" "io-util" "macros" "net" "time"))) (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("sync"))) (d #t) (k 2)) (d (n "tokio-util") (r "^0.7.1") (f (quote ("codec"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^0.8.2") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "1c7drv58aifjgyc4gf861fma4jc5nmiszb8ca1rgcqrqkxz9k1h0")))

(define-public crate-bore-cli-0.4.1 (c (n "bore-cli") (v "0.4.1") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^4.0.22") (f (quote ("derive" "env"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "futures-util") (r "^0.3.21") (f (quote ("sink"))) (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("rt-multi-thread" "io-util" "macros" "net" "time"))) (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("sync"))) (d #t) (k 2)) (d (n "tokio-util") (r "^0.7.1") (f (quote ("codec"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^1.2.1") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "1fghsj0a4w1ysm8z63clyj8y9l4wfhajqvmb4m8lcndzbn96whpv")))

(define-public crate-bore-cli-0.5.0 (c (n "bore-cli") (v "0.5.0") (d (list (d (n "anyhow") (r "^1.0.56") (f (quote ("backtrace"))) (d #t) (k 0)) (d (n "clap") (r "^4.0.22") (f (quote ("derive" "env"))) (d #t) (k 0)) (d (n "dashmap") (r "^5.2.0") (d #t) (k 0)) (d (n "fastrand") (r "^1.9.0") (d #t) (k 0)) (d (n "futures-util") (r "^0.3.21") (f (quote ("sink"))) (d #t) (k 0)) (d (n "hex") (r "^0.4.3") (d #t) (k 0)) (d (n "hmac") (r "^0.12.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "rstest") (r "^0.15.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.136") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.79") (d #t) (k 0)) (d (n "sha2") (r "^0.10.2") (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("rt-multi-thread" "io-util" "macros" "net" "time"))) (d #t) (k 0)) (d (n "tokio") (r "^1.17.0") (f (quote ("sync"))) (d #t) (k 2)) (d (n "tokio-util") (r "^0.7.1") (f (quote ("codec"))) (d #t) (k 0)) (d (n "tracing") (r "^0.1.32") (d #t) (k 0)) (d (n "tracing-subscriber") (r "^0.3.10") (d #t) (k 0)) (d (n "uuid") (r "^1.2.1") (f (quote ("serde" "v4"))) (d #t) (k 0)))) (h "04vaf1gkvpx00ia90q165fj30fq7511ra8jhfwivabzq4ynyfwps")))

