(define-module (crates-io la tt lattice-graph) #:use-module (crates-io))

(define-public crate-lattice-graph-0.3.0 (c (n "lattice-graph") (v "0.3.0") (d (list (d (n "const-generic-wrap") (r "^0.3") (o #t) (k 0)) (d (n "const-generic-wrap") (r "^0.3") (d #t) (k 2)) (d (n "criterion") (r "^0.3.4") (d #t) (k 2)) (d (n "fixedbitset") (r "^0.2") (d #t) (k 0)) (d (n "petgraph") (r "^0.5") (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 2)))) (h "0d40i7lbwi809a85rgxsp5acnhg42klnb9xj9xn7f28w2r1rgq9i") (f (quote (("default" "const-generic-wrap")))) (y #t)))

(define-public crate-lattice-graph-0.4.0 (c (n "lattice-graph") (v "0.4.0") (d (list (d (n "const-generic-wrap") (r "^0.3") (o #t) (k 0)) (d (n "const-generic-wrap") (r "^0.3") (d #t) (k 2)) (d (n "criterion") (r "^0.3.4") (d #t) (k 2)) (d (n "fixedbitset") (r "^0.2") (d #t) (k 0)) (d (n "petgraph") (r "^0.5") (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 2)) (d (n "rstest") (r "^0.10.0") (d #t) (k 2)))) (h "10ycvrs4yq0cimzyys2k67n754m89ccz165sw07k5swnlz84sr1b") (f (quote (("default" "const-generic-wrap"))))))

(define-public crate-lattice-graph-0.5.0 (c (n "lattice-graph") (v "0.5.0") (d (list (d (n "const-generic-wrap") (r "^0.3") (o #t) (k 0)) (d (n "const-generic-wrap") (r "^0.3") (d #t) (k 2)) (d (n "criterion") (r "^0.3.4") (d #t) (k 2)) (d (n "fixedbitset") (r "^0.2") (d #t) (k 0)) (d (n "petgraph") (r "^0.5") (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 2)) (d (n "rstest") (r "^0.10.0") (d #t) (k 2)))) (h "0bhi0iczgz4f1skxliqs2hhb71g0gk6wih055wjmks5jcqvj1jvv") (f (quote (("default" "const-generic-wrap"))))))

(define-public crate-lattice-graph-0.5.1 (c (n "lattice-graph") (v "0.5.1") (d (list (d (n "const-generic-wrap") (r "^0.3") (o #t) (k 0)) (d (n "const-generic-wrap") (r "^0.3") (d #t) (k 2)) (d (n "criterion") (r "^0.3.4") (d #t) (k 2)) (d (n "fixedbitset") (r "^0.2") (d #t) (k 0)) (d (n "petgraph") (r "^0.5") (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 2)) (d (n "rstest") (r "^0.10.0") (d #t) (k 2)))) (h "11ibmyyv7sc2xa1gldvq8yqvn3s8bw1xz59mcc177hr9a1vjzbm3") (f (quote (("default" "const-generic-wrap"))))))

(define-public crate-lattice-graph-0.6.1 (c (n "lattice-graph") (v "0.6.1") (d (list (d (n "const-generic-wrap") (r "^0.3") (o #t) (k 0)) (d (n "const-generic-wrap") (r "^0.3") (d #t) (k 2)) (d (n "criterion") (r "^0.3.4") (d #t) (k 2)) (d (n "fixedbitset") (r "^0.4") (d #t) (k 0)) (d (n "hex2d") (r "^1.0") (o #t) (k 0)) (d (n "petgraph") (r "^0.6") (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 2)) (d (n "rstest") (r "^0.12.0") (d #t) (k 2)))) (h "1d668kaymv060y40bv2gsgkj3vq9ynr42k8ksz1n8h6icvbvb1ys") (f (quote (("default" "const-generic-wrap" "hex2d"))))))

