(define-module (crates-io le lw lelwel) #:use-module (crates-io))

(define-public crate-lelwel-0.1.0 (c (n "lelwel") (v "0.1.0") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "10jpwcv7j6miaxqcp7yywf4b089qpbklrxpxsdxazxccfrbkyg67") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap")))) (y #t)))

(define-public crate-lelwel-0.1.1 (c (n "lelwel") (v "0.1.1") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "1yibiiwbkww70s433mwjg9zg887qijqcnaa32zvakzyf0bq0644v") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.1.2 (c (n "lelwel") (v "0.1.2") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "1zj5rcwm6y7bwyf2mjjb7v24s22xvzmrxcz6kgd66v9gz5qzi9zp") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.1.3 (c (n "lelwel") (v "0.1.3") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "0inixmz4q7x0w5aa1wiqzr4lsn7myi23jn56z6wa8z298pl68ci6") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.2.0 (c (n "lelwel") (v "0.2.0") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "0bsxn32jyd41g2hljidnjhn0p1qynmg4py8704x36y82j2zd5ssx") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.2.1 (c (n "lelwel") (v "0.2.1") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "0irqvcdhd2cf60kmxxan2gp7mp5b60sfp4badvb3smmixy18za6h") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.2.2 (c (n "lelwel") (v "0.2.2") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "1bs88xz4mi37zj785297l9sfmnrr4sh0kcq7hzb3zj7a5d1ahmhw") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.2.3 (c (n "lelwel") (v "0.2.3") (d (list (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "1chxwk0qgvfhri81hm789x3yzqkhrbgakgmbqkf158q0r4iib3qs") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap"))))))

(define-public crate-lelwel-0.2.4 (c (n "lelwel") (v "0.2.4") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "084df2nnzf31flhk7sds29hfzqvq2372hp5yq90nxp92jdc13vq7") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.2.5 (c (n "lelwel") (v "0.2.5") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "04vr6vb7n9q9hy6wsxbg900vz7jmv1rsr0dmca1anmmkdajfi6pd") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.3.0 (c (n "lelwel") (v "0.3.0") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "1sgbr18zx7rcllqd2v24g305h14kp2a8zr98h6kvqfzqkjmkv6p6") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.3.1 (c (n "lelwel") (v "0.3.1") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "1473a4iji37p3hn427g8q9pxmlhq1g6agiz5z5wlznhcxfspmr4r") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.4.0 (c (n "lelwel") (v "0.4.0") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "168j1z9ixs0a9ijrb7r54zzbkvz1xfhaxv81na33s5mr7gpjsl9w") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.4.1 (c (n "lelwel") (v "0.4.1") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.6.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.0-beta.2") (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.123") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.62") (o #t) (d #t) (k 0)))) (h "0mvsc4rf9g0g2yjfqa0apb9wivy41b1a7mw1sjqdjshq9x6qgrh4") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.4.2 (c (n "lelwel") (v "0.4.2") (d (list (d (n "atty") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "bumpalo") (r "^3.9.1") (f (quote ("collections" "boxed"))) (d #t) (k 0)) (d (n "clap") (r "^3.0.7") (f (quote ("cargo"))) (o #t) (d #t) (k 0)) (d (n "lsp-server") (r "^0.5.2") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.91.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.133") (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.74") (o #t) (d #t) (k 0)))) (h "0p5fkkjgf4ip38wljrdb87fpzsmlamwc5xgzw75p3n28pf86i2ad") (f (quote (("lsp" "lsp-server" "lsp-types" "serde" "serde_json") ("cli" "clap" "atty"))))))

(define-public crate-lelwel-0.5.0 (c (n "lelwel") (v "0.5.0") (d (list (d (n "clap") (r "^4.4") (f (quote ("cargo"))) (o #t) (d #t) (k 0)) (d (n "codespan-lsp") (r "^0.11.1") (o #t) (d #t) (k 0)) (d (n "codespan-reporting") (r "^0.11.1") (d #t) (k 0)) (d (n "logos") (r "^0.13.0") (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.29.1") (f (quote ("full"))) (o #t) (d #t) (k 0)) (d (n "tower-lsp") (r "^0.20.0") (o #t) (d #t) (k 0)))) (h "1niwjdnjyqnxclmh2p1cj3m4sxy7y2awnl76pdcml2rrglgwm2fx") (f (quote (("lsp" "tokio" "tower-lsp" "codespan-lsp" "lsp-types") ("cli" "clap"))))))

(define-public crate-lelwel-0.5.1 (c (n "lelwel") (v "0.5.1") (d (list (d (n "clap") (r "^4.4") (f (quote ("cargo"))) (o #t) (d #t) (k 0)) (d (n "codespan-lsp") (r "^0.11.1") (o #t) (d #t) (k 0)) (d (n "codespan-reporting") (r "^0.11.1") (d #t) (k 0)) (d (n "logos") (r "^0.13.0") (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.29.1") (f (quote ("full"))) (o #t) (d #t) (k 0)) (d (n "tower-lsp") (r "^0.20.0") (o #t) (d #t) (k 0)))) (h "08l8iih7hdg413gs8nrzih42lyhmp6da1nfgrhjjlyrx3vnlsa2b") (f (quote (("lsp" "tokio" "tower-lsp" "codespan-lsp" "lsp-types") ("cli" "clap"))))))

(define-public crate-lelwel-0.6.0 (c (n "lelwel") (v "0.6.0") (d (list (d (n "clap") (r "^4.4") (f (quote ("cargo"))) (o #t) (d #t) (k 0)) (d (n "codespan-lsp") (r "^0.11.1") (o #t) (d #t) (k 0)) (d (n "codespan-reporting") (r "^0.11.1") (d #t) (k 0)) (d (n "logos") (r "^0.14.0") (d #t) (k 0)) (d (n "lsp-types") (r "^0.88.0") (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.29.1") (f (quote ("full"))) (o #t) (d #t) (k 0)) (d (n "tower-lsp") (r "^0.20.0") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.92") (o #t) (d #t) (k 0)))) (h "0bp8nbdq8191rm59zfsv9d00ka73p0vxy7h7vax7d0vn7m70vc51") (f (quote (("wasm" "wasm-bindgen") ("lsp" "tokio" "tower-lsp" "codespan-lsp" "lsp-types") ("cli" "clap"))))))

