(define-module (crates-io pi nk pink-subrpc) #:use-module (crates-io))

(define-public crate-pink-subrpc-0.1.0 (c (n "pink-subrpc") (v "0.1.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "pink-extension") (r "^0.2") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.2") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.11") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^6.0.0") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "0p7d5dkskh4dnfdzsjdpca1s4c5lzkx6wfcrxcpjs3kp6cgzkl32") (f (quote (("std" "scale/std" "scale-info/std" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.1.1 (c (n "pink-subrpc") (v "0.1.1") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.2") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.2") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.11") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^6.0.0") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "0nzs7fv3xa41ilqp189n7h2qpsrw8klp9865ha90gd1qqjiasjl9") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std")))) (y #t)))

(define-public crate-pink-subrpc-0.2.0 (c (n "pink-subrpc") (v "0.2.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.2") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.2") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.11") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^6.0.0") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "0hwjpx9bv61si0j05ccydn38z5q7z14knvi95rp1gps1cgdn17wb") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.2.1 (c (n "pink-subrpc") (v "0.2.1") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.2") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.2") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.1") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^5") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "1a5kgy4jqqn9640lakaz71r64ljndlda2n89fbcq10rqchisaxxc") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.3.0 (c (n "pink-subrpc") (v "0.3.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.4") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.4") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.1") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^5") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "0xiy08w2y2227qjj46fpyvrf573n6pdm5cprrbb7nax24m13mg2c") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std")))) (y #t)))

(define-public crate-pink-subrpc-0.4.0 (c (n "pink-subrpc") (v "0.4.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.4") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.4") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.1") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^5") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "1gj1blqm5grlq819wd3dkfl0p8d46zrim0rrmchk812zxkqsqmc7") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.4.1 (c (n "pink-subrpc") (v "0.4.1") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.4") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.4") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.1") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^5") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "1kg1v48hh1vlf9628z9q3w9igrnpq80qadikahfnzdpg4ic52kbv") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.4.2 (c (n "pink-subrpc") (v "0.4.2") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.3") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.4") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.4") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.1") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.1") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^5") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "0ndmhvys60hq8gl5jalfxrwaaq8ifgnq7rfy1w7b3mhggvs4xa5d") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.4.3 (c (n "pink-subrpc") (v "0.4.3") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.4.1") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.4") (f (quote ("ink-as-dependency"))) (k 0)) (d (n "pink-extension-runtime") (r "^0.4") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.1") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.3") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^9") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "00yv075614rmal1fs8dbh23nbczmwgjfdzf498f2f89mz07vwrn8") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.4.4 (c (n "pink-subrpc") (v "0.4.4") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.4.1") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.4") (k 0)) (d (n "pink-extension-runtime") (r "^0.4") (d #t) (k 2)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.2") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.6.5") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2.10.0") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^9") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "13gbbwc5ksbybynz3q6n79lskg7nlbijymynl01rmcx52cib8kzm") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std")))) (y #t)))

(define-public crate-pink-subrpc-0.5.0 (c (n "pink-subrpc") (v "0.5.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.4.1") (d #t) (k 0)) (d (n "impl-serde") (r "^0.4.0") (o #t) (d #t) (k 0)) (d (n "pink-extension") (r "^0.5") (k 0)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.2") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.6.5") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2.10.0") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^9") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "1zigmy5js7wly16j4s82fqvsn9h27a57qrkzwavrm1nbqdcy5g9z") (f (quote (("std" "scale/std" "scale-info/std" "impl-serde" "pink-extension/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.6.0-dev.0 (c (n "pink-subrpc") (v "0.6.0-dev.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.4.1") (d #t) (k 0)) (d (n "pink") (r "^0.1.0-dev.0") (k 0)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.2") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.6.5") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2.10.0") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^9") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "0h6q6r89h6ismawvli4cfba3pqv5c9iz1f6cbi080klckjkcmzs9") (f (quote (("std" "scale/std" "scale-info/std" "pink/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

(define-public crate-pink-subrpc-0.6.0 (c (n "pink-subrpc") (v "0.6.0") (d (list (d (n "base58") (r "^0.2.0") (k 0)) (d (n "hex") (r "^0.4.3") (f (quote ("alloc"))) (k 0)) (d (n "hex-literal") (r "^0.4.1") (d #t) (k 0)) (d (n "pink") (r "^0.4.0") (k 0)) (d (n "pink-json") (r "^0.4") (k 0)) (d (n "primitive-types") (r "^0.12.2") (f (quote ("codec" "scale-info"))) (k 0)) (d (n "scale") (r "^3.6.5") (f (quote ("derive"))) (k 0) (p "parity-scale-codec")) (d (n "scale-info") (r "^2.10.0") (f (quote ("derive"))) (o #t) (k 0)) (d (n "serde") (r "^1.0.140") (f (quote ("derive" "alloc"))) (k 0)) (d (n "sp-core-hashing") (r "^9") (k 0)) (d (n "ss58-registry") (r "^1.33.0") (k 0)))) (h "08bn51mvylfhmb36qp5wyavfqd80fijgl4biqhnbjnhck5izc1j8") (f (quote (("std" "scale/std" "scale-info/std" "pink/std" "pink-json/std" "sp-core-hashing/std" "primitive-types/std") ("default" "std"))))))

