(define-module (crates-io al ir aliri_braid_impl) #:use-module (crates-io))

(define-public crate-aliri_braid_impl-0.1.0 (c (n "aliri_braid_impl") (v "0.1.0") (d (list (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "00v2gfivfci8lj2rcbymfgdfxz0fz79bc55k0znwbr02f3h41zn4")))

(define-public crate-aliri_braid_impl-0.1.1 (c (n "aliri_braid_impl") (v "0.1.1") (d (list (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0v5d86ihm6w4hvk72pl3cmr144xy9jgylkxsw8kif8clvyq8m0r9")))

(define-public crate-aliri_braid_impl-0.1.2 (c (n "aliri_braid_impl") (v "0.1.2") (d (list (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "12spzvdpmpzdlnp58i4822xbr46mri009sllx5iminlzw1nm01jg")))

(define-public crate-aliri_braid_impl-0.1.3 (c (n "aliri_braid_impl") (v "0.1.3") (d (list (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1fjhdccy5y2zj55zpp92xd8bcyqc3y89zv6sxmczwjcd6vwxnyaf")))

(define-public crate-aliri_braid_impl-0.1.4 (c (n "aliri_braid_impl") (v "0.1.4") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1b5wjvaydq4i83g5k4yjq7lr4x7z1mxnp05bak7i6hgxckpmndkv")))

(define-public crate-aliri_braid_impl-0.1.5 (c (n "aliri_braid_impl") (v "0.1.5") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "14g4chqzxn20y6nnv77z23fwc16y8njl9bvxzg6hv9n3k5fqfdhf")))

(define-public crate-aliri_braid_impl-0.1.6 (c (n "aliri_braid_impl") (v "0.1.6") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0ywz92y1bczbc5f3z8md93xirr46csz12z8r16awkyczgc9cdl52")))

(define-public crate-aliri_braid_impl-0.1.7 (c (n "aliri_braid_impl") (v "0.1.7") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1qb3wpspgq6cfakvsx3crd42bdn9a50v5z3d3d58v09g2f4xn7a9")))

(define-public crate-aliri_braid_impl-0.1.8 (c (n "aliri_braid_impl") (v "0.1.8") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "051ggqqr9m4vfabjklxmvlh8z99ymb43majldfn382a583b8ny3k")))

(define-public crate-aliri_braid_impl-0.1.9 (c (n "aliri_braid_impl") (v "0.1.9") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0hj3k76wn3ysqdfwknyzfq5kg5wa4k3p06iqdc2q8fckihlxc8bf")))

(define-public crate-aliri_braid_impl-0.1.10 (c (n "aliri_braid_impl") (v "0.1.10") (d (list (d (n "pretty_assertions") (r "^0.7.2") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1i8h251ljq36cdk6j2gwb0ffvaw3hc8sp5jdhvhhn1ycvsbzx6hg")))

(define-public crate-aliri_braid_impl-0.2.0 (c (n "aliri_braid_impl") (v "0.2.0") (d (list (d (n "pretty_assertions") (r "^1.2.1") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0i170iyqma3bhf22dzaizmjqzqd5cqnw0np8cwazxhknix1aw4gm")))

(define-public crate-aliri_braid_impl-0.2.1 (c (n "aliri_braid_impl") (v "0.2.1") (d (list (d (n "pretty_assertions") (r "^1.2.1") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1rm8q5mykd6gr91zc8d73n539wd0fhkhqwwzcyjm58cx62509fgc")))

(define-public crate-aliri_braid_impl-0.2.2 (c (n "aliri_braid_impl") (v "0.2.2") (d (list (d (n "pretty_assertions") (r "^1.2.1") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0fbqqfcdnjb66cb2bcmmfn8n45ydcfw6rbp3bvqc59h96c100kix")))

(define-public crate-aliri_braid_impl-0.2.3 (c (n "aliri_braid_impl") (v "0.2.3") (d (list (d (n "pretty_assertions") (r "^1.2.1") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "02ai16ajfql78jc6bd488zn7yw463avkv2cxjjx94ww52v53pw6h")))

(define-public crate-aliri_braid_impl-0.2.4 (c (n "aliri_braid_impl") (v "0.2.4") (d (list (d (n "pretty_assertions") (r "^1.2.1") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "1jznpr58fmlyfnbdvzp96v92qdfxnp5f08y72p6akz53mf56r1f0")))

(define-public crate-aliri_braid_impl-0.3.0 (c (n "aliri_braid_impl") (v "0.3.0") (d (list (d (n "pretty_assertions") (r "^1.3.0") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0vnm7zcvkp5wd3mcs53nfwxv9mlm6yxwm45cnxf0w590q5agqsq1")))

(define-public crate-aliri_braid_impl-0.3.1 (c (n "aliri_braid_impl") (v "0.3.1") (d (list (d (n "pretty_assertions") (r "^1.3.0") (d #t) (k 2)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^1") (f (quote ("full"))) (d #t) (k 0)))) (h "0x0bf47rgzrz4rk9lavskinx5prhl3k1430p7428v3lr9s1yg8dx")))

(define-public crate-aliri_braid_impl-0.4.0 (c (n "aliri_braid_impl") (v "0.4.0") (d (list (d (n "pretty_assertions") (r "^1.3.0") (d #t) (k 2)) (d (n "proc-macro2") (r "^1.0.56") (d #t) (k 0)) (d (n "quote") (r "^1.0.26") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 2)) (d (n "serde_json") (r "^1") (d #t) (k 2)) (d (n "syn") (r "^2.0.15") (f (quote ("full"))) (d #t) (k 0)))) (h "10q2q8pq5klb0bcy41x20n7d6ihkcsdp52n1jrkqm1g1rm7prsyi")))

