(define-module (crates-io mc -s mc-sgx-tservice) #:use-module (crates-io))

(define-public crate-mc-sgx-tservice-0.2.0 (c (n "mc-sgx-tservice") (v "0.2.0") (d (list (d (n "mc-sgx-core-sys-types") (r "=0.2.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.2.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.2.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.2.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.2.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.2.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.2.0") (d #t) (k 0)))) (h "1w0r3gy1zv4vzxw8s66z93lfrfpk5zhc8yphnch4m5pf5jy80ch3") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.2.1 (c (n "mc-sgx-tservice") (v "0.2.1") (d (list (d (n "mc-sgx-core-sys-types") (r "=0.2.1") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.2.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.2.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.2.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.2.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.2.1") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.2.1") (d #t) (k 0)))) (h "1zqn9jn6cpdhb1jmynl9p897b8xdwcndvkqswdab4fsi5ifwja19") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.3.0 (c (n "mc-sgx-tservice") (v "0.3.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.3.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.3.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.3.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.3.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.3.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.3.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.3.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.3.0") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0qlq1jifa2nkwgzqwcqvv612lpqjacfl0jyxg5214hw8iwhfnl00") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.4.0 (c (n "mc-sgx-tservice") (v "0.4.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.4.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.4.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.4.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.4.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.4.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.4.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.4.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.4.0") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1vv88dr03j5j4p0nvj5kf89myr1lhv2m5kgrk28m06lvdmkjr0yi") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.4.1 (c (n "mc-sgx-tservice") (v "0.4.1") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.4.1") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.4.1") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.4.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.4.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.4.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.4.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.4.1") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.4.1") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1d9dvyckwxgrh86kk35zkpxk1zbz57rpkdfkp7k4wf1zjamwv3pq") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.4.2 (c (n "mc-sgx-tservice") (v "0.4.2") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.4.2") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.4.2") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.4.2") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.4.2") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.4.2") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.4.2") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.4.2") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.4.2") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0yd0m73rvzfacpk02r437hly7zniqs5cg5d1w7scdb0bbknl2q2c") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.5.0 (c (n "mc-sgx-tservice") (v "0.5.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.5.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.5.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.5.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.5.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.5.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.5.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.5.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.5.0") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1bsyqd21g6plkp2gk8l0mijvdj0cmb7s3lwx9fw0plj8cdffas4n") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.6.0 (c (n "mc-sgx-tservice") (v "0.6.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.6.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.6.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.6.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.6.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.6.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.6.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.6.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.6.0") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0als84vjq33rf96ihr7j93l4m59wd6jf8i0mqqmmpj11cjzbni7r") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.6.1 (c (n "mc-sgx-tservice") (v "0.6.1") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.6.1") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.6.1") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.6.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.6.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.6.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.6.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.6.1") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.6.1") (d #t) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1qs49jp5s6kbmpykd02g2rirhzzxy0xv595sjnpfva8bqk9dg6wy") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.7.0 (c (n "mc-sgx-tservice") (v "0.7.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.7.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.7.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.7.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.7.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.7.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.7.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.152") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0992j3fjk1kacbfy28k8cny9a9k6703385wll72xh384wqkv6mvp") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.7.1 (c (n "mc-sgx-tservice") (v "0.7.1") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.7.1") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.7.1") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.7.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.7.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.7.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.1") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.7.1") (d #t) (k 0)) (d (n "serde") (r "^1.0.152") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0dcb4gfamdi6ha1dygrrm43709kznrdw2cqk4v927vs99m1yv828") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.7.2 (c (n "mc-sgx-tservice") (v "0.7.2") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.7.2") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.7.2") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.7.2") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.7.2") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.7.2") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.2") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.2") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.7.2") (d #t) (k 0)) (d (n "serde") (r "^1.0.152") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1hhlnvv4vcanf4xa1lmd4hqzvnb3i713xzq3c50j9fyk4b4ydcbc") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.7.3 (c (n "mc-sgx-tservice") (v "0.7.3") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.7.3") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.7.3") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.7.3") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.7.3") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.7.3") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.3") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.3") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.7.3") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "010mwcwfvb6p14ik76dxym1h4di5img78l30q8z6rfcqy3bx60sa") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.7.4 (c (n "mc-sgx-tservice") (v "0.7.4") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.7.4") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.7.4") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.7.4") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.7.4") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.7.4") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.4") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.4") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.7.4") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "08dqas769iqr1mlaqbmrv0vb83m3v2s5rdlppx55l33dp1vjnn5i") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.7.5 (c (n "mc-sgx-tservice") (v "0.7.5") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.7.5") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.7.5") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.7.5") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.7.5") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.7.5") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.5") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.7.5") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.7.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "03gcbpj7nmmmlg8pd5m3845pmj53zc5hyw2ivwj3vlgiqqg0rxcd") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.8.0 (c (n "mc-sgx-tservice") (v "0.8.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.8.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.8.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.8.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.8.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.8.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.8.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.8.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.8.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0h5bbvajxkzi6zr97ij9d5pnsdrf66f71g78lgp3sz019mqjhs5k") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.9.0 (c (n "mc-sgx-tservice") (v "0.9.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.9.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.9.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.9.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.9.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.9.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.9.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.9.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.9.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "0kl60k2kh0r4q7yw4xl64pbjc7rjj45hr74a7832ff9dpb47vzks") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.10.0 (c (n "mc-sgx-tservice") (v "0.10.0") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.10.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.10.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.10.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.10.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.10.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.10.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.10.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.10.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1nva46jlxn5k7899ixizdvsr9xvhmband3km4iq8gv20n75smgv6") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.10.1 (c (n "mc-sgx-tservice") (v "0.10.1") (d (list (d (n "displaydoc") (r "^0.2.3") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.10.1") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.10.1") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.10.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.10.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.10.1") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.10.1") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.10.1") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.10.1") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^1.0.2") (d #t) (k 2)))) (h "1053j9nz0y9qik7753aqql4q0sg7bbcw4vylkwpy9win3p98r62f") (r "1.62.1")))

(define-public crate-mc-sgx-tservice-0.11.0 (c (n "mc-sgx-tservice") (v "0.11.0") (d (list (d (n "displaydoc") (r "^0.2") (k 0)) (d (n "mc-sgx-core-sys-types") (r "=0.11.0") (d #t) (k 0)) (d (n "mc-sgx-core-types") (r "=0.11.0") (d #t) (k 0)) (d (n "mc-sgx-trts") (r "=0.11.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys") (r "=0.11.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-sys-types") (r "=0.11.0") (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.11.0") (f (quote ("alloc"))) (d #t) (k 0)) (d (n "mc-sgx-tservice-types") (r "=0.11.0") (f (quote ("test-utils"))) (d #t) (k 2)) (d (n "mc-sgx-util") (r "=0.11.0") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "alloc"))) (k 0)) (d (n "yare") (r "^2") (d #t) (k 2)))) (h "1zyh02yp0gq3qmjczfny9apb14la49jca6z6wcgfm7z31nf46ynw") (r "1.62.1")))

