(define-module (crates-io pr oc processes) #:use-module (crates-io))

(define-public crate-processes-0.1.0 (c (n "processes") (v "0.1.0") (d (list (d (n "path-absolutize") (r "^3.0") (k 0)) (d (n "same-file") (r "^1.0") (k 0)) (d (n "shrinkwraprs") (r "^0.3") (k 0)) (d (n "stopwatch2") (r "^2.0") (k 0)) (d (n "sysinfo") (r "^0.27") (k 0)) (d (n "thiserror") (r "^1.0") (k 0)) (d (n "widestring") (r "^1.0") (f (quote ("std" "alloc"))) (k 0)) (d (n "winapi") (r "^0.3") (f (quote ("processthreadsapi" "wow64apiset"))) (k 0)) (d (n "current_platform") (r "^0.2") (k 2)) (d (n "tempfile") (r "^3.3") (k 2)))) (h "1q9n3ylmf9vl6vvpv0p1fwv0s1k131q7y4dhwhnpwkf7ds74r3nj") (f (quote (("remote-alloc" "memory" "nightly") ("nightly") ("memory" "winapi/memoryapi") ("full" "default") ("doc-cfg" "full") ("default" "memory"))))))

(define-public crate-processes-0.2.0 (c (n "processes") (v "0.2.0") (d (list (d (n "memoffset") (r "^0.8") (k 0)) (d (n "ntapi") (r "^0.4") (f (quote ("user"))) (k 0)) (d (n "path-absolutize") (r "^3.0") (k 0)) (d (n "same-file") (r "^1.0") (k 0)) (d (n "shrinkwraprs") (r "^0.3") (k 0)) (d (n "stopwatch2") (r "^2.0") (k 0)) (d (n "thiserror") (r "^1.0") (k 0)) (d (n "widestring") (r "^1.0") (f (quote ("std" "alloc"))) (k 0)) (d (n "winapi") (r "^0.3") (f (quote ("processthreadsapi" "wow64apiset" "winbase" "synchapi" "psapi" "sysinfoapi"))) (k 0)) (d (n "winresult") (r "^0.1") (k 0)) (d (n "current_platform") (r "^0.2") (k 2)) (d (n "tempfile") (r "^3.3") (k 2)))) (h "0bkfnp689aqql1525a13pczr1rkyvcjk0fd3q7zn3gyzfxd49vl0") (f (quote (("remote-alloc" "memory" "nightly") ("nightly") ("memory" "winapi/memoryapi") ("full" "default") ("doc-cfg" "full") ("default" "memory"))))))

(define-public crate-processes-0.3.0 (c (n "processes") (v "0.3.0") (d (list (d (n "memoffset") (r "^0.8") (k 0)) (d (n "ntapi") (r "^0.4") (f (quote ("user"))) (k 0)) (d (n "path-absolutize") (r "^3.0") (k 0)) (d (n "same-file") (r "^1.0") (k 0)) (d (n "shrinkwraprs") (r "^0.3") (k 0)) (d (n "stopwatch2") (r "^2.0") (k 0)) (d (n "thiserror") (r "^1.0") (k 0)) (d (n "widestring") (r "^1.0") (f (quote ("std" "alloc"))) (k 0)) (d (n "winapi") (r "^0.3") (f (quote ("processthreadsapi" "wow64apiset" "winbase" "synchapi" "psapi" "sysinfoapi"))) (k 0)) (d (n "winresult") (r "^0.1") (k 0)) (d (n "current_platform") (r "^0.2") (k 2)) (d (n "tempfile") (r "^3.3") (k 2)))) (h "10wdkgz5rbpmg9cfimbzml4gj21bfvfj8adx2x23zmplkkcl4zal") (f (quote (("remote-alloc" "memory" "nightly") ("nightly") ("memory" "winapi/memoryapi") ("full" "default") ("doc-cfg" "full") ("default" "memory"))))))

(define-public crate-processes-0.4.0 (c (n "processes") (v "0.4.0") (d (list (d (n "current_platform") (r "^0.2") (k 2)) (d (n "memoffset") (r "^0.8") (k 0)) (d (n "ntapi") (r "^0.4") (f (quote ("user"))) (k 0)) (d (n "path-absolutize") (r "^3.0") (k 0)) (d (n "same-file") (r "^1.0") (k 0)) (d (n "shrinkwraprs") (r "^0.3") (k 0)) (d (n "stopwatch2") (r "^2.0") (k 0)) (d (n "tempfile") (r "^3.3") (k 2)) (d (n "thiserror") (r "^1.0") (k 0)) (d (n "widestring") (r "^1.0") (f (quote ("std" "alloc"))) (k 0)) (d (n "winapi") (r "^0.3") (f (quote ("processthreadsapi" "wow64apiset" "winbase" "synchapi" "psapi" "sysinfoapi"))) (k 0)) (d (n "winresult") (r "^0.1") (k 0)))) (h "1lv3y8rqjz1j4ays7vfl31y61f8kkfkl20q8amqmba39gpxaw63x") (f (quote (("remote-alloc" "memory" "nightly") ("nightly") ("memory" "winapi/memoryapi") ("full" "default") ("doc-cfg" "full") ("default" "memory"))))))

