(define-module (crates-io na pi napi-derive-backend) #:use-module (crates-io))

(define-public crate-napi-derive-backend-1.0.0 (c (n "napi-derive-backend") (v "1.0.0") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "021pk6sqn6b9gj8f88hk46r1i2pp4il1jk04a0c9bbjnswrvg8zw") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.1 (c (n "napi-derive-backend") (v "1.0.1") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1lc07avpg9c0irpk9n64wdwjcp0xkkvs9hr7gkd0h5zmmlash91k") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.2 (c (n "napi-derive-backend") (v "1.0.2") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1jlzwgfqivc26rq5xvc7bw5y3bxdnz8j9izvcwqhjxh2ldwwsxbs") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.3 (c (n "napi-derive-backend") (v "1.0.3") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "01p4y8zbm8kciwv4c296yjm02bl8z095hxzkr45kgpp6ldsijsdr") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.4 (c (n "napi-derive-backend") (v "1.0.4") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0kh90wyv652bh0yjvvw25xjhf8nphyrn6c665an4hs1cjifqi8b3") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.5 (c (n "napi-derive-backend") (v "1.0.5") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1sxq8idycd6kxkmn80krzks2qj1aj3p45dv5h3zjvbgbw7wrmsbp") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.6 (c (n "napi-derive-backend") (v "1.0.6") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0r6b5j85zwcia64mhdsj5v8377k8rmz0l6jgqk3a1jaihq4vliwl") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.7 (c (n "napi-derive-backend") (v "1.0.7") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0pyblmkhrxd2ca4209vb99pvxxiwj39iw32avabqj62cz0xrzhpd") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.8 (c (n "napi-derive-backend") (v "1.0.8") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1vzr5qizdw39rir2a8kb5jvawvzmx0nicsqmr5cgggjczg1k51w8") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.9 (c (n "napi-derive-backend") (v "1.0.9") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1h8sv07f1vqk9rihliifzzxivlswq96lhih0pzhgxrcna2xz7p04") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.10 (c (n "napi-derive-backend") (v "1.0.10") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0jwm7rzzckipkrwas5pfa0ym7727aqzdixl1017k40qzq29mjnxg") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.11 (c (n "napi-derive-backend") (v "1.0.11") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "12inri7h9rdw22g80s6kh7s0a8q2bpc49jcngjkmy962l2xbiqp5") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.12 (c (n "napi-derive-backend") (v "1.0.12") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1m4fbhhjffprzviilnh7gaq3wgkxa034w0095plp3lypk8kbpq51") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.13 (c (n "napi-derive-backend") (v "1.0.13") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "03zhz6r1y7lf3dsmiswy2n7hl3fz8vcbbc7yzz0w2xfwvizyhmsq") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.14 (c (n "napi-derive-backend") (v "1.0.14") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "04sajbngfxmkgchqw9m3x17rlgq2q9kclxdn38cps9cqnw3363gh") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.15 (c (n "napi-derive-backend") (v "1.0.15") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0rqhv24grf5x4czmpjikyp1ya4sxv8kzl6rgyij2dj653q5crjqq") (f (quote (("type-def" "regex" "once_cell") ("strict"))))))

(define-public crate-napi-derive-backend-1.0.16 (c (n "napi-derive-backend") (v "1.0.16") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1zkavbsn9fpxi9jqhfjprvrp466imdiwmlnlda0mhp6s583mlqqh") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.17 (c (n "napi-derive-backend") (v "1.0.17") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0il0r93pb6vqgmpsm0q3c4kzq1a3vgqx86llijj7ldq2zfcb648v") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.18 (c (n "napi-derive-backend") (v "1.0.18") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "00d7712dh820spcwb4c42p5pf9mb201g8akr84x08drizj1y94n9") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.19 (c (n "napi-derive-backend") (v "1.0.19") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "02cfmr17zzl8hpcg5yy7pjzkq9r970jzdj42agqqd6gx561h7x4j") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.20 (c (n "napi-derive-backend") (v "1.0.20") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "16m76mvgil3j9cd2cam1gg4jl7921c1a9hgj1mz85cxsb2kbpzhg") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.21 (c (n "napi-derive-backend") (v "1.0.21") (d (list (d (n "convert_case") (r "^0.4") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "13a4z8lqvw2zs434jbhlmpp1ripacf9xxjisz6diw8apfq8kjz28") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.22 (c (n "napi-derive-backend") (v "1.0.22") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "026mg96a900jla0z1g8idxmzgy2ya5s4vkrx800v4cwycpi3xymh") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.23 (c (n "napi-derive-backend") (v "1.0.23") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "09gfgq119k3xri888fn27lxw0xsij6wz1c09asp5qnnxfniksqih") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.24 (c (n "napi-derive-backend") (v "1.0.24") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0y6jk21ynyini1a9aph1dds5wkqqr2miwxz19jfri8l5x62n72r9") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.25 (c (n "napi-derive-backend") (v "1.0.25") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1bxl49a322j8zcg4ls8dansvqwfnsribxl8543rcsdana824yzs2") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.26 (c (n "napi-derive-backend") (v "1.0.26") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1vj7gznl0w409pni15jddz5q88yjb69lvn5ybxv5hk11sa9v44kb") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.27-canary.0 (c (n "napi-derive-backend") (v "1.0.27-canary.0") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1v51f7viznn6fajqxsmz3agair7ip7vim8v1m2iwsivqv68id20p") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.27-canary.1 (c (n "napi-derive-backend") (v "1.0.27-canary.1") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0djar8axkvbxcby02ywmllcrawphaj6672iwmiqqvrjj81r90wj4") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.27 (c (n "napi-derive-backend") (v "1.0.27") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "10yvjrri4b66hr5prjr2a72kxrj9g4qj9124gng8a17n6kw6kqr7") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.28 (c (n "napi-derive-backend") (v "1.0.28") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0k51r3gy2ydnpfj4vj870cz4nw4mpfzm69gfj83yah6v3hjhxsvi") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.29 (c (n "napi-derive-backend") (v "1.0.29") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1jsa1g4zizwbclz50b1kn9s9dv5aq89wx3kdgq1bagh1x1h5ckjw") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.30 (c (n "napi-derive-backend") (v "1.0.30") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0v6blss05fxn3klqvx6rwbshfmscpl5235kqk713f96jgwai39qi") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.31 (c (n "napi-derive-backend") (v "1.0.31") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0m47dz74j9yzcwnba4qjh2pyhd44mwn178yhxcm1g9dlvp0smk8b") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.32 (c (n "napi-derive-backend") (v "1.0.32") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1f1mp00bxjqib6awa178gsxwbn71d1dxx3c5yg0h4hjgl4yvijm5") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop"))))))

(define-public crate-napi-derive-backend-1.0.33 (c (n "napi-derive-backend") (v "1.0.33") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1skqk9qlbj9gk9b6q90cpb4b69nad54y6ln9s32s3z7bcpl0cxn9") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.34 (c (n "napi-derive-backend") (v "1.0.34") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "08g4j4yq4mv08cs4rc0wm03jwxd3x8k5p0l8z4acrv14fpl9pnqc") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.35 (c (n "napi-derive-backend") (v "1.0.35") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0f0d7akcrcny145vrmz5zm31hiz2pxqhq2rpz3sk2padx01ybq7y") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.36 (c (n "napi-derive-backend") (v "1.0.36") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1w4x9bhlnckmik92kiiiz51riarkih74lrdicwn30bfk6kgwc49v") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.37 (c (n "napi-derive-backend") (v "1.0.37") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0c59l0wk77d6c5h04fyp4w87sqvd9kfxa25j4rvqmb2g4q04iflj") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.38 (c (n "napi-derive-backend") (v "1.0.38") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0dmb3ir9r1gm870zk0jdnl9crcmn5w8iqfk5s75jyi7b2c2n8dbc") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.39 (c (n "napi-derive-backend") (v "1.0.39") (d (list (d (n "convert_case") (r "^0.5") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1ig4rdp0v0m192ll933ld9lf38qblciywgm31zj57dk16axyknv6") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.40 (c (n "napi-derive-backend") (v "1.0.40") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0hv89z3ivgm1gpdvzv689av604sg3b60hijbirpn7ymn0kzmz4hp") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.41 (c (n "napi-derive-backend") (v "1.0.41") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0nqwrh3a1xx92zrvn2zihy1wp7kfadrnvzsgf8byxsxf04il2fz1") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.42 (c (n "napi-derive-backend") (v "1.0.42") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "132j7yhhjc7iavs7gky5713hbm5fr2hscpw3kz9c5wdpl84siima") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.43 (c (n "napi-derive-backend") (v "1.0.43") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0q8dxdgp7a8qk61hr9639274p5am37l2rzcdia9w6gp73sxydr2p") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.44 (c (n "napi-derive-backend") (v "1.0.44") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0va0wvvv0hwcvdgqcg3zxrs5a28dnwb0hkvbgng3nrpmf3xdac29") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.45 (c (n "napi-derive-backend") (v "1.0.45") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "10dkmgdq5ksfpb4qxmcqy4aamwq1j8i9x01dbsdipmgny6jlpky2") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.46 (c (n "napi-derive-backend") (v "1.0.46") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1y9ix3pi3xx9dw2rb8in53vijvhkl4f1sbydkkgh4x5y45nlkncw") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.47 (c (n "napi-derive-backend") (v "1.0.47") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1nf7f791dj78hxl0xckdfjqiqfgkm8gz1i7jgijw6aqvf1lfxw38") (f (quote (("type-def" "regex" "once_cell") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.48 (c (n "napi-derive-backend") (v "1.0.48") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0z0c087fgm4337sf1v75xcb2y7n9ffnnzi7dkanxd9msyngzy4y7") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.49 (c (n "napi-derive-backend") (v "1.0.49") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "09crp78d7pwkaa8wkid4z8f73j7ai3j3zamhhfvl0gl09nybachf") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.50 (c (n "napi-derive-backend") (v "1.0.50") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0jgklrdhkvrdr1vw20diqnvzfy65rqk9vn7q99y9qg5fa0jq81y3") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.51 (c (n "napi-derive-backend") (v "1.0.51") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1rsln1pd98z5rlw2l5pifijbdpiz6kd54fp3ss7gk9jbbfpaz0qa") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.52 (c (n "napi-derive-backend") (v "1.0.52") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "05wy00faa3bz2lqcrwnlr3l9hzwrw3qcapljiy26ml38j73cgfr0") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.57")))

(define-public crate-napi-derive-backend-1.0.53 (c (n "napi-derive-backend") (v "1.0.53") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1p439lr4xx67rp4p7hgcfcl2yhbbxxnyq3fixwyrga4xp0kyww14") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.54 (c (n "napi-derive-backend") (v "1.0.54") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "007gj6liz1dw9paylqqsywvmyk1kys9d3754j7ap6302ai5ymlzc") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.55 (c (n "napi-derive-backend") (v "1.0.55") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "14avyvadx03nsv25hh2vzy83fnlgzq6psi31nslr50926dghx5im") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.56 (c (n "napi-derive-backend") (v "1.0.56") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^1.0.61") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1cqv3fjcx8dcwxga601a6lvswby6bdmc6f7yvxbspz8m0vcf8sa8") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.57 (c (n "napi-derive-backend") (v "1.0.57") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1y5lrp919r0rb6j3gh2pl8l2wmmh0zj2281s44k6j7aj3cr3d8jf") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.58 (c (n "napi-derive-backend") (v "1.0.58") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1i27vmfbpgnbkw0ksv8wyjiy8kgfdi34874rbmq53plwpivzf513") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.59 (c (n "napi-derive-backend") (v "1.0.59") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "17ld99dgsxxpbbi0k6xm1y2wpil9mj1zdrsmprcsj66fbzb19icf") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.60 (c (n "napi-derive-backend") (v "1.0.60") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "11lpxg9s07d3cqazcs0awb7qmkhx3kfmzrvbck5wrlbgqr5dgwkc") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.61 (c (n "napi-derive-backend") (v "1.0.61") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (o #t) (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "07gzi6vfn8092i2agvlpsr0bnqdr4c1zqfah4anpq01p7908yfyh") (f (quote (("type-def" "regex" "once_cell" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.62 (c (n "napi-derive-backend") (v "1.0.62") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1d5frmx0whggbccdqs63g89zw5wx2lyaxlm6b9gr4gmqsywai1gp") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-2.0.0-alpha.0 (c (n "napi-derive-backend") (v "2.0.0-alpha.0") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "007sd0lv8da8l0w2f8hrh4x38fyx7q707b883b502z4r6inln0ba") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.63 (c (n "napi-derive-backend") (v "1.0.63") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "00h9m417yby4xfpm8r2miyrjd1ipvl9m5lg6627f5nba9yv2clff") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-2.0.0-alpha.1 (c (n "napi-derive-backend") (v "2.0.0-alpha.1") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "1zmmgn9d46y83sg593r40jrmh48gn0p2hysjjcrhz3g5q8jcqw23") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.64 (c (n "napi-derive-backend") (v "1.0.64") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "02jmcx61h3sb3limd4ppy4mdh5j3iqr6wh35wkmj891fckz6mrz5") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.65 (c (n "napi-derive-backend") (v "1.0.65") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "167lrb2gbs7b7p14fz9afg8ms6qbjqcd0yy1p478n5rvsil5iqy3") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.66 (c (n "napi-derive-backend") (v "1.0.66") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0i60x8gyi4b6vgnvb4bb833jrnd7v5zrhkkpk04j9d3a4hcin16s") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

(define-public crate-napi-derive-backend-1.0.67 (c (n "napi-derive-backend") (v "1.0.67") (d (list (d (n "convert_case") (r "^0.6") (d #t) (k 0)) (d (n "once_cell") (r "^1") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1") (o #t) (d #t) (k 0)) (d (n "semver") (r "^1") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2") (f (quote ("fold" "full" "extra-traits"))) (d #t) (k 0)))) (h "0gp7bbxnh517wfw0bbswmxyiha80bni6lppbj5ijdczk6w2c1wmz") (f (quote (("type-def" "regex" "semver") ("strict") ("noop")))) (r "1.65")))

