(define-module (crates-io co mp compact-time) #:use-module (crates-io))

(define-public crate-compact-time-0.1.0 (c (n "compact-time") (v "0.1.0") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "minicbor") (r "^0.20.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "rustix") (r "^0.38.28") (f (quote ("time"))) (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.185") (f (quote ("derive"))) (d #t) (k 0)) (d (n "tz-rs") (r "^0.6.14") (o #t) (d #t) (k 0)))) (h "19yzhpscvk84v3pvxmfrk4rg36ipllf7vyddai3r3rzdjn03whi6") (f (quote (("utc" "tz-rs") ("executable" "coarse" "utc" "clap") ("coarse" "rustix"))))))

(define-public crate-compact-time-0.2.0 (c (n "compact-time") (v "0.2.0") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "minicbor") (r "^0.21.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "quickcheck") (r "^1") (d #t) (k 2)) (d (n "rustix") (r "^0.38.28") (f (quote ("time"))) (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.185") (f (quote ("derive"))) (d #t) (k 0)) (d (n "tz-rs") (r "^0.6.14") (o #t) (d #t) (k 0)))) (h "0ah2yknw5p3gznmb3c4ibsp48d5rf1mq98r7hszipbc09d077i78") (f (quote (("utc" "tz-rs") ("executable" "coarse" "utc" "clap") ("coarse" "rustix"))))))

(define-public crate-compact-time-0.3.0 (c (n "compact-time") (v "0.3.0") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "minicbor") (r "^0.21.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "quickcheck") (r "^1") (d #t) (k 2)) (d (n "rustix") (r "^0.38.28") (f (quote ("time"))) (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.185") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "tz-rs") (r "^0.6.14") (o #t) (d #t) (k 0)))) (h "1qgjnc5s54xrkb7r9cmrxd1kafyh9lv51m5jkqapn68r6s4xnwma") (f (quote (("utc" "tz-rs") ("full" "coarse" "utc" "minicbor" "serde") ("executable" "coarse" "utc" "clap") ("coarse" "rustix"))))))

(define-public crate-compact-time-0.4.0 (c (n "compact-time") (v "0.4.0") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "minicbor") (r "^0.22.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "quickcheck") (r "^1") (d #t) (k 2)) (d (n "rustix") (r "^0.38.28") (f (quote ("time"))) (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.185") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "tz-rs") (r "^0.6.14") (o #t) (d #t) (k 0)))) (h "19pgx3k3y181x13sl2kw6c7kkfjfy4ryh8kfzh8fjqa0fzxq75kw") (f (quote (("utc" "tz-rs") ("full" "coarse" "utc" "minicbor" "serde") ("executable" "coarse" "utc" "clap") ("coarse" "rustix"))))))

(define-public crate-compact-time-0.5.0 (c (n "compact-time") (v "0.5.0") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "minicbor") (r "^0.23.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "quickcheck") (r "^1") (d #t) (k 2)) (d (n "rustix") (r "^0.38.28") (f (quote ("time"))) (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.185") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "tz-rs") (r "^0.6.14") (o #t) (d #t) (k 0)))) (h "0ylb1xnpxak7zcyd7wwsfj7884ikcla6d15d44n4475pk8awk0h3") (f (quote (("utc" "tz-rs") ("full" "coarse" "utc" "minicbor" "serde") ("executable" "coarse" "utc" "clap") ("coarse" "rustix"))))))

(define-public crate-compact-time-0.6.0 (c (n "compact-time") (v "0.6.0") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "minicbor") (r "^0.24.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "quickcheck") (r "^1") (d #t) (k 2)) (d (n "rustix") (r "^0.38.28") (f (quote ("time"))) (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.185") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "tz-rs") (r "^0.6.14") (o #t) (d #t) (k 0)))) (h "1qk2azfp7mgpfysa16kry2swwab4yhrcidbry3ph2dz18wa4sn5v") (f (quote (("utc" "tz-rs") ("full" "coarse" "utc" "minicbor" "serde") ("executable" "coarse" "utc" "clap") ("coarse" "rustix"))))))

