(define-module (crates-io ca tg catgirl-engine-server) #:use-module (crates-io))

(define-public crate-catgirl-engine-server-0.2.0 (c (n "catgirl-engine-server") (v "0.2.0") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "0xrblqpfc6dwk6xlvxfpxiap4xnvlsq8ll7625nr96hn4696npj9")))

(define-public crate-catgirl-engine-server-0.9.0 (c (n "catgirl-engine-server") (v "0.9.0") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "0jch366j6zyagzcg4pnmb71qqj48q2k8y4fv9zqm8i8h5q0xgpdj")))

(define-public crate-catgirl-engine-server-0.9.1 (c (n "catgirl-engine-server") (v "0.9.1") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "06bcsnnb2rlbyay2rvxk1addp9wxd8v813kc0dr7w8a995fwqc43")))

(define-public crate-catgirl-engine-server-0.9.3 (c (n "catgirl-engine-server") (v "0.9.3") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "1bcax69sl2lkhs54b1yf7xnszz6fpl6jc2yxwmwwmkpn3jnic40z")))

(define-public crate-catgirl-engine-server-0.9.4 (c (n "catgirl-engine-server") (v "0.9.4") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "0cc733m231zsn20dgbaihshardc6r1qay08faw295fgg8fs4zi2d")))

(define-public crate-catgirl-engine-server-0.10.0 (c (n "catgirl-engine-server") (v "0.10.0") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "03x1m74ck2cxrqi77cg3pk7yncnjpp39nzymppgvs2zj5z8jcxy1")))

(define-public crate-catgirl-engine-server-0.10.1 (c (n "catgirl-engine-server") (v "0.10.1") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)))) (h "06cwfdxbr2xgai3plvv59l0i45bmqz2cgmzbpji80x3pz6jj4wnn")))

(define-public crate-catgirl-engine-server-0.11.0 (c (n "catgirl-engine-server") (v "0.11.0") (d (list (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.11.0") (d #t) (k 0) (p "catgirl-engine-utils")))) (h "1jp83s4jvb85ni41lzi24q9z0bjsw6y6h9sw74fipld9gb39cqcy")))

(define-public crate-catgirl-engine-server-0.12.4 (c (n "catgirl-engine-server") (v "0.12.4") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.4") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1jj9m436hpfb0576hggh1l995p55wajza0irhzikmrl5giav5sa7")))

(define-public crate-catgirl-engine-server-0.12.5 (c (n "catgirl-engine-server") (v "0.12.5") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.5") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "054xz3njq3hixan280dmr5nm75sg3i631cx1k7mwd26k970fpxmd")))

(define-public crate-catgirl-engine-server-0.12.6 (c (n "catgirl-engine-server") (v "0.12.6") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.6") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0wp953c2b3lcx8nm9a7pzvk8lg3gkd4n9h241mp3sgyj3ya49qr1")))

(define-public crate-catgirl-engine-server-0.12.7 (c (n "catgirl-engine-server") (v "0.12.7") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.7") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0kn0lb3lbrwml8n8mv6p1983m3s9v3knqci89pis3lsy4fyh7xji")))

(define-public crate-catgirl-engine-server-0.12.8 (c (n "catgirl-engine-server") (v "0.12.8") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.8") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1byy30vb91p6x0x43w76zpp50gnqlssckaxihmzm927abry04203")))

(define-public crate-catgirl-engine-server-0.12.9 (c (n "catgirl-engine-server") (v "0.12.9") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.9") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "18rkjhhmgag11xpg41w6dbkwf3ksi3hyiq8rnli75ybk4zqp87lz")))

(define-public crate-catgirl-engine-server-0.12.10 (c (n "catgirl-engine-server") (v "0.12.10") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.10") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "05km6k6mdgscfwnnnnjacg17rmbw1qzps5213n75ar5b64ivbd8q")))

(define-public crate-catgirl-engine-server-0.12.11 (c (n "catgirl-engine-server") (v "0.12.11") (d (list (d (n "build-info") (r "^0.0.37") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.37") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.11") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0aszqx8qfcf3bwsna8bqmg6pi9619vg2fqsh2vx1knhlxwa5v4g7")))

(define-public crate-catgirl-engine-server-0.12.12 (c (n "catgirl-engine-server") (v "0.12.12") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (o #t) (k 0)) (d (n "build-info-build") (r "^0.0.36") (o #t) (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.12") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1xi8lv12syry7nr3ap38ixrz1c6qdcilm4yhnjcr6aqniqbras95") (f (quote (("default" "build-info")))) (s 2) (e (quote (("build-info" "dep:build-info-build" "dep:build-info"))))))

(define-public crate-catgirl-engine-server-0.12.13 (c (n "catgirl-engine-server") (v "0.12.13") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (o #t) (k 0)) (d (n "build-info-build") (r "^0.0.36") (o #t) (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.13") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0v4s5g5b81dr6i3yb0v1pxvblxz1sz3f9vncczwgp0if6q997ld4") (f (quote (("default" "build-info")))) (s 2) (e (quote (("build-info" "dep:build-info-build" "dep:build-info"))))))

(define-public crate-catgirl-engine-server-0.12.14 (c (n "catgirl-engine-server") (v "0.12.14") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (o #t) (k 0)) (d (n "build-info-build") (r "^0.0.36") (o #t) (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.14") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1lb2b6apinf3a8jiirfcl26sq6zlfaiwgbblfz6zb1x4qyqgvkbr") (f (quote (("default" "build-info")))) (s 2) (e (quote (("build-info" "dep:build-info-build" "dep:build-info"))))))

(define-public crate-catgirl-engine-server-0.12.15 (c (n "catgirl-engine-server") (v "0.12.15") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (o #t) (k 0)) (d (n "build-info-build") (r "^0.0.36") (o #t) (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.15") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0mklb6s356rf006b0fwxral73gaj7w21b8jixf5d5sjvj2p79g37") (f (quote (("default" "build-info")))) (s 2) (e (quote (("build-info" "dep:build-info-build" "dep:build-info"))))))

(define-public crate-catgirl-engine-server-0.12.16 (c (n "catgirl-engine-server") (v "0.12.16") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.16") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1pgi7j9p0fc9vwklzdl9kbxb9vnjww1r9ja8plapi66vnjdf8929") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.17 (c (n "catgirl-engine-server") (v "0.12.17") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.17") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "09bdnbbhsva9hsdb95icspg46l038676s75d8c6xxn0hcghb4shj") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.18 (c (n "catgirl-engine-server") (v "0.12.18") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.18") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0d1q7gzw2xjh33h5hx3a1qps4a5bm056iaz93zbmv0g769mifika") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.19 (c (n "catgirl-engine-server") (v "0.12.19") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.19") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1qlbvsh95dmk93bi8jsf5dxhbbrxv22m3zmy5ai5mjq56a22dj6g") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.20 (c (n "catgirl-engine-server") (v "0.12.20") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.20") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1jpjn95vh1568cdm5qng852b8hr14v8wvqy6hzzmy45cckzqi0b4") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.21 (c (n "catgirl-engine-server") (v "0.12.21") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.21") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1rmr63xcxhk3sm88vydwg3h92p0zmbsndki6aa8n2gayq0xwf3qm") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.22 (c (n "catgirl-engine-server") (v "0.12.22") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.22") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1l5y70w7w5vkickznnd16x1anypvdc8i34ava3rzm34i14qb40l4") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.23 (c (n "catgirl-engine-server") (v "0.12.23") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.23") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0qf0dc4vzwa4bzpvavd1qyl9rva50mhdlwdzk7bkx1q2arxwnf6w") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.24 (c (n "catgirl-engine-server") (v "0.12.24") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.24") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "05nvx5dfnsvm35hjdadasa885graa3a1cs2q9iylv039gnz2qjby") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.25 (c (n "catgirl-engine-server") (v "0.12.25") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.25") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1qzy0b5i0yfnfmj7kr8lx6cyjd6b14bvfmnz2zg69513cbqasgq5") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.26 (c (n "catgirl-engine-server") (v "0.12.26") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.26") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1agvaqcfi2mfsdhhqx22vk9gjc5bx94dhzq7668hcx8fily4b386") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.27 (c (n "catgirl-engine-server") (v "0.12.27") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.27") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1n6hy88msnl4v5v815yx70iq4y9qn1y7nl5rp2i302i7jwdgdq64") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.28 (c (n "catgirl-engine-server") (v "0.12.28") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.28") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "09hv1a7vlg1kmj2k361d61zcv33n6zqwaldw9vrfc1lmj1g17gks") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.29 (c (n "catgirl-engine-server") (v "0.12.29") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.29") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1fys88pywfvk5lfp1dwf8nsgabawxysi6vgj88b5ibzjq2v1l1qs") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.30 (c (n "catgirl-engine-server") (v "0.12.30") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.30") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "17vsmyhc4pyhlf1j6klizfshmigi8k6ydmh52255196rsaslz0fg") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.32 (c (n "catgirl-engine-server") (v "0.12.32") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.32") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1brshww14w4y3lfgln8i93xykby4kn71qm0b7cg10xkv17yjm7js") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.33 (c (n "catgirl-engine-server") (v "0.12.33") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.33") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1k6p92q3f6g6r1x8vlk08pgvfszyk0f7rq8gzgjh8kda86k8c1pg") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.34 (c (n "catgirl-engine-server") (v "0.12.34") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.34") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "07pxd2yzp291brz6m6yajd8bwvm1liaf7yx5v41iwgz9f5jy8bpc") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.35 (c (n "catgirl-engine-server") (v "0.12.35") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.35") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0gz8n2gldw2cxcckgld9zx2lh65lf5w9plwn6v6gjgyxv7c2bqsf") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.36 (c (n "catgirl-engine-server") (v "0.12.36") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.36") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1rh6g2sk66apkfvk8yf2hx6zschcyfrp9i0r60z39miy3zi4fa6c") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.37 (c (n "catgirl-engine-server") (v "0.12.37") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.37") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "04l2xyqjmqqiwk197a8fgiwwarm2khakyx2n6pk5id80zan1s1a8") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.38 (c (n "catgirl-engine-server") (v "0.12.38") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.38") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1lxxqya9ml7rv26mhmi45g945x3b95958js855h4v3wyblpk83s3") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.39 (c (n "catgirl-engine-server") (v "0.12.39") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.39") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1vllivyl8116y9300192d7van1x1j949267nxbh59l8ams9vdlmr") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.40 (c (n "catgirl-engine-server") (v "0.12.40") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.40") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1j5z772v5m9cfx9n2p130v88i4gakqcs5nygc81h3b260nhq8hip") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.41 (c (n "catgirl-engine-server") (v "0.12.41") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.41") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1hfx5s449am14yrx7rfx8byrak9m02ijmk0rj53r86l9zp1mfp2l") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.42 (c (n "catgirl-engine-server") (v "0.12.42") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.42") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "038vkmri6lkc43pnjrli6y9rsrp32zm0c5kb3g8n3hhdrgnpdv5s") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.43 (c (n "catgirl-engine-server") (v "0.12.43") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.43") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "081ikffp34bl8s3y0v54wgika3nkzphpsdavrkjrfrqfvvgbhbi0") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.44 (c (n "catgirl-engine-server") (v "0.12.44") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.44") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0nzhi9qica5vk0rzbaaz9mzwzhkmnx2930gqbfkxi7rcf14vsmiw") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.45 (c (n "catgirl-engine-server") (v "0.12.45") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.45") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0k3vymms5kh38qxg1n9isfq5dcpmqmcmcl8cr32v1s5mld2s8avk") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.46 (c (n "catgirl-engine-server") (v "0.12.46") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.46") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "018bdsmjb7wc3k197iwqnpv52iq2vz108kdr644kpsb0mga4mljq") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.47 (c (n "catgirl-engine-server") (v "0.12.47") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.47") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "11sh322rq8xjjjnbrwnqw6pzw9c4hfj1z3rkjywbh796zpjaidpy") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.48 (c (n "catgirl-engine-server") (v "0.12.48") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "ctrlc") (r "~3") (t "cfg(any(target_family=\"unix\", target_family=\"windows\"))") (k 0)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.48") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "07hdw25nlzv6w4v3p6y7f83dj1q0zy0d75414k2mnif51bm8mdsb") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.49 (c (n "catgirl-engine-server") (v "0.12.49") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "ctrlc") (r "~3") (t "cfg(any(target_family=\"unix\", target_family=\"windows\"))") (k 0)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.49") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1adsj3rrwpbiww4k41njlh7qjgan0nxpk5rqlkzv4xmq2z7q6v1y") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.50 (c (n "catgirl-engine-server") (v "0.12.50") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "ctrlc") (r "~3") (t "cfg(any(target_family=\"unix\", target_family=\"windows\"))") (k 0)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.50") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1sf5d82bpd0nkks76zaj7sjiywj71vdp7bfns2bmwk3x567h3vsh") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.51 (c (n "catgirl-engine-server") (v "0.12.51") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "ctrlc") (r "~3") (t "cfg(any(target_family=\"unix\", target_family=\"windows\"))") (k 0)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.51") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "1sim9gkrdcfsc549nqyri5idf69vwc6sjdg5gwwi41bwghb6zim3") (f (quote (("default"))))))

(define-public crate-catgirl-engine-server-0.12.52 (c (n "catgirl-engine-server") (v "0.12.52") (d (list (d (n "build-info") (r "^0.0.36") (f (quote ("runtime"))) (k 0)) (d (n "build-info-build") (r "^0.0.36") (k 1)) (d (n "ctrlc") (r "~3") (t "cfg(any(target_family=\"unix\", target_family=\"windows\"))") (k 0)) (d (n "rhai") (r "~1") (f (quote ("serde"))) (k 0)) (d (n "tracing") (r "~0.1") (f (quote ("log"))) (k 0)) (d (n "utils") (r "^0.12.52") (d #t) (k 0) (p "catgirl-engine-utils")) (d (n "wasm-bindgen") (r "~0.2") (d #t) (k 0)))) (h "0yl2jkgm7qhfxk7c4271i3ikh0irmlzd4aq1mmqz2146d0kn48gx") (f (quote (("default"))))))

