(define-module (crates-io am ad amadeus-serde) #:use-module (crates-io))

(define-public crate-amadeus-serde-0.1.1 (c (n "amadeus-serde") (v "0.1.1") (d (list (d (n "amadeus-core") (r "^0.1") (d #t) (k 0)) (d (n "amadeus-types") (r "^0.1") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_closure") (r "^0.1") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0rxrrjbqzww81bagdkyz8haaczak9jvqfxrhgd6rbmxmxfjgxvhr")))

(define-public crate-amadeus-serde-0.1.2 (c (n "amadeus-serde") (v "0.1.2") (d (list (d (n "amadeus-core") (r "= 0.1.2") (d #t) (k 0)) (d (n "amadeus-types") (r "= 0.1.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_closure") (r "^0.1") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "1r2is8wig9nc5xmnv81amgfkqvhyk7p3rzkai8rxs0rd8hxgjk3w")))

(define-public crate-amadeus-serde-0.1.3 (c (n "amadeus-serde") (v "0.1.3") (d (list (d (n "amadeus-core") (r "= 0.1.3") (d #t) (k 0)) (d (n "amadeus-types") (r "= 0.1.3") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0m2b5kwf0zg3m2fv5bz16r6z88099xslg2hl484l6w5ygnf7ymmr") (f (quote (("doc"))))))

(define-public crate-amadeus-serde-0.1.4 (c (n "amadeus-serde") (v "0.1.4") (d (list (d (n "amadeus-core") (r "= 0.1.4") (d #t) (k 0)) (d (n "amadeus-types") (r "= 0.1.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "1063xayj5d8y4n16k4ijwgzrraj3q4rr6n94z815z5my8wgva5zm") (f (quote (("doc"))))))

(define-public crate-amadeus-serde-0.1.5 (c (n "amadeus-serde") (v "0.1.5") (d (list (d (n "amadeus-core") (r "= 0.1.5") (d #t) (k 0)) (d (n "amadeus-types") (r "= 0.1.5") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "11a618c6cjpflyrxm0q0jxpkhw05azw7jmk9fsv1rna6l3hvlklc") (f (quote (("doc"))))))

(define-public crate-amadeus-serde-0.1.6 (c (n "amadeus-serde") (v "0.1.6") (d (list (d (n "amadeus-core") (r "= 0.1.6") (d #t) (k 0)) (d (n "amadeus-types") (r "= 0.1.6") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0cpbs8gr47sssj15vbas99c2zl1frvh848lhp4l98h57pmqyllns") (f (quote (("doc"))))))

(define-public crate-amadeus-serde-0.1.7 (c (n "amadeus-serde") (v "0.1.7") (d (list (d (n "amadeus-core") (r "= 0.1.7") (d #t) (k 0)) (d (n "amadeus-types") (r "= 0.1.7") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0hfnz2gp02kxg2q62rgl5lp5hg2lgp6n38q44x49dijwbpsjl6nl") (f (quote (("doc"))))))

(define-public crate-amadeus-serde-0.2.0 (c (n "amadeus-serde") (v "0.2.0") (d (list (d (n "amadeus-core") (r "=0.2.0") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.2.0") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "021gcgdkh6b7p6ms4r05ljw9sb8bkw3jadh51iciw7m81g6i8phz") (f (quote (("doc" "amadeus-core/doc"))))))

(define-public crate-amadeus-serde-0.2.1 (c (n "amadeus-serde") (v "0.2.1") (d (list (d (n "amadeus-core") (r "=0.2.1") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.2.1") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "07j7v0cqpbxvl2nbqixqg5423xrw407c1lnzn7vg9lkwh8ycxvdm") (f (quote (("doc" "amadeus-core/doc"))))))

(define-public crate-amadeus-serde-0.2.2 (c (n "amadeus-serde") (v "0.2.2") (d (list (d (n "amadeus-core") (r "=0.2.2") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.2.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0byala1y6p3wkh4zy3988snv2ldgbby1vijx58f3brf97qanfch8")))

(define-public crate-amadeus-serde-0.2.3 (c (n "amadeus-serde") (v "0.2.3") (d (list (d (n "amadeus-core") (r "=0.2.3") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.2.3") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "1d0s9kvnv0w6k6d511ar6wazpyayfkpk4nbpdlqbrssa6wzplqf6")))

(define-public crate-amadeus-serde-0.2.4 (c (n "amadeus-serde") (v "0.2.4") (d (list (d (n "amadeus-core") (r "=0.2.4") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.2.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0bqxrmrwy2qr43s1a7y9qf1yxmi9zb053m9c724gy3fyrlkyr6z4")))

(define-public crate-amadeus-serde-0.2.5 (c (n "amadeus-serde") (v "0.2.5") (d (list (d (n "amadeus-core") (r "=0.2.5") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.2.5") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0yfgc1zzngz8whs89m135sv0mgb67n6llnfg6b52v6iw4j0m9ywi")))

(define-public crate-amadeus-serde-0.3.0 (c (n "amadeus-serde") (v "0.3.0") (d (list (d (n "amadeus-core") (r "=0.3.0") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.0") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)) (d (n "vec-utils") (r "^0.2") (d #t) (k 0)))) (h "1lw2ijf5rxsjg23gps42zy5mj3wz8k5z1kbxi5p53474pbzmnwyd")))

(define-public crate-amadeus-serde-0.3.1 (c (n "amadeus-serde") (v "0.3.1") (d (list (d (n "amadeus-core") (r "=0.3.1") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.1") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)) (d (n "vec-utils") (r "^0.2") (d #t) (k 0)))) (h "1l5ppkmbyk4f03vvxf7cf598q8r0hzlfii6gkml4z7x9ssdhn3l2")))

(define-public crate-amadeus-serde-0.3.2 (c (n "amadeus-serde") (v "0.3.2") (d (list (d (n "amadeus-core") (r "=0.3.2") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)) (d (n "vec-utils") (r "^0.2") (d #t) (k 0)))) (h "13n7ngwkppbxm9cbbvgrzqisz0h9adyxlk2rd5nmhxp2bgbkr0wi")))

(define-public crate-amadeus-serde-0.3.3 (c (n "amadeus-serde") (v "0.3.3") (d (list (d (n "amadeus-core") (r "=0.3.3") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.3") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)) (d (n "vec-utils") (r "^0.2") (d #t) (k 0)))) (h "13w2g4fvhv6q4y20459dzwqlw4zg0kpxpwqkv3shgc7rar3y2zwb")))

(define-public crate-amadeus-serde-0.3.4 (c (n "amadeus-serde") (v "0.3.4") (d (list (d (n "amadeus-core") (r "=0.3.4") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0rm5lf8c0sh7k4wmqfagnz6s9sgdpmbk47w6y3ipdjyfg4g05pwx")))

(define-public crate-amadeus-serde-0.3.5 (c (n "amadeus-serde") (v "0.3.5") (d (list (d (n "amadeus-core") (r "=0.3.5") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.5") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0z7ggjlphg74vb5p8fagazz1wzzmsi49fwfpl7qnshkk7q5hxa6j")))

(define-public crate-amadeus-serde-0.3.6 (c (n "amadeus-serde") (v "0.3.6") (d (list (d (n "amadeus-core") (r "=0.3.6") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.6") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "1svf6b6p93hifv56dzk2bzhgi8sig8p5d8n1qi5f2wss934p8f2i")))

(define-public crate-amadeus-serde-0.3.7 (c (n "amadeus-serde") (v "0.3.7") (d (list (d (n "amadeus-core") (r "=0.3.7") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.3.7") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "0p192ar8a2sg6v21scvknxzhlsscrg4c110amh6kifdsmb8ins2b")))

(define-public crate-amadeus-serde-0.4.0 (c (n "amadeus-serde") (v "0.4.0") (d (list (d (n "amadeus-core") (r "=0.4.0") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.4.0") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1") (f (quote ("serde"))) (d #t) (k 0)))) (h "118rd4wswrpcba1z4qa9bgqxbbs4p0fla1i66hrmh9hnvigpz898")))

(define-public crate-amadeus-serde-0.4.1 (c (n "amadeus-serde") (v "0.4.1") (d (list (d (n "amadeus-core") (r "=0.4.1") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.4.1") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "linked-hash-map") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1.7") (f (quote ("serde"))) (k 0)))) (h "0lackkl1bsb5mpx6rpi8iw0xxkyrhj4iy4lc5fd4qk155hxl6kb9")))

(define-public crate-amadeus-serde-0.4.2 (c (n "amadeus-serde") (v "0.4.2") (d (list (d (n "amadeus-core") (r "=0.4.2") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.4.2") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "hashlink") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1.7") (f (quote ("serde"))) (k 0)))) (h "1082kmhm88l2vzapkd72sl3xfy21wjcc02vryrpvx99l41018gbk")))

(define-public crate-amadeus-serde-0.4.3 (c (n "amadeus-serde") (v "0.4.3") (d (list (d (n "amadeus-core") (r "=0.4.3") (d #t) (k 0)) (d (n "amadeus-types") (r "=0.4.3") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (k 0)) (d (n "csv") (r "^1.0") (d #t) (k 0)) (d (n "educe") (r "^0.4") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "hashlink") (r "^0.5") (d #t) (k 0)) (d (n "recycle") (r "^0.1") (d #t) (k 0)) (d (n "rustversion") (r "^1.0") (d #t) (k 1)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_bytes") (r "^0.11") (d #t) (k 0)) (d (n "serde_closure") (r "^0.3") (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "sum") (r "^0.1.7") (f (quote ("serde"))) (k 0)))) (h "1b38vh60nr2jr90f9hm1a91yvif1mlvq7ma6vndkvbwf9gmdzkw2")))

