(define-module (crates-io ru ps rups) #:use-module (crates-io))

(define-public crate-rups-0.5.0 (c (n "rups") (v "0.5.0") (d (list (d (n "rustls") (r "^0.19") (o #t) (d #t) (k 0)) (d (n "shell-words") (r "^1.0.0") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("net" "io-util" "rt"))) (o #t) (d #t) (k 0)) (d (n "tokio-rustls") (r "^0.22") (o #t) (d #t) (k 0)) (d (n "webpki") (r "^0.21") (o #t) (d #t) (k 0)) (d (n "webpki-roots") (r "^0.21") (o #t) (d #t) (k 0)))) (h "1wxfq61zlvp6pxlhhrakgsi5xrihbv6xa0qahg4f8b0xxsfmww7h") (f (quote (("ssl" "rustls" "rustls/dangerous_configuration" "webpki" "webpki-roots") ("default") ("async-ssl" "async" "tokio-rustls" "ssl") ("async-rt" "async" "tokio/rt-multi-thread" "tokio/macros") ("async" "tokio"))))))

(define-public crate-rups-0.5.1 (c (n "rups") (v "0.5.1") (d (list (d (n "rustls") (r "^0.19") (o #t) (d #t) (k 0)) (d (n "shell-words") (r "^1.0.0") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("net" "io-util" "rt"))) (o #t) (d #t) (k 0)) (d (n "tokio-rustls") (r "^0.22") (o #t) (d #t) (k 0)) (d (n "webpki") (r "^0.21") (o #t) (d #t) (k 0)) (d (n "webpki-roots") (r "^0.21") (o #t) (d #t) (k 0)))) (h "1pi74kf7kavqfx4shz3nfn4qx71imh99slddwlkaqa28i72gpcgc") (f (quote (("ssl" "rustls" "rustls/dangerous_configuration" "webpki" "webpki-roots") ("default") ("async-ssl" "async" "tokio-rustls" "ssl") ("async-rt" "async" "tokio/rt-multi-thread" "tokio/macros") ("async" "tokio"))))))

(define-public crate-rups-0.5.2 (c (n "rups") (v "0.5.2") (d (list (d (n "rustls") (r "^0.19") (o #t) (d #t) (k 0)) (d (n "shell-words") (r "^1.0.0") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("net" "io-util" "rt"))) (o #t) (d #t) (k 0)) (d (n "tokio-rustls") (r "^0.22") (o #t) (d #t) (k 0)) (d (n "webpki") (r "^0.21") (o #t) (d #t) (k 0)) (d (n "webpki-roots") (r "^0.21") (o #t) (d #t) (k 0)))) (h "0ajk4l0mslxjsgdgn1xfiww2ha7x5z99wclmzjylhqkjzrbgvjqh") (f (quote (("ssl" "rustls" "rustls/dangerous_configuration" "webpki" "webpki-roots") ("default") ("async-ssl" "async" "tokio-rustls" "ssl") ("async-rt" "async" "tokio/rt-multi-thread" "tokio/macros") ("async" "tokio"))))))

(define-public crate-rups-0.5.3 (c (n "rups") (v "0.5.3") (d (list (d (n "rustls") (r "^0.19") (o #t) (d #t) (k 0)) (d (n "shell-words") (r "^1.0.0") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("net" "io-util" "rt"))) (o #t) (d #t) (k 0)) (d (n "tokio-rustls") (r "^0.22") (o #t) (d #t) (k 0)) (d (n "webpki") (r "^0.21") (o #t) (d #t) (k 0)) (d (n "webpki-roots") (r "^0.21") (o #t) (d #t) (k 0)))) (h "0gq11fjnrkgyvbchfs1kp728aijwm0c454rq4h4g8sgdiz1ybicr") (f (quote (("write") ("ssl" "rustls" "rustls/dangerous_configuration" "webpki" "webpki-roots") ("default") ("async-ssl" "async" "tokio-rustls" "ssl") ("async-rt" "async" "tokio/rt-multi-thread" "tokio/macros") ("async" "tokio"))))))

(define-public crate-rups-0.6.0 (c (n "rups") (v "0.6.0") (d (list (d (n "rustls") (r "^0.19") (o #t) (d #t) (k 0)) (d (n "shell-words") (r "^1.0.0") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("net" "io-util" "rt"))) (o #t) (d #t) (k 0)) (d (n "tokio-rustls") (r "^0.22") (o #t) (d #t) (k 0)) (d (n "webpki") (r "^0.21") (o #t) (d #t) (k 0)) (d (n "webpki-roots") (r "^0.21") (o #t) (d #t) (k 0)))) (h "0zss5kq02z0mzc2x6rldymzqpgrcwbg5wvk8qzz845nzm5gsbwp6") (f (quote (("write") ("ssl" "rustls" "rustls/dangerous_configuration" "webpki" "webpki-roots") ("default") ("async-ssl" "async" "tokio-rustls" "ssl") ("async-rt" "async" "tokio/rt-multi-thread" "tokio/macros") ("async" "tokio"))))))

(define-public crate-rups-0.6.1 (c (n "rups") (v "0.6.1") (d (list (d (n "rustls") (r "^0.19") (o #t) (d #t) (k 0)) (d (n "shell-words") (r "^1.0.0") (d #t) (k 0)) (d (n "tokio") (r "^1") (f (quote ("net" "io-util" "rt"))) (o #t) (d #t) (k 0)) (d (n "tokio-rustls") (r "^0.22") (o #t) (d #t) (k 0)) (d (n "webpki") (r "^0.21") (o #t) (d #t) (k 0)) (d (n "webpki-roots") (r "^0.21") (o #t) (d #t) (k 0)))) (h "0if0i25fjr78mknpih678jggvcd7ai5107scr9h2ayp1hcf4z9ri") (f (quote (("write") ("ssl" "rustls" "rustls/dangerous_configuration" "webpki" "webpki-roots") ("default") ("async-ssl" "async" "tokio-rustls" "ssl") ("async-rt" "async" "tokio/rt-multi-thread" "tokio/macros") ("async" "tokio"))))))

