(define-module (crates-io ac ts actson) #:use-module (crates-io))

(define-public crate-actson-0.1.0 (c (n "actson") (v "0.1.0") (d (list (d (n "dtoa") (r "^1.0.6") (d #t) (k 2)) (d (n "ringbuffer") (r "^0.14.0") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.97") (f (quote ("float_roundtrip"))) (d #t) (k 2)))) (h "0jx533kxy044756qajgimfrjw9akbk7hxy8182m07jvldcaf7m7r")))

(define-public crate-actson-0.2.0 (c (n "actson") (v "0.2.0") (d (list (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "lexical") (r "^6.1.1") (d #t) (k 0)) (d (n "ringbuffer") (r "^0.14.1") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.99") (f (quote ("float_roundtrip"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.99") (f (quote ("float_roundtrip"))) (d #t) (k 2)) (d (n "tokio") (r "^1.29.0") (f (quote ("io-util" "rt-multi-thread"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.29.0") (f (quote ("fs" "macros" "rt-multi-thread"))) (d #t) (k 2)))) (h "1ydzyw4a8i89vlw2pw5h6pdi6bfmyj5l4rppsjcx3gxzis3x5skm") (f (quote (("default" "tokio")))) (s 2) (e (quote (("tokio" "dep:tokio") ("serde_json" "dep:serde_json"))))))

(define-public crate-actson-0.3.0 (c (n "actson") (v "0.3.0") (d (list (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "lexical") (r "^6.1.1") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.103") (f (quote ("float_roundtrip"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.103") (f (quote ("float_roundtrip"))) (d #t) (k 2)) (d (n "tokio") (r "^1.29.1") (f (quote ("io-util" "rt-multi-thread"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.29.1") (f (quote ("fs" "macros" "rt-multi-thread"))) (d #t) (k 2)))) (h "1qc9m3wgwh7jias6xxcaa0jgbmghzcwzhihb9rid8fba060yj54n") (f (quote (("default" "tokio")))) (s 2) (e (quote (("tokio" "dep:tokio") ("serde_json" "dep:serde_json"))))))

(define-public crate-actson-0.3.1 (c (n "actson") (v "0.3.1") (d (list (d (n "btoi") (r "^0.4.3") (d #t) (k 0)) (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "dtoa") (r "^1.0.9") (d #t) (k 2)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (d #t) (k 2)) (d (n "tokio") (r "^1.36.0") (f (quote ("io-util" "rt-multi-thread"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.36.0") (f (quote ("fs" "macros" "rt-multi-thread"))) (d #t) (k 2)))) (h "129x2fjky7licrmkaangj4bvlh51wzvgmsinb73ilj65hg1b68bj") (f (quote (("default")))) (y #t) (s 2) (e (quote (("tokio" "dep:tokio") ("serde_json" "dep:serde_json"))))))

(define-public crate-actson-0.4.0 (c (n "actson") (v "0.4.0") (d (list (d (n "btoi") (r "^0.4.3") (d #t) (k 0)) (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "dtoa") (r "^1.0.9") (d #t) (k 2)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (d #t) (k 2)) (d (n "tokio") (r "^1.36.0") (f (quote ("io-util" "rt-multi-thread"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.36.0") (f (quote ("fs" "macros" "rt-multi-thread"))) (d #t) (k 2)))) (h "1f5y1c3qrq1spv9ph83qbynbdavd7cwqx9s74a7li970fi4gvwbb") (f (quote (("default")))) (s 2) (e (quote (("tokio" "dep:tokio") ("serde_json" "dep:serde_json"))))))

(define-public crate-actson-0.5.0 (c (n "actson") (v "0.5.0") (d (list (d (n "btoi") (r "^0.4.3") (d #t) (k 0)) (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "dtoa") (r "^1.0.9") (d #t) (k 2)) (d (n "num-traits") (r "^0.2.18") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (d #t) (k 2)) (d (n "thiserror") (r "^1.0.57") (d #t) (k 0)) (d (n "tokio") (r "^1.36.0") (f (quote ("io-util" "rt-multi-thread"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.36.0") (f (quote ("fs" "macros" "rt-multi-thread"))) (d #t) (k 2)))) (h "13v8bnsg295ymv4dyhinh34qd4rjvh9ahzqp4rvrkrxiqpnrgddd") (f (quote (("default")))) (s 2) (e (quote (("tokio" "dep:tokio") ("serde_json" "dep:serde_json"))))))

(define-public crate-actson-1.0.0 (c (n "actson") (v "1.0.0") (d (list (d (n "btoi") (r "^0.4.3") (d #t) (k 0)) (d (n "criterion") (r "^0.5.1") (d #t) (k 2)) (d (n "dtoa") (r "^1.0.9") (d #t) (k 2)) (d (n "num-traits") (r "^0.2.18") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (o #t) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.114") (f (quote ("float_roundtrip"))) (d #t) (k 2)) (d (n "thiserror") (r "^1.0.57") (d #t) (k 0)) (d (n "tokio") (r "^1.36.0") (f (quote ("io-util" "rt-multi-thread"))) (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.36.0") (f (quote ("fs" "macros" "rt-multi-thread"))) (d #t) (k 2)))) (h "1lw9vmymsrj1caqnd0im91gk4jb573c851c0xx4w2p1a49j2al0w") (f (quote (("default")))) (s 2) (e (quote (("tokio" "dep:tokio") ("serde_json" "dep:serde_json"))))))

