(define-module (crates-io re lu reluax) #:use-module (crates-io))

(define-public crate-reluax-0.1.0 (c (n "reluax") (v "0.1.0") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (d #t) (k 0)) (d (n "color-eyre") (r "^0.6.2") (d #t) (k 0)) (d (n "http-body-util") (r "^0.1.0") (d #t) (k 0)) (d (n "hyper") (r "^1.1.0") (f (quote ("http1" "http2" "server"))) (d #t) (k 0)) (d (n "hyper-util") (r "^0.1.2") (f (quote ("http1" "http2" "server" "tokio"))) (d #t) (k 0)) (d (n "rlua") (r "^0.19.7") (f (quote ("system-luajit"))) (k 0)) (d (n "tempfile") (r "^3.9.0") (d #t) (k 0)) (d (n "tokio") (r "^1.35.1") (f (quote ("macros" "rt-multi-thread"))) (d #t) (k 0)) (d (n "utf8-read") (r "^0.4.0") (d #t) (k 0)))) (h "18kiyq1k3bgdhkl64nd9zvfqakd430z457s046mizgjrfdfiz4wl")))

(define-public crate-reluax-0.1.1 (c (n "reluax") (v "0.1.1") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (d #t) (k 0)) (d (n "color-eyre") (r "^0.6.2") (d #t) (k 0)) (d (n "http-body-util") (r "^0.1.0") (d #t) (k 0)) (d (n "hyper") (r "^1.1.0") (f (quote ("http1" "http2" "server"))) (d #t) (k 0)) (d (n "hyper-util") (r "^0.1.2") (f (quote ("http1" "http2" "server" "tokio"))) (d #t) (k 0)) (d (n "rlua") (r "^0.19.7") (f (quote ("system-luajit"))) (k 0)) (d (n "tempfile") (r "^3.9.0") (d #t) (k 0)) (d (n "tokio") (r "^1.35.1") (f (quote ("macros" "rt-multi-thread"))) (d #t) (k 0)) (d (n "utf8-read") (r "^0.4.0") (d #t) (k 0)))) (h "1jk3y1qprvar8prfskicrknppkw0cz939a44yg87qbyz8lxwwh1z")))

(define-public crate-reluax-0.2.0 (c (n "reluax") (v "0.2.0") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (d #t) (k 0)) (d (n "color-eyre") (r "^0.6.2") (d #t) (k 0)) (d (n "http-body-util") (r "^0.1.0") (d #t) (k 0)) (d (n "hyper") (r "^1.1.0") (f (quote ("http1" "http2" "server"))) (d #t) (k 0)) (d (n "hyper-util") (r "^0.1.2") (f (quote ("http1" "http2" "server" "tokio"))) (d #t) (k 0)) (d (n "rlua") (r "^0.19.7") (f (quote ("system-luajit"))) (k 0)) (d (n "tempfile") (r "^3.9.0") (d #t) (k 0)) (d (n "tokio") (r "^1.35.1") (f (quote ("macros" "rt-multi-thread"))) (d #t) (k 0)) (d (n "utf8-read") (r "^0.4.0") (d #t) (k 0)))) (h "1cl8flgw3y9zch2mdzjr3glfi4npb04f79qadi4zv8spgvd4nm5v")))

(define-public crate-reluax-0.2.1 (c (n "reluax") (v "0.2.1") (d (list (d (n "clap") (r "^4.4.14") (f (quote ("derive"))) (d #t) (k 0)) (d (n "color-eyre") (r "^0.6.2") (d #t) (k 0)) (d (n "http-body-util") (r "^0.1.0") (d #t) (k 0)) (d (n "hyper") (r "^1.1.0") (f (quote ("http1" "http2" "server"))) (d #t) (k 0)) (d (n "hyper-util") (r "^0.1.2") (f (quote ("http1" "http2" "server" "tokio"))) (d #t) (k 0)) (d (n "rlua") (r "^0.19.7") (f (quote ("system-luajit"))) (k 0)) (d (n "tempfile") (r "^3.9.0") (d #t) (k 0)) (d (n "tokio") (r "^1.35.1") (f (quote ("macros" "rt-multi-thread"))) (d #t) (k 0)) (d (n "utf8-read") (r "^0.4.0") (d #t) (k 0)))) (h "1yydhklmqmp0fvbmv5bhs9b8r6qkgka865fg0lnqvnjjpfs4f425")))

