(define-module (crates-io do tr dotrain-lsp) #:use-module (crates-io))

(define-public crate-dotrain-lsp-6.0.1-alpha.2 (c (n "dotrain-lsp") (v "6.0.1-alpha.2") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.2") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "00n0fjpk8p003c76znf9z1flhd5qbwiva06hf29nlnf9iv8ya5w0") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.3 (c (n "dotrain-lsp") (v "6.0.1-alpha.3") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.3") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1p4qbg60hxa3fycva0ml02b83srx00d2wq8j4xdirwf1iw9nd03c") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.4 (c (n "dotrain-lsp") (v "6.0.1-alpha.4") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.4") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1m34si38is051adzb8klj6dinh3j95n2plpw1pbzxzsv941zv209") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.5 (c (n "dotrain-lsp") (v "6.0.1-alpha.5") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.5") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "03zcfjxxii814pnzb8a0g96p83xabbrvassw7bzdin2xp9h197mp") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.6 (c (n "dotrain-lsp") (v "6.0.1-alpha.6") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.6") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "0h34a7ra8p7fmg8ql7aqfw5c6jd9mn39vsfdr2i01m5vraq1i7yg") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.7 (c (n "dotrain-lsp") (v "6.0.1-alpha.7") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.7") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1f0daq77bzjn3z589m01zykigydsz72ap4ha25rvilzmqr71i491") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.8 (c (n "dotrain-lsp") (v "6.0.1-alpha.8") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.8") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1z02by3pzqk5vgsfi16clip93pjmsx7v4vq3km1cakdv1073qgzb") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.9 (c (n "dotrain-lsp") (v "6.0.1-alpha.9") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.9") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1hrvn2n6ahkwc1w71q0jj24dx1029pq3ilmj112cqc3r27pnj7ks") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.10 (c (n "dotrain-lsp") (v "6.0.1-alpha.10") (d (list (d (n "alloy-primitives") (r "^0.5.0") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.10") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1pdcysp6l4mc88i16y8x0c7yy0afaljw1fs9a68q6mkfgp10ms31") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.11 (c (n "dotrain-lsp") (v "6.0.1-alpha.11") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.11") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "18dmn4rqvbc2bcnhrg3dhfqdy94r42p3p85mwl8bkvfamf1qd8dw") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.12 (c (n "dotrain-lsp") (v "6.0.1-alpha.12") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.12") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "0cgxfyppp97kf19r6x8pg6rnfy26xvfgdvvid6rap4w4xz5alnld") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.13 (c (n "dotrain-lsp") (v "6.0.1-alpha.13") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.13") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "087gx2sblmf9sxiiiykv2jwx7qf16rxqalrx572mn8v3y3qa7fsp") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.14 (c (n "dotrain-lsp") (v "6.0.1-alpha.14") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.14") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "0j78l6nq65d07afj6q3jwbpgvhkic7gqd592l7c4bmw1nailf80v") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.15 (c (n "dotrain-lsp") (v "6.0.1-alpha.15") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.15") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1gc2826vy77gg2zvy14wk8zman4rj6h59g2p3hbg3s2h7n6r74cl") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.16 (c (n "dotrain-lsp") (v "6.0.1-alpha.16") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.16") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "1hyd5xwzwwzza1bh3qyfwz11qxgxmj2xpra036h66v3nzfdwj9id") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.17 (c (n "dotrain-lsp") (v "6.0.1-alpha.17") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.17") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "0xrh323dw8fwjcql10imqicg7ks1q7lvnmypmqcc33sqy2yra57m") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

(define-public crate-dotrain-lsp-6.0.1-alpha.18 (c (n "dotrain-lsp") (v "6.0.1-alpha.18") (d (list (d (n "alloy-primitives") (r "^0.6.3") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.75") (d #t) (k 0)) (d (n "dotrain") (r "^6.0.1-alpha.18") (d #t) (k 0)) (d (n "js-sys") (r "^0.3.66") (o #t) (d #t) (k 0)) (d (n "lsp-types") (r "^0.94.1") (d #t) (k 0)) (d (n "once_cell") (r "^1.18.0") (d #t) (k 0)) (d (n "regex") (r "^1.10.2") (d #t) (k 0)) (d (n "serde-wasm-bindgen") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "tsify") (r "^0.4.5") (f (quote ("js" "wasm-bindgen"))) (o #t) (k 0)) (d (n "wasm-bindgen") (r "^0.2.89") (o #t) (d #t) (k 0)) (d (n "wasm-bindgen-futures") (r "^0.4.39") (o #t) (d #t) (k 0)))) (h "0cpjlvhqvldjg200scrn1jmylgd3a93iaikmbsiq7v2l2d2dfkb9") (s 2) (e (quote (("js-api" "dotrain/js-api" "dep:js-sys" "dep:wasm-bindgen" "dep:serde-wasm-bindgen" "dep:wasm-bindgen-futures" "dep:tsify"))))))

