(define-module (crates-io bi na binary-security-check) #:use-module (crates-io))

(define-public crate-binary-security-check-1.2.0 (c (n "binary-security-check") (v "1.2.0") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.3") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.4") (d #t) (k 0)) (d (n "scroll") (r "^0.10") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.9") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "16kpilabjf5vczia3vkp2n9yjpm0bi6c6252r1112lf7kq5nclix")))

(define-public crate-binary-security-check-1.2.1 (c (n "binary-security-check") (v "1.2.1") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.3") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.4") (d #t) (k 0)) (d (n "scroll") (r "^0.10") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.9") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "1hp92wimjcvdnq6gm5mdjziw09h2wvhagibglq9a2qfzcnlxny0i")))

(define-public crate-binary-security-check-1.2.2 (c (n "binary-security-check") (v "1.2.2") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.3") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.4") (d #t) (k 0)) (d (n "scroll") (r "^0.10") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.9") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "01x9959jis00gwy5njpp68zp5hhkkdgfim7qw348dhbbhgddijx4")))

(define-public crate-binary-security-check-1.2.3 (c (n "binary-security-check") (v "1.2.3") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.4") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.4") (d #t) (k 0)) (d (n "scroll") (r "^0.10") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.10") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0pnqsmagsqhca54010sj6mxsj2qqjwl6pnpd2rdza9y53ri37312")))

(define-public crate-binary-security-check-1.2.4 (c (n "binary-security-check") (v "1.2.4") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.4") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "scroll") (r "^0.10") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.10") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "08vp4p5mxkkfd51izlc2p3478m35j9i6sm21d8k75mmj141wkvlg")))

(define-public crate-binary-security-check-1.2.5 (c (n "binary-security-check") (v "1.2.5") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.5") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.11") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "01ld71a4h288lsx9pj11yafbwhbw8399fyw5801i2lh0p6mcvnx1")))

(define-public crate-binary-security-check-1.2.6 (c (n "binary-security-check") (v "1.2.6") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.5") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.6") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "1h02k2v3s6fbl7gi7qg51in9jf75j7v98vsjkh2s4bncarrn74d6")))

(define-public crate-binary-security-check-1.2.7 (c (n "binary-security-check") (v "1.2.7") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.7") (d #t) (k 0)) (d (n "rayon") (r "^1.5") (d #t) (k 0)) (d (n "regex") (r "^1.7") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0hx19jjnfwqv4z33ap4jvhc2all3vhkyxjq4a963pv012j78157w")))

(define-public crate-binary-security-check-1.2.8 (c (n "binary-security-check") (v "1.2.8") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.7") (d #t) (k 0)) (d (n "rayon") (r "^1.6") (d #t) (k 0)) (d (n "regex") (r "^1.7") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "1r6lahfbgqkj4lr7cb10w6mlfj1sw8diz96cc6z7mrc6ah3gqjsd")))

(define-public crate-binary-security-check-1.2.9 (c (n "binary-security-check") (v "1.2.9") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.8") (d #t) (k 0)) (d (n "rayon") (r "^1.6") (d #t) (k 0)) (d (n "regex") (r "^1.7") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "06dndxv1rghbi7bmcgcbpmrx40zq0wyfabz80pjm4bxmppmc0311")))

(define-public crate-binary-security-check-1.2.10 (c (n "binary-security-check") (v "1.2.10") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.6") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.8") (d #t) (k 0)) (d (n "rayon") (r "^1.7") (d #t) (k 0)) (d (n "regex") (r "^1.7") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0ibv83k0yqg98idgr0q4nzv7v8lwvl92fmy5hjv5ar78wvjkcs65")))

(define-public crate-binary-security-check-1.2.11 (c (n "binary-security-check") (v "1.2.11") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.7") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.9") (d #t) (k 0)) (d (n "rayon") (r "^1.7") (d #t) (k 0)) (d (n "regex") (r "^1.9") (d #t) (k 0)) (d (n "scroll") (r "^0.11") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "1d7jxrjgcdvy11gsbfcl0dhnx86bhjdhshw1zkiwfnpds4xvqy4n")))

(define-public crate-binary-security-check-1.2.12 (c (n "binary-security-check") (v "1.2.12") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.9") (d #t) (k 0)) (d (n "rayon") (r "^1.8") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "scroll") (r "^0.12") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0z7yqihjb69x1qvz6wcvx096pa3mpal7fyh4xdihxpj156qx7gqq")))

(define-public crate-binary-security-check-1.2.13 (c (n "binary-security-check") (v "1.2.13") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.9") (d #t) (k 0)) (d (n "rayon") (r "^1.8") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "scroll") (r "^0.12") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "1qszwph42bwr0p0fgnjfw1sh9jh372vwfrw8sigffh6rzvv7xkqn")))

(define-public crate-binary-security-check-1.2.14 (c (n "binary-security-check") (v "1.2.14") (d (list (d (n "docopt") (r "^1.1") (d #t) (k 0)) (d (n "goblin") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap") (r "^0.7") (d #t) (k 0)) (d (n "memoffset") (r "^0.9") (d #t) (k 0)) (d (n "rayon") (r "^1.8") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "scroll") (r "^0.12") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "simplelog") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.1") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "167zhq1fapdhrd96mbd7b7i7ssap93na5winjgizc2igqysjks7r")))

(define-public crate-binary-security-check-1.2.15 (c (n "binary-security-check") (v "1.2.15") (d (list (d (n "clap") (r "^4.5") (f (quote ("color" "help" "usage" "error-context" "suggestions" "derive" "cargo"))) (d #t) (k 0)) (d (n "flexi_logger") (r "^0.27") (d #t) (k 0)) (d (n "goblin") (r "^0.8") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap2") (r "^0.9") (d #t) (k 0)) (d (n "memoffset") (r "^0.9") (d #t) (k 0)) (d (n "once_cell") (r "^1.19") (d #t) (k 0)) (d (n "rayon") (r "^1.8") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "scroll") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.4") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "1avkp8m4lhfdf71786wwfvik96m87i6brhgy78gdaq54j4ah7h1d")))

(define-public crate-binary-security-check-1.3.0 (c (n "binary-security-check") (v "1.3.0") (d (list (d (n "clap") (r "^4.5") (f (quote ("color" "help" "usage" "error-context" "suggestions" "derive" "cargo"))) (d #t) (k 0)) (d (n "dynamic-loader-cache") (r "^0.1") (d #t) (k 0)) (d (n "flexi_logger") (r "^0.27") (d #t) (k 0)) (d (n "goblin") (r "^0.8") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap2") (r "^0.9") (d #t) (k 0)) (d (n "memoffset") (r "^0.9") (d #t) (k 0)) (d (n "once_cell") (r "^1.19") (d #t) (k 0)) (d (n "rayon") (r "^1.8") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "scroll") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.4") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "08l0pdgirgq50pppyqvl2nx96603sgf1fpk20bys99d902hz9app")))

(define-public crate-binary-security-check-1.3.1 (c (n "binary-security-check") (v "1.3.1") (d (list (d (n "clap") (r "^4.5") (f (quote ("color" "help" "usage" "error-context" "suggestions" "derive" "cargo"))) (d #t) (k 0)) (d (n "dynamic-loader-cache") (r "^0.1") (d #t) (k 0)) (d (n "flexi_logger") (r "^0.28") (d #t) (k 0)) (d (n "goblin") (r "^0.8") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "memmap2") (r "^0.9") (d #t) (k 0)) (d (n "once_cell") (r "^1.19") (d #t) (k 0)) (d (n "rayon") (r "^1.10") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "scroll") (r "^0.12") (d #t) (k 0)) (d (n "termcolor") (r "^1.4") (d #t) (k 0)) (d (n "thiserror") (r "^1.0") (d #t) (k 0)))) (h "0ld39wj0fjli0y1mfp77pl9mb13kivp29rmazdgbv7wcl8ss3y04")))

