(define-module (crates-io tw il twilight-http-ratelimiting) #:use-module (crates-io))

(define-public crate-twilight-http-ratelimiting-0.8.0 (c (n "twilight-http-ratelimiting") (v "0.8.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "1c4d4g6wxp0w4mimb9b9zsqskqgmngikh8zavj8rnc7nbm63wkd8") (f (quote (("default" "tracing"))))))

(define-public crate-twilight-http-ratelimiting-0.8.1 (c (n "twilight-http-ratelimiting") (v "0.8.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "1x2214wplfbplvw7r5gj1ha7fkg0agi0mw3xaj1l1z9jyx3grl5h") (f (quote (("default" "tracing"))))))

(define-public crate-twilight-http-ratelimiting-0.8.2 (c (n "twilight-http-ratelimiting") (v "0.8.2") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "02q6kkxzm8lwxyzhrg830fjzqh2wy2nknkvynkib1n25qhmnsmpr") (f (quote (("default" "tracing"))))))

(define-public crate-twilight-http-ratelimiting-0.8.3 (c (n "twilight-http-ratelimiting") (v "0.8.3") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "1fi6vd2pq1dcqlf79wrwqlkszg9q328qrzww79m8scbsz0mh9rrl") (f (quote (("default" "tracing"))))))

(define-public crate-twilight-http-ratelimiting-0.8.4 (c (n "twilight-http-ratelimiting") (v "0.8.4") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "0jp64nxp5m0z150pr0zih0z5qdvhixxj5hbzsba23dcqvbcx25rx") (f (quote (("default" "tracing"))))))

(define-public crate-twilight-http-ratelimiting-0.9.0 (c (n "twilight-http-ratelimiting") (v "0.9.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "0sjz5wnnds941qann53hph2l3z66bckklxb0j6a7cb9vavkw733a") (f (quote (("default" "tracing")))) (r "1.57")))

(define-public crate-twilight-http-ratelimiting-0.10.0 (c (n "twilight-http-ratelimiting") (v "0.10.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "19psw50h8m2y7v27byl3c31y7j2lf11hxgr3sbv87svmbjw95dn6") (f (quote (("default" "tracing")))) (r "1.57")))

(define-public crate-twilight-http-ratelimiting-0.10.1 (c (n "twilight-http-ratelimiting") (v "0.10.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "0l477915g7r540bzladdc25wza3i6h6ab4mnf78584g3zk0rcvy7") (f (quote (("default" "tracing")))) (r "1.57")))

(define-public crate-twilight-http-ratelimiting-0.10.2 (c (n "twilight-http-ratelimiting") (v "0.10.2") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (o #t) (k 0)))) (h "1lhsjqpr6hpvm2wv7ygf5977k9fqxs326fzn174vb8xvp06igdqr") (f (quote (("default" "tracing")))) (r "1.57")))

(define-public crate-twilight-http-ratelimiting-0.11.0 (c (n "twilight-http-ratelimiting") (v "0.11.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1") (f (quote ("std" "attributes"))) (k 0)))) (h "0wpzx69nskhdyz1hm1bh5gldjv5wijvw3hs1vn6v23l13m19wcpq") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.11.1 (c (n "twilight-http-ratelimiting") (v "0.11.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0lzjdmhrdf7c1xask727q35xzx4hfxi09ly80n08zksdxc7w0fhp") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.12.0 (c (n "twilight-http-ratelimiting") (v "0.12.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "08vda1aywqh72sm54wsrm0qfdypz0gm9k77d49yg7fs2ry49bqfd") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.12.1 (c (n "twilight-http-ratelimiting") (v "0.12.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "1a0lxbnx6aphv438mdsp70yb5c3pvlr0784fiz2mcc9msj69hbxf") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.12.2 (c (n "twilight-http-ratelimiting") (v "0.12.2") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "00dvvv0f99235lphz7zpj0nf9aqmlq9fy6c5f65v2q1133aqymvr") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.13.0 (c (n "twilight-http-ratelimiting") (v "0.13.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0a60zb5vqg3f95jg328bvkmjn5pigp8fqmdyai0fpmp22vkpg59v") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.13.1 (c (n "twilight-http-ratelimiting") (v "0.13.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "17ig04r5div8zk8qili5c6p5bkgayrv1rwr6kmv4xasnd0w1ypdp") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.13.2 (c (n "twilight-http-ratelimiting") (v "0.13.2") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "1nhaipn499ap22qi684zj972b7lrrh14389pdq1x3jlsmb521yzg") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.13.3 (c (n "twilight-http-ratelimiting") (v "0.13.3") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "1k3q5jzqq0ym654jbiifyaf3xnh299wjicikgsxfp1nr6dzw5m6w") (r "1.60")))

(define-public crate-twilight-http-ratelimiting-0.14.0 (c (n "twilight-http-ratelimiting") (v "0.14.0") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0p7zkhwhzsrdr9bwz0gfkwdnyn39hww780q7sjkjd66s3bav7i35") (r "1.64")))

(define-public crate-twilight-http-ratelimiting-0.14.1 (c (n "twilight-http-ratelimiting") (v "0.14.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "09j7wanfmnz6rwxjzjdcl5ghkzqnsq1k5ndw1d73j3rcx7fi118k") (r "1.64")))

(define-public crate-twilight-http-ratelimiting-0.15.0-rc.1 (c (n "twilight-http-ratelimiting") (v "0.15.0-rc.1") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0vlj2nnqfn463dykdb8p5f80kcmcsiz5pan3kv2vb4swww0bgfq2") (r "1.64")))

(define-public crate-twilight-http-ratelimiting-0.14.2 (c (n "twilight-http-ratelimiting") (v "0.14.2") (d (list (d (n "criterion") (r "^0.3") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0f4zdc6jxixs5gysd5g2kw2i7c0hqkx9vn254frm5cljjg69iahi") (r "1.64")))

(define-public crate-twilight-http-ratelimiting-0.15.0 (c (n "twilight-http-ratelimiting") (v "0.15.0") (d (list (d (n "criterion") (r "^0.4") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "10lh8p83agbaf71gf8wp1rzx0dla8kv4zlrqlsz4hih7vr0lw3xf") (r "1.64")))

(define-public crate-twilight-http-ratelimiting-0.15.1 (c (n "twilight-http-ratelimiting") (v "0.15.1") (d (list (d (n "criterion") (r "^0.4") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "1n63w3gsxms5d9i49pmkj0bv38vls1s8q0jxfyngphsgan3bjgpr") (r "1.64")))

(define-public crate-twilight-http-ratelimiting-0.15.2 (c (n "twilight-http-ratelimiting") (v "0.15.2") (d (list (d (n "criterion") (r "^0.4") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0l9rvwc6m0rl08k1qa2wknm96qqcn5bnbxngqh4p45dvyknwjy48") (r "1.67")))

(define-public crate-twilight-http-ratelimiting-0.15.3 (c (n "twilight-http-ratelimiting") (v "0.15.3") (d (list (d (n "criterion") (r "^0.4") (k 2)) (d (n "futures-util") (r "^0.3") (k 0)) (d (n "http") (r "^0.2") (k 0)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "0azh4z0kq3c499a4749yrkkaqrp2nyqf8b3jbddqs2pn7ws06jma") (r "1.67")))

(define-public crate-twilight-http-ratelimiting-0.16.0-rc.1 (c (n "twilight-http-ratelimiting") (v "0.16.0-rc.1") (d (list (d (n "criterion") (r "^0.4") (k 2)) (d (n "http") (r "^1") (k 2)) (d (n "static_assertions") (r "^1.1.0") (k 2)) (d (n "tokio") (r "^1") (f (quote ("rt" "sync" "time"))) (k 0)) (d (n "tokio") (r "^1.0") (f (quote ("macros" "rt-multi-thread"))) (k 2)) (d (n "tracing") (r "^0.1.23") (f (quote ("std" "attributes"))) (k 0)))) (h "1imxh698gdsiaak89852x5wrdpknh5iq4bmkscw6ifjj2z2i9y47") (r "1.67")))

