(define-module (crates-io gi t- git-odb) #:use-module (crates-io))

(define-public crate-git-odb-0.1.0 (c (n "git-odb") (v "0.1.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.1.0") (d #t) (k 0)) (d (n "git-object") (r "^0.1.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.3.6") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "quick-error") (r "^1.2.3") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "uluru") (r "^0.4.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "0mmy8mbzwsw8xanlcppp0bg8gkzdj68xavh8mz3f722a7k5cw3pb") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.3.0 (c (n "git-odb") (v "0.3.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.3.0") (d #t) (k 0)) (d (n "git-object") (r "^0.3.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "quick-error") (r "^2.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "0k1d5prcnf0lm92jklhplc7gm1jxg1hnlarknxzfp8w69a4m8kpr") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.4.0 (c (n "git-odb") (v "0.4.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.4.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "quick-error") (r "^2.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "14rm1s0xx7zikpk82d8ndask5pl39w69ywkkaikjhqwwlnzmpkyi") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.4.1 (c (n "git-odb") (v "0.4.1") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.6.0") (d #t) (k 0)) (d (n "git-object") (r "^0.4.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "quick-error") (r "^2.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "1kv182y6p9zjaj7mjlxm7ly9pph5dql08b8vanjwkpaq11bz5p0w") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.4.2 (c (n "git-odb") (v "0.4.2") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.7.0") (f (quote ("git-object"))) (d #t) (k 0)) (d (n "git-object") (r "^0.4.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "1zw0b80r8vzm8xalhp3564fb6w57h54q9kih4g2vhx8zk8crp9ns") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.5.0 (c (n "git-odb") (v "0.5.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.8.0") (f (quote ("git-object"))) (d #t) (k 0)) (d (n "git-object") (r "^0.4.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "07671m71j0mzphdg1n4jsd7dzl0yvmgb8kw0ffn4n21vs3c3ap5r") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.6.0 (c (n "git-odb") (v "0.6.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.9.0") (f (quote ("git-object"))) (d #t) (k 0)) (d (n "git-object") (r "^0.5.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "0cg8clw749m2nc26bkbgvnz1yky2wmxlbx3cxz41avpx4qzddi2m") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.7.0 (c (n "git-odb") (v "0.7.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.10.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.1.0") (d #t) (k 0)) (d (n "git-object") (r "^0.6.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)) (d (n "walkdir") (r "^2.1.4") (d #t) (k 0)))) (h "1kc5sfyl9x2szf0f1malagm454iw1x855dswvgclybmk8yiagyhw") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.7.1 (c (n "git-odb") (v "0.7.1") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.11.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.1.0") (d #t) (k 0)) (d (n "git-object") (r "^0.6.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)))) (h "1wghhdn0i4klh723ha66j3wng39217j22a9x40db7zc9qnam39mr") (f (quote (("serde1" "serde" "git-object/serde1")))) (y #t)))

(define-public crate-git-odb-0.8.0 (c (n "git-odb") (v "0.8.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "git-features") (r "^0.11.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.1.0") (d #t) (k 0)) (d (n "git-object") (r "^0.6.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "miniz_oxide") (r "^0.4.1") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.6.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)))) (h "1mgsbxrr6mw0hsdk3i08bfx09yby1s7khmpyi30y3hgb8vlc36wr") (f (quote (("serde1" "serde" "git-object/serde1"))))))

(define-public crate-git-odb-0.9.0 (c (n "git-odb") (v "0.9.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.17") (k 0)) (d (n "git-features") (r "^0.11.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.1.0") (d #t) (k 0)) (d (n "git-object") (r "^0.6.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)))) (h "0aszjc45swg3in6288lr9y0ch5qpfygf5ycicis7jnhn9fffcmpf") (f (quote (("serde1" "serde" "git-object/serde1") ("default" "flate2/zlib-ng-compat"))))))

(define-public crate-git-odb-0.9.1 (c (n "git-odb") (v "0.9.1") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.17") (k 0)) (d (n "git-features") (r "^0.11.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.1.0") (d #t) (k 0)) (d (n "git-object") (r "^0.6.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)))) (h "1fsz892dac16lpyw13qps487f2a15my8bgb47597vwi2560mpsvp") (f (quote (("serde1" "serde" "git-object/serde1") ("default" "flate2/zlib-ng-compat"))))))

(define-public crate-git-odb-0.10.0 (c (n "git-odb") (v "0.10.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.17") (k 0)) (d (n "git-features") (r "^0.12.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.2.0") (d #t) (k 0)) (d (n "git-object") (r "^0.7.0") (d #t) (k 0)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempdir") (r "^0.3.7") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^1.0.0") (d #t) (k 0)))) (h "1parc0hx53ci63xfgvgfi2rhg9hw1473vmabsmybvg30zc5misgx") (f (quote (("serde1" "serde" "git-object/serde1") ("polonius") ("default" "flate2/zlib-ng-compat"))))))

(define-public crate-git-odb-0.12.0 (c (n "git-odb") (v "0.12.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.17") (k 0)) (d (n "git-features") (r "^0.13.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.3.0") (d #t) (k 0)) (d (n "git-object") (r "^0.8.0") (d #t) (k 0)) (d (n "git-testtools") (r "^0.1") (d #t) (k 2)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "memory-lru") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^2.0.0") (o #t) (d #t) (k 0)))) (h "0fycdd0lrlj311k0rsjsfirx8a6m9g1y2fbmnnmbjdbvfrjzhlc6") (f (quote (("serde1" "serde" "git-object/serde1") ("pack-cache-lru-static" "uluru") ("pack-cache-lru-dynamic" "memory-lru") ("internal-testing-git-features-parallel" "git-features/parallel") ("default" "flate2/zlib-ng-compat"))))))

(define-public crate-git-odb-0.14.0 (c (n "git-odb") (v "0.14.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.17") (k 0)) (d (n "git-features") (r "^0.13.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.3.0") (d #t) (k 0)) (d (n "git-object") (r "^0.8.0") (d #t) (k 0)) (d (n "git-testtools") (r "^0.1") (d #t) (k 2)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "memory-lru") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^2.0.0") (o #t) (d #t) (k 0)))) (h "03imljp17z5fxhziwkfb30h3lhl4y1mq941zv4kigycwws7p8bdy") (f (quote (("serde1" "serde" "git-object/serde1") ("pack-cache-lru-static" "uluru") ("pack-cache-lru-dynamic" "memory-lru") ("internal-testing-git-features-parallel" "git-features/parallel") ("default" "flate2/zlib-ng-compat"))))))

(define-public crate-git-odb-0.15.0 (c (n "git-odb") (v "0.15.0") (d (list (d (n "bstr") (r "^0.2.13") (f (quote ("std"))) (k 2)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.2.3") (d #t) (k 0)) (d (n "bytesize") (r "^1.0.1") (d #t) (k 0)) (d (n "common_macros") (r "^0.1.1") (d #t) (k 2)) (d (n "filebuffer") (r "^0.4.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.17") (k 0)) (d (n "git-features") (r "^0.14.0") (d #t) (k 0)) (d (n "git-hash") (r "^0.3.0") (d #t) (k 0)) (d (n "git-object") (r "^0.9.0") (d #t) (k 0)) (d (n "git-testtools") (r "^0.1") (d #t) (k 2)) (d (n "hex") (r "^0.4.2") (d #t) (k 2)) (d (n "itoa") (r "^0.4.6") (d #t) (k 0)) (d (n "memory-lru") (r "^0.1.0") (o #t) (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.0") (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "smallvec") (r "^1.3.0") (d #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.20") (d #t) (k 0)) (d (n "uluru") (r "^2.0.0") (o #t) (d #t) (k 0)))) (h "1lzngfpchyc1wqcs56h36364d0dmcd9jcm046ci2drfhqzg4g2k8") (f (quote (("serde1" "serde" "git-object/serde1") ("pack-cache-lru-static" "uluru") ("pack-cache-lru-dynamic" "memory-lru") ("internal-testing-git-features-parallel" "git-features/parallel") ("default" "flate2/zlib-ng-compat"))))))

(define-public crate-git-odb-0.16.0 (c (n "git-odb") (v "0.16.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-actor") (r "^0.2.0") (d #t) (k 2)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.10.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.3") (d #t) (k 0)) (d (n "git-testtools") (r "^0.3") (d #t) (k 2)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1n9hr2zrfv8ldfcpbl2a4pb1jrqgr9xxmb8ziwim2f45n0flg6l4") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.16.1 (c (n "git-odb") (v "0.16.1") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-actor") (r "^0.2.0") (d #t) (k 2)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.10.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.3") (d #t) (k 0)) (d (n "git-testtools") (r "^0.3") (d #t) (k 2)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0750qcnqa59ffan5a0mb1px0987sq9lr88nyscz5h70zs2qxb5fw") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.17.0 (c (n "git-odb") (v "0.17.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-actor") (r "^0.3.0") (d #t) (k 2)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.11.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.5") (d #t) (k 0)) (d (n "git-testtools") (r "^0.4") (d #t) (k 2)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0c0k3i7gkaclszysfl1hggbadc9frh722j4kqf31l7bi45pdzga3") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.18.0 (c (n "git-odb") (v "0.18.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-actor") (r "^0.3.0") (d #t) (k 2)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.11.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.6") (d #t) (k 0)) (d (n "git-testtools") (r "^0.4") (d #t) (k 2)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "186xzz8lhdgxbp0rgb4jf0rkzxs4b9biczcj8n42wy51479xlmjf") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.20.0 (c (n "git-odb") (v "0.20.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-actor") (r "^0.3.1") (d #t) (k 2)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.12.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.8.0") (d #t) (k 0)) (d (n "git-testtools") (r "^0.4") (d #t) (k 2)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1axbszm4fffpglq681xi1ibj2jgwysbnayrwwy1f2wh3cayxb3d7") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.20.1 (c (n "git-odb") (v "0.20.1") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.12.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.8.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1a68qccja127sdgxch3xnil6jkl9549qrkvk4c059bhxfn3qhs1d") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.20.2 (c (n "git-odb") (v "0.20.2") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.12.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.8.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1psq3rsj16p81mqrsqzglgc1k83q7zp2a3l95xrx46rpqs9q6hmd") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.21.0 (c (n "git-odb") (v "0.21.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.5.0") (d #t) (k 0)) (d (n "git-object") (r "^0.13.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.9.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1j3kqha7pdsh3d2p59m4irvfc6b6rbykl0h9g5qxzlj2hw556n6v") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.21.1 (c (n "git-odb") (v "0.21.1") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.6.0") (d #t) (k 0)) (d (n "git-object") (r "^0.13.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.10.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1padad08gbba160xqv4gxkwqkbs37m5s6pza7jv6i3m23nw6j1zj") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.21.2 (c (n "git-odb") (v "0.21.2") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.6.0") (d #t) (k 0)) (d (n "git-object") (r "^0.14.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.11.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1xdrv4vb51qx9fydv5fmk70x7xm8241rbdp0cx7k1wp6m51wxbhl") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.21.3 (c (n "git-odb") (v "0.21.3") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.6.0") (d #t) (k 0)) (d (n "git-object") (r "^0.14.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.11.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1lp7iinhv5p7vr7fs6v2712vmirkzbi1jq3dkkkc4xxq4dgijrc8") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.22.0 (c (n "git-odb") (v "0.22.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.16.5") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.7.0") (d #t) (k 0)) (d (n "git-object") (r "^0.14.1") (d #t) (k 0)) (d (n "git-pack") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1jzgdykp13dyszfi77s4hip3gnvwlbc6nrp4h3dldc61wxgfflim") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.23.0 (c (n "git-odb") (v "0.23.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.17.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.8.0") (d #t) (k 0)) (d (n "git-object") (r "^0.15.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.13.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "03m9ipqgp5cmsg0cifawdrig8r9nb79azwcg8p1vfvs95klihwb0") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.24.0 (c (n "git-odb") (v "0.24.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.17.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.8.0") (d #t) (k 0)) (d (n "git-object") (r "^0.15.1") (d #t) (k 0)) (d (n "git-pack") (r "^0.14.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "06mcqbnv45wq1b0kvmy7xaim1kibyznz8syikkhyy6qainkq0925") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.25.0 (c (n "git-odb") (v "0.25.0") (d (list (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "git-features") (r "^0.18.0") (f (quote ("rustsha1" "walkdir" "zlib"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.8.0") (d #t) (k 0)) (d (n "git-object") (r "^0.16.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.15.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^0.7.1") (d #t) (k 2)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0bx9y1a03bgnb9mfy3fmcva67ga9k798278d43qdvpclak9n31xi") (f (quote (("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.26.0 (c (n "git-odb") (v "0.26.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "btoi") (r "^0.4.2") (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.19.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.1") (d #t) (k 0)) (d (n "git-object") (r "^0.17.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.16.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.11.2") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "176k92bk865v4syb8azvx8i4l2bfsg5fk81cw0bh6zlyj255gcv1") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.27.0 (c (n "git-odb") (v "0.27.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.20.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32" "bstr"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.3") (d #t) (k 0)) (d (n "git-object") (r "^0.18.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.17.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1w9d505avx0gza1hbcsl0pw8rpdjvb0lngb0da47ssjycxcifbwv") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.28.0 (c (n "git-odb") (v "0.28.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.20.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32" "bstr"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.3") (d #t) (k 0)) (d (n "git-object") (r "^0.18.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.18.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0p3g0qf06l88z6c8ywcapinxr1yhdk6kx16j9148584pqlq30hxv") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.29.0 (c (n "git-odb") (v "0.29.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.21.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.4") (d #t) (k 0)) (d (n "git-object") (r "^0.19.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.19.0") (d #t) (k 0)) (d (n "git-path") (r "^0.1.1") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0h2dsbrlkp802s5hbsj1adyfksrz4zlia6azkbv940zq3mgq15k9") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.30.0 (c (n "git-odb") (v "0.30.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.21.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.5") (d #t) (k 0)) (d (n "git-object") (r "^0.19.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.20.0") (d #t) (k 0)) (d (n "git-path") (r "^0.2.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0a7dy97ap5s6pim347jh7kgii60nmniy0cbyjvc853wwvz1z5596") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.31.0 (c (n "git-odb") (v "0.31.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.22.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.6") (d #t) (k 0)) (d (n "git-object") (r "^0.20.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.21.0") (d #t) (k 0)) (d (n "git-path") (r "^0.4.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.0") (d #t) (k 0)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0qf5r5w0jn0yva1w2vri0l4gbnd7lfsl19cwrngsj8ggz12z1w1z") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.31.1 (c (n "git-odb") (v "0.31.1") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.22.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.7") (d #t) (k 0)) (d (n "git-object") (r "^0.20.1") (d #t) (k 0)) (d (n "git-pack") (r "^0.21.1") (d #t) (k 0)) (d (n "git-path") (r "^0.4.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0786ggj0y6bx0xhw84hgvy5z6bh9h7jn6kh2hicy1fvxbzc5k4z6") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.31.2 (c (n "git-odb") (v "0.31.2") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.22.2") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.8") (d #t) (k 0)) (d (n "git-object") (r "^0.20.2") (d #t) (k 0)) (d (n "git-pack") (r "^0.21.2") (d #t) (k 0)) (d (n "git-path") (r "^0.4.1") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.1") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "145k588wd2ldby4rpvd3z1d9iiickw36qhh7xdllaba91nw8nms4") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.32.0 (c (n "git-odb") (v "0.32.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.22.3") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.8") (d #t) (k 0)) (d (n "git-object") (r "^0.20.3") (d #t) (k 0)) (d (n "git-pack") (r "^0.22.0") (d #t) (k 0)) (d (n "git-path") (r "^0.4.1") (d #t) (k 0)) (d (n "git-quote") (r "^0.2.1") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1xigy4kba6w8hwhf2l7zb52gwaw2laqdx22m9r5nq64dq57wslrk") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.33.0 (c (n "git-odb") (v "0.33.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.22.5") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.10") (d #t) (k 0)) (d (n "git-object") (r "^0.21.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.23.0") (d #t) (k 0)) (d (n "git-path") (r "^0.5.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.3.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0mfn22k01cr1w8p2451ag71gksnwhssanfl9pvkh80mr9nr4nf52") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.34.0 (c (n "git-odb") (v "0.34.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.23.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.11") (d #t) (k 0)) (d (n "git-object") (r "^0.22.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.24.0") (d #t) (k 0)) (d (n "git-path") (r "^0.5.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.3.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0g7nb6f86d5jv8n3shbm10rbz623kazkwdsnfwp63wh2mm2azfs3") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.35.0 (c (n "git-odb") (v "0.35.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.23.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.11") (d #t) (k 0)) (d (n "git-object") (r "^0.22.1") (d #t) (k 0)) (d (n "git-pack") (r "^0.25.0") (d #t) (k 0)) (d (n "git-path") (r "^0.5.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.3.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "19l85bbg9l8m9vz07yqlc8i1ilcm8c8xf5ia4gpdzn67381sgbma") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.36.0 (c (n "git-odb") (v "0.36.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.23.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.9.11") (d #t) (k 0)) (d (n "git-object") (r "^0.22.1") (d #t) (k 0)) (d (n "git-pack") (r "^0.26.0") (d #t) (k 0)) (d (n "git-path") (r "^0.5.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.3.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0p5rjwfdca59jjq1q0qk7yqfiliriindrrpy8vdcqvrj6z7n9svn") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.37.0 (c (n "git-odb") (v "0.37.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.24.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.0") (d #t) (k 0)) (d (n "git-object") (r "^0.23.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.27.0") (d #t) (k 0)) (d (n "git-path") (r "^0.6.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0jsq7436zq6brpc0mdmrlgdnpqm16gwjjka12m14a9h3ryk3sj8k") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.38.0 (c (n "git-odb") (v "0.38.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.25.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.1") (d #t) (k 0)) (d (n "git-object") (r "^0.24.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.28.0") (d #t) (k 0)) (d (n "git-path") (r "^0.7.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1bfhw3im9468yfkp7bnz7im1hq2vb6hzjd8jwjmsxn1h9jg0c2m3") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.38.1 (c (n "git-odb") (v "0.38.1") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.25.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.1") (d #t) (k 0)) (d (n "git-object") (r "^0.24.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.28.0") (d #t) (k 0)) (d (n "git-path") (r "^0.7.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1p939n181mp9gd20zxw5wdzpgqfqg9s5y599kv9scnmjpcck8csm") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.39.0 (c (n "git-odb") (v "0.39.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.26.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.1") (d #t) (k 0)) (d (n "git-object") (r "^0.25.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.29.0") (d #t) (k 0)) (d (n "git-path") (r "^0.7.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "044v3cjhk4qwxn1l2bkj3d5nj1rm068jjkb613hrb2z4gbj89sl4") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.40.0 (c (n "git-odb") (v "0.40.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.26.0") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.1") (d #t) (k 0)) (d (n "git-object") (r "^0.26.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.30.0") (d #t) (k 0)) (d (n "git-path") (r "^0.7.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0cq3fniamhs0lyaxvvp2s2v6wymk8x2x4n17hh46xzyswfh1aqb1") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.40.1 (c (n "git-odb") (v "0.40.1") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.26.1") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.1") (d #t) (k 0)) (d (n "git-object") (r "^0.26.0") (d #t) (k 0)) (d (n "git-pack") (r "^0.30.1") (d #t) (k 0)) (d (n "git-path") (r "^0.7.0") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.0") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "18pfya6kcvwsmzhrcrbp432g8rwrwr46vy8h58si69h6s7hi8ddl") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel"))))))

(define-public crate-git-odb-0.40.2 (c (n "git-odb") (v "0.40.2") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.26.2") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.2") (d #t) (k 0)) (d (n "git-object") (r "^0.26.1") (d #t) (k 0)) (d (n "git-pack") (r "^0.30.2") (d #t) (k 0)) (d (n "git-path") (r "^0.7.1") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.1") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "1kigm741wlscbn46shp8dr57fs4n4fdgrqj7cgw5l9d0b1gzq16v") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel")))) (r "1.64")))

(define-public crate-git-odb-0.41.0 (c (n "git-odb") (v "0.41.0") (d (list (d (n "arc-swap") (r "^1.5.0") (d #t) (k 0)) (d (n "crossbeam-channel") (r "^0.5.6") (d #t) (k 2)) (d (n "document-features") (r "^0.2.0") (o #t) (d #t) (k 0)) (d (n "filetime") (r "^0.2.15") (d #t) (k 2)) (d (n "git-features") (r "^0.26.5") (f (quote ("rustsha1" "walkdir" "zlib" "crc32"))) (d #t) (k 0)) (d (n "git-hash") (r "^0.10.3") (d #t) (k 0)) (d (n "git-object") (r "^0.26.2") (d #t) (k 0)) (d (n "git-pack") (r "^0.31.0") (d #t) (k 0)) (d (n "git-path") (r "^0.7.2") (d #t) (k 0)) (d (n "git-quote") (r "^0.4.2") (d #t) (k 0)) (d (n "maplit") (r "^1.0.2") (d #t) (k 2)) (d (n "num_cpus") (r "^1.13.1") (d #t) (k 2)) (d (n "parking_lot") (r "^0.12.0") (d #t) (k 0)) (d (n "pretty_assertions") (r "^1.0.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (o #t) (k 0)) (d (n "tempfile") (r "^3.1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.26") (d #t) (k 0)))) (h "0nxs0h1m3k6k0kl50d93dykdqdbsrmyab1rbapg4ynk7q989mfqq") (f (quote (("serde1" "serde" "git-hash/serde1" "git-object/serde1" "git-pack/serde1") ("internal-testing-git-features-parallel" "git-features/parallel")))) (r "1.64")))

