(define-module (crates-io ro ut routing) #:use-module (crates-io))

(define-public crate-routing-0.0.6 (c (n "routing") (v "0.0.6") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "lru-cache") (r "*") (d #t) (k 0)) (d (n "maidsafe_types") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rust-sqlite") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0njx9hvmks39rwm76d7nr027w6z6s8nkv6fclyfy5p0xiwnq1hyl")))

(define-public crate-routing-0.0.7 (c (n "routing") (v "0.0.7") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.3") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.0") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rusqlite") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0n478zlh0hcw5f8cv77q0jd6h6qp6k2azq9h2nyg1jv7k8wvfdwd")))

(define-public crate-routing-0.0.8 (c (n "routing") (v "0.0.8") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.3") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.0") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rusqlite") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "154crpsnj9hg6myg2v7f1lc1di382cpb21719nzzx527ga09d69p")))

(define-public crate-routing-0.0.9 (c (n "routing") (v "0.0.9") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.3") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.0") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rusqlite") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1lyd4g8nai7gs0n4wpgrsmjpn6jmdd1p8lgy76j94f258sblmvl7")))

(define-public crate-routing-0.1.0 (c (n "routing") (v "0.1.0") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.3") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.0") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rusqlite") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1x2rwhx0jcnfx59jlvc5aw1z2mfknkxpgs68457w2j1m90a4308n")))

(define-public crate-routing-0.1.1 (c (n "routing") (v "0.1.1") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.3") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.0") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rusqlite") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1vrbwa71vs5cqpfykjnn1fsa9lp0r43km9rk62qdr3fb1jlwrsj8")))

(define-public crate-routing-0.1.2 (c (n "routing") (v "0.1.2") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.0") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1sfpyjmcdsqzxm5y1zg9j6kf7yd97sx8a55xhdrd7lclr261qs50")))

(define-public crate-routing-0.1.3 (c (n "routing") (v "0.1.3") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.5") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.4") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1pdy6jj1c2wsm59s6pg800rmccasgq2hc14z2b6mn87pvic9w4lb")))

(define-public crate-routing-0.1.31 (c (n "routing") (v "0.1.31") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.51") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.4") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0k92ccs48n3c91yrnkh2skz10r2ykfx61y7xk4k5jn2z1x541k47")))

(define-public crate-routing-0.1.32 (c (n "routing") (v "0.1.32") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.51") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.4") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0ryay1gm4dn0d68blrpbyvlky7an5hrg1p8j3ahkiy0nnw6wx9ha")))

(define-public crate-routing-0.1.33 (c (n "routing") (v "0.1.33") (d (list (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.51") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.4") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1jrc83fv7rzz6na2wr5cigpzn9ylcnwsj160bxdpvw3cbnkhfxng")))

(define-public crate-routing-0.1.34 (c (n "routing") (v "0.1.34") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.51") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1lf7b78r6vy0mx6am9ajkl3mafjccbfhhyqhgdmnikx752lhs20z")))

(define-public crate-routing-0.1.4 (c (n "routing") (v "0.1.4") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.7") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0fradh5i5m3bb4i6s22br9qcb609s9z4wynpjq51izqzy7kbpnxg")))

(define-public crate-routing-0.1.40 (c (n "routing") (v "0.1.40") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.7") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0lj8x9cvfyry92axmfwb6lw64qg69jf7kjyn9jmhjwqgq5sxfhp7")))

(define-public crate-routing-0.1.41 (c (n "routing") (v "0.1.41") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.8") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "082srdcj76jw4jiawn25fnjw5552zknrjsmvw963ac35yc9gh1cg")))

(define-public crate-routing-0.1.60 (c (n "routing") (v "0.1.60") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.8") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0mk8xlimj1kh9v3mx13jc68xmhgfa5ka1grna7bm72cl0kx1mkd0")))

(define-public crate-routing-0.1.61 (c (n "routing") (v "0.1.61") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "^0.0.8") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0yb26qrfymxw2pl2n4jn6qa4jaraaz9bdjgk5highrf918605p04")))

(define-public crate-routing-0.1.62 (c (n "routing") (v "0.1.62") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1kcxmj6v70g54lcvxbpzmv76sdvq8jakz36cs1lcbj8i26wcdz56")))

(define-public crate-routing-0.1.63 (c (n "routing") (v "0.1.63") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0zigmwmz43b1s549gk2s1k1422al7la77hr1zh4ksbn0y00q3rvz")))

(define-public crate-routing-0.1.64 (c (n "routing") (v "0.1.64") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1w1dfsmvyjxxjfng09mzbq1l5p35dy9h048v06zylx7a634vgym8")))

(define-public crate-routing-0.1.70 (c (n "routing") (v "0.1.70") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "14m08sziy656ap1252i15r2cdczkb31yrpcb34nvhqs4ssc25m6d")))

(define-public crate-routing-0.1.71 (c (n "routing") (v "0.1.71") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "10zchs6qxda27xfw59nvyggki0dbxdf48hn451ak6mmf5v13z2yx")))

(define-public crate-routing-0.1.72 (c (n "routing") (v "0.1.72") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0wa0bwixirfc9kakadr6snpqhckarh6isbf6l46d7zkrc22xblwf")))

(define-public crate-routing-0.2.0 (c (n "routing") (v "0.2.0") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.4") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "18y9m3avlxwz73qjzdwamrnabx03j8vlj5ysjkg3m85y4ixh4nxs")))

(define-public crate-routing-0.2.1 (c (n "routing") (v "0.2.1") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.0.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "^0.0.5") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0yydwsap1pb9zdkw6x2vybvlhrlzv3nj9b1kzgcazq8ppfdjka9w")))

(define-public crate-routing-0.2.2 (c (n "routing") (v "0.2.2") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1pqdw0g42y7jk60qj1rls2hbg0rfq729219sz30w2yhhysfydvv8")))

(define-public crate-routing-0.2.3 (c (n "routing") (v "0.2.3") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0bkcj62ciiggp1rz6kf5lz3d4yy72kz5p3kyclgaifbdp6g4jgri")))

(define-public crate-routing-0.2.4 (c (n "routing") (v "0.2.4") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "15qs9fx71msiamk56qbhvfwnjymcq22rpjngzcl88zs6123pw70n")))

(define-public crate-routing-0.2.5 (c (n "routing") (v "0.2.5") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "12i1wbz72g9q3pf622bjkzdi0ijlmqk616aazkdb1h9yk5ld433f")))

(define-public crate-routing-0.2.6 (c (n "routing") (v "0.2.6") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1wrb0ymdbjgv5njispvk3z99h49038446gzzz19g6h0kjdr3y6y3")))

(define-public crate-routing-0.2.7 (c (n "routing") (v "0.2.7") (d (list (d (n "accumulator") (r "^0.0.1") (d #t) (k 0)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "^0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0xin2gx9mlm5qmf1v3ss6sps1h0j8m678sms6y37hv0k6ijk0nzq")))

(define-public crate-routing-0.2.8 (c (n "routing") (v "0.2.8") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.1.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "037qpx7ldiz9n70br22hx9xgqsiqr504kx8y17jjzqwksrrw38ss")))

(define-public crate-routing-0.3.0 (c (n "routing") (v "0.3.0") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 2)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "maidsafe_sodiumoxide") (r "*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sentinel") (r "0.1.*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "00a40rg4pwxiayby7y9fc1svn8r6xgaj6bgmbnal305fyjmbsvq5")))

(define-public crate-routing-0.3.1 (c (n "routing") (v "0.3.1") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 2)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0lqkv0wnrg5ypcjivwiz9sfhzysxs6gi1blws0zp51hqgfmajcnm")))

(define-public crate-routing-0.3.2 (c (n "routing") (v "0.3.2") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 2)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "10mfsxd7c41nm70c8qibdg29mxzklc36sbcprcwrf6b32i0wbkr3")))

(define-public crate-routing-0.3.3 (c (n "routing") (v "0.3.3") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 2)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0zwaimjbvl2fvwka759wqaxc2q2ibjv5khv13nj72vkl6lcicx7h")))

(define-public crate-routing-0.3.4 (c (n "routing") (v "0.3.4") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 2)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0wh65xgj0wi0ipmwb0dh1490lhbbl64ng5lp8jk4fj68h89md7il")))

(define-public crate-routing-0.3.5 (c (n "routing") (v "0.3.5") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 2)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "17w457qnr5cjwk3jz481f3wp5n31rymvyqvcgj0adybg0r5p8jq9")))

(define-public crate-routing-0.3.6 (c (n "routing") (v "0.3.6") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1qjd0jjqnyisn49m077z7am5n73c0a7jysi4ydzd3jnw8b6950ja")))

(define-public crate-routing-0.3.7 (c (n "routing") (v "0.3.7") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1sl5qldp7qm1xy3k672hg2gy23ryr4ivhg6l08b1w8ax261ymnxl")))

(define-public crate-routing-0.3.8 (c (n "routing") (v "0.3.8") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0yd1zz2gg71lkix7p5ir5plrv6p3zswp3kqzdvkx9j1za460xgfs")))

(define-public crate-routing-0.3.9 (c (n "routing") (v "0.3.9") (d (list (d (n "accumulator") (r "0.0.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1drzfm1j1x5fjmw4wz08q3da41zwxf4rs6qs1rypd1fyywdr5njn")))

(define-public crate-routing-0.3.10 (c (n "routing") (v "0.3.10") (d (list (d (n "accumulator") (r "0.1.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0mj5hibzyp30jr9r70l99yzyqrp2kx18sm5rpbsiqq1dc3sviimi")))

(define-public crate-routing-0.3.11 (c (n "routing") (v "0.3.11") (d (list (d (n "accumulator") (r "0.1.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0hlwhkkw7z7cvlrasgygp1awslrq32gi2i9k1h7msyprhijc0kzk")))

(define-public crate-routing-0.3.12 (c (n "routing") (v "0.3.12") (d (list (d (n "accumulator") (r "0.1.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.2.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1pddf6jlhsclcbjach5jipyrhismcp7xsq75kmpkq2r88k8xlays")))

(define-public crate-routing-0.4.0 (c (n "routing") (v "0.4.0") (d (list (d (n "accumulator") (r "0.1.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.3.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "0m08fxlmq2bgrv8lmp9z2hi6kpijxwna60iip39rn796llfyx15n")))

(define-public crate-routing-0.4.1 (c (n "routing") (v "0.4.1") (d (list (d (n "accumulator") (r "0.1.*") (d #t) (k 0)) (d (n "bit-vec") (r "*") (d #t) (k 2)) (d (n "cbor") (r "*") (d #t) (k 0)) (d (n "crust") (r "0.4.*") (d #t) (k 0)) (d (n "docopt") (r "*") (d #t) (k 0)) (d (n "env_logger") (r "*") (d #t) (k 0)) (d (n "itertools") (r "*") (d #t) (k 0)) (d (n "log") (r "*") (d #t) (k 0)) (d (n "lru_time_cache") (r "0.2.*") (d #t) (k 0)) (d (n "message_filter") (r "0.1.*") (d #t) (k 0)) (d (n "rand") (r "*") (d #t) (k 0)) (d (n "rustc-serialize") (r "*") (d #t) (k 0)) (d (n "sodiumoxide") (r "*") (d #t) (k 0)) (d (n "time") (r "*") (d #t) (k 0)))) (h "1kayvaljjya87b0ipikfrim225lf5sx5s91mb3mx9642ypa9r7r9")))

(define-public crate-routing-0.4.2 (c (n "routing") (v "0.4.2") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.5.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.75") (d #t) (k 0)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 0)) (d (n "itertools") (r "~0.4.3") (d #t) (k 0)) (d (n "log") (r "~0.3.3") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.4") (d #t) (k 0)) (d (n "message_filter") (r "~0.1.5") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)))) (h "1npi002lixrzmarlijc3jryhczj02qc1fqykrrfigrqjfn81rmf8")))

(define-public crate-routing-0.5.0 (c (n "routing") (v "0.5.0") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.7.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.3") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.4") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "1ldawlsjl10jxv6sywq80xn33300sv284nxv4mh08a72ry2cpi0f")))

(define-public crate-routing-0.5.1 (c (n "routing") (v "0.5.1") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.7.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.3") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.4") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "0pz25y7m0rcndnvbwp392xbhnbs1qzmlyvkdjghmsmd69k5c7ykm")))

(define-public crate-routing-0.5.2 (c (n "routing") (v "0.5.2") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.7.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.3") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.4") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "051xz0fscmdzgxx0wgmabc73y25y1r0i39g699wwwgk2kr1ac3xp")))

(define-public crate-routing-0.5.3 (c (n "routing") (v "0.5.3") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.7.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.3") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.4") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 2)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "0hja76jijxl17k9gi52538y1imn5qxvi5p4kbcl7kfmk1wxpbbd6")))

(define-public crate-routing-0.6.1 (c (n "routing") (v "0.6.1") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.8.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.5") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.4") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 2)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "170wgz9rq7brrikr845jrnd3si8hf1cqlhywfkg0vcd2781bfc15")))

(define-public crate-routing-0.6.2 (c (n "routing") (v "0.6.2") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.8.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.5") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.5") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "1wj6rj9vfhb0cr543kvx26kswj0pspzvs4m3awc8q6w0fj57xrax")))

(define-public crate-routing-0.6.3 (c (n "routing") (v "0.6.3") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "bit-vec") (r "~0.4.2") (d #t) (k 2)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "crust") (r "~0.8.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 2)) (d (n "ip") (r "~1.0.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.5") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.0.5") (d #t) (k 0)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.1") (d #t) (k 0)))) (h "119j85hfqa2yavvbwzzlymz5xin6mnfmsl7sq46ra3841vam1fjc")))

(define-public crate-routing-0.7.0 (c (n "routing") (v "0.7.0") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "clippy") (r "~0.0.44") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.8.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 2)) (d (n "ip") (r "~1.1.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.5") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.3.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.6") (d #t) (k 2)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.1.5") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.4") (d #t) (k 0)))) (h "03x24yyv6ff1w7dv101f240iqa3n974hv14k6l6bx1b4zy9akd62")))

(define-public crate-routing-0.7.1 (c (n "routing") (v "0.7.1") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "clippy") (r "~0.0.44") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.8.3") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 2)) (d (n "ip") (r "~1.1.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.5") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.3.2") (d #t) (k 0)) (d (n "libc") (r "~0.2.6") (d #t) (k 2)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.2.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.4") (d #t) (k 0)))) (h "1424vs9713pcd7a9wk3kvsj9ns4fl5vnp623j6gxkj91i1lliprc")))

(define-public crate-routing-0.8.0 (c (n "routing") (v "0.8.0") (d (list (d (n "accumulator") (r "~0.1.3") (d #t) (k 0)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "clippy") (r "~0.0.44") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.8.3") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "env_logger") (r "~0.3.2") (d #t) (k 2)) (d (n "ip") (r "~1.1.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.5") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.3.2") (d #t) (k 0)) (d (n "libc") (r "~0.2.6") (d #t) (k 2)) (d (n "log") (r "~0.3.4") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.5") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.2.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.12") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.16") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.4") (d #t) (k 0)))) (h "16j05vkg3kc0phjk6j1nkx38bxfldrr9v3hps6yrapfzn6jsjq8v")))

(define-public crate-routing-0.9.0 (c (n "routing") (v "0.9.0") (d (list (d (n "accumulator") (r "~0.1.4") (d #t) (k 0)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "clippy") (r "~0.0.44") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.8.3") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "ip") (r "~1.1.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.10") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.3.3") (d #t) (k 0)) (d (n "libc") (r "~0.2.7") (d #t) (k 2)) (d (n "log") (r "~0.3.5") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.6") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.3.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.18") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.5") (d #t) (k 0)))) (h "1ngp5ha0k9lqjwrgj7rnbhpm5zl68bv66w2wr97qfg28jv7kb704") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.10.0 (c (n "routing") (v "0.10.0") (d (list (d (n "accumulator") (r "~0.1.4") (d #t) (k 0)) (d (n "cbor") (r "~0.3.16") (d #t) (k 0)) (d (n "clippy") (r "~0.0.44") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.8.3") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "ip") (r "~1.1.0") (d #t) (k 0)) (d (n "itertools") (r "~0.4.10") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.3.3") (d #t) (k 0)) (d (n "libc") (r "~0.2.7") (d #t) (k 2)) (d (n "log") (r "~0.3.5") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.6") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.3.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.18") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.0.5") (d #t) (k 0)))) (h "11gn59ck6fqy64xar1nr12205vpl65ajfl2mcx3935yzpymb3slv") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.11.0 (c (n "routing") (v "0.11.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.46") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.9.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "itertools") (r "~0.4.10") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.7") (d #t) (k 2)) (d (n "log") (r "~0.3.5") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.4.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.18") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "10w7qzv63rp0w25gkivsy9iyjsirz8avqdj2h0v80h9a37r176g5") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.11.1 (c (n "routing") (v "0.11.1") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.46") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.9.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "itertools") (r "~0.4.10") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.7") (d #t) (k 2)) (d (n "log") (r "~0.3.5") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.4.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.18") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0ch6q7354sf4593yppznl0gjjpww5dl1xa1pjma6y49x5iyil3ff") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.12.0 (c (n "routing") (v "0.12.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.46") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.9.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "itertools") (r "~0.4.10") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.7") (d #t) (k 2)) (d (n "log") (r "~0.3.5") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.4.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.18") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.9") (d #t) (k 0)) (d (n "time") (r "~0.1.34") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "056wxmr3cdiydrnczl7v7cm3jjn7qps08whkwm7398zflmi0sms2") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.13.0 (c (n "routing") (v "0.13.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.61") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.78") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.7") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "^0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0j2wmwzbgblc8zkim8nv3n01pazqlgwk4nsv1hy9qbjx5jgz0fsp") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.14.0 (c (n "routing") (v "0.14.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0b3khq9as8p84bc6jvgr6m8bz145qxvsp6nfwnkcypf2l345l0jb") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.15.0 (c (n "routing") (v "0.15.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0kdhsxak7iw30wyahi77p0snhl1wph3a1dgg6v905gnzag7h931v") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.15.1 (c (n "routing") (v "0.15.1") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0x8m8sdmy12rzkpplvycgay9f29q78nfj3w5y5lh71kgqbkdf13c") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.16.0 (c (n "routing") (v "0.16.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.1") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "15rh52z0al4chxmzrsin9b2zgdr0r2lc9z6wsz8k4fjva09k2car") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.16.1 (c (n "routing") (v "0.16.1") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.2") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0sd1vncgjk136lsd643nsk3kcxl0xing5jlp6z7002m2qsppxbrn") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.16.2 (c (n "routing") (v "0.16.2") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.2") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0why7h73nzvwysk8s5j2v75lhm2kp7lq43x1rwxm136f2fb86cca") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.16.3 (c (n "routing") (v "0.16.3") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.10.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.2") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0hyvy008l9ybk482vys61il8bl6lxfqw37gbrzvzna088diafnqc") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.17.0 (c (n "routing") (v "0.17.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.11.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.12") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.4.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.9") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.2") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0n2hywsh26bj4fl8wp0sm40s6qfh9qa7pzkwldmndmgs4ya576hq") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.18.0 (c (n "routing") (v "0.18.0") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.11.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.3") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "1ljszncxcwh2xi2lxh465cvyrq050xaf9v22xc88xnhs21s2zkn9") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.18.1 (c (n "routing") (v "0.18.1") (d (list (d (n "accumulator") (r "~0.2.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.11.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.2.7") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.3") (d #t) (k 0)) (d (n "message_filter") (r "~0.3.1") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "time") (r "~0.1.35") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "12qmwxc8jq5d2bmpy8zxq4y0p8mhm1zpk5bg7zh72zd2sn7l79ir") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.18.2 (c (n "routing") (v "0.18.2") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.11.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.3.1") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.3") (d #t) (k 0)) (d (n "message_filter") (r "~0.5.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "078sw6sl6qci16fp0xi06ac0cyaqgjsz8zas7lhmba87bszflhig") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.18.3 (c (n "routing") (v "0.18.3") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.63") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.11.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.3.1") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.3") (d #t) (k 0)) (d (n "message_filter") (r "~0.5.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "19m38fv9jglhqn0p1wcrvvlk5rnrjbpmniwdz4lzmad4v0px9sc5") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.18.4 (c (n "routing") (v "0.18.4") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.64") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.12.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "^0.8.0") (d #t) (k 1)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.3.1") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.4") (d #t) (k 0)) (d (n "message_filter") (r "~0.5.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "1l8z6ga7mm0m57rrl0k6x4swb88slrk6vhl6pnayi4ijbvfjmm95") (f (quote (("use-mock-crust") ("generate-diagrams"))))))

(define-public crate-routing-0.18.5 (c (n "routing") (v "0.18.5") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.65") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.12.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "^0.8.0") (d #t) (k 1)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.3.1") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.4") (d #t) (k 0)) (d (n "message_filter") (r "~0.5.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0b3ynf2m34xwvwmkza1ngk0h973m23xfpsqahz96i28hri99hj9f") (f (quote (("use-mock-crust") ("generate-diagrams"))))))

(define-public crate-routing-0.19.0 (c (n "routing") (v "0.19.0") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.66") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.13.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "~0.9.4") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.3.1") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.4") (d #t) (k 0)) (d (n "message_filter") (r "~0.5.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "0457hznigkxi12hv316qjp419jzjx1x83gxypk54w9pwgmdyg6ff") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.19.1 (c (n "routing") (v "0.19.1") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.66") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.13.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "~0.9.4") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.13") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.5.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.10") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.3.1") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.5.4") (d #t) (k 0)) (d (n "message_filter") (r "~0.5.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "xor_name") (r "~0.1.0") (d #t) (k 0)))) (h "1fjpzqabh9pzzk28m06lwlp3ii9g8a64l6k81a9bpmsf3wqsazg9") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.20.0 (c (n "routing") (v "0.20.0") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.69") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.14.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "~0.9.6") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.15") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.11") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.6.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.6.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)))) (h "1cdp59d527q5y05acffpyay4vbkqsp8b2bdp16ydfgxyzkyw7wmb") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.21.0 (c (n "routing") (v "0.21.0") (d (list (d (n "accumulator") (r "~0.3.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.69") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.14.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "~0.9.6") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.15") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.11") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.6.0") (d #t) (k 0)) (d (n "message_filter") (r "~0.6.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)))) (h "1spfyk798yiinzmgfc7aagcmxva4nrdxfsz729vigh5w9awj2pfv") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.22.0 (c (n "routing") (v "0.22.0") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.76") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.15.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.80") (d #t) (k 2)) (d (n "hyper") (r "~0.9.7") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.15") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.6.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)))) (h "04pjiz565agwjsb217g9aynlh132iswdd3qcyjckh0zfn6qxn5wi") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.23.0 (c (n "routing") (v "0.23.0") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.77") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1g7skvgpwknsbqjs0n3jdjcb8dxcv8ah82n85h0da199b8v2nmb2") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.23.1 (c (n "routing") (v "0.23.1") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.77") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1sh6xqm5lwg6lli4md3x79rd2hkm8gphr5h1n6238i0l6jig304j") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.23.2 (c (n "routing") (v "0.23.2") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.77") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "~0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "11d9b302399xa657vjm4nby738m2wrpwa68v0ymjgn88pfkahhxc") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.24.0 (c (n "routing") (v "0.24.0") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.79") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "11qijr5qj5jwgbis3qar65h5q5b43hh3zfqg2kwibjq4z5vjphf7") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.24.1 (c (n "routing") (v "0.24.1") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.79") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "0imxrmqbvna1lnqwlh07advafl89z57zsh0w5zrm579qydpa3x58") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.24.2 (c (n "routing") (v "0.24.2") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.79") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "10z8pkbqqinr3s7arbxxxa31166j1gszfgh5ni6s1psh84kb7cwq") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.24.3 (c (n "routing") (v "0.24.3") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.79") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1g1i735ivqw3avbi3lvn75fdss1i560jl2yqn8y5lzd4qxz6xk0h") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.25.0 (c (n "routing") (v "0.25.0") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.79") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "09mdhjawd3jzc77la8yfq26s4kklwsvjsv5a33m1vxazjxz8vmah") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.25.1 (c (n "routing") (v "0.25.1") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.79") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "085l011qqdr38g778d8w7qxrnmjxy1rknj2dcmaqzvzmhfa5fvgc") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.23.3 (c (n "routing") (v "0.23.3") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.77") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.16.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.8.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "sodiumoxide") (r "= 0.0.10") (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (o #t) (d #t) (k 0)) (d (n "sodiumoxide_extras") (r "~0.1.0") (d #t) (k 2)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1kczq6sbf727739pa5nwgpwmblny4637vjjnlhqllp8a7jdpm3d0") (f (quote (("use-mock-crust" "sodiumoxide_extras") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.23.4 (c (n "routing") (v "0.23.4") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.80") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.17.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.9.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.1") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "0vvvwfslm1ba8194nwgi4wgiqxbdzrhlss14qncbw8ij67v2zqsk") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.26.0 (c (n "routing") (v "0.26.0") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.80") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.18.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.81") (d #t) (k 2)) (d (n "hyper") (r "~0.9.9") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.4.16") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.12") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.4.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.9.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.1") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "01mqn2cr848rg7a7phrk4wp8qyi11bfhgjxzmmjwln9dmisfv27a") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.27.0 (c (n "routing") (v "0.27.0") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.95") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.19.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "hyper") (r "~0.9.10") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.5.2") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.16") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1nzjikl6s16x1marmjlzckc0rpw3nyvap5l4gl1fz1nvg7nrpyaj") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.27.1 (c (n "routing") (v "0.27.1") (d (list (d (n "accumulator") (r "~0.4.0") (d #t) (k 0)) (d (n "clippy") (r "~0.0.95") (o #t) (d #t) (k 0)) (d (n "crust") (r "~0.19.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "hyper") (r "~0.9.10") (o #t) (d #t) (k 1)) (d (n "itertools") (r "~0.5.2") (d #t) (k 0)) (d (n "kademlia_routing_table") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.16") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.14") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.19") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "09hvn3v4cix4fcma2w3ks9py2bk551c4rsf0y0v49d82jknafbg8") (f (quote (("use-mock-crust") ("generate-diagrams" "hyper"))))))

(define-public crate-routing-0.28.0 (c (n "routing") (v "0.28.0") (d (list (d (n "crust") (r "^0.20.1") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "itertools") (r "~0.5.9") (d #t) (k 0)) (d (n "libc") (r "~0.2.20") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "^0.3.0-pre") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.22") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.1.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "03754f73x9d5i2c1rn5bw0fzf2zs004hyzbn6djhzk8xh0dh81zn") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.28.1 (c (n "routing") (v "0.28.1") (d (list (d (n "crust") (r "^0.20.2") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "itertools") (r "~0.5.9") (d #t) (k 0)) (d (n "libc") (r "~0.2.20") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "^0.3.0-pre") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.22") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.1.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1p4rwh12gb1wnwi79gf79lwv2l9iga1pqpk3wmkbp42d1237w3ik") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.28.2 (c (n "routing") (v "0.28.2") (d (list (d (n "crust") (r "~0.22.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "itertools") (r "~0.5.9") (d #t) (k 0)) (d (n "libc") (r "~0.2.20") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "^0.3.0-pre") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.22") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.1.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "0lxdl10z85kiwkb4h9zh5kgc5n9jcsx5izxq80590yc08iwy0qsb") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.28.3 (c (n "routing") (v "0.28.3") (d (list (d (n "crust") (r "~0.23.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "itertools") (r "~0.5.9") (d #t) (k 0)) (d (n "libc") (r "~0.2.20") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.3.1") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.22") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.2.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "0z41xgahn095w3r8czs7iq0i9629lhrqlb89gk3kmsp1xbgn3002") (f (quote (("use-mock-crust")))) (y #t)))

(define-public crate-routing-0.28.4 (c (n "routing") (v "0.28.4") (d (list (d (n "crust") (r "~0.23.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "itertools") (r "~0.5.9") (d #t) (k 0)) (d (n "libc") (r "~0.2.20") (d #t) (k 2)) (d (n "log") (r "~0.3.6") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.10.0") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.3.1") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.1.2") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.22") (d #t) (k 0)) (d (n "term") (r "~0.4.4") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.2.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1q5dkpzjq5g6yzlxja86wihagviwg1xc59yrn2fm7yiprbsxan43") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.28.5 (c (n "routing") (v "0.28.5") (d (list (d (n "accumulator") (r "~0.5.0") (d #t) (k 0)) (d (n "crust") (r "~0.24.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.5.9") (d #t) (k 0)) (d (n "libc") (r "~0.2.21") (d #t) (k 2)) (d (n "log") (r "~0.3.7") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.5.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.11.2") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.3.1") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.2.0") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.23") (d #t) (k 2)) (d (n "serde") (r "~0.9.13") (d #t) (k 0)) (d (n "serde_derive") (r "~0.9.13") (d #t) (k 0)) (d (n "term") (r "~0.4.5") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.2.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "124pbxjxi6hmk0l78jg262ppic2jixmnyk2sly2mhrb54mad2i16") (f (quote (("use-mock-crust"))))))

(define-public crate-routing-0.29.0 (c (n "routing") (v "0.29.0") (d (list (d (n "crust") (r "~0.25.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "fake_clock") (r "~0.1.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.21") (d #t) (k 2)) (d (n "log") (r "~0.3.7") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.6.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.12.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.37") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.4.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.3.0") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.23") (d #t) (k 2)) (d (n "serde") (r "~1.0.6") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.6") (d #t) (k 0)) (d (n "term") (r "~0.4.5") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.2.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1nqc6hnnclk7ywm5nfrpdi4s3an9y737mmapsp9gq42nnwjc3qh2") (f (quote (("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.30.0 (c (n "routing") (v "0.30.0") (d (list (d (n "crust") (r "~0.25.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "fake_clock") (r "~0.1.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.21") (d #t) (k 2)) (d (n "log") (r "~0.3.7") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.6.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.12.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.37") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.4.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.3.0") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.23") (d #t) (k 2)) (d (n "serde") (r "~1.0.6") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.6") (d #t) (k 0)) (d (n "term") (r "~0.4.5") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.2.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1m85pqzad0sp23zfw3k7x7cmx620yfbqvpbcrwsm2w2c389mjc3j") (f (quote (("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.31.0 (c (n "routing") (v "0.31.0") (d (list (d (n "crust") (r "~0.27.0") (d #t) (k 0)) (d (n "docopt") (r "~0.6.86") (d #t) (k 2)) (d (n "fake_clock") (r "~0.1.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.0") (d #t) (k 0)) (d (n "libc") (r "~0.2.21") (d #t) (k 2)) (d (n "log") (r "~0.3.7") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.6.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.13.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.37") (d #t) (k 0)) (d (n "quick-error") (r "~1.1.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.4.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.3.0") (d #t) (k 0)) (d (n "rustc-serialize") (r "~0.3.23") (d #t) (k 2)) (d (n "serde") (r "~1.0.6") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.6") (d #t) (k 0)) (d (n "term") (r "~0.4.5") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.2.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "150baz7r168sclywk599h6xwvjfgayrhybihq7gdqkhqjpkcvhm5") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.32.0 (c (n "routing") (v "0.32.0") (d (list (d (n "config_file_handler") (r "~0.8.0") (d #t) (k 0)) (d (n "crust") (r "~0.28.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.28") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.5.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1ii2gki3v2r1x769ml878g2adf92drn01pi3g5in1f1q43hmn7pk") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.32.1 (c (n "routing") (v "0.32.1") (d (list (d (n "config_file_handler") (r "~0.8.0") (d #t) (k 0)) (d (n "crust") (r "~0.28.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.28") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.5.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1d51ayilggr0sb9qisdh51wkgljmmb5mp2x2dvxfgiqyr8mck8zd") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.32.2 (c (n "routing") (v "0.32.2") (d (list (d (n "config_file_handler") (r "~0.8.0") (d #t) (k 0)) (d (n "crust") (r "~0.28.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.28") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.15") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.5.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1ywn4d1ff4px2cgyqk1brmr44j5fff03yqwi2ns5p15fk1w65hpy") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.33.0 (c (n "routing") (v "0.33.0") (d (list (d (n "config_file_handler") (r "~0.8.1") (d #t) (k 0)) (d (n "crust") (r "~0.28.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.29") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.16") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.5.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1ww6izjcj5klh32p78zczrzx0xxqdxf24dbchhbimlv7rapaxrnc") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.33.1 (c (n "routing") (v "0.33.1") (d (list (d (n "config_file_handler") (r "~0.8.1") (d #t) (k 0)) (d (n "crust") (r "~0.28.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.29") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.16") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.5.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "0v6v8yvi60037bxjsykn87hf8h0b9vfnd9h91q587v6daibnsyn4") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.33.2 (c (n "routing") (v "0.33.2") (d (list (d (n "config_file_handler") (r "~0.8.1") (d #t) (k 0)) (d (n "crust") (r "~0.28.1") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.29") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.16") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.5.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "1ss6wc662ywllap3n5sr8q4n4c8adgx4ma8xavlzsdyh764k5ax7") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.34.0 (c (n "routing") (v "0.34.0") (d (list (d (n "config_file_handler") (r "~0.8.1") (d #t) (k 0)) (d (n "crust") (r "~0.29.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.29") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.14.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.16") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.6.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.11") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.2") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "0qgh962f4q03bv18rr7bpg5invm8x7dhngnn40rzkdfzj07zj8ll") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.35.0 (c (n "routing") (v "0.35.0") (d (list (d (n "config_file_handler") (r "~0.9.0") (d #t) (k 0)) (d (n "crust") (r "~0.30.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.1") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.2.0") (d #t) (k 0)) (d (n "itertools") (r "~0.6.1") (d #t) (k 0)) (d (n "libc") (r "~0.2.29") (d #t) (k 2)) (d (n "log") (r "~0.3.8") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.7.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.15.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.40") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.0") (d #t) (k 0)) (d (n "rand") (r "~0.3.16") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.7.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.25") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.25") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.8") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.1") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "03hxdpypqj3hvd8f2dm6gzp28wp4lch0pn57i8bfkw4y2akbq581") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.36.0 (c (n "routing") (v "0.36.0") (d (list (d (n "config_file_handler") (r "~0.10.0") (d #t) (k 0)) (d (n "crust") (r "~0.30.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.3") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.3.1") (d #t) (k 0)) (d (n "itertools") (r "~0.7.8") (d #t) (k 0)) (d (n "libc") (r "~0.2.40") (d #t) (k 2)) (d (n "log") (r "~0.4.1") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.8.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.15.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.43") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.1") (d #t) (k 0)) (d (n "rand") (r "~0.4.2") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.7.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.37") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.37") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.13") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.1.0") (d #t) (k 0)))) (h "05rldj9c23ccm8hy9rdi3vpz1766h4x6a02680mdq23n0my0d21r") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.37.0 (c (n "routing") (v "0.37.0") (d (list (d (n "config_file_handler") (r "~0.11.0") (d #t) (k 0)) (d (n "crust") (r "~0.31.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.3") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.3.1") (d #t) (k 0)) (d (n "itertools") (r "~0.7.8") (d #t) (k 0)) (d (n "libc") (r "~0.2.40") (d #t) (k 2)) (d (n "log") (r "~0.4.1") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.8.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.16.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.43") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.1") (d #t) (k 0)) (d (n "rand") (r "~0.4.2") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.10.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.37") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.37") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.13") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.2.0") (d #t) (k 0)))) (h "1fdi0i80cjgp1ymhaqvgscg0kv3ksr5hi6qf4n9vbv1x2ihr15zx") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

(define-public crate-routing-0.37.1 (c (n "routing") (v "0.37.1") (d (list (d (n "config_file_handler") (r "~0.11.0") (d #t) (k 0)) (d (n "crust") (r "~0.31.0") (d #t) (k 0)) (d (n "docopt") (r "~0.8.3") (d #t) (k 2)) (d (n "fake_clock") (r "~0.2.0") (d #t) (k 0)) (d (n "hex") (r "~0.3.1") (d #t) (k 0)) (d (n "itertools") (r "~0.7.8") (d #t) (k 0)) (d (n "libc") (r "~0.2.40") (d #t) (k 2)) (d (n "log") (r "~0.4.1") (d #t) (k 0)) (d (n "lru_time_cache") (r "~0.8.0") (d #t) (k 0)) (d (n "maidsafe_utilities") (r "~0.16.0") (d #t) (k 0)) (d (n "num-bigint") (r "~0.1.43") (d #t) (k 0)) (d (n "quick-error") (r "~1.2.1") (d #t) (k 0)) (d (n "rand") (r "~0.4.2") (d #t) (k 0)) (d (n "resource_proof") (r "~0.5.0") (d #t) (k 0)) (d (n "rust_sodium") (r "~0.10.0") (d #t) (k 0)) (d (n "serde") (r "~1.0.37") (d #t) (k 0)) (d (n "serde_derive") (r "~1.0.37") (d #t) (k 0)) (d (n "serde_json") (r "~1.0.13") (d #t) (k 2)) (d (n "term") (r "~0.4.6") (d #t) (k 0)) (d (n "tiny-keccak") (r "~1.3.0") (d #t) (k 0)) (d (n "unwrap") (r "~1.2.0") (d #t) (k 0)))) (h "0qjgcgpv7civszrdczsrawa8kccmbz93ya0kzir0mqgjhiz9s2hi") (f (quote (("use-mock-crypto" "use-mock-crust") ("use-mock-crust" "lru_time_cache/fake_clock"))))))

