(define-module (crates-io wa sm wasmer-singlepass-backend-near) #:use-module (crates-io))

(define-public crate-wasmer-singlepass-backend-near-0.17.1 (c (n "wasmer-singlepass-backend-near") (v "0.17.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "dynasm") (r "^1.0.0") (d #t) (k 0)) (d (n "dynasmrt") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2.68") (d #t) (k 0)) (d (n "nix") (r "^0.15") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "smallvec") (r "^1") (d #t) (k 0)) (d (n "wasmer-runtime-core-near") (r "^0.17.1") (d #t) (k 0)))) (h "0hamd7926him4dpmyma0yfgsfl0s9gmj4p4lwixncncgxx1kbwnk") (f (quote (("deterministic-execution" "wasmer-runtime-core-near/deterministic-execution") ("default"))))))

(define-public crate-wasmer-singlepass-backend-near-0.18.0-pre.1 (c (n "wasmer-singlepass-backend-near") (v "0.18.0-pre.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 0)) (d (n "borsh") (r "^0.9.0") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "dynasm") (r "^1.0.0") (d #t) (k 0)) (d (n "dynasmrt") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2.68") (d #t) (k 0)) (d (n "nix") (r "^0.15") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "smallvec") (r "^1") (d #t) (k 0)) (d (n "wasmer-runtime-core") (r "^0.18.0-pre.1") (d #t) (k 0) (p "wasmer-runtime-core-near")))) (h "17khwykicwrx2ybrmnnig9njy5aa3ygigk4bh29ii5panr5vhqm8") (f (quote (("deterministic-execution" "wasmer-runtime-core/deterministic-execution") ("default"))))))

(define-public crate-wasmer-singlepass-backend-near-0.18.0 (c (n "wasmer-singlepass-backend-near") (v "0.18.0") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 0)) (d (n "borsh") (r "^0.9.0") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "dynasm") (r "^1.0.0") (d #t) (k 0)) (d (n "dynasmrt") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2.68") (d #t) (k 0)) (d (n "nix") (r "^0.15") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "smallvec") (r "^1") (d #t) (k 0)) (d (n "wasmer-runtime-core") (r "^0.18.0") (d #t) (k 0) (p "wasmer-runtime-core-near")))) (h "16vx3j72myg0vcs8h404nq03704c7bkk0jfbcn2g6jm4bpda5vsv") (f (quote (("deterministic-execution" "wasmer-runtime-core/deterministic-execution") ("default"))))))

(define-public crate-wasmer-singlepass-backend-near-0.18.1 (c (n "wasmer-singlepass-backend-near") (v "0.18.1") (d (list (d (n "bincode") (r "^1.2") (d #t) (k 0)) (d (n "borsh") (r "^0.9.0") (d #t) (k 0)) (d (n "byteorder") (r "^1.3") (d #t) (k 0)) (d (n "dynasm") (r "^1.0.0") (d #t) (k 0)) (d (n "dynasmrt") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "libc") (r "^0.2.68") (d #t) (k 0)) (d (n "nix") (r "^0.15") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0") (d #t) (k 0)) (d (n "smallvec") (r "^1") (d #t) (k 0)) (d (n "wasmer-runtime-core") (r "^0.18.1") (d #t) (k 0) (p "wasmer-runtime-core-near")))) (h "1y2ksvff8gclcml5i3zkbqzdm7b4h6z4sv8qg6rgkg60lq5xsvjz") (f (quote (("deterministic-execution" "wasmer-runtime-core/deterministic-execution") ("default"))))))

