(define-module (crates-io sa ma samael) #:use-module (crates-io))

(define-public crate-samael-0.0.1 (c (n "samael") (v "0.0.1") (d (list (d (n "base64") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "quick-xml") (r "^0.17") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "reqwest") (r "^0.10") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "tokio") (r "^0.2") (f (quote ("full"))) (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)))) (h "0akplx089m26b3fgj5i0m1vsq0jpfr70jvmvrri9q6yvw203ca78")))

(define-public crate-samael-0.0.2 (c (n "samael") (v "0.0.2") (d (list (d (n "base64") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "quick-xml") (r "^0.17") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)))) (h "0d7w303x7axjrrmjkvc0ka97yalg56palj2q7dqlp7gc5fkps1wd")))

(define-public crate-samael-0.0.3 (c (n "samael") (v "0.0.3") (d (list (d (n "base64") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "quick-xml") (r "^0.17") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)))) (h "18gv3z6r2idl1qbpmmlb1yggj0i09c7vg2c1k32hhhjgaighdakh")))

(define-public crate-samael-0.0.4 (c (n "samael") (v "0.0.4") (d (list (d (n "base64") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "quick-xml") (r "^0.17") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)))) (h "0031ql8vgfg1m9s6mhzk6lilvps5ycb9d3rfwc2zrivh7aac308y")))

(define-public crate-samael-0.0.5 (c (n "samael") (v "0.0.5") (d (list (d (n "base64") (r "^0.11") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "derive_builder") (r "^0.9.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "quick-xml") (r "^0.17") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)))) (h "1sfs3ns7767ffhsq0314ndiz7x12rg2cb0a1mzjwdk88y4qplh5h")))

(define-public crate-samael-0.0.6 (c (n "samael") (v "0.0.6") (d (list (d (n "base64") (r "^0.12") (d #t) (k 0)) (d (n "bindgen") (r "^0.51.0") (d #t) (k 1)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.9.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.2.13") (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.17.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^0.8.1") (f (quote ("v4"))) (d #t) (k 0)))) (h "1dvnj6y1hpx1j3xqmql2ryd554mz7qdw05bln5j4nbllffhhfvan") (f (quote (("xmlsec" "libc" "lazy_static"))))))

(define-public crate-samael-0.0.7 (c (n "samael") (v "0.0.7") (d (list (d (n "base64") (r "^0.12") (d #t) (k 0)) (d (n "bindgen") (r "^0.51.0") (d #t) (k 1)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.9.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.17.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^0.8.1") (f (quote ("v4"))) (d #t) (k 0)))) (h "1liljiw3ppsxrh7sanan363nd1fr7m9a85vpkhjf54hc0m4g9byp") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.8 (c (n "samael") (v "0.0.8") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bindgen") (r "^0.59.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.10.2") (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.0") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.22.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.6") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^0.8.1") (f (quote ("v4"))) (d #t) (k 0)))) (h "0z3xb9cjxwck4g0j8vb5951hx7081pxpbcmvprxzrm248cwimrsa") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.9 (c (n "samael") (v "0.0.9") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bindgen") (r "^0.60.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.11.2") (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.0") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.23.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.7") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r ">=0.8.0, <2.0.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "1pakwv2fpxcy2rbwlk64psna6jzq82mik0fw6x3p4z93y58z8ky5") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.10 (c (n "samael") (v "0.0.10") (d (list (d (n "base64") (r "^0.21") (d #t) (k 0)) (d (n "bindgen") (r "^0.64.0") (d #t) (k 1)) (d (n "chrono") (r "^0.4") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.12.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.0") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.23.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.7") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r ">=0.8.0, <2.0.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "13cdxv7bd0n481gc6fprsr1k49xfkgg7wpa46zj6d0p8173cmwzw") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.11 (c (n "samael") (v "0.0.11") (d (list (d (n "base64") (r "^0.21.0") (d #t) (k 0)) (d (n "bindgen") (r "^0.65.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.12.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10.0") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.28.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "snafu") (r "^0.7") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^1.3.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "1sl6xh135pfl8lxzwbv0r4ndbmll1szp77x9rhgji6147766fnx8") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.12 (c (n "samael") (v "0.0.12") (d (list (d (n "base64") (r "^0.21.0") (d #t) (k 0)) (d (n "bindgen") (r "^0.65.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.12.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10.0") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.28.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.40") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^1.3.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "0n3rw9v8hv19nmxvy24hcwm8msxrn0s0f306pxx212nrsaxsdwbs") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.13 (c (n "samael") (v "0.0.13") (d (list (d (n "base64") (r "^0.21.0") (d #t) (k 0)) (d (n "bindgen") (r "^0.68.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.12.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10.0") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.30.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.40") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^1.3.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "01ka475zcdv9c2cd9jjbz9lbviwgyy2k5qghhw2avm7bjhz6lmbx") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.14 (c (n "samael") (v "0.0.14") (d (list (d (n "base64") (r "^0.21.0") (d #t) (k 0)) (d (n "bindgen") (r "^0.69.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.12.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10.0") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.30.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.40") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^1.3.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "1x24yyn5646h2dh0z3d9d5d9v307306j777n1by50755sjm86mdp") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

(define-public crate-samael-0.0.15 (c (n "samael") (v "0.0.15") (d (list (d (n "base64") (r "^0.22.0") (d #t) (k 0)) (d (n "bindgen") (r "^0.69.1") (d #t) (k 1)) (d (n "chrono") (r "^0.4.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "data-encoding") (r "^2.2.0") (d #t) (k 0)) (d (n "derive_builder") (r "^0.20.0") (d #t) (k 0)) (d (n "flate2") (r "^1.0.0") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2.66") (o #t) (d #t) (k 0)) (d (n "libxml") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "openssl") (r "^0.10.0") (d #t) (k 0)) (d (n "openssl-probe") (r "^0.1.2") (d #t) (k 0)) (d (n "openssl-sys") (r "^0.9.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3.17") (d #t) (k 1)) (d (n "quick-xml") (r "^0.31.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1.0.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "thiserror") (r "^1.0.40") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)) (d (n "uuid") (r "^1.3.0") (f (quote ("v4"))) (d #t) (k 0)))) (h "1bqysy1fb1r74zhalj3909k262mxglv9lc183rl6f1sw26i65a2x") (f (quote (("xmlsec" "libc" "lazy_static" "libxml"))))))

