(define-module (crates-io sp ir spirit-daemonize) #:use-module (crates-io))

(define-public crate-spirit-daemonize-0.1.0 (c (n "spirit-daemonize") (v "0.1.0") (d (list (d (n "failure") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.11") (d #t) (k 0)) (d (n "privdrop") (r "~0.2") (d #t) (k 0)) (d (n "serde") (r "~1") (d #t) (k 0)) (d (n "serde_derive") (r "~1") (d #t) (k 0)) (d (n "spirit") (r "~0.2") (d #t) (k 0)) (d (n "structopt") (r "~0.2") (d #t) (k 0)) (d (n "version-sync") (r "~0.5") (d #t) (k 2)))) (h "00q4fgjm31g5wbj3s78jahg4p6mw6wzkcd64imchd3ksjgr3k7ap")))

(define-public crate-spirit-daemonize-0.1.1 (c (n "spirit-daemonize") (v "0.1.1") (d (list (d (n "failure") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.11") (d #t) (k 0)) (d (n "privdrop") (r "~0.2") (d #t) (k 0)) (d (n "serde") (r "~1") (d #t) (k 0)) (d (n "serde_derive") (r "~1") (d #t) (k 0)) (d (n "spirit") (r "~0.2") (d #t) (k 0)) (d (n "structopt") (r "~0.2") (d #t) (k 0)) (d (n "version-sync") (r "~0.5") (d #t) (k 2)))) (h "1sn3xh1nv1xpspsr00nlk02a23s1iwfq08knr4agwjqgsws7gw99")))

(define-public crate-spirit-daemonize-0.1.2 (c (n "spirit-daemonize") (v "0.1.2") (d (list (d (n "failure") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.11") (d #t) (k 0)) (d (n "privdrop") (r "~0.2") (d #t) (k 0)) (d (n "serde") (r "~1") (d #t) (k 0)) (d (n "serde_derive") (r "~1") (d #t) (k 0)) (d (n "spirit") (r "~0.2") (k 0)) (d (n "structopt") (r "~0.2") (d #t) (k 0)) (d (n "version-sync") (r "~0.5") (d #t) (k 2)))) (h "003n639slbw8yhcsippkzlrhsdydmyghz6iwmyvisrn787waakzw")))

(define-public crate-spirit-daemonize-0.1.3 (c (n "spirit-daemonize") (v "0.1.3") (d (list (d (n "failure") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.11") (d #t) (k 0)) (d (n "privdrop") (r "~0.2") (d #t) (k 0)) (d (n "serde") (r "~1") (d #t) (k 0)) (d (n "serde_derive") (r "~1") (d #t) (k 0)) (d (n "spirit") (r "~0.2") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.2") (d #t) (k 0)) (d (n "version-sync") (r "~0.6") (d #t) (k 2)))) (h "039011zgf7nidw0481c89yxzqfa9fdldckp2r884c4dgkyra0h23") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.2.0 (c (n "spirit-daemonize") (v "0.2.0") (d (list (d (n "failure") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.13") (d #t) (k 0)) (d (n "privdrop") (r "~0.2") (d #t) (k 0)) (d (n "serde") (r "~1") (d #t) (k 0)) (d (n "serde_derive") (r "~1") (d #t) (k 0)) (d (n "spirit") (r "~0.3") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.2") (d #t) (k 0)) (d (n "version-sync") (r "~0.7") (d #t) (k 2)))) (h "0zp03lpxb1qhb89sl0awn74kj566bzx8mbm2fmb6v5m683bv3pwh") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.2.1 (c (n "spirit-daemonize") (v "0.2.1") (d (list (d (n "failure") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.13") (d #t) (k 0)) (d (n "privdrop") (r "~0.2") (d #t) (k 0)) (d (n "serde") (r "~1") (d #t) (k 0)) (d (n "serde_derive") (r "~1") (d #t) (k 0)) (d (n "spirit") (r "~0.3") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.2") (d #t) (k 0)) (d (n "version-sync") (r "~0.7") (d #t) (k 2)))) (h "0793qg768wbj0dd32mrg2x3chg5k1732nl462g65xgsdsjq7n2m0") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.3.0 (c (n "spirit-daemonize") (v "0.3.0") (d (list (d (n "err-context") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.15") (d #t) (k 0)) (d (n "privdrop") (r "~0.3") (d #t) (k 0)) (d (n "serde") (r "~1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "spirit") (r "~0.4") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.3") (k 0)) (d (n "version-sync") (r "~0.8") (d #t) (k 2)))) (h "0jb7qr8qx4xhwjqf5p4q6abvvj1zrbqwkq0b863w2bid8zx73rp5") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.3.1 (c (n "spirit-daemonize") (v "0.3.1") (d (list (d (n "err-context") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.17") (d #t) (k 0)) (d (n "privdrop") (r "~0.3") (d #t) (k 0)) (d (n "serde") (r "~1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "spirit") (r "~0.4") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.3") (k 0)) (d (n "version-sync") (r "~0.9") (d #t) (k 2)))) (h "0rg2pb3cpfhc53js4d6v49nim9zmjznzs97351wsi4qvwbgka794") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.3.2 (c (n "spirit-daemonize") (v "0.3.2") (d (list (d (n "err-context") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.18") (d #t) (k 0)) (d (n "privdrop") (r "~0.3") (d #t) (k 0)) (d (n "serde") (r "~1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "spirit") (r "~0.4") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.3") (k 0)) (d (n "version-sync") (r "~0.9") (d #t) (k 2)))) (h "0r77l56qm0v3957lg16z2f8vdmcm7yzs1hqmc2bj00y641hvw2qr") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.4.0 (c (n "spirit-daemonize") (v "0.4.0") (d (list (d (n "err-context") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.18") (d #t) (k 0)) (d (n "privdrop") (r "~0.3") (d #t) (k 0)) (d (n "serde") (r "~1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "spirit") (r "~0.4") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.3") (k 0)) (d (n "version-sync") (r "~0.9") (d #t) (k 2)))) (h "1wx1dbmnd1h2hs3kpfpz1jrmdpingwcj6m46y4zkwqpq58j05mry") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.5.0 (c (n "spirit-daemonize") (v "0.5.0") (d (list (d (n "err-context") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.18") (d #t) (k 0)) (d (n "privdrop") (r "~0.3") (d #t) (k 0)) (d (n "serde") (r "~1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "spirit") (r "~0.4") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.3") (k 0)))) (h "0d28b1jqzavg2j4ysl1l510y3vs09mm11rf9g42c4i47fb2rsqf3") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

(define-public crate-spirit-daemonize-0.5.1 (c (n "spirit-daemonize") (v "0.5.1") (d (list (d (n "err-context") (r "~0.1") (d #t) (k 0)) (d (n "log") (r "~0.4") (d #t) (k 0)) (d (n "nix") (r "~0.23") (d #t) (k 0)) (d (n "privdrop") (r "~0.5") (d #t) (k 0)) (d (n "serde") (r "~1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "spirit") (r "~0.4") (k 0)) (d (n "structdoc") (r "~0.1") (o #t) (d #t) (k 0)) (d (n "structopt") (r "~0.3") (k 0)))) (h "14w53zwfa5b2xzmsqm5ds3450z92khm59wsgrvv51hn0453rnb5y") (f (quote (("default" "cfg-help") ("cfg-help" "spirit/cfg-help" "structdoc"))))))

