(define-module (crates-io ea ip eaip) #:use-module (crates-io))

(define-public crate-eaip-0.1.0 (c (n "eaip") (v "0.1.0") (d (list (d (n "airac") (r "^0.1") (d #t) (k 0)) (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "ego-tree") (r "^0.6.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "pretty_env_logger") (r "^0.4") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (d #t) (k 0)) (d (n "scraper") (r "^0.13") (d #t) (k 0)) (d (n "table-extract") (r "^0.2") (d #t) (k 0)) (d (n "tokio") (r "^1.18") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.2") (d #t) (k 0)))) (h "1jg88g7l37myqmfsgrwksdysx48rwjkz3qn80qhb13dw0gdxy9br") (f (quote (("examples" "tokio" "tokio/rt" "tokio/rt-multi-thread" "tokio/macros" "pretty_env_logger"))))))

(define-public crate-eaip-0.2.0 (c (n "eaip") (v "0.2.0") (d (list (d (n "airac") (r "^0.1") (d #t) (k 0)) (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "ego-tree") (r "^0.6.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "pretty_env_logger") (r "^0.4") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (d #t) (k 0)) (d (n "scraper") (r "^0.13") (d #t) (k 0)) (d (n "table-extract") (r "^0.2") (d #t) (k 0)) (d (n "tokio") (r "^1.18") (o #t) (d #t) (k 0)) (d (n "url") (r "^2.2") (d #t) (k 0)))) (h "005lfrqnqvyg032raji6rnj4829jcx8dphl367bzwm4h964fg3c4") (f (quote (("examples" "tokio" "tokio/rt" "tokio/rt-multi-thread" "tokio/macros" "pretty_env_logger"))))))

(define-public crate-eaip-0.4.0 (c (n "eaip") (v "0.4.0") (d (list (d (n "airac") (r "^0.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.57") (o #t) (d #t) (k 0)) (d (n "anyhow") (r "^1.0.57") (d #t) (k 2)) (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "ego-tree") (r "^0.6.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "pretty_env_logger") (r "^0.4") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (d #t) (k 0)) (d (n "scraper") (r "^0.13") (d #t) (k 0)) (d (n "tokio") (r "^1.18") (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.18") (f (quote ("rt" "rt-multi-thread" "macros"))) (d #t) (k 2)) (d (n "url") (r "^2.2") (d #t) (k 0)))) (h "01gwrp8kvvkfmlnisnjihx3gvsdr19mivq1llclm8vbj8sg45ysy") (f (quote (("test-online") ("examples" "tokio" "tokio/rt" "tokio/rt-multi-thread" "tokio/macros" "pretty_env_logger" "anyhow"))))))

(define-public crate-eaip-0.5.0 (c (n "eaip") (v "0.5.0") (d (list (d (n "airac") (r "^0.1") (d #t) (k 0)) (d (n "anyhow") (r "^1.0.57") (o #t) (d #t) (k 0)) (d (n "anyhow") (r "^1.0.57") (d #t) (k 2)) (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "chrono") (r "^0.4.19") (d #t) (k 0)) (d (n "ego-tree") (r "^0.6.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.4") (d #t) (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "pretty_env_logger") (r "^0.4") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.5") (d #t) (k 0)) (d (n "reqwest") (r "^0.11") (d #t) (k 0)) (d (n "scraper") (r "^0.13") (d #t) (k 0)) (d (n "tokio") (r "^1.18") (o #t) (d #t) (k 0)) (d (n "tokio") (r "^1.18") (f (quote ("rt" "rt-multi-thread" "macros"))) (d #t) (k 2)) (d (n "url") (r "^2.2") (d #t) (k 0)))) (h "1dc3nlcf999zhz0v1lilxpwkx1c6nfwkprsc99zxmcwvwl9n3021") (f (quote (("test-online") ("examples" "tokio" "tokio/rt" "tokio/rt-multi-thread" "tokio/macros" "pretty_env_logger" "anyhow"))))))

