(define-module (crates-io au to autogenerated-assimp-sys) #:use-module (crates-io))

(define-public crate-autogenerated-assimp-sys-0.1.0 (c (n "autogenerated-assimp-sys") (v "0.1.0") (d (list (d (n "bindgen") (r "^0.54") (d #t) (k 1)) (d (n "cmake") (r "^0.1") (d #t) (k 1)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3") (d #t) (k 1)))) (h "0770h8m84racnibawyx0lxydi6rwcjd7x03rd4lwwfr2hyd7zvn6") (l "assimp")))

(define-public crate-autogenerated-assimp-sys-0.1.1 (c (n "autogenerated-assimp-sys") (v "0.1.1") (d (list (d (n "bindgen") (r "^0.54") (d #t) (k 1)) (d (n "cmake") (r "^0.1") (d #t) (k 1)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3") (d #t) (k 1)))) (h "1iyb9cnn2krs7b8qxz09pfhdvp6xzvkp89g8bi22kq7rsgwdaf41") (l "assimp")))

(define-public crate-autogenerated-assimp-sys-0.1.2 (c (n "autogenerated-assimp-sys") (v "0.1.2") (d (list (d (n "bindgen") (r "^0.54") (d #t) (k 1)) (d (n "cmake") (r "^0.1") (d #t) (k 1)) (d (n "libz-sys") (r "^1.0") (d #t) (k 0)) (d (n "pkg-config") (r "^0.3") (d #t) (k 1)))) (h "1rb35zmdasimrjbckl7p5mfcl14s2zp27l53qdvw54nv8yzk648k") (l "assimp")))

