(define-module (crates-io st ic sticker) #:use-module (crates-io))

(define-public crate-sticker-0.5.1 (c (n "sticker") (v "0.5.1") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.11") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.7.1") (d #t) (k 0)) (d (n "flate2") (r "^1") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "ndarray") (r "^0.12") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.1.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)))) (h "16kvrgwd7hqscgnq0kpwnnpffvlg9fijda4jcqsbslsxnxh06y5p")))

(define-public crate-sticker-0.6.0 (c (n "sticker") (v "0.6.0") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.11") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.7.1") (d #t) (k 0)) (d (n "flate2") (r "^1") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "ndarray") (r "^0.12") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.6.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)))) (h "1snsm7r9v9aw482fd4wy2xd528frr68ppf6ykhcg7zzbn238wg34")))

(define-public crate-sticker-0.7.0 (c (n "sticker") (v "0.7.0") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.11") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.10.1") (d #t) (k 0)) (d (n "flate2") (r ">= 1.0.0, < 1.0.10") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "ndarray") (r "^0.12") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.7.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)))) (h "1j21wiw80gkpzqrwd8wncjddwj7sbm2cw582ndj01yyxyr579pbr")))

(define-public crate-sticker-0.8.0 (c (n "sticker") (v "0.8.0") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.10.1") (d #t) (k 0)) (d (n "flate2") (r ">= 1.0.0, < 1.0.10") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "ndarray") (r "^0.12") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.7.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)))) (h "18bzpy89681m26vc4k662rhwxz8cn4khav9vq13kq8fgb4hwx2z1")))

(define-public crate-sticker-0.9.0 (c (n "sticker") (v "0.9.0") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.10.1") (d #t) (k 0)) (d (n "flate2") (r ">= 1.0.0, < 1.0.10") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "ndarray") (r "^0.12") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.7.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)))) (h "0arssp307m065wbpswk36x73ssjjdbixcj7zd5qp3rf8c0q9rzbi")))

(define-public crate-sticker-0.10.0 (c (n "sticker") (v "0.10.0") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.10.1") (d #t) (k 0)) (d (n "flate2") (r ">= 1.0.0, < 1.0.10") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "ndarray") (r "^0.12") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_cbor") (r "^0.10") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.10.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)) (d (n "toml") (r "^0.5") (d #t) (k 0)))) (h "04xn1k2irvspzn577ydra9lwymidbdw4ff5jwjfv7aazmr9z6bym")))

(define-public crate-sticker-0.11.0 (c (n "sticker") (v "0.11.0") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.11") (d #t) (k 0)) (d (n "flate2") (r ">= 1.0.0, < 1.0.10") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "ndarray") (r "^0.13") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.3") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "rand_xorshift") (r "^0.2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_cbor") (r "^0.10") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-encoders") (r "^0.1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.11.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)) (d (n "toml") (r "^0.5") (d #t) (k 0)))) (h "17f975w6h5njgjdjxp9z3vdv3z4ilgv5468lp7snm6dqyzh1rahl")))

(define-public crate-sticker-0.11.1 (c (n "sticker") (v "0.11.1") (d (list (d (n "approx") (r "^0.3") (d #t) (k 2)) (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "finalfusion") (r "^0.12") (d #t) (k 0)) (d (n "flate2") (r ">=1.0.0, <1.0.10") (d #t) (k 2)) (d (n "itertools") (r "^0.8") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "ndarray") (r "^0.13") (d #t) (k 0)) (d (n "ndarray-tensorflow") (r "^0.3") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "protobuf") (r "^2") (d #t) (k 0)) (d (n "rand") (r "^0.7") (d #t) (k 0)) (d (n "rand_xorshift") (r "^0.2") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_cbor") (r "^0.10") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "sticker-encoders") (r "^0.1") (d #t) (k 0)) (d (n "sticker-tf-proto") (r "^0.11.0") (d #t) (k 0)) (d (n "tensorflow") (r "^0.13") (d #t) (k 0)) (d (n "toml") (r "^0.5") (d #t) (k 0)))) (h "0zc8ir0ijfyskh30067icbinmx71imys4mpjzzc0lm6av8pg6yw4")))

