(define-module (crates-io st ic sticker-encoders) #:use-module (crates-io))

(define-public crate-sticker-encoders-0.1.0 (c (n "sticker-encoders") (v "0.1.0") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "0rqzrl8bxbv8fbg089fhfg6cqphgpwgjlla84mhhllaj7kdcw0rn")))

(define-public crate-sticker-encoders-0.1.1 (c (n "sticker-encoders") (v "0.1.1") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "1zbr277p3ri9wmr4iwcjfz4kxyw1wcrk8s2bjvib23mx7zfnmxhx")))

(define-public crate-sticker-encoders-0.1.2 (c (n "sticker-encoders") (v "0.1.2") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "1dp3sr3g9ak8igwn5h0m8r1ljg4karmvixdkydk2s91rwx01nxza")))

(define-public crate-sticker-encoders-0.1.3 (c (n "sticker-encoders") (v "0.1.3") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "1dhnp44wwgi7gbq9rlrv4sqcvqji2gi54gwq17nls0bhzcbh1mbr")))

(define-public crate-sticker-encoders-0.1.4 (c (n "sticker-encoders") (v "0.1.4") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "19488magv0w5cm0d7ljgynrcwkx350hsls5nj3gsy9y75f38z3mi")))

(define-public crate-sticker-encoders-0.2.0 (c (n "sticker-encoders") (v "0.2.0") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "19v1lp9ah7vhxd87bh0ld7iqx1jda1bdjg2cvyvg6ckj64b7ippp")))

(define-public crate-sticker-encoders-0.3.0 (c (n "sticker-encoders") (v "0.3.0") (d (list (d (n "conllu") (r "^0.3") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "0b1pqkpyag0sshxjwk2slgkm517x7rinjg850kyssmp0wri3rdpy")))

(define-public crate-sticker-encoders-0.3.1 (c (n "sticker-encoders") (v "0.3.1") (d (list (d (n "conllu") (r "^0.3") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "14fqccnhqlxi55r35zm91r23849j8ks3wpbw0syrf46wfal40bjh")))

(define-public crate-sticker-encoders-0.2.1 (c (n "sticker-encoders") (v "0.2.1") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "0mxyb2sdy0agrksrh0avdrhscpzkw9cdkb2hlxn184v83a36lf1y")))

(define-public crate-sticker-encoders-0.3.2 (c (n "sticker-encoders") (v "0.3.2") (d (list (d (n "conllu") (r "^0.3") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "1fbksi5lm3zcq3zlg3gq97zd43y8k5r1y5fvlv0vshiafb4kdfrz")))

(define-public crate-sticker-encoders-0.1.5 (c (n "sticker-encoders") (v "0.1.5") (d (list (d (n "conllx") (r "^0.12.1") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "failure") (r "^0.1") (d #t) (k 0)) (d (n "numberer") (r "^0.1") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)))) (h "1igr9q4yxd01bkgx5f79pf8721vzyxdrxa6pjnzcp6jrszdk6rhz")))

(define-public crate-sticker-encoders-0.4.0 (c (n "sticker-encoders") (v "0.4.0") (d (list (d (n "conllu") (r "^0.3") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "numberer") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.4") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "0i2n3a03yqrpa4pp7cvyg1lvd4sc623dlh2a8w8xxdhjvigwkrsy")))

(define-public crate-sticker-encoders-0.5.0 (c (n "sticker-encoders") (v "0.5.0") (d (list (d (n "conllu") (r "^0.5") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "numberer") (r "^0.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "1s9ddx6dirdqfy589f96jx9353hyyh1sb321n4xq460sdiz2m5kv")))

(define-public crate-sticker-encoders-0.5.1 (c (n "sticker-encoders") (v "0.5.1") (d (list (d (n "conllu") (r "^0.5") (d #t) (k 0)) (d (n "edit_tree") (r "^0.1.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "numberer") (r "^0.2") (d #t) (k 0)) (d (n "ohnomore") (r "^0.2.2") (d #t) (k 0)) (d (n "ordered-float") (r "^1") (d #t) (k 0)) (d (n "petgraph") (r "^0.5") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "thiserror") (r "^1") (d #t) (k 0)))) (h "0fb5xcy211mp6gn6x4jm8mxvr4kyrnpyjw8dzrgq1byh3ssi91c2")))

