(define-module (crates-io vc on vcontrol) #:use-module (crates-io))

(define-public crate-vcontrol-0.1.0 (c (n "vcontrol") (v "0.1.0") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "clap") (r "^2.32") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 0)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.3.0") (f (quote ("serde_yaml"))) (d #t) (k 0)))) (h "16nmvpg7nlh2crq2ka7x8km29ic5ah9gnpn0p5nxvjc5s094h098") (f (quote (("cli" "clap"))))))

(define-public crate-vcontrol-0.2.0 (c (n "vcontrol") (v "0.2.0") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 1)) (d (n "clap") (r "^2.32") (o #t) (d #t) (k 0)) (d (n "phf") (r "^0.7") (d #t) (k 0)) (d (n "phf") (r "^0.7") (d #t) (k 1)) (d (n "phf_codegen") (r "^0.7") (d #t) (k 1)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 1)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 1)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 1)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.3.0") (f (quote ("serde_yaml"))) (d #t) (k 1)))) (h "1qlxb9l5q54ikbwnxrzzri4rhav788zg7cwbcm00z483laf4jgj6") (f (quote (("cli" "clap"))))))

(define-public crate-vcontrol-0.3.0 (c (n "vcontrol") (v "0.3.0") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 1)) (d (n "clap") (r "^2.32") (o #t) (d #t) (k 0)) (d (n "phf") (r "^0.7") (d #t) (k 0)) (d (n "phf") (r "^0.7") (d #t) (k 1)) (d (n "phf_codegen") (r "^0.7") (d #t) (k 1)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 1)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 1)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 1)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.3.0") (f (quote ("serde_yaml"))) (d #t) (k 1)))) (h "1xdrhfdy3c1r4q7xbj7vsqf2vfjyc7999mhlzbfpd9vdj8hba9sg") (f (quote (("cli" "clap"))))))

(define-public crate-vcontrol-0.3.1 (c (n "vcontrol") (v "0.3.1") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 1)) (d (n "clap") (r "^2.32") (o #t) (d #t) (k 0)) (d (n "phf") (r "^0.7") (d #t) (k 0)) (d (n "phf") (r "^0.7") (d #t) (k 1)) (d (n "phf_codegen") (r "^0.7") (d #t) (k 1)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 1)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 1)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 1)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.3.0") (f (quote ("serde_yaml"))) (d #t) (k 1)))) (h "11ndlbf2wqbjpvr8k8hr82mnlwjapgwwajz915mv0gqwyv0n88z4") (f (quote (("cli" "clap"))))))

(define-public crate-vcontrol-0.3.2 (c (n "vcontrol") (v "0.3.2") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 1)) (d (n "clap") (r "^2.33") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (t "cfg(unix)") (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "phf") (r "^0.8") (d #t) (k 0)) (d (n "phf_codegen") (r "^0.8") (d #t) (k 1)) (d (n "phf_shared") (r "^0.8") (d #t) (k 0)) (d (n "phf_shared") (r "^0.8") (d #t) (k 1)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 1)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 1)) (d (n "serde_json") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 1)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.4.0") (f (quote ("serde_yaml"))) (d #t) (k 1)))) (h "0s6xva2k4mcikksn34902n696d8vhgp9axdmp3214wkqg3bhwqji") (f (quote (("cli" "clap" "serde_json"))))))

(define-public crate-vcontrol-0.3.3 (c (n "vcontrol") (v "0.3.3") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 1)) (d (n "clap") (r "^2.33") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (t "cfg(unix)") (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "phf") (r "^0.8") (d #t) (k 0)) (d (n "phf_codegen") (r "^0.8") (d #t) (k 1)) (d (n "phf_shared") (r "^0.8") (d #t) (k 0)) (d (n "phf_shared") (r "^0.8") (d #t) (k 1)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 1)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 1)) (d (n "serde_json") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 1)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.4.0") (f (quote ("serde_yaml"))) (d #t) (k 1)))) (h "03rhnz67sqamr4idw28jf9vy6wglbbamynz24njdndi75wdd75z1") (f (quote (("cli" "clap" "serde_json"))))))

(define-public crate-vcontrol-0.3.4 (c (n "vcontrol") (v "0.3.4") (d (list (d (n "chrono") (r "^0.4") (d #t) (k 0)) (d (n "chrono") (r "^0.4") (d #t) (k 1)) (d (n "clap") (r "^2.33") (o #t) (d #t) (k 0)) (d (n "libc") (r "^0.2") (d #t) (t "cfg(unix)") (k 0)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "phf") (r "^0.8") (d #t) (k 0)) (d (n "phf_codegen") (r "^0.8") (d #t) (k 1)) (d (n "phf_shared") (r "^0.8") (d #t) (k 0)) (d (n "phf_shared") (r "^0.8") (d #t) (k 1)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 1)) (d (n "serde_derive") (r "^1") (d #t) (k 0)) (d (n "serde_derive") (r "^1") (d #t) (k 1)) (d (n "serde_json") (r "^1") (o #t) (d #t) (k 0)) (d (n "serde_yaml") (r "^0.8") (d #t) (k 1)) (d (n "serial") (r "^0.4") (d #t) (k 0)) (d (n "serial-core") (r "^0.4") (d #t) (k 0)) (d (n "yaml-merge-keys") (r "^0.4.0") (f (quote ("serde_yaml"))) (d #t) (k 1)))) (h "0p5szykm4b1hgnfnhwqsza8aynlpjaldpq1zmxg1wgrwpfjczhf5") (f (quote (("cli" "clap" "serde_json"))))))

