(define-module (crates-io ru so rusoto_codepipeline) #:use-module (crates-io))

(define-public crate-rusoto_codepipeline-0.25.0 (c (n "rusoto_codepipeline") (v "0.25.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.25.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.24.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1hrfllm1vbwf44yvdl48wfhvk62cndd993jc2w3iiw3pzalaqwf3")))

(define-public crate-rusoto_codepipeline-0.26.0 (c (n "rusoto_codepipeline") (v "0.26.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.26.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.24.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1xrf4w2qr3yyvf9r91brgbnsjrx38zmf5h5mpqp0aqzjifxf4j1q")))

(define-public crate-rusoto_codepipeline-0.27.0 (c (n "rusoto_codepipeline") (v "0.27.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.27.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.25.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1m1pk40ca5zhf150jk16jfk0zq8bzzkgy9aiclfvmylh981g03ff")))

(define-public crate-rusoto_codepipeline-0.28.0 (c (n "rusoto_codepipeline") (v "0.28.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.28.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.25.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1f0vvfx5cyisidxpdk0wcdyd5j4jjgy2qas19n3wfggz87kg9c2j")))

(define-public crate-rusoto_codepipeline-0.29.0 (c (n "rusoto_codepipeline") (v "0.29.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.29.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.25.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "00cqxf44z7lcqq3si63zjjgj16yzlssqk14mxb6bfr3kmivhi2d0")))

(define-public crate-rusoto_codepipeline-0.30.0 (c (n "rusoto_codepipeline") (v "0.30.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.30.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.25.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "0y1w51igfxnvjh5rxdylyfzsnv51dwsaiksaryfbfff1mzw8k1mj")))

(define-public crate-rusoto_codepipeline-0.31.0 (c (n "rusoto_codepipeline") (v "0.31.0") (d (list (d (n "hyper") (r "^0.10.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.31.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.25.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "0g2l62n76fnyhkns11jb04xn2q7b4q7m6ax76ahf4caykda66fbr")))

(define-public crate-rusoto_codepipeline-0.32.0 (c (n "rusoto_codepipeline") (v "0.32.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "hyper") (r "^0.11.0") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.32.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.26.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)) (d (n "tokio-core") (r "^0.1.10") (d #t) (k 0)))) (h "1pibir6n4hs6cm03asdlwh7y822mp5dvjx61p5vmwjc4armmibn3")))

(define-public crate-rusoto_codepipeline-0.33.0 (c (n "rusoto_codepipeline") (v "0.33.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.33.0") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.26.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "186av62053sic5044dg81dilkdccdkbc9dpqbx62s01k62jp553a")))

(define-public crate-rusoto_codepipeline-0.33.1 (c (n "rusoto_codepipeline") (v "0.33.1") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.33.1") (d #t) (k 0)) (d (n "rusoto_mock") (r "^0.27.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1pdmlspn4rc03p43fh64k0qfwkwbpnyhiv1ghzf94cb7g6grxga1")))

(define-public crate-rusoto_codepipeline-0.34.0 (c (n "rusoto_codepipeline") (v "0.34.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.34.0") (k 0)) (d (n "rusoto_mock") (r "^0.28.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "0vsjm9aa8hvmqcahnywf4g9gsvp8gwb23kp5d4hh5nga9zfv3x01") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.35.0 (c (n "rusoto_codepipeline") (v "0.35.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.35.0") (k 0)) (d (n "rusoto_mock") (r "^0.29.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1d5hw7q49rplg4xs67n8l592nglm5m8gjyy1acb5pg03bghpi6sy") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.36.0 (c (n "rusoto_codepipeline") (v "0.36.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.36.0") (k 0)) (d (n "rusoto_mock") (r "^0.30.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "0ssykq1lz8l42l0fswpssyk7qj7q3fhdhx3pdwwpq3hcp14r2p9x") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.37.0 (c (n "rusoto_codepipeline") (v "0.37.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.37.0") (k 0)) (d (n "rusoto_mock") (r "^0.31.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1lrwgsb49fkzxh9nm0f7069a6ahh6wy42aipnzc4jyzfz6p6mpz4") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.38.0 (c (n "rusoto_codepipeline") (v "0.38.0") (d (list (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.38.0") (k 0)) (d (n "rusoto_mock") (r "^0.31.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "0r54fr6j35hnigwkfpc49x9c1xwrfkfp3cfk7m3vg6bvdcr25x48") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.39.0 (c (n "rusoto_codepipeline") (v "0.39.0") (d (list (d (n "bytes") (r "^0.4.12") (d #t) (k 0)) (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.39.0") (k 0)) (d (n "rusoto_mock") (r "^0.39.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "0bm8sjn1w14g4bnl8wz19jqyr7aczr1swawjgzkqdhppbyddd58c") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.40.0 (c (n "rusoto_codepipeline") (v "0.40.0") (d (list (d (n "bytes") (r "^0.4.12") (d #t) (k 0)) (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.40.0") (k 0)) (d (n "rusoto_mock") (r "^0.40.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1agvhc3a52d179kmzijl9r4cidzy2a3wni64kw7bpr3zhq5g4byq") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.41.0 (c (n "rusoto_codepipeline") (v "0.41.0") (d (list (d (n "bytes") (r "^0.4.12") (d #t) (k 0)) (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.41.0") (k 0)) (d (n "rusoto_mock") (r "^0.41.0") (d #t) (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1kd0bnhir5yvjcrvi5h99fg2pvja4xlzlvp9zh0g8mfg7rgdig47") (f (quote (("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.42.0 (c (n "rusoto_codepipeline") (v "0.42.0") (d (list (d (n "bytes") (r "^0.4.12") (d #t) (k 0)) (d (n "futures") (r "^0.1.16") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.42.0") (k 0)) (d (n "rusoto_mock") (r "^0.42.0") (k 2)) (d (n "serde") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.2") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.1") (d #t) (k 0)))) (h "1ab3k1qmv3dhqwf5yf3lyw4bvnp10qh56wgj949yhqp4zlcr71wq") (f (quote (("serialize_structs") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.43.0-beta.1 (c (n "rusoto_codepipeline") (v "0.43.0-beta.1") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.43.0-beta.1") (k 0)) (d (n "rusoto_mock") (r "^0.43.0-beta.1") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2") (d #t) (k 2)))) (h "0sbma7s4d1kvixvjm5k3nhf9j9r09ra06qhqflx5ciy9d1afs3jm") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.43.0 (c (n "rusoto_codepipeline") (v "0.43.0") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.43.0") (k 0)) (d (n "rusoto_mock") (r "^0.43.0") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2") (d #t) (k 2)))) (h "0rh0hiwkgi5yl9rkvmg0ay4h88ijghgnfxa11mbln7x0py4wgcgj") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.44.0 (c (n "rusoto_codepipeline") (v "0.44.0") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.44.0") (k 0)) (d (n "rusoto_mock") (r "^0.44.0") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2") (d #t) (k 2)))) (h "0fcma94fazih98k0h8ywplcn86fkxg885cvmy5jf3i4bbga4zlc4") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.45.0 (c (n "rusoto_codepipeline") (v "0.45.0") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^0.5") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.45.0") (k 0)) (d (n "rusoto_mock") (r "^0.45.0") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^0.2") (d #t) (k 2)))) (h "0anvd1xwcsvhr028r1m76s9a49bi5k20yxaigcv4vnza6i6r72yp") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.46.0 (c (n "rusoto_codepipeline") (v "0.46.0") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.46.0") (k 0)) (d (n "rusoto_mock") (r "^0.46.0") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (d #t) (k 2)))) (h "0yzysz1qy6kibzd8wsrgpk3l5xqkhpgqlxv88brnm2k9d2ja5ygb") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.47.0 (c (n "rusoto_codepipeline") (v "0.47.0") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.47.0") (k 0)) (d (n "rusoto_mock") (r "^0.47.0") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (d #t) (k 2)))) (h "15637pak1wnqj2z5f1y7ib4mjwpmvg2skkwzbcyzrkl9ps1zds3r") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

(define-public crate-rusoto_codepipeline-0.48.0 (c (n "rusoto_codepipeline") (v "0.48.0") (d (list (d (n "async-trait") (r "^0.1") (d #t) (k 0)) (d (n "bytes") (r "^1.0") (d #t) (k 0)) (d (n "futures") (r "^0.3") (d #t) (k 0)) (d (n "rusoto_core") (r "^0.48.0") (k 0)) (d (n "rusoto_mock") (r "^0.48.0") (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0") (d #t) (k 0)) (d (n "tokio") (r "^1.0") (d #t) (k 2)))) (h "0ahzb04ny9lmiryy8nvqx2mrkyj00n2x3zc8f1irk450n1ab39p0") (f (quote (("serialize_structs" "bytes/serde") ("rustls" "rusoto_core/rustls") ("native-tls" "rusoto_core/native-tls") ("deserialize_structs" "bytes/serde") ("default" "native-tls"))))))

