(define-module (crates-io jx l- jxl-render) #:use-module (crates-io))

(define-public crate-jxl-render-0.1.0 (c (n "jxl-render") (v "0.1.0") (d (list (d (n "jxl-bitstream") (r "^0.2.1") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.2.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "0jivvwaskpbva5pl0aqhpvx6vcpnsifx3mzg6va1yidbwax2ba44")))

(define-public crate-jxl-render-0.2.0 (c (n "jxl-render") (v "0.2.0") (d (list (d (n "jxl-bitstream") (r "^0.2.1") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.2.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "0hvgp4yfvp8s35nghdgglgwvcrf99ylg7hbjdibkcsix2jh2p10a")))

(define-public crate-jxl-render-0.3.0 (c (n "jxl-render") (v "0.3.0") (d (list (d (n "jxl-bitstream") (r "^0.2.3") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.2.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "15wjkm397zd9gvfa0nw6nwwrp7wwh93dg6h52c5fddmkbmqq8ikp")))

(define-public crate-jxl-render-0.4.0 (c (n "jxl-render") (v "0.4.0") (d (list (d (n "jxl-bitstream") (r "^0.2.3") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.2.3") (d #t) (k 0)) (d (n "jxl-color") (r "^0.3.2") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.5.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.5.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.3.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "0zkhr03nckj8d6gg6lgwkamifx5s8njqpk5h1j0dqvc9qk3d2mvi")))

(define-public crate-jxl-render-0.5.0 (c (n "jxl-render") (v "0.5.0") (d (list (d (n "jxl-bitstream") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.6.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-image") (r "^0.6.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.4.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "1gw1b01ngljsd96gypgz45kkhf1n95shvd7ycnzgwj9hz2c2z1jb")))

(define-public crate-jxl-render-0.5.1 (c (n "jxl-render") (v "0.5.1") (d (list (d (n "jxl-bitstream") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.6.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.2.0") (d #t) (k 0)) (d (n "jxl-image") (r "^0.6.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.4.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "0ccrcvyi94gacbas6c4syazlf7lxz4sa9qkm9dkn8wzcyiiqiq6a")))

(define-public crate-jxl-render-0.6.0 (c (n "jxl-render") (v "0.6.0") (d (list (d (n "jxl-bitstream") (r "^0.3.1") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.5.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.7.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.3.0") (d #t) (k 0)) (d (n "jxl-image") (r "^0.7.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.5.0") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.0") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.5.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.37") (f (quote ("std"))) (k 0)))) (h "14jkqh5xg7zyar1zba7s1ry880pfmjsnqlihczpv5ql5zvdfvcn8")))

(define-public crate-jxl-render-0.7.0 (c (n "jxl-render") (v "0.7.0") (d (list (d (n "jxl-bitstream") (r "^0.3.2") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.3.1") (d #t) (k 0)) (d (n "jxl-color") (r "^0.6.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.8.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-image") (r "^0.8.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.6.0") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.6.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.40") (f (quote ("std"))) (k 0)))) (h "0rqyrkgl4zhhfc5yk2lwh69n09jw0rx9gfh3h1hfh29d403j7p9n")))

(define-public crate-jxl-render-0.7.1 (c (n "jxl-render") (v "0.7.1") (d (list (d (n "jxl-bitstream") (r "^0.3.2") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.3.2") (d #t) (k 0)) (d (n "jxl-color") (r "^0.6.1") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.8.1") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.4.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.8.1") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.6.1") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.6.1") (d #t) (k 0)) (d (n "tracing") (r "^0.1.40") (f (quote ("std"))) (k 0)))) (h "0vclnyg9hx4cszxqm511kr0hj061mxv3xa81hrcv2n19vxrrb04h")))

(define-public crate-jxl-render-0.7.2 (c (n "jxl-render") (v "0.7.2") (d (list (d (n "jxl-bitstream") (r "^0.3.2") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.3.2") (d #t) (k 0)) (d (n "jxl-color") (r "^0.6.1") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.8.1") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.4.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.8.1") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.6.2") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.6.1") (d #t) (k 0)) (d (n "tracing") (r "^0.1.40") (f (quote ("std"))) (k 0)))) (h "1zqkh0n75s6dhxg28gjrgbdyg2dz72354830ssiihi8gsb231z6q")))

(define-public crate-jxl-render-0.8.0 (c (n "jxl-render") (v "0.8.0") (d (list (d (n "jxl-bitstream") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-coding") (r "^0.4.0") (d #t) (k 0)) (d (n "jxl-color") (r "^0.7.0") (d #t) (k 0)) (d (n "jxl-frame") (r "^0.9.0") (d #t) (k 0)) (d (n "jxl-grid") (r "^0.4.1") (d #t) (k 0)) (d (n "jxl-image") (r "^0.9.0") (d #t) (k 0)) (d (n "jxl-modular") (r "^0.7.0") (d #t) (k 0)) (d (n "jxl-threadpool") (r "^0.1.1") (d #t) (k 0)) (d (n "jxl-vardct") (r "^0.7.0") (d #t) (k 0)) (d (n "tracing") (r "^0.1.40") (f (quote ("std"))) (k 0)))) (h "125y8phw1vp092vs6zjpqfravd2fb5f7fjkmd7x2vax61ix8ysna")))

