(define-module (crates-io ca sp casper-engine-test-support) #:use-module (crates-io))

(define-public crate-casper-engine-test-support-0.1.0 (c (n "casper-engine-test-support") (v "0.1.0") (d (list (d (n "casper-contract") (r "^0.1.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-engine-grpc-server") (r "^0.1.0") (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.1.0") (d #t) (k 0)) (d (n "casper-types") (r "^0.1.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "grpc") (r "^0.6.1") (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1445b77yybkxkxh9hlg18452xj61cc9x67xjb860ksr7jxw4pgjm") (f (quote (("use-system-contracts") ("use-as-wasm") ("test-support" "casper-engine-grpc-server/test-support" "casper-contract/test-support") ("no-unstable-features" "casper-contract/no-unstable-features" "casper-engine-grpc-server/no-unstable-features" "casper-types/no-unstable-features"))))))

(define-public crate-casper-engine-test-support-0.2.1 (c (n "casper-engine-test-support") (v "0.2.1") (d (list (d (n "casper-contract") (r "^0.2.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-engine-grpc-server") (r "^0.2.1") (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.2.1") (d #t) (k 0)) (d (n "casper-types") (r "^0.2.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "grpc") (r "^0.6.1") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "171ya8h0x31aabz2v82fsagk2vyxgp8g4sf7lpnj3b5s1n31wmbn") (f (quote (("use-system-contracts") ("use-as-wasm") ("test-support" "casper-engine-grpc-server/test-support" "casper-contract/test-support") ("no-unstable-features" "casper-contract/no-unstable-features" "casper-engine-grpc-server/no-unstable-features" "casper-types/no-unstable-features"))))))

(define-public crate-casper-engine-test-support-0.6.3 (c (n "casper-engine-test-support") (v "0.6.3") (d (list (d (n "casper-contract") (r "^0.6.3") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-engine-grpc-server") (r "^0.6.3") (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.6.3") (d #t) (k 0)) (d (n "casper-types") (r "^0.6.3") (f (quote ("std"))) (d #t) (k 0)) (d (n "grpc") (r "^0.6.1") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "04fwqy2r9431cj6ypsj3vyii3lzfhz44bs2f882f50iqqy1c90kq") (f (quote (("use-system-contracts") ("use-as-wasm") ("test-support" "casper-engine-grpc-server/test-support" "casper-contract/test-support")))) (y #t)))

(define-public crate-casper-engine-test-support-0.7.0 (c (n "casper-engine-test-support") (v "0.7.0") (d (list (d (n "casper-contract") (r "^0.7.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.7.0") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^0.7.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "0981sn2nxq90gj7r7qizmx1bdmvv0gr8x7m1vwrk59341x9sl5wh") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-0.7.5 (c (n "casper-engine-test-support") (v "0.7.5") (d (list (d (n "casper-contract") (r "^0.7.5") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.7.5") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^0.7.5") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "07w52a1n4yfvb5pjlgzw4wsk1dbblabjbly1h07mrkgs7nig8aqc") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-0.7.6 (c (n "casper-engine-test-support") (v "0.7.6") (d (list (d (n "casper-contract") (r "^0.7.6") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.7.6") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^0.7.6") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1ldzjirmd989padvhqzpjbpxs8fr9a8bzxxhczmiq0ydhxp6n456") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-0.9.3 (c (n "casper-engine-test-support") (v "0.9.3") (d (list (d (n "casper-contract") (r "^0.9.3") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.9.3") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^0.9.3") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "15zw2bm82lmsn4q4v8p24vx4h0xlasqpbidzvqn5bm26k29hdpaf") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-0.9.4 (c (n "casper-engine-test-support") (v "0.9.4") (d (list (d (n "casper-contract") (r "^0.9.4") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^0.9.4") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^0.9.4") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1gv0grm1pgy7hrzwwgad9736w76g51nn5xfcg1xdm1i41avb09zk") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.0.0 (c (n "casper-engine-test-support") (v "1.0.0") (d (list (d (n "casper-contract") (r "^1.0.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.0.0") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.0.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "01lar99kq50k0fmiy5aqavvw9pmb89403z03a0pjgvmhl9bwbwih") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.0.1 (c (n "casper-engine-test-support") (v "1.0.1") (d (list (d (n "casper-contract") (r "^1.0.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.0.1") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.0.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "0vih5kci6pisqxzmiah93gidgifr2p3mfyi2pfkwx7qc3s9i7mkk") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.1.0 (c (n "casper-engine-test-support") (v "1.1.0") (d (list (d (n "casper-contract") (r "^1.1.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.1.0") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.1.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "06b5p9imb7xx3xvc4jk7qy6wjh9x7g18xhafmgxhycw0axx3vhnk") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support")))) (y #t)))

(define-public crate-casper-engine-test-support-1.1.1 (c (n "casper-engine-test-support") (v "1.1.1") (d (list (d (n "casper-contract") (r "^1.1.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.1.1") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.1.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.3.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "protobuf") (r "=2.8") (d #t) (k 0)) (d (n "rand") (r "^0.7.2") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1cimr39rw0aiql0cc7adahb4gai0cxnccnhbynxckzwqi9kdswnk") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.2.0 (c (n "casper-engine-test-support") (v "1.2.0") (d (list (d (n "casper-contract") (r "^1.2.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.2.0") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.2.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "0grnzhyy7p2xwnv1xwl6np40iljfz193aj49ifig5ap8dzw63mvv") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.2.1 (c (n "casper-engine-test-support") (v "1.2.1") (d (list (d (n "casper-contract") (r "^1.2.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.2.1") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.2.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "0kqw3v5cv6bcccnv4yvyia1229my2mij10zpznacn5w4igxss4lc") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.3.0 (c (n "casper-engine-test-support") (v "1.3.0") (d (list (d (n "casper-contract") (r "^1.3.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.3.0") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.3.0") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1axvzw9xjzdahqwgxwx223xrxjwwns0vj4dphw3ddca1lz3q01gj") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.3.1 (c (n "casper-engine-test-support") (v "1.3.1") (d (list (d (n "casper-contract") (r "^1.3.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.3.1") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.3.1") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1gdk9bz8668rb9z24yisgdn098h8njd5rnwl5p80xxllrbsa4z84") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.3.2 (c (n "casper-engine-test-support") (v "1.3.2") (d (list (d (n "casper-contract") (r "^1.3.2") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.3.2") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.3.2") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "1fmsn3j5gl7mdls95arsrv8fbly3vcv3irppwn2yshyp34p6vbs4") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.3.3 (c (n "casper-engine-test-support") (v "1.3.3") (d (list (d (n "casper-contract") (r "^1.3.3") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.3.3") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.3.3") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "0b9j8vbaazqw1xd8rrh38jpjq9d7vxpwc7c3hzpp43kh44rw0s51") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.3.4 (c (n "casper-engine-test-support") (v "1.3.4") (d (list (d (n "casper-contract") (r "^1.3.4") (f (quote ("std"))) (d #t) (k 0)) (d (n "casper-execution-engine") (r "^1.3.4") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-types") (r "^1.3.4") (f (quote ("std"))) (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "0nxja4phy181ba06zvqdspmnlvk2n565mjr8v5001w918njqwrwq") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-1.4.0 (c (n "casper-engine-test-support") (v "1.4.0") (d (list (d (n "casper-contract") (r "^1.4.0") (k 0)) (d (n "casper-execution-engine") (r "^1.4.0") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.0") (d #t) (k 0)) (d (n "casper-types") (r "^1.4.0") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "00pszil654j1hqq8g0i49vbrqr5wgyac0006vrmvp5d43c9w1ayr") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support")))) (y #t)))

(define-public crate-casper-engine-test-support-1.4.1 (c (n "casper-engine-test-support") (v "1.4.1") (d (list (d (n "casper-contract") (r "^1.4.1") (k 0)) (d (n "casper-execution-engine") (r "^1.4.1") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.1") (d #t) (k 0)) (d (n "casper-types") (r "^1.4.1") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9") (d #t) (k 2)))) (h "134l6wqab46scij28lf00517dp89izxq9ll7pidbd7lp3i52nbz5") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-2.0.0 (c (n "casper-engine-test-support") (v "2.0.0") (d (list (d (n "casper-contract") (r "^1.4.1") (k 0)) (d (n "casper-execution-engine") (r "^1.4.1") (f (quote ("gens"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.1") (d #t) (k 0)) (d (n "casper-types") (r "^1.4.1") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.8") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.10") (d #t) (k 0)) (d (n "once_cell") (r "^1.5.2") (d #t) (k 0)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "0fmmnx751di5lxr0i52lr9ydyry1ckjcfa2vvpiy15yvn8cpv2j0") (f (quote (("use-as-wasm") ("test-support" "casper-contract/test-support"))))))

(define-public crate-casper-engine-test-support-2.0.1 (c (n "casper-engine-test-support") (v "2.0.1") (d (list (d (n "casper-execution-engine") (r "^1") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1") (d #t) (k 0)) (d (n "casper-types") (r "^1") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "0dz3ai43gsyvzl634bhhlkwcym0qbjbp3an84frghxp51gj8yiah") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-2.0.2 (c (n "casper-engine-test-support") (v "2.0.2") (d (list (d (n "casper-execution-engine") (r "^1.4.2") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.2") (d #t) (k 0)) (d (n "casper-types") (r "^1.4.4") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "08j3c4k0n479168sn04d42w07vbpkk6yijpnzjl3d3mwg6lc93j1") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-2.0.3 (c (n "casper-engine-test-support") (v "2.0.3") (d (list (d (n "casper-execution-engine") (r "^1.4.3") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.2") (d #t) (k 0)) (d (n "casper-types") (r "^1.4.5") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "0h2j02k9xwaawjpyxg83di7badrk6a5fjkd9s1wfgl59a2csmbhk") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-2.1.0 (c (n "casper-engine-test-support") (v "2.1.0") (d (list (d (n "casper-execution-engine") (r "^1.5.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.3") (d #t) (k 0)) (d (n "casper-types") (r "^1.5.0") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "0nv86annk39xcv9r1vzwy1lqvwjh8638hj7fbqa9lrw8h7z88nrg") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-2.2.0 (c (n "casper-engine-test-support") (v "2.2.0") (d (list (d (n "casper-execution-engine") (r "^2.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.3") (d #t) (k 0)) (d (n "casper-types") (r "^1.5.0") (d #t) (k 0)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "tempfile") (r "^3") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "0433z9vpdzc38ijl4n5vg6f67ssbid4q0fxi04p9hjr9ncmla5sr") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-2.3.0 (c (n "casper-engine-test-support") (v "2.3.0") (d (list (d (n "casper-execution-engine") (r "^3.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.3") (d #t) (k 0)) (d (n "casper-types") (r "^1.5.0") (d #t) (k 0)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "0ibs5vdvcx96ypwk533blzyy7iyax2y6f9kcdvvdl0nwlb5hv684") (f (quote (("use-as-wasm") ("test-support")))) (y #t)))

(define-public crate-casper-engine-test-support-3.0.0 (c (n "casper-engine-test-support") (v "3.0.0") (d (list (d (n "casper-execution-engine") (r "^3.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.3") (d #t) (k 0)) (d (n "casper-types") (r "^1.5.0") (d #t) (k 0)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "06jdym4xhj4anfk0ilznjzsc9rcsard1nq8zpbdhcbzq1vij6ryb") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-3.1.0 (c (n "casper-engine-test-support") (v "3.1.0") (d (list (d (n "casper-execution-engine") (r "^3.1.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.3") (d #t) (k 0)) (d (n "casper-types") (r "^1.6.0") (d #t) (k 0)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "00cl7ql7z4zhkzkd3sx2l9b0nz1254gvjxnfkabirhih5mh0np1k") (f (quote (("use-as-wasm") ("test-support")))) (y #t)))

(define-public crate-casper-engine-test-support-3.1.1 (c (n "casper-engine-test-support") (v "3.1.1") (d (list (d (n "casper-execution-engine") (r "^3.1.1") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.3") (d #t) (k 0)) (d (n "casper-types") (r "^1.6.0") (d #t) (k 0)) (d (n "casper-types") (r "^1.6.0") (f (quote ("std"))) (d #t) (k 2)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "1kgia6y3vcv8p8wykb68vzb69gsk72am0x6b2mjndk3c25afir9g") (f (quote (("use-as-wasm") ("test-support")))) (y #t)))

(define-public crate-casper-engine-test-support-4.0.0 (c (n "casper-engine-test-support") (v "4.0.0") (d (list (d (n "casper-execution-engine") (r "^4.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^1.4.4") (d #t) (k 0)) (d (n "casper-types") (r "^2.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^2.0.0") (f (quote ("std"))) (d #t) (k 2)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb") (r "^0.8.0") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "12nggrj0as47pscyn9f6xcbxi2q66ff8kh7j5irbv5kcgbwl0spp") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-5.0.0 (c (n "casper-engine-test-support") (v "5.0.0") (d (list (d (n "casper-execution-engine") (r "^5.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^2.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^3.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^3.0.0") (f (quote ("std"))) (d #t) (k 2)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb-rkv") (r "^0.14") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3.4.0") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "1vfvr9amr2s23jlj2n4qybvkq5d0hi2za2j6xjgmxkhngpv9fazr") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-6.0.0 (c (n "casper-engine-test-support") (v "6.0.0") (d (list (d (n "casper-execution-engine") (r "^6.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^2.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^3.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^3.0.0") (f (quote ("std"))) (d #t) (k 2)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb-rkv") (r "^0.14") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3.4.0") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "1nrk811ylywdp2igmndrqqm7mr9fnsqpqdd1jnixn8k9114wn77g") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-7.0.0 (c (n "casper-engine-test-support") (v "7.0.0") (d (list (d (n "casper-execution-engine") (r "^7.0.0") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^3.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^4.0.1") (d #t) (k 0)) (d (n "casper-types") (r "^4.0.1") (f (quote ("std"))) (d #t) (k 2)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb-rkv") (r "^0.14") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3.4.0") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "1r0xv4k6vgz0wyjd91jwadcxq63i0pr5dqd7yk24d1b7air4lmly") (f (quote (("use-as-wasm") ("test-support"))))))

(define-public crate-casper-engine-test-support-7.0.1 (c (n "casper-engine-test-support") (v "7.0.1") (d (list (d (n "casper-execution-engine") (r "^7.0.1") (f (quote ("test-support"))) (d #t) (k 0)) (d (n "casper-hashing") (r "^3.0.0") (d #t) (k 0)) (d (n "casper-types") (r "^4.0.1") (d #t) (k 0)) (d (n "casper-types") (r "^4.0.1") (f (quote ("std"))) (d #t) (k 2)) (d (n "filesize") (r "^0.2.0") (d #t) (k 0)) (d (n "humantime") (r "^2") (d #t) (k 0)) (d (n "lmdb-rkv") (r "^0.14") (d #t) (k 0)) (d (n "log") (r "^0.4.14") (d #t) (k 0)) (d (n "num-rational") (r "^0.4.0") (d #t) (k 0)) (d (n "num-traits") (r "^0.2.14") (d #t) (k 0)) (d (n "once_cell") (r "^1.8.0") (d #t) (k 0)) (d (n "rand") (r "^0.8.4") (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive" "rc"))) (d #t) (k 0)) (d (n "tempfile") (r "^3.4.0") (d #t) (k 0)) (d (n "toml") (r "^0.5.6") (d #t) (k 0)) (d (n "version-sync") (r "^0.9.3") (d #t) (k 2)))) (h "009wgprrifxlv99jn9mkmmv9c5ms3mcsir7kkny3y90p5w1z2rvr") (f (quote (("use-as-wasm") ("test-support"))))))

