(define-module (crates-io ca sp casperlabs-types) #:use-module (crates-io))

(define-public crate-casperlabs-types-0.1.0 (c (n "casperlabs-types") (v "0.1.0") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "18bpw3hdkal0b3chf3gia56zakb2jbjgl0z67rsni62flnj5i86a") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.2.0 (c (n "casperlabs-types") (v "0.2.0") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "0nwa0bb09dwzwx58yk5gd13y269zhr4fzjy5jnkzasmplfrzvymq") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.3.0 (c (n "casperlabs-types") (v "0.3.0") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "0skwghqjyci4j0wj0lslvjj9ckcspjhjvk3b54mh0b4rfsiv6yp1") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.4.0 (c (n "casperlabs-types") (v "0.4.0") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "0qb32rdqcajnzf7gv633dbk9gb3wfsj231qbq8j9wz5l0sr64b9v") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.4.1 (c (n "casperlabs-types") (v "0.4.1") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "0aq266fxaqfsxs5igngblgm5fmvvrgzx5fv5z8wr8fyjrprdp0ri") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.5.0 (c (n "casperlabs-types") (v "0.5.0") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "1amzzdr5c6l37xmdvdivjv5mw0aw1nhld8q4mqj122ang0n7lpp3") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.5.1 (c (n "casperlabs-types") (v "0.5.1") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "0kzr1dkr46yj5la6jizyravcp1nj06fnxmvvflqr0q7zfgjlad4k") (f (quote (("std" "base16/std") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.6.0 (c (n "casperlabs-types") (v "0.6.0") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "1cvj7r0yiw21ncxvz1jd2rry6asx157lfml4xrxcn93952l1cfwd") (f (quote (("std" "base16/std") ("no-unstable-features") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

(define-public crate-casperlabs-types-0.6.1 (c (n "casperlabs-types") (v "0.6.1") (d (list (d (n "base16") (r "^0.2.1") (k 0)) (d (n "bitflags") (r "^1") (d #t) (k 0)) (d (n "blake2") (r "^0.8.1") (k 0)) (d (n "failure") (r "^0.1.6") (f (quote ("failure_derive"))) (k 0)) (d (n "hex_fmt") (r "^0.3.0") (d #t) (k 0)) (d (n "num-derive") (r "^0.3.0") (k 0)) (d (n "num-integer") (r "^0.1.42") (k 0)) (d (n "num-traits") (r "^0.2.10") (k 0)) (d (n "proptest") (r "^0.9.4") (o #t) (d #t) (k 0)) (d (n "proptest") (r "^0.9.4") (d #t) (k 2)) (d (n "uint") (r "^0.8.2") (k 0)) (d (n "version-sync") (r "^0.8") (d #t) (k 2)))) (h "0p3y2wk2xb4wwd9yzm9s7jz04ivlz9bilhvkpw9ngvz52z0c2s6l") (f (quote (("std" "base16/std") ("no-unstable-features") ("gens" "std" "proptest/std") ("default" "base16/alloc")))) (y #t)))

