(define-module (crates-io fa st fasthash) #:use-module (crates-io))

(define-public crate-fasthash-0.1.0 (c (n "fasthash") (v "0.1.0") (d (list (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.1.0") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 2)))) (h "1pgb9mc3jyj4nkir8jbs7wp7v0ixdx8xan71qx986cxh502p335z")))

(define-public crate-fasthash-0.1.1 (c (n "fasthash") (v "0.1.1") (d (list (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.1.0") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 2)))) (h "1mha3ww5hgwpg1qcyqp6xsdkkb1h26i6616026xb8bijf6frs65d")))

(define-public crate-fasthash-0.2.0 (c (n "fasthash") (v "0.2.0") (d (list (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.0") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 2)))) (h "18qw9cbr710x2c6r5mwrxyr771h2ffgbsv4bvrhbdc68hql1i1rn") (f (quote (("sse42" "fasthash-sys/sse42") ("doc") ("default" "sse42"))))))

(define-public crate-fasthash-0.2.1 (c (n "fasthash") (v "0.2.1") (d (list (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.1") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)))) (h "1157plccqbdx6irq1l8b5pkqx84w1zqcwr9ns7yq8axk1sh1nhd2") (f (quote (("sse42" "fasthash-sys/sse42") ("doc") ("default" "sse42"))))))

(define-public crate-fasthash-0.2.2 (c (n "fasthash") (v "0.2.2") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.2") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.2") (d #t) (k 0)))) (h "1wdi1l5crizrhqm5xv73nnyzhwxamykhck5579d3ka7kvna9d5nf") (f (quote (("sse42" "fasthash-sys/sse42") ("doc") ("default" "sse42"))))))

(define-public crate-fasthash-0.2.3 (c (n "fasthash") (v "0.2.3") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.3") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.2") (d #t) (k 0)))) (h "1ffw693rcam59n44mdxmnqbyww3rsnir9h6xpin4z06ckjpyjs41") (f (quote (("sse42" "fasthash-sys/sse42") ("i128") ("doc") ("default" "i128" "sse42"))))))

(define-public crate-fasthash-0.2.4 (c (n "fasthash") (v "0.2.4") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.4") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.2") (d #t) (k 0)))) (h "0gcr4zb81cy4bij1r63k2xnqdn3yzzq06ij81bk84szkvwncllxd") (f (quote (("sse42" "fasthash-sys/sse42") ("i128") ("doc") ("default" "i128" "sse42") ("bindgen" "fasthash-sys/bindgen"))))))

(define-public crate-fasthash-0.2.5 (c (n "fasthash") (v "0.2.5") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.5") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.2") (d #t) (k 0)))) (h "0192hn0qishy6hvpxyjjika8faw5am8jjbj7c7wjg7zhfsibvi0l") (f (quote (("sse42" "fasthash-sys/sse42") ("i128") ("doc") ("default" "sse42" "doc") ("bindgen" "fasthash-sys/bindgen"))))))

(define-public crate-fasthash-0.2.6 (c (n "fasthash") (v "0.2.6") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r "^1.1") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.6") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.2") (d #t) (k 0)))) (h "0sab15am0c88v8sbwc8hp11gpkwxkb59bmmy0lfnnp4k09h1349h") (f (quote (("sse42" "fasthash-sys/sse42") ("i128") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "doc"))))))

(define-public crate-fasthash-0.2.7 (c (n "fasthash") (v "0.2.7") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r ">= 1.1, < 1.5") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.7") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.3") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.2") (d #t) (k 0)))) (h "1bvpl71rdpv1gg8svw7c8r7pfny7zyqm3q7ix0gr2g25lqph4k6c") (f (quote (("sse42" "fasthash-sys/sse42") ("i128") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "doc"))))))

(define-public crate-fasthash-0.2.8 (c (n "fasthash") (v "0.2.8") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "extprim") (r "^1.5") (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.2.8") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.4") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.3") (d #t) (k 0)))) (h "161vjx5nli4cj6fcz4z1ix69sypq12ifzxc4pfkjrw6p1kzhr5cb") (f (quote (("sse42" "fasthash-sys/sse42") ("i128") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "doc"))))))

(define-public crate-fasthash-0.3.0 (c (n "fasthash") (v "0.3.0") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.3.0") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.5") (d #t) (k 2)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.3") (d #t) (k 0)))) (h "0ahs7ra360xlsli9rgk8w1a9ynvvc22ldvs5s1mymlwmm2g25ylf") (f (quote (("sse42" "fasthash-sys/sse42") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "aes" "avx" "avx2" "doc") ("avx2" "fasthash-sys/avx2") ("avx" "fasthash-sys/avx") ("aes" "fasthash-sys/aes")))) (y #t)))

(define-public crate-fasthash-0.3.1 (c (n "fasthash") (v "0.3.1") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.3.1") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.5") (d #t) (k 2)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.3") (d #t) (k 0)))) (h "0n6n0shfnwcgllkwhffmqrqv71fz5lnkk5if3iwdp0ls7jcsjlqb") (f (quote (("sse42" "fasthash-sys/sse42") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "aes" "avx" "avx2" "doc") ("avx2" "fasthash-sys/avx2") ("avx" "fasthash-sys/avx") ("aes" "fasthash-sys/aes"))))))

(define-public crate-fasthash-0.3.2 (c (n "fasthash") (v "0.3.2") (d (list (d (n "clippy") (r "0.*") (o #t) (d #t) (k 0)) (d (n "fasthash-sys") (r "^0.3.2") (d #t) (k 0)) (d (n "fnv") (r "^1.0") (d #t) (k 2)) (d (n "rand") (r "^0.5") (d #t) (k 2)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.3") (d #t) (k 0)))) (h "1fzkccqqb4v0zjgrxb5bqm59jlpxri7759nh4d9hhn9mvwavfmnf") (f (quote (("sse42" "fasthash-sys/sse42") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "aes" "avx" "avx2" "doc") ("avx2" "fasthash-sys/avx2") ("avx" "fasthash-sys/avx") ("aes" "fasthash-sys/aes"))))))

(define-public crate-fasthash-0.4.0 (c (n "fasthash") (v "0.4.0") (d (list (d (n "cfg-if") (r "^0.1") (d #t) (k 0)) (d (n "criterion") (r "^0.2") (d #t) (k 2)) (d (n "fasthash-sys") (r "^0.3.2") (d #t) (k 0)) (d (n "lazy_static") (r "^1.3") (d #t) (k 2)) (d (n "num-traits") (r "^0.2") (d #t) (k 0)) (d (n "seahash") (r "^3.0") (d #t) (k 0)) (d (n "xoroshiro128") (r "^0.3") (d #t) (k 0)))) (h "03v9g4ajw0zk9pv2ranq65xcly1b68hg0qzc2y8y1ajfdfa168h3") (f (quote (("sse42" "fasthash-sys/sse42") ("gen" "fasthash-sys/gen") ("doc") ("default" "sse42" "aes" "avx" "avx2" "doc") ("avx2" "fasthash-sys/avx2") ("avx" "fasthash-sys/avx") ("aes" "fasthash-sys/aes"))))))

