(define-module (crates-io bi tv bitvec_simd) #:use-module (crates-io))

(define-public crate-bitvec_simd-0.1.0 (c (n "bitvec_simd") (v "0.1.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0bh0m1lzgwajppf9n3fqzlpp8vw5x68fpp9h2zdxvh88m89kg5dj")))

(define-public crate-bitvec_simd-0.2.0 (c (n "bitvec_simd") (v "0.2.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0y5j7h9jfby89vyf709wlgfx0b3yjpsfjw6gd2lwzn2n7qcagmmx")))

(define-public crate-bitvec_simd-0.3.0 (c (n "bitvec_simd") (v "0.3.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0c1il5yybr96dr5v3pki2844gshsl4lyvjywx04235qs0scr06vr")))

(define-public crate-bitvec_simd-0.4.0 (c (n "bitvec_simd") (v "0.4.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1p7nv85ifnhp2n47lwqw2h9023snpa3940rflcl1w0p8j04dv42q")))

(define-public crate-bitvec_simd-0.5.0 (c (n "bitvec_simd") (v "0.5.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0zd48dqmy9s7cklzlp05r6hx6ycbhbyqvvbfv8cwhw5jxf44ij9l")))

(define-public crate-bitvec_simd-0.6.0 (c (n "bitvec_simd") (v "0.6.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0b6m18l58j40b9iiwpqv7yv7mzx1px2m12l6wza2bk0fapc1wr8f")))

(define-public crate-bitvec_simd-0.7.0 (c (n "bitvec_simd") (v "0.7.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1rawalwg7m9i1xgxw06x6nkpk9ncc86w0gizz5h67fmapdr5hhkh")))

(define-public crate-bitvec_simd-0.8.0 (c (n "bitvec_simd") (v "0.8.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1svxl717xcv6qwva7c6x8n10rx87v3kqf16pmbdljyk944lsqa79")))

(define-public crate-bitvec_simd-0.9.0 (c (n "bitvec_simd") (v "0.9.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "09pnbbany1ysr58s2ipayljaxmnm3lisr8cm98hhjmr63080bgwg")))

(define-public crate-bitvec_simd-0.10.0 (c (n "bitvec_simd") (v "0.10.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^0.22") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "smallvec") (r "^1.7") (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1jyj5cdbdhp8fz5a8yami4zdj9phfrqh81s7fha998yw5nc2l04h")))

(define-public crate-bitvec_simd-0.11.0 (c (n "bitvec_simd") (v "0.11.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "smallvec") (r "^1.7") (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "184xf5bfkm50qj9l1v8qjr0ainhaza4rgc715zi89ny7jp7advv3")))

(define-public crate-bitvec_simd-0.12.0 (c (n "bitvec_simd") (v "0.12.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "smallvec") (r "^1.7") (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1v3gngdj0rzprm4ikh66bxqar8r5smzgaq63qqnwgaqfhql1mphb")))

(define-public crate-bitvec_simd-0.13.0 (c (n "bitvec_simd") (v "0.13.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "smallvec") (r "^1.7") (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1yzcnbljpkqr2pjajq0x77m2s9kfni23bzifxqbfmf06lk5fby3s")))

(define-public crate-bitvec_simd-0.14.0 (c (n "bitvec_simd") (v "0.14.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "smallvec") (r "^1.7") (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "08ffphgdricqdkzsh33spgdb4mxhf3fqw3a8wmgk9r689ild56mg")))

(define-public crate-bitvec_simd-0.15.0 (c (n "bitvec_simd") (v "0.15.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "smallvec") (r "^1.7") (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "03hm0ibzw2kqghh75503h7l5m2dvzmcf9fnv0zyzmisap9fy1s5w")))

(define-public crate-bitvec_simd-0.16.0 (c (n "bitvec_simd") (v "0.16.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1") (o #t) (k 0)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0y8d8hkjnds6wfgpnipmzxvzcm7369khaiqj8y214zxssrzpg676") (f (quote (("use-serde" "serde"))))))

(define-public crate-bitvec_simd-0.17.0 (c (n "bitvec_simd") (v "0.17.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "10ggy607pfk60jzh8pc53iwsq3d77xmbjyx3jxyx5qq11hi3cl0h") (f (quote (("use_serde"))))))

(define-public crate-bitvec_simd-0.18.0 (c (n "bitvec_simd") (v "0.18.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0l2n7za373j311nfcvn96kz16dbnf39j02bavqsdnf8dlxk3li17") (f (quote (("use_serde"))))))

(define-public crate-bitvec_simd-0.19.0 (c (n "bitvec_simd") (v "0.19.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "120kpfkzyn9b8ksypy09m2kij6j9rbgs9svnszhbjqgmc8pjd14i") (f (quote (("use_serde" "serde") ("std") ("default" "std"))))))

(define-public crate-bitvec_simd-0.20.0 (c (n "bitvec_simd") (v "0.20.0") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0hyla6vzjyck018jwxpbh5kv49rqx0fw38ix886s3qkpvd3vhrri") (f (quote (("use_serde" "serde") ("std") ("default" "std"))))))

(define-public crate-bitvec_simd-0.20.1 (c (n "bitvec_simd") (v "0.20.1") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "182lcgpcw0p11ny4m8yhs2b626mwfkna712z9y6gqssfsi654h5p") (f (quote (("use_serde" "serde") ("std") ("default" "std"))))))

(define-public crate-bitvec_simd-0.20.2 (c (n "bitvec_simd") (v "0.20.2") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1w3cqbp02bcf1c7lcmf3q9pvlqmchi9szb4f1mphrfh18rg714df") (f (quote (("use_serde" "serde") ("std") ("default" "std"))))))

(define-public crate-bitvec_simd-0.20.3 (c (n "bitvec_simd") (v "0.20.3") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "0rchk2diyv5xnhvy4hcm0dvk8q14p60f3f6lzlj7g4qfr500i76a") (f (quote (("use_serde" "serde") ("std") ("default" "std"))))))

(define-public crate-bitvec_simd-0.20.4 (c (n "bitvec_simd") (v "0.20.4") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "01xbf6fp2y7x490wi7i731br523fsqhfnp7m5ri1cj7iaxgmgr84") (f (quote (("use_serde" "serde") ("std") ("default" "std")))) (r "1.56")))

(define-public crate-bitvec_simd-0.20.5 (c (n "bitvec_simd") (v "0.20.5") (d (list (d (n "bit-vec") (r "^0.6") (d #t) (k 2)) (d (n "bitvec") (r "^1.0") (d #t) (k 2)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "serde") (r "^1.0") (f (quote ("derive"))) (o #t) (d #t) (k 0)) (d (n "serde_test") (r "^1.0") (d #t) (k 2)) (d (n "smallvec") (r "^1.8") (f (quote ("const_generics" "serde"))) (d #t) (k 0)) (d (n "wide") (r "^0.7") (d #t) (k 0)))) (h "1i7crwqz56h59s2ii2frvwq7kl86c1d1jpr5vc9jq6ghy8pndgip") (f (quote (("use_serde" "serde") ("std") ("default" "std")))) (r "1.56")))

