(define-module (crates-io pu ll pullup) #:use-module (crates-io))

(define-public crate-pullup-0.1.0 (c (n "pullup") (v "0.1.0") (d (list (d (n "pulldown-cmark") (r "^0.9.2") (o #t) (d #t) (k 0)) (d (n "pulldown_mdbook") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "pulldown_typst") (r "^0.1") (o #t) (d #t) (k 0)) (d (n "similar-asserts") (r "^1.5.0") (d #t) (k 2)) (d (n "typed-builder") (r "^0.18.0") (o #t) (d #t) (k 0)))) (h "1fishw634wasgd0wkl070mcf92d5skm2hsy81qybannsi6gpfr97") (s 2) (e (quote (("typst" "dep:pulldown_typst") ("mdbook" "dep:pulldown_mdbook" "markdown") ("markdown" "dep:pulldown-cmark") ("builder" "dep:typed-builder"))))))

(define-public crate-pullup-0.2.0 (c (n "pullup") (v "0.2.0") (d (list (d (n "pulldown-cmark") (r "^0.9.2") (o #t) (d #t) (k 0)) (d (n "pulldown_mdbook") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "pulldown_typst") (r "^0.2") (o #t) (d #t) (k 0)) (d (n "similar-asserts") (r "^1.5.0") (d #t) (k 2)) (d (n "typed-builder") (r "^0.18.0") (o #t) (d #t) (k 0)))) (h "1ak114l5dijw8i5w2n2ng4md3c8nf80krgay0gam40pnfa8w4aaa") (s 2) (e (quote (("typst" "dep:pulldown_typst") ("mdbook" "dep:pulldown_mdbook" "markdown") ("markdown" "dep:pulldown-cmark") ("builder" "dep:typed-builder"))))))

(define-public crate-pullup-0.3.0 (c (n "pullup") (v "0.3.0") (d (list (d (n "pulldown-cmark") (r "^0.9.2") (o #t) (d #t) (k 0)) (d (n "pulldown_mdbook") (r "^0.3") (o #t) (d #t) (k 0)) (d (n "pulldown_typst") (r "^0.3") (o #t) (d #t) (k 0)) (d (n "similar-asserts") (r "^1.5.0") (d #t) (k 2)) (d (n "tracing") (r "^0.1.40") (o #t) (d #t) (k 0)) (d (n "typed-builder") (r "^0.18.0") (o #t) (d #t) (k 0)))) (h "0w4cq7bs2zdhki0c807v9grpbxq42a05ps7n74awdh67cs5g6fbm") (s 2) (e (quote (("typst" "dep:pulldown_typst") ("tracing" "dep:tracing" "pulldown_typst/tracing" "pulldown_mdbook/tracing") ("mdbook" "dep:pulldown_mdbook" "markdown") ("markdown" "dep:pulldown-cmark") ("builder" "dep:typed-builder"))))))

(define-public crate-pullup-0.3.1 (c (n "pullup") (v "0.3.1") (d (list (d (n "pulldown-cmark") (r "^0.9.2") (o #t) (d #t) (k 0)) (d (n "pulldown_mdbook") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "pulldown_typst") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "similar-asserts") (r "^1.5.0") (d #t) (k 2)) (d (n "tracing") (r "^0.1.40") (o #t) (d #t) (k 0)) (d (n "typed-builder") (r "^0.18.0") (o #t) (d #t) (k 0)))) (h "13pmck0pkcb72alr9v4q38kigpc3v82v86rri6ab5av4bsirkl00") (s 2) (e (quote (("typst" "dep:pulldown_typst") ("tracing" "dep:tracing" "pulldown_typst/tracing" "pulldown_mdbook/tracing") ("mdbook" "dep:pulldown_mdbook" "markdown") ("markdown" "dep:pulldown-cmark") ("builder" "dep:typed-builder"))))))

(define-public crate-pullup-0.3.2 (c (n "pullup") (v "0.3.2") (d (list (d (n "pulldown-cmark") (r "^0.9.2") (o #t) (d #t) (k 0)) (d (n "pulldown_mdbook") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "pulldown_typst") (r "^0.3.2") (o #t) (d #t) (k 0)) (d (n "similar-asserts") (r "^1.5.0") (d #t) (k 2)) (d (n "tracing") (r "^0.1.40") (o #t) (d #t) (k 0)) (d (n "typed-builder") (r "^0.18.0") (o #t) (d #t) (k 0)))) (h "0lvpz3rma4d74p76026m4rmncchfvd1507g9h9r93jrxzdkcb2nl") (s 2) (e (quote (("typst" "dep:pulldown_typst") ("tracing" "dep:tracing" "pulldown_typst/tracing" "pulldown_mdbook/tracing") ("mdbook" "dep:pulldown_mdbook" "markdown") ("markdown" "dep:pulldown-cmark") ("builder" "dep:typed-builder"))))))

(define-public crate-pullup-0.3.3 (c (n "pullup") (v "0.3.3") (d (list (d (n "pulldown-cmark") (r "^0.9.2") (o #t) (d #t) (k 0)) (d (n "pulldown_mdbook") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "pulldown_typst") (r "^0.3.3") (o #t) (d #t) (k 0)) (d (n "similar-asserts") (r "^1.5.0") (d #t) (k 2)) (d (n "tracing") (r "^0.1.40") (o #t) (d #t) (k 0)) (d (n "typed-builder") (r "^0.18.0") (o #t) (d #t) (k 0)))) (h "0mzb121ssda6yh1rmzvmxmhbb1jga91ngz2acswvyskbxvavd012") (s 2) (e (quote (("typst" "dep:pulldown_typst") ("tracing" "dep:tracing" "pulldown_typst/tracing" "pulldown_mdbook/tracing") ("mdbook" "dep:pulldown_mdbook" "markdown") ("markdown" "dep:pulldown-cmark") ("builder" "dep:typed-builder"))))))

