(define-module (crates-io li br librashader-cache) #:use-module (crates-io))

(define-public crate-librashader-cache-0.1.0-rc.4 (c (n "librashader-cache") (v "0.1.0-rc.4") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (f (quote ("rayon"))) (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.0-rc.4") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.0-rc.4") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1v3jkdkni70j2200k6yzxfwx831p30fk23vkqxdr831j81si38yg") (f (quote (("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.0-rc.5 (c (n "librashader-cache") (v "0.1.0-rc.5") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (f (quote ("rayon"))) (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.0-rc.5") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.0-rc.5") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0g9rri7x7l7cxr83cj08pz1lkhvzrnxls3hcyg8l21x5qs45jm6j") (f (quote (("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.0-rc.6 (c (n "librashader-cache") (v "0.1.0-rc.6") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.0-rc.6") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.0-rc.6") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0bnilr5kjkjnv7my05fh5500lwhwrbfx8fgll25khj7lpkzqlphr") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.0-rc.7 (c (n "librashader-cache") (v "0.1.0-rc.7") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.0-rc.7") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.0-rc.7") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1i6j31bw9m8dk4869had8pjzm2ynivr4vh08fjsgr2xwycsycycv") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.0 (c (n "librashader-cache") (v "0.1.0") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.0") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.0") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1dygc8msb5fm38g63indcwb5z2yk4h8fm7ilmd70jnahpr1rrrk1") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.1 (c (n "librashader-cache") (v "0.1.1") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.1") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.1") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "09bh7ndnqgv5h5cv23h8mlci9f758fg40hwxvm9gc8cpisysbdhl") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.2 (c (n "librashader-cache") (v "0.1.2") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.2") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.2") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "01n44nnzs2vwgzhj555s58rzanhq7s841qvdw7fg410p4fhwbkxj") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.3 (c (n "librashader-cache") (v "0.1.3") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.3") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.3") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.44.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0ls9g5y1z5h8yfblhymrnd7azg8xcvcacgami3p2kb7c52vra9cj") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.1.4 (c (n "librashader-cache") (v "0.1.4") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.1.4") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.1.4") (f (quote ("serialize" "dxil"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1b3wpyxyhprnkbisib5z95h8fyb76ayz766i45dli3d0p011hg0r") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows"))))))

(define-public crate-librashader-cache-0.2.0-beta.2 (c (n "librashader-cache") (v "0.2.0-beta.2") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.2") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1jv9bq9r7wy0piivw866i0zmkfkczdng23f8mrljiydk0kd05zlv") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.3 (c (n "librashader-cache") (v "0.2.0-beta.3") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.3") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.3") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "14s7byaqyxqlyanirdhzr8n2qndqrp927nmknikqymfzglhr6flf") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.4 (c (n "librashader-cache") (v "0.2.0-beta.4") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.4") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.4") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1br6nnsppv40l87hdd80hcixlkjnfsksdc26aabhcp81hhz7k7ar") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.5 (c (n "librashader-cache") (v "0.2.0-beta.5") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.5") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.5") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0jgax8dwgrycl6aiyajylm8jv6nizrii72yagvchpabzb2396920") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.6 (c (n "librashader-cache") (v "0.2.0-beta.6") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.6") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.6") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1j079l387xp4qsl8ns25mrj15ifjrj3pj72hp71xwc56fd1s1p23") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.7 (c (n "librashader-cache") (v "0.2.0-beta.7") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.7") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.7") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1h6kz4sr3mb0a00z8sv3m86aks8f4q4hv1yvfr2p31a3m8jvwnd8") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.8 (c (n "librashader-cache") (v "0.2.0-beta.8") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.8") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.8") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1bi4zf3j4cawcmi7knymjhfwr226c8q969qnfj85m630n8b49kp7") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.9 (c (n "librashader-cache") (v "0.2.0-beta.9") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.9") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.9") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1cqsd8rzzn88by4wj370i8lnrsw1g6yc1v82q0ydgm6qsc66pfqq") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.10 (c (n "librashader-cache") (v "0.2.0-beta.10") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.10") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.10") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0h4gm7im3yg6xl10lj5id0k61r7igd3c4wm5qp3klnpj8vfna8jz") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.11 (c (n "librashader-cache") (v "0.2.0-beta.11") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.11") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.11") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.28.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1i7yx2lz770kq1vnr6rgaprsvyhagc2z7r68wjpmdsan1djviizm") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.14 (c (n "librashader-cache") (v "0.2.0-beta.14") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.14") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.14") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "rusqlite") (r "^0.30.0") (f (quote ("bundled"))) (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0ccm4wisj9ra5dha4pxqpfrxx9ir2ghla5rrrwwdfpzdla5hiknc") (f (quote (("docsrs" "blake3/pure" "rusqlite/in_gecko") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.16 (c (n "librashader-cache") (v "0.2.0-beta.16") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.16") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.16") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "13m2j868inhd5wwm5sfrky0353dgaqk9fpbzizqkkkcxja5db43z") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.17 (c (n "librashader-cache") (v "0.2.0-beta.17") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.17") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.17") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0qr129f3szjizqq7mj4p9g348q5iy7nyi61dqvb81d9jjy6yxpb9") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-beta.18 (c (n "librashader-cache") (v "0.2.0-beta.18") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-beta.18") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-beta.18") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0nrjd9w0gs7zbkdrdg9rqwfhgh4ng3qyh7yv7ypv1ljnnpy1p604") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-rc.1 (c (n "librashader-cache") (v "0.2.0-rc.1") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-rc.1") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-rc.1") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1s9vqysm8p3d0y56sw5syspa8xmv0spvm8bz7axxlg8rp8wvcs7x") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-rc.2 (c (n "librashader-cache") (v "0.2.0-rc.2") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-rc.2") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-rc.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0fsaxalqw4w9v4nlyxyimxqk2zcvk0xm04dfy5286850r8gmjvf0") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0-rc.3 (c (n "librashader-cache") (v "0.2.0-rc.3") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0-rc.3") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0-rc.3") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1dip1p7z3cy0i8lw9lab54r8ggdfrfijgarz4zj493ylpqm5z4ja") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.0 (c (n "librashader-cache") (v "0.2.0") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.0") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.0") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "18n6664d4cx8gm4l7yjhnk9isj65pyp3d8spn7cqwiyjvff20z7w") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.1 (c (n "librashader-cache") (v "0.2.1") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.1") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.1") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "18a9hdvnbwdc66251pd022rszcyg353mrs1zd2mch7kzkx4f3jn5") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.2 (c (n "librashader-cache") (v "0.2.2") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.2") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.2") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0fg0hw8kzg37fxqcpvwywxh8nn2p7jhpf0m1jalv0yp78w1xw9km") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.3 (c (n "librashader-cache") (v "0.2.3") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.3") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.3") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.48.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "0m6lakak3mp90sly2rwybijzpsxk7p9ddrww9hbyinfjaaq21yib") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.4 (c (n "librashader-cache") (v "0.2.4") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.4") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.4") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.52.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "02ibnbnqxz984j932c9gl2hbc4zsqx2slm370x3w84xb30hdlrbn") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.5 (c (n "librashader-cache") (v "0.2.5") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.5") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.5") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.52.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1jn4s03xrjhncmy5h9pdx15prss1y457l8gr2dxx80xf8v2ljcsf") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.6 (c (n "librashader-cache") (v "0.2.6") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.6") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.6") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.52.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1p9ds3lbjy8gv1fpri1kllj80q3ql9qb8ny0gn4gajirh5qi5l7a") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

(define-public crate-librashader-cache-0.2.7 (c (n "librashader-cache") (v "0.2.7") (d (list (d (n "bincode") (r "^2.0.0-rc.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "blake3") (r "^1.3.3") (d #t) (k 0)) (d (n "bytemuck") (r "^1.13.0") (d #t) (k 0)) (d (n "librashader-preprocess") (r "^0.2.7") (d #t) (k 0)) (d (n "librashader-reflect") (r "^0.2.7") (f (quote ("serialize"))) (d #t) (k 0)) (d (n "persy") (r "^1.4.7") (d #t) (k 0)) (d (n "platform-dirs") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0") (d #t) (k 0)) (d (n "thiserror") (r "^1.0.38") (d #t) (k 0)) (d (n "windows") (r "^0.52.0") (f (quote ("Win32_Graphics_Direct3D" "Win32_Graphics_Direct3D_Fxc" "Win32_Graphics_Direct3D_Dxc"))) (o #t) (d #t) (t "cfg(windows)") (k 0)))) (h "1ws0q98ddikjnv9n00wadz3cila6rrfap3pyswq4q1cx2iifhixh") (f (quote (("docsrs" "blake3/pure") ("d3d" "windows" "librashader-reflect/dxil"))))))

