(define-module (crates-io io co iocore) #:use-module (crates-io))

(define-public crate-iocore-0.0.0 (c (n "iocore") (v "0.0.0") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1mpj7xs5czsxv25236z107vcyyr06ainxw6mc87xsqc6d5wv5c8c")))

(define-public crate-iocore-0.0.1 (c (n "iocore") (v "0.0.1") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "036527fys2hqhn4x8g3zydqyq20nqmcmpk6ha5scaxzlrf6vdm7m")))

(define-public crate-iocore-0.0.10 (c (n "iocore") (v "0.0.10") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1mmib2rn5r1kqlhk24ibrxkai8rwiy9vr3aqpwg42y1qmkcbhcvd")))

(define-public crate-iocore-0.1.10 (c (n "iocore") (v "0.1.10") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "06ylxj19mmcy6iihl8b8z6akrvfgpsb06x5rfs5k3xvqjxnl3sxs")))

(define-public crate-iocore-0.1.11 (c (n "iocore") (v "0.1.11") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1zzrhswm2nm0lycqwmqp0s9dhy0y3fcmc9h6jbwdnrw09ka27nsp")))

(define-public crate-iocore-0.10.0 (c (n "iocore") (v "0.10.0") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1xdwl06ia9xk7vg1jdl45hv13h81da4lm729rwg7k9h6ca3drmvp")))

(define-public crate-iocore-0.100.1 (c (n "iocore") (v "0.100.1") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1n74v9gjrwlimkqjy2ynz2kndffdv3gvvfjjfb8r4wvg2z32qjlz")))

(define-public crate-iocore-0.101.0 (c (n "iocore") (v "0.101.0") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1nkcykgh8as8n98403nbsvi48f7rkgkk4b1k9zamxw2l3w3c37z3")))

(define-public crate-iocore-0.110.0 (c (n "iocore") (v "0.110.0") (d (list (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "sanitation") (r "^0.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.190") (f (quote ("derive" "alloc" "rc"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "0hdidwc57vhlkvlh2x1ydas15vp98mgryfm4yd13smrb6i93jvcs")))

(define-public crate-iocore-0.110.1 (c (n "iocore") (v "0.110.1") (d (list (d (n "chrono") (r "^0.4.31") (f (quote ("alloc" "serde"))) (d #t) (k 0)) (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "sanitation") (r "^0.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.190") (f (quote ("derive" "alloc" "rc"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1fq8nfg55pgx6qp9kf1gg89q155v3r6n82l3iqh7z62vdkzslhbd")))

(define-public crate-iocore-0.111.0 (c (n "iocore") (v "0.111.0") (d (list (d (n "chrono") (r "^0.4.31") (f (quote ("alloc" "serde"))) (d #t) (k 0)) (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.9.6") (f (quote ("use_std" "pattern" "logging" "perf-dfa-full"))) (d #t) (k 0)) (d (n "sanitation") (r "^0.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.190") (f (quote ("derive" "alloc" "rc"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "1s4grg8vqp10pr8b4z61ppclbflg2mn64czldnvwvxjvhm7zn54x")))

(define-public crate-iocore-0.111.1 (c (n "iocore") (v "0.111.1") (d (list (d (n "chrono") (r "^0.4.31") (f (quote ("alloc" "serde"))) (d #t) (k 0)) (d (n "glob") (r "^0.3.1") (d #t) (k 0)) (d (n "regex") (r "^1.10.3") (f (quote ("use_std"))) (d #t) (k 2)) (d (n "sanitation") (r "^0.0.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.190") (f (quote ("derive" "alloc" "rc"))) (d #t) (k 0)) (d (n "shellexpand") (r "^3.1.0") (f (quote ("full"))) (d #t) (k 0)) (d (n "walkdir") (r "^2.4.0") (d #t) (k 0)))) (h "067kljlcsjp85ia52d2k20pk743a3yvyjmnbygb1xm320bwdm4wf")))

