(define-module (crates-io at om atomic_lib) #:use-module (crates-io))

(define-public crate-atomic_lib-0.1.0 (c (n "atomic_lib") (v "0.1.0") (d (list (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)))) (h "0r962k95m3l0g67q6g2w34bhmg1g8qzk74npgqlh055sq1nnsbiq")))

(define-public crate-atomic_lib-0.5.0 (c (n "atomic_lib") (v "0.5.0") (d (list (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)))) (h "1pcwvwl4nbxp16ns0zjydphxvcni187nmnbzambk16fb5ln4l653")))

(define-public crate-atomic_lib-0.6.0 (c (n "atomic_lib") (v "0.6.0") (d (list (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)))) (h "1ydq43j3dcrm2fw8hzwnwbi4icaglw4yiz33v06vwkgrhpzjxca0")))

(define-public crate-atomic_lib-0.7.0 (c (n "atomic_lib") (v "0.7.0") (d (list (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)))) (h "1k5l9mkzqmw6iba4qq7kaijyfvz9qll85f1ap5gxlm7wvx0rpq9z")))

(define-public crate-atomic_lib-0.7.1 (c (n "atomic_lib") (v "0.7.1") (d (list (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)))) (h "0w57n872phsz70z3qj3ly8m9a2ksq4g8aljwm7bn15662wdwgrlk")))

(define-public crate-atomic_lib-0.8.1 (c (n "atomic_lib") (v "0.8.1") (d (list (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)))) (h "1ggwc40fw2pm8am3ljfdg0zyc5b67w2mq82m04crdka343spq34b")))

(define-public crate-atomic_lib-0.10.0 (c (n "atomic_lib") (v "0.10.0") (d (list (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)) (d (n "sled") (r "^0.34.3") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.4.0") (d #t) (k 0)))) (h "0q7cczz1cqyhc111mxsrxwsxcf5h91bai4m2qm712pb6mj2y1gh6") (f (quote (("db" "sled" "bincode"))))))

(define-public crate-atomic_lib-0.10.1 (c (n "atomic_lib") (v "0.10.1") (d (list (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "lazy-static-include") (r "^3.0.5") (d #t) (k 0)) (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)) (d (n "sled") (r "^0.34.3") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.4.0") (d #t) (k 0)))) (h "0n6p3z8g3s5aqbjm0yrr5kx2vxzxla24ngachlb3babjc1665rzl") (f (quote (("db" "sled" "bincode"))))))

(define-public crate-atomic_lib-0.11.0 (c (n "atomic_lib") (v "0.11.0") (d (list (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)) (d (n "sled") (r "^0.34.3") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.4.0") (d #t) (k 0)))) (h "1d5infwwxzs7pqd5hj64pjcam5a1c9npk10r3vm7zg4sl44kywmb") (f (quote (("db" "sled" "bincode"))))))

(define-public crate-atomic_lib-0.12.0 (c (n "atomic_lib") (v "0.12.0") (d (list (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)) (d (n "sled") (r "^0.34.3") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.4.0") (d #t) (k 0)))) (h "0v429gkw1355mhwf1h4xzz1l0vn5y34m7wxrkccy40is0yybf9yd") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode"))))))

(define-public crate-atomic_lib-0.13.0 (c (n "atomic_lib") (v "0.13.0") (d (list (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)) (d (n "sled") (r "^0.34.3") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.4.0") (d #t) (k 0)))) (h "0n7ilvgyci9ygp3qfjcsvw6qjbv3hx8x3sxj5b5b8n0cxmvvkksw") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode"))))))

(define-public crate-atomic_lib-0.15.0 (c (n "atomic_lib") (v "0.15.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.7.3") (d #t) (k 0)) (d (n "regex") (r "^1.3.9") (d #t) (k 0)) (d (n "ring") (r "^0.16.15") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.114") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.57") (d #t) (k 0)) (d (n "sled") (r "^0.34.3") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.4.0") (d #t) (k 0)) (d (n "url") (r "^2.1.1") (d #t) (k 0)))) (h "14cszv06lafp5v6q1ijblzm4r0waq7ff7k4vlmlyv24baviwzq0k") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode"))))))

(define-public crate-atomic_lib-0.17.0 (c (n "atomic_lib") (v "0.17.0") (d (list (d (n "base64") (r ">=0.13.0, <0.14.0") (d #t) (k 0)) (d (n "bincode") (r ">=1.3.1, <2.0.0") (o #t) (d #t) (k 0)) (d (n "dirs") (r ">=3.0.1, <4.0.0") (o #t) (d #t) (k 0)) (d (n "rand") (r ">=0.7.3, <0.8.0") (d #t) (k 0)) (d (n "regex") (r ">=1.3.9, <2.0.0") (d #t) (k 0)) (d (n "ring") (r ">=0.16.15, <0.17.0") (d #t) (k 0)) (d (n "rio_api") (r ">=0.5.0, <0.6.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r ">=0.5.0, <0.6.0") (o #t) (d #t) (k 0)) (d (n "serde") (r ">=1.0.114, <2.0.0") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r ">=1.0.57, <2.0.0") (d #t) (k 0)) (d (n "sled") (r ">=0.34.3, <0.35.0") (o #t) (d #t) (k 0)) (d (n "toml") (r ">=0.5.7, <0.6.0") (o #t) (d #t) (k 0)) (d (n "ureq") (r ">=1.4.0, <2.0.0") (d #t) (k 0)) (d (n "url") (r ">=2.1.1, <3.0.0") (d #t) (k 0)))) (h "0xg92zx5c38mkqiq7bx0yyvxfg53gzx5lxzxpxyvjy7l2zq7amhd") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.17.1 (c (n "atomic_lib") (v "0.17.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "19m5kcd7h2d7jr25nsmnm73b4wc4472adzaqbl807jl8zmxi1lck") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.17.2 (c (n "atomic_lib") (v "0.17.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "0w0vdp1zaz07qan259d322xglbaiwvavzhj9jwqyx58czpqbj1a5") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.18.0 (c (n "atomic_lib") (v "0.18.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "1acmy88vpx0plrkc45y2phz6mrxz4x0j8bh8sllrvd125xn4ddiy") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.19.0 (c (n "atomic_lib") (v "0.19.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "0qmimv8mipam6zawqqsfhg2ly0b4ap0gjms3v2z84pvh4djlqv5i") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.20.0 (c (n "atomic_lib") (v "0.20.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7.2") (d #t) (k 2)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "1f49k5z7zjqcdjyvgb1hh1pkgc5ak2wygca6278adv4fpmrpjiq2") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.20.1 (c (n "atomic_lib") (v "0.20.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7.2") (d #t) (k 2)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "08jnlz0wkfpx647yqm6zqicxi126mdxyzqax3q23514ixb8na4xz") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.21.0 (c (n "atomic_lib") (v "0.21.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7.2") (d #t) (k 2)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "0rsb28f4pf6xsvrrvvl2h05dvki4vkhlw0n7n26dlsz8zcil152b") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.22.0 (c (n "atomic_lib") (v "0.22.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7.2") (d #t) (k 2)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "05g1whn9zvxfl2qyj8sgg6v4kbz4wh6sm08rl48kbpqwd8r0hyip") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.22.3 (c (n "atomic_lib") (v "0.22.3") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.1") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7.2") (d #t) (k 2)) (d (n "rand") (r "^0.8.0") (d #t) (k 0)) (d (n "regex") (r "^1.4.2") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.0") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.118") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.60") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.0") (d #t) (k 0)))) (h "04ac02va7x4qvr8p02acin07ymf54x67m83fj5zcqxn47j6zmb2j") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.23.0 (c (n "atomic_lib") (v "0.23.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)))) (h "1nmj06dh95sgh9xjzzzbcz0j7mggca6bsazkhyvq5qgk70falnmh") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.23.2 (c (n "atomic_lib") (v "0.23.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)))) (h "15dp905mi1xripbf7wjf9bzkzlvqgw77x7r1gjs5y6fq4b2v2jaj") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.23.3 (c (n "atomic_lib") (v "0.23.3") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)))) (h "1wxhf1cy9hac466c21ym1w4qawi7m27ph02fwff6vfdc3vf387aj") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.24.0 (c (n "atomic_lib") (v "0.24.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "1wc49ng39vip8z3ib7w3dm8yjlkaflrlxk313xijzna2iiv8j0qf") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.24.1 (c (n "atomic_lib") (v "0.24.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "02hfpw0ipljzb06vq5vbh1zv7f0smq8hrxb7nis5hwsvfmbcg9n6") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.24.2 (c (n "atomic_lib") (v "0.24.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "09j7rybhqlfbvs3kiyasimiz5fanl2v64w96zyvhm3ha5l9m9bmz") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.25.0 (c (n "atomic_lib") (v "0.25.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "1483cyn61q2ff1a1njadlbk04nv3vmirs4fik5sci058013m6i50") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml")))) (y #t)))

(define-public crate-atomic_lib-0.25.1 (c (n "atomic_lib") (v "0.25.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "1i84h9myhpfbim6p5sw8virqr08r3dn49ynapvhzgxqxz36cz83c") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.25.2 (c (n "atomic_lib") (v "0.25.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "132bsjdmgfs4l8mkb20dpn9bbvywigjr28gs4q0nzifjf2139x5w") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.25.3 (c (n "atomic_lib") (v "0.25.3") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "1dg3nq540bpflzqhfi2bh95br7j5n6v1mzdmw670c26dlkas5fz9") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.25.6 (c (n "atomic_lib") (v "0.25.6") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "0vz9sw2wzgvj5idgbd4544qg6mzw97yccm3avvdjz7nsv19bp475") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.26.0 (c (n "atomic_lib") (v "0.26.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "0gcpw523d1i87xpibij13mrjsdwch9rdl2rjlx1mfxa9v7hixqhs") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.26.1 (c (n "atomic_lib") (v "0.26.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^3.0.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.5.3") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^1.3.3") (d #t) (k 0)))) (h "1ji267wfvfawyxg6in3xipqkq391zqswsm87zb2igxcpm8cxbvdm") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.26.2 (c (n "atomic_lib") (v "0.26.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "1s21pvlhjbddx1vfdvy746sbvrzrwhln89dvsfk0xhgdgq1sfvwn") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.27.0 (c (n "atomic_lib") (v "0.27.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "0ml236lvd1g3rfd2f7glv2pvprpk2fwmnfsajlzzwcvc2871grrp") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.27.1 (c (n "atomic_lib") (v "0.27.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "0symqgym7ig41da1ba09nrw7blh4qivz0jacq62i2k4r6vzll8qc") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.28.0 (c (n "atomic_lib") (v "0.28.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "0iigq9r54gdccmmr8f5q97wksifn4vz2z0iq0nr5wr4hjd0jqwrr") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.28.1 (c (n "atomic_lib") (v "0.28.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "076pyih8w7ki3lhqfinimibf95m3w2xrxs2qp088qgbbjwbdk6wg") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.28.2 (c (n "atomic_lib") (v "0.28.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "09hwxrzn7i4lpp7dnbyc13z7696a97m0m0rlvppd52yxv1i94346") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.29.0 (c (n "atomic_lib") (v "0.29.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "11alj1xrkgfd0av2bnk1zpxiyigngkln6jjp9sm42lmpiskk2vsx") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.29.2 (c (n "atomic_lib") (v "0.29.2") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "0456lh65xmhi0q9ivz8809ilhjldz299iqz481cxwzlhl2qbvdvd") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.30.0 (c (n "atomic_lib") (v "0.30.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "082xj6wp26k9rff7rnqdrblhb0arxkm10r3gm75q4dvlhnpv94al") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.30.1 (c (n "atomic_lib") (v "0.30.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1.29") (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "00yxmpykhjpixf6sdar6d724q6xaar0dqs4lmqf1nfcfr80xmimr") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.30.3 (c (n "atomic_lib") (v "0.30.3") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1.29") (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "11pm2lx0hjjqncl84x638i9m0hfmq9y21hvc17h7w4ckpfa0n6a4") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.30.4 (c (n "atomic_lib") (v "0.30.4") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1.29") (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "1d2a8alc8bvq1akih3kfz1fh49wi0sih7nrrg76xnk3pfzq67ir9") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.31.0 (c (n "atomic_lib") (v "0.31.0") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1.29") (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "0jnmy03npg26824m6lbzf7fcrxqrxb57304q7lz5nib8rk2ksk78") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.31.1 (c (n "atomic_lib") (v "0.31.1") (d (list (d (n "base64") (r "^0.13.0") (d #t) (k 0)) (d (n "bincode") (r "^1.3.2") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "dirs") (r "^4.0.0") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "lazy_static") (r "^1.4.0") (d #t) (k 2)) (d (n "ntest") (r "^0.7.3") (d #t) (k 2)) (d (n "rand") (r "^0.8.3") (d #t) (k 0)) (d (n "regex") (r "^1.4.5") (d #t) (k 0)) (d (n "ring") (r "^0.16.20") (d #t) (k 0)) (d (n "rio_api") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.6.1") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1.0.125") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1.0.64") (d #t) (k 0)) (d (n "sled") (r "^0.34.6") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5.8") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1.29") (d #t) (k 0)) (d (n "ureq") (r "^1.5.4") (d #t) (k 0)) (d (n "url") (r "^2.2.1") (d #t) (k 0)) (d (n "urlencoding") (r "^2.1.0") (d #t) (k 0)))) (h "11pjd8zy109rqh21mlrgvayn9a9pw7fg62ryij6kqdi5gbk9mw2i") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "dirs" "toml"))))))

(define-public crate-atomic_lib-0.32.0 (c (n "atomic_lib") (v "0.32.0") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "0k83pwgc7r1r38g9jxs2sh759s4grv0xmlq13g0jx283642v24aw") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.32.1 (c (n "atomic_lib") (v "0.32.1") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "19w616xajg5v6l42kgf94jpw2af5y2mx35s57722gjlnr4hygp9s") (f (quote (("rdf" "rio_api" "rio_turtle") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.33.0 (c (n "atomic_lib") (v "0.33.0") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "12smhx05bmyy7qqdqz6vi93igd9ji9gq3qshqw7k2r802hmzi3fq") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.33.1 (c (n "atomic_lib") (v "0.33.1") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "16bm65chw6qfk13wprk209057ll5b726fxgk7kf2a6qi9v9hpw6p") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.34.0 (c (n "atomic_lib") (v "0.34.0") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "1dji71f722c6yv2f1pjf1qd3h6dd3rnh2pl34fxw3gq0k41q71xd") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.34.1 (c (n "atomic_lib") (v "0.34.1") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "1h7gkgv4b4j1l07q3wmmk0zlw023jdh5a0pf35hbp4h2z1yikkhl") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.34.2 (c (n "atomic_lib") (v "0.34.2") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "15yp1kzsbdw7gdy7mib8fvfvl9r1xdzahh9kfa7942w1hb76afq1") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml")))) (y #t)))

(define-public crate-atomic_lib-0.34.3 (c (n "atomic_lib") (v "0.34.3") (d (list (d (n "base64") (r "^0.13") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.3") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.13") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.7") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.5") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "1ydxlir3drxys5qnjifl3zs6qkr1y5iasz81c2jrnxjydys0d07d") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.34.5 (c (n "atomic_lib") (v "0.34.5") (d (list (d (n "base64") (r "^0.21") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.4") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchiki") (r "^0.8.1") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.9") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "10fg8py63jijh84r125kh2wp0ddwdd551l4hm62pqipsbsciiynv") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.36.0 (c (n "atomic_lib") (v "0.36.0") (d (list (d (n "base64") (r "^0.21") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.4") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchikiki") (r "^0.8.2") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.9") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.16.19") (d #t) (k 0)) (d (n "rio_api") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "0kxzqvf6qar2izqb96xvn9p5pja437dnv3pyilkkyih1hj94rkbh") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchikiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.36.1 (c (n "atomic_lib") (v "0.36.1") (d (list (d (n "base64") (r "^0.21") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.4") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchikiki") (r "^0.8.2") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^0.3.1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.9") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.17.6") (d #t) (k 0)) (d (n "rio_api") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.7") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "1pxrbvynvas1xgldgm0c40000dls289h7qmascfnmxs733iw3dqq") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchikiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

(define-public crate-atomic_lib-0.37.0 (c (n "atomic_lib") (v "0.37.0") (d (list (d (n "base64") (r "^0.21") (d #t) (k 0)) (d (n "bincode") (r "^1") (o #t) (d #t) (k 0)) (d (n "criterion") (r "^0.5") (d #t) (k 2)) (d (n "directories") (r ">=2, <5") (o #t) (d #t) (k 0)) (d (n "html2md") (r "^0.2.14") (o #t) (d #t) (k 0)) (d (n "iai") (r "^0.1") (d #t) (k 2)) (d (n "kuchikiki") (r "^0.8.2") (o #t) (d #t) (k 0)) (d (n "lazy_static") (r "^1") (d #t) (k 2)) (d (n "lol_html") (r "^1") (o #t) (d #t) (k 0)) (d (n "ntest") (r "^0.9") (d #t) (k 2)) (d (n "rand") (r "^0.8") (d #t) (k 0)) (d (n "regex") (r "^1") (d #t) (k 0)) (d (n "ring") (r "^0.17.6") (d #t) (k 0)) (d (n "rio_api") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "rio_turtle") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "serde") (r "^1") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_jcs") (r "^0.1.0") (d #t) (k 0)) (d (n "serde_json") (r "^1") (d #t) (k 0)) (d (n "sled") (r "^0.34") (f (quote ("no_logs"))) (o #t) (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)) (d (n "tracing") (r "^0.1") (d #t) (k 0)) (d (n "ureq") (r "^2") (d #t) (k 0)) (d (n "url") (r "^2") (d #t) (k 0)) (d (n "urlencoding") (r "^2") (d #t) (k 0)))) (h "1pkyl8icnkrlidcgp54bzazsljnh3ghmwfg1qimkr1zxfk0g6zjf") (f (quote (("rdf" "rio_api" "rio_turtle") ("html" "kuchikiki" "lol_html" "html2md") ("db" "sled" "bincode") ("config" "directories" "toml"))))))

