(define-module (crates-io ti gh tighterror-build) #:use-module (crates-io))

(define-public crate-tighterror-build-0.0.2 (c (n "tighterror-build") (v "0.0.2") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "191ynxx7vykghl874nr02ymaf5m66lpd5ndyifk0pv1dla0r4x2k") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.3 (c (n "tighterror-build") (v "0.0.3") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "1z7y8y2c7jrdgw6bzi6rca4jkqbdfgqwkii1iipsw51fycd3372r") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.4 (c (n "tighterror-build") (v "0.0.4") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "01mhvqh2lihcp2z34zdgz8hgq8p6p6k3075h78js936h143n26mx") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.5 (c (n "tighterror-build") (v "0.0.5") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tighterror") (r "^0.0.5") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "1lgvypsviwf19lfnvzm2la4dgcy270w33vpfvwg351yrpkizwfms") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.6 (c (n "tighterror-build") (v "0.0.6") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.10") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tighterror") (r "^0.0.6") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "103z2hd4awi8qjmh4fyrgbc3hf31x1sxf10rzglpzfcxlhjgg1rg") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.7 (c (n "tighterror-build") (v "0.0.7") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tighterror") (r "^0.0.7") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "1c6mjs13vly82p288123swhfhrkgjasxiqgcqjynjzr7318qbja3") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.8 (c (n "tighterror-build") (v "0.0.8") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.8") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "1v9q43g1gg3mzfkhi0q3pvacqzcw21p5afxp0n4wkyygxw9wkkg1") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.9 (c (n "tighterror-build") (v "0.0.9") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.9") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "0d1fnpwy05zz6fws58ygb7fkacgc6iiy81s9p0anqszlv5rlv99m") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.10 (c (n "tighterror-build") (v "0.0.10") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.10") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "08qrkzqvfbzqg1df23kbd51zxn8zns1k2mnjbl3w01c0chjwy9pv") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.11 (c (n "tighterror-build") (v "0.0.11") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.11") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "1v2x7d5f6777xf8a6rrl5vfaxjb5bw86zsqgi3lipkgz0ydgarch") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.12 (c (n "tighterror-build") (v "0.0.12") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.12") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "16p3ijalirp7rvpm70wvf8vl91bcc3q3lpk08pihbg0jvdvm7vxl") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.13 (c (n "tighterror-build") (v "0.0.13") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.13") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "1sqwdm8f0svc6fm2i0ki0928yial476p9a4zy93nm09g7cv03cxf") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.14 (c (n "tighterror-build") (v "0.0.14") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.14") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "0h594g24j509665qz5py5ycprin232lz3mslskiy3w27i040apxi") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

(define-public crate-tighterror-build-0.0.15 (c (n "tighterror-build") (v "0.0.15") (d (list (d (n "cfg-if") (r "^1.0.0") (d #t) (k 0)) (d (n "convert_case") (r "^0.6.0") (d #t) (k 0)) (d (n "env_logger") (r "^0.11.1") (d #t) (k 2)) (d (n "log") (r "^0.4") (d #t) (k 0)) (d (n "prettyplease") (r "^0.2") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0") (d #t) (k 0)) (d (n "quote") (r "^1.0") (d #t) (k 0)) (d (n "regex") (r "^1.10") (d #t) (k 0)) (d (n "serde") (r "^1") (d #t) (k 0)) (d (n "serde_yaml") (r "^0.9") (o #t) (d #t) (k 0)) (d (n "syn") (r "^2.0") (f (quote ("parsing"))) (k 0)) (d (n "tempfile") (r "^3.10.0") (d #t) (k 0)) (d (n "tighterror") (r "^0.0.15") (d #t) (k 0)) (d (n "toml") (r "^0.8") (o #t) (d #t) (k 0)))) (h "0xc52vq6kwqs11g0kxizp72ja639785iwiw86vkqpsi8n0kpqm4v") (f (quote (("default" "yaml" "toml")))) (s 2) (e (quote (("yaml" "dep:serde_yaml") ("toml" "dep:toml"))))))

