(define-module (crates-io co nf configure-semantic-release-manifest) #:use-module (crates-io))

(define-public crate-configure-semantic-release-manifest-1.0.0 (c (n "configure-semantic-release-manifest") (v "1.0.0") (d (list (d (n "clap") (r "=4.0.32") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "^0.10.0") (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "serde") (r "^1.0.137") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.81") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "11ckp48lgazrjn5268kifa2hld5nrhaj38x5hr3ysgzpcwr81iwq")))

(define-public crate-configure-semantic-release-manifest-1.0.1 (c (n "configure-semantic-release-manifest") (v "1.0.1") (d (list (d (n "clap") (r "=4.0.32") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "^0.10.0") (k 0)) (d (n "log") (r "^0.4.17") (d #t) (k 0)) (d (n "serde") (r "^1.0.137") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.81") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0gfnzy5wadcm3fhsn2sra3fy03dgp8k1wyywxadcn6wbilwxhb2h")))

(define-public crate-configure-semantic-release-manifest-1.0.2 (c (n "configure-semantic-release-manifest") (v "1.0.2") (d (list (d (n "clap") (r "=4.0.32") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.137") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.81") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0fsh6gish6icjqlv38z9ifyxf2a3a11fgbww1b0r7dkxl03fyrh6")))

(define-public crate-configure-semantic-release-manifest-1.0.3 (c (n "configure-semantic-release-manifest") (v "1.0.3") (d (list (d (n "clap") (r "=4.0.32") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.81") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "02rgcyid0hlv85p2jp5j2kdhq6w21f543kcb1fx69dy1agwzdkj1")))

(define-public crate-configure-semantic-release-manifest-1.0.4 (c (n "configure-semantic-release-manifest") (v "1.0.4") (d (list (d (n "clap") (r "=4.0.32") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.91") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0739h39gxf60r5rwzhcswbw4pd1bxwz3fxzh9c6dqf4p61wamz9r")))

(define-public crate-configure-semantic-release-manifest-1.0.5 (c (n "configure-semantic-release-manifest") (v "1.0.5") (d (list (d (n "clap") (r "=4.1.1") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.91") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0jc9h088n3qid0yjfqjsmn5gfil17l7br28y99xl048jy0r21gc7")))

(define-public crate-configure-semantic-release-manifest-1.0.6 (c (n "configure-semantic-release-manifest") (v "1.0.6") (d (list (d (n "clap") (r "=4.1.1") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.91") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0wdrjv9yll4zrvnj3k2g8r974a8nc0br750mj2wvcc1zwhd5249i")))

(define-public crate-configure-semantic-release-manifest-1.0.7 (c (n "configure-semantic-release-manifest") (v "1.0.7") (d (list (d (n "clap") (r "=4.1.4") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.91") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "13jznvx9d06r10asdbgk2cxpbvy04bxdjgwbyq1khbpmdjpfr4x6")))

(define-public crate-configure-semantic-release-manifest-1.0.8 (c (n "configure-semantic-release-manifest") (v "1.0.8") (d (list (d (n "clap") (r "=4.1.4") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.92") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "1bln1r952zwm33s195r5igfvy336j7slxphwk15ssb48jkqlm1r3")))

(define-public crate-configure-semantic-release-manifest-1.0.9 (c (n "configure-semantic-release-manifest") (v "1.0.9") (d (list (d (n "clap") (r "=4.1.4") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0zximrs8jxp7n2hhzb782d94qm3s0mrgwhn6miinjfsrwnk6gj3g")))

(define-public crate-configure-semantic-release-manifest-1.0.10 (c (n "configure-semantic-release-manifest") (v "1.0.10") (d (list (d (n "clap") (r "=4.1.6") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde") (r "=1.0.152") (f (quote ("derive"))) (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0xvprzq8hhlzzgjdvx4vrn0gbli3qbgj8jqsmpj1fsbin8bpqgy2")))

(define-public crate-configure-semantic-release-manifest-1.0.11 (c (n "configure-semantic-release-manifest") (v "1.0.11") (d (list (d (n "clap") (r "=4.1.6") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "1g59k7m9q90gq5s28mkynf9bs06rgxmzzr0i50a1x4byax382pfp")))

(define-public crate-configure-semantic-release-manifest-1.0.12 (c (n "configure-semantic-release-manifest") (v "1.0.12") (d (list (d (n "clap") (r "=4.1.6") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.4") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)) (d (n "thiserror") (r "=1.0.38") (d #t) (k 0)))) (h "0c26ff086a4k8bz4c2nmn09hs8wly36cv12v43ibamcvqr69gyhf")))

(define-public crate-configure-semantic-release-manifest-1.0.13 (c (n "configure-semantic-release-manifest") (v "1.0.13") (d (list (d (n "clap") (r "=4.1.6") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "08zx4q389d6qlh3nff30mmxfrzqkc40nn3sl9nwzcmd80840znv1")))

(define-public crate-configure-semantic-release-manifest-1.0.14 (c (n "configure-semantic-release-manifest") (v "1.0.14") (d (list (d (n "clap") (r "=4.1.7") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "14x1fqgj82r2vbxplr3jm2gglmc29fjdk7qlxyy1bm215ji4vw7d")))

(define-public crate-configure-semantic-release-manifest-1.0.15 (c (n "configure-semantic-release-manifest") (v "1.0.15") (d (list (d (n "clap") (r "=4.1.8") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.93") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0wai48ks9j8l9yc13xih0bg5fx4jafk1bf4qn83k4kbahcv0z0f9")))

(define-public crate-configure-semantic-release-manifest-1.0.16 (c (n "configure-semantic-release-manifest") (v "1.0.16") (d (list (d (n "clap") (r "=4.1.8") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0xg9br2h4kn871ckpr21da0lx518v2smljjis89i70qvk2g84g5b")))

(define-public crate-configure-semantic-release-manifest-1.0.17 (c (n "configure-semantic-release-manifest") (v "1.0.17") (d (list (d (n "clap") (r "=4.1.9") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "19r46cbwp8x90i3nvx1nm3h1wq02nr3lic2glzdkqj2afl8gyacv")))

(define-public crate-configure-semantic-release-manifest-1.0.18 (c (n "configure-semantic-release-manifest") (v "1.0.18") (d (list (d (n "clap") (r "=4.1.10") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1xwjjgqgww9v85sbrma6mpna24v4w3wfb73ysr3568rvy1dgr3yh")))

(define-public crate-configure-semantic-release-manifest-1.0.19 (c (n "configure-semantic-release-manifest") (v "1.0.19") (d (list (d (n "clap") (r "=4.1.11") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0m8b7inx9dnwb7sywl01ivfqvnlmclwzpi7wgaab9nrfq3p8afq4")))

(define-public crate-configure-semantic-release-manifest-1.0.20 (c (n "configure-semantic-release-manifest") (v "1.0.20") (d (list (d (n "clap") (r "=4.1.13") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.2") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "12pk7y3jd5q4nzx95j23ciw15hdml2ygzp05hk6rv0lv3iasnx08")))

(define-public crate-configure-semantic-release-manifest-1.0.21 (c (n "configure-semantic-release-manifest") (v "1.0.21") (d (list (d (n "clap") (r "=4.1.13") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1gi3r96b6qs7r3kakg8ap3qdjv5jq4isa2npmkgbnf4n32hhcnfh")))

(define-public crate-configure-semantic-release-manifest-1.0.22 (c (n "configure-semantic-release-manifest") (v "1.0.22") (d (list (d (n "clap") (r "=4.1.14") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.94") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1l0c1hhpz8h0c62yli0891x437a8mrkcgl1g6m7l66wspca49cdm")))

(define-public crate-configure-semantic-release-manifest-1.0.23 (c (n "configure-semantic-release-manifest") (v "1.0.23") (d (list (d (n "clap") (r "=4.1.14") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.95") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0spc579nvjsy6k9zirvrmsbs3rcch16969kj4nyd04f8dwnb9l3q")))

(define-public crate-configure-semantic-release-manifest-1.0.24 (c (n "configure-semantic-release-manifest") (v "1.0.24") (d (list (d (n "clap") (r "=4.2.0") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.95") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0i5xjjxc3s3pv84l69wsgzghf0g5fxfzkzird2scy6izrq9j7lgy")))

(define-public crate-configure-semantic-release-manifest-1.0.25 (c (n "configure-semantic-release-manifest") (v "1.0.25") (d (list (d (n "clap") (r "=4.2.1") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.95") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1vn0amkshy8fpldk3syfknvzyc72s7hysh0jila4nvjnm15sjfim")))

(define-public crate-configure-semantic-release-manifest-1.0.26 (c (n "configure-semantic-release-manifest") (v "1.0.26") (d (list (d (n "clap") (r "=4.2.1") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1hvfhxchl3hlbmkh4rgl6hczz3d7bv448nz2zs4zpk0bm75pfd6i")))

(define-public crate-configure-semantic-release-manifest-1.0.27 (c (n "configure-semantic-release-manifest") (v "1.0.27") (d (list (d (n "clap") (r "=4.2.2") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1hhvxlif85k6di8lx3xs6j9w0gs5zgdsh7i24xj8vry2q8wbismb")))

(define-public crate-configure-semantic-release-manifest-1.0.28 (c (n "configure-semantic-release-manifest") (v "1.0.28") (d (list (d (n "clap") (r "=4.2.3") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0na0nxn0yc7a38h3wd08ac722mp93rh37fnfnjyyk34cz63cq986")))

(define-public crate-configure-semantic-release-manifest-1.0.29 (c (n "configure-semantic-release-manifest") (v "1.0.29") (d (list (d (n "clap") (r "=4.2.4") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1q3ll2z25m3rdsvwvwizvp0533ml5s2zfgn5n2kdqg1c7yyl9yps")))

(define-public crate-configure-semantic-release-manifest-1.0.30 (c (n "configure-semantic-release-manifest") (v "1.0.30") (d (list (d (n "clap") (r "=4.2.5") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0f4l9spdyak8a7y2aqbl6avf2kmv7g7868cspjh1hgc5wsv2g233")))

(define-public crate-configure-semantic-release-manifest-1.0.31 (c (n "configure-semantic-release-manifest") (v "1.0.31") (d (list (d (n "clap") (r "=4.2.7") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.5") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "05b2k3l4qb1j133889zs1xr71lml765y46crlb4x3c6yyjxhjhy3")))

(define-public crate-configure-semantic-release-manifest-1.0.32 (c (n "configure-semantic-release-manifest") (v "1.0.32") (d (list (d (n "clap") (r "=4.2.7") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.7") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "08b35bykqzrala0kfiz4ac2xr8iicdgnak1lb92i5cclv33qn814")))

(define-public crate-configure-semantic-release-manifest-1.0.33 (c (n "configure-semantic-release-manifest") (v "1.0.33") (d (list (d (n "clap") (r "=4.2.7") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0xhdnhmxwg16x86r5qdnxbbl5wvw5rds3la8dx1pi5gsciwi5f3v")))

(define-public crate-configure-semantic-release-manifest-1.0.34 (c (n "configure-semantic-release-manifest") (v "1.0.34") (d (list (d (n "clap") (r "=4.2.7") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1r9v22nrg2i4a5yf2hhqmzvkmlxz10q3hb6c45ar0mcywnyivpkc")))

(define-public crate-configure-semantic-release-manifest-1.0.35 (c (n "configure-semantic-release-manifest") (v "1.0.35") (d (list (d (n "clap") (r "=4.3.0") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.17") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0v04d97v9l1v9d9fss7w4vp6j87pnz43mmiqhi02g7widm5q5b87")))

(define-public crate-configure-semantic-release-manifest-1.0.36 (c (n "configure-semantic-release-manifest") (v "1.0.36") (d (list (d (n "clap") (r "=4.3.0") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.18") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0bk1kxbx4gffbdg7l2f97d704yzfqcs3lsb51whg7mh584ifg661")))

(define-public crate-configure-semantic-release-manifest-1.0.37 (c (n "configure-semantic-release-manifest") (v "1.0.37") (d (list (d (n "clap") (r "=4.3.1") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.18") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0ypvv5alhndbrmv8hr3m76ycmlwin521rw3rkwiif3cgi0dzyy1s")))

(define-public crate-configure-semantic-release-manifest-1.0.38 (c (n "configure-semantic-release-manifest") (v "1.0.38") (d (list (d (n "clap") (r "=4.3.2") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.18") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0sfp51f6mm672vkr7c1sszkh928bm0m8lwgfhr5cab1s8ivkgcyn")))

(define-public crate-configure-semantic-release-manifest-1.0.39 (c (n "configure-semantic-release-manifest") (v "1.0.39") (d (list (d (n "clap") (r "=4.3.3") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.18") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0g60rb49yy28f1picmividsdv7hsxbqwpizmdqhf6psm4mjv8ckx")))

(define-public crate-configure-semantic-release-manifest-1.0.40 (c (n "configure-semantic-release-manifest") (v "1.0.40") (d (list (d (n "clap") (r "=4.3.3") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0jhz0f6iz5x8kbndv8y0pmafdscajjjdrm9rbr7zlb3xznwh7gah")))

(define-public crate-configure-semantic-release-manifest-1.0.41 (c (n "configure-semantic-release-manifest") (v "1.0.41") (d (list (d (n "clap") (r "=4.3.4") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.96") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "08rdkw7k5hmdvaw95gga4c8fhyc48brzxfz9zv8wdgq7d32nblql")))

(define-public crate-configure-semantic-release-manifest-1.0.42 (c (n "configure-semantic-release-manifest") (v "1.0.42") (d (list (d (n "clap") (r "=4.3.4") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.97") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "01kf8kvrm17zrbnjdx46a6g30ygqmgsigprmdfxkxh4qkmij8778")))

(define-public crate-configure-semantic-release-manifest-1.0.43 (c (n "configure-semantic-release-manifest") (v "1.0.43") (d (list (d (n "clap") (r "=4.3.5") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.97") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1i6dw7p25d57s8hivlachj47k195v0p8azn0cnz06wx6igw75lxp")))

(define-public crate-configure-semantic-release-manifest-1.0.44 (c (n "configure-semantic-release-manifest") (v "1.0.44") (d (list (d (n "clap") (r "=4.3.8") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.97") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0zmjkm4481aki5mxvgcwwfbc8l2vzr5z3b3kwsfqswmp0bfpg4kc")))

(define-public crate-configure-semantic-release-manifest-1.0.45 (c (n "configure-semantic-release-manifest") (v "1.0.45") (d (list (d (n "clap") (r "=4.3.8") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=1.9.3") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.99") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1lshmyby9kyncnnrkjnhr7hrbmkh2l9xnldvfvkqilyyi7v7vi55")))

(define-public crate-configure-semantic-release-manifest-1.0.46 (c (n "configure-semantic-release-manifest") (v "1.0.46") (d (list (d (n "clap") (r "=4.3.8") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.99") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "034x2zybca3qnqkp108r9r67cglvs3d072bpvp6867cd5nb87df3")))

(define-public crate-configure-semantic-release-manifest-1.0.47 (c (n "configure-semantic-release-manifest") (v "1.0.47") (d (list (d (n "clap") (r "=4.3.9") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.99") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1rbf6y3w3vs8iwr4xnmbnzi5rm899wjhxvagxz05jwb5wv3057ld")))

(define-public crate-configure-semantic-release-manifest-1.0.48 (c (n "configure-semantic-release-manifest") (v "1.0.48") (d (list (d (n "clap") (r "=4.3.10") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.99") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1yfa0xw51gv41pyjkvkn3n9s6agviarssl979p5002xm4fhgzz9d")))

(define-public crate-configure-semantic-release-manifest-1.0.49 (c (n "configure-semantic-release-manifest") (v "1.0.49") (d (list (d (n "clap") (r "=4.3.10") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.100") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "122kq4vaizbncjyjipk83lg3z3pbcgfpp4iblj1na3lshc8r15kr")))

(define-public crate-configure-semantic-release-manifest-1.0.50 (c (n "configure-semantic-release-manifest") (v "1.0.50") (d (list (d (n "clap") (r "=4.3.11") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.100") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0ihflk4ycca3yhsgvwwdqsn111flqvwf6d0gz6yqvilg8rbmjd9b")))

(define-public crate-configure-semantic-release-manifest-1.0.51 (c (n "configure-semantic-release-manifest") (v "1.0.51") (d (list (d (n "clap") (r "=4.3.11") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.102") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0m2vl9vnb8bjz0lhwdpqa91cbcppycvc78hg97k7j7j6isc1frhw")))

(define-public crate-configure-semantic-release-manifest-1.0.52 (c (n "configure-semantic-release-manifest") (v "1.0.52") (d (list (d (n "clap") (r "=4.3.12") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.102") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0cm04zmv3imh4a2s1bb2c4r90f7vdi6lcm89rf6sg2mlmny3nn0b")))

(define-public crate-configure-semantic-release-manifest-1.0.53 (c (n "configure-semantic-release-manifest") (v "1.0.53") (d (list (d (n "clap") (r "=4.3.12") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.103") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "16gpxvmq6bz3v46134qfinimmn7mxsjlpld0njap6rciqdp3l8cv")))

(define-public crate-configure-semantic-release-manifest-1.0.54 (c (n "configure-semantic-release-manifest") (v "1.0.54") (d (list (d (n "clap") (r "=4.3.15") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.103") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "091l531rrbcv6n38630nxc55jkxvfrmzvfynjjpk2hvnq0airv2h")))

(define-public crate-configure-semantic-release-manifest-1.0.55 (c (n "configure-semantic-release-manifest") (v "1.0.55") (d (list (d (n "clap") (r "=4.3.16") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.103") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1213m9j5vlfj5gyz4naqcx4j3iwlgf4zgrb6mag50734cqgg757l")))

(define-public crate-configure-semantic-release-manifest-1.0.56 (c (n "configure-semantic-release-manifest") (v "1.0.56") (d (list (d (n "clap") (r "=4.3.17") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.103") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "18p76pi6m1vpv17gy370ds7kfgl62zp55jl7ik574mr9vm9s5plh")))

(define-public crate-configure-semantic-release-manifest-1.0.57 (c (n "configure-semantic-release-manifest") (v "1.0.57") (d (list (d (n "clap") (r "=4.3.19") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.103") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0lsc2q5rds719cskyq4zx6q054y5wl6a1wdsha3ckz60rdlpj068")))

(define-public crate-configure-semantic-release-manifest-1.0.58 (c (n "configure-semantic-release-manifest") (v "1.0.58") (d (list (d (n "clap") (r "=4.3.19") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.104") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1xwi0s7w3mcxfcfv706rcp98gfx03qbj2a55kzmrj009qcdncymx")))

(define-public crate-configure-semantic-release-manifest-1.0.59 (c (n "configure-semantic-release-manifest") (v "1.0.59") (d (list (d (n "clap") (r "=4.3.21") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.19") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.104") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1ldd2jw1sd4nv12agkpk9ki20yjlqdpwcjxfrayzbbgpgn4nwdwv")))

(define-public crate-configure-semantic-release-manifest-1.0.60 (c (n "configure-semantic-release-manifest") (v "1.0.60") (d (list (d (n "clap") (r "=4.3.21") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.104") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0qwb9plz01kl1ilbgsrnj25kr2s1sy8hcbz5yql0z30wf94mpwdc")))

(define-public crate-configure-semantic-release-manifest-1.0.61 (c (n "configure-semantic-release-manifest") (v "1.0.61") (d (list (d (n "clap") (r "=4.3.21") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "02k65i0h10din1q1jh2anjz5n4nvzwdz5m25cgxa8113sp85an46")))

(define-public crate-configure-semantic-release-manifest-1.0.62 (c (n "configure-semantic-release-manifest") (v "1.0.62") (d (list (d (n "clap") (r "=4.3.22") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0na79ixhhcy566l9dynbb21nx3g1wzw4ihkdqdqlrdjm4lx9w9dc")))

(define-public crate-configure-semantic-release-manifest-1.0.63 (c (n "configure-semantic-release-manifest") (v "1.0.63") (d (list (d (n "clap") (r "=4.3.23") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0k841fwl4pfgrcd6d8imqagrwzyyh261cxc9aqnbqbghjxvfnnra")))

(define-public crate-configure-semantic-release-manifest-1.0.64 (c (n "configure-semantic-release-manifest") (v "1.0.64") (d (list (d (n "clap") (r "=4.3.24") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1y7rw7z1g97v5ka0ilifjrslsfd6kcjw18vhd8x3irw2h6m7k72c")))

(define-public crate-configure-semantic-release-manifest-1.0.65 (c (n "configure-semantic-release-manifest") (v "1.0.65") (d (list (d (n "clap") (r "=4.4.0") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1ia6z82krswjlja078rs7yj1svc2k67n4s83pa7dphbynhhqm5qn")))

(define-public crate-configure-semantic-release-manifest-1.0.66 (c (n "configure-semantic-release-manifest") (v "1.0.66") (d (list (d (n "clap") (r "=4.4.1") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "1x1ar1i1ayp42zkrzblmv862xhd74i1zcm17yyprfnh7vgmhx7w4")))

(define-public crate-configure-semantic-release-manifest-1.0.67 (c (n "configure-semantic-release-manifest") (v "1.0.67") (d (list (d (n "clap") (r "=4.4.2") (f (quote ("cargo" "derive" "wrap_help"))) (d #t) (k 0)) (d (n "env_logger") (r "=0.10.0") (k 0)) (d (n "find-semantic-release-config") (r "=1.0.8") (d #t) (k 0)) (d (n "indexmap") (r "=2.0.0") (f (quote ("serde"))) (d #t) (k 0)) (d (n "log") (r "=0.4.20") (d #t) (k 0)) (d (n "serde_json") (r "=1.0.105") (f (quote ("preserve_order"))) (d #t) (k 0)))) (h "0w5cx38zfsfilr8afdwzwnwsp0jwr2xrbc5ndv0c5n89rfhqk83d")))

