(define-module (crates-io gd na gdnative_bindings_generator) #:use-module (crates-io))

(define-public crate-gdnative_bindings_generator-0.1.0 (c (n "gdnative_bindings_generator") (v "0.1.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.3") (d #t) (k 0)))) (h "0g6n1whdd08v40q18bg5jy7qprfxy8fxwvrrdr6dhajn4myp4lfa")))

(define-public crate-gdnative_bindings_generator-0.2.0 (c (n "gdnative_bindings_generator") (v "0.2.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.3") (d #t) (k 0)))) (h "14if1mqz8154vds6kczlgygfi2gvbh4c9bwa2ny3vnazmzf9slic")))

(define-public crate-gdnative_bindings_generator-0.3.0 (c (n "gdnative_bindings_generator") (v "0.3.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.3") (d #t) (k 0)))) (h "0xn44y5wwldm897xih9q4llzdgidanbrjdgl0d5132afb365wsjb")))

(define-public crate-gdnative_bindings_generator-0.7.0 (c (n "gdnative_bindings_generator") (v "0.7.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.3") (d #t) (k 0)))) (h "1alig2w3jqzn4lgak597k6p8pibfxsqg7m4bip8c5jlwclrvn9va")))

(define-public crate-gdnative_bindings_generator-0.8.0 (c (n "gdnative_bindings_generator") (v "0.8.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.3") (d #t) (k 0)))) (h "08vqglsm62mdp0f9dnybag8pcdfz474knx07305hb71dj86va7c4")))

(define-public crate-gdnative_bindings_generator-0.8.1 (c (n "gdnative_bindings_generator") (v "0.8.1") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "serde") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_derive") (r "^1.0.15") (d #t) (k 0)) (d (n "serde_json") (r "^1.0.3") (d #t) (k 0)))) (h "1vqar1189i15m0ymfcqfh0h5glbzp9gnznsjlwyp27152h1smr2k")))

(define-public crate-gdnative_bindings_generator-0.9.0-preview.0 (c (n "gdnative_bindings_generator") (v "0.9.0-preview.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "miniserde") (r "=0.1.13") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0.6") (d #t) (k 0)) (d (n "quote") (r "^1.0.2") (d #t) (k 0)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)))) (h "041k8g7jf11wrsw03zb6dgxxzm9ncbskc01iffdkylz76am76sdw") (f (quote (("debug"))))))

(define-public crate-gdnative_bindings_generator-0.9.0 (c (n "gdnative_bindings_generator") (v "0.9.0") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "miniserde") (r "=0.1.13") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0.6") (d #t) (k 0)) (d (n "quote") (r "^1.0.2") (d #t) (k 0)) (d (n "roxmltree") (r "^0.13.0") (d #t) (k 0)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)))) (h "1m9r0xn795h57j5a40h3zn7m8yxlkx4d7smgnfmh2czp81v9l824") (f (quote (("debug"))))))

(define-public crate-gdnative_bindings_generator-0.9.1 (c (n "gdnative_bindings_generator") (v "0.9.1") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "miniserde") (r "=0.1.13") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0.6") (d #t) (k 0)) (d (n "quote") (r "^1.0.2") (d #t) (k 0)) (d (n "roxmltree") (r "^0.13.0") (d #t) (k 0)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)))) (h "0x0cagrjsswss6dgfrwn2zyd94w55hxmrbm002mjwlri57c67zl3") (f (quote (("debug"))))))

(define-public crate-gdnative_bindings_generator-0.9.2 (c (n "gdnative_bindings_generator") (v "0.9.2") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "miniserde") (r "=0.1.13") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0.6") (d #t) (k 0)) (d (n "quote") (r "^1.0.2") (d #t) (k 0)) (d (n "roxmltree") (r "^0.14.0") (d #t) (k 0)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.7") (d #t) (k 0)))) (h "1v39f4v8qxp66vfi6ymnbh3wfdngjp11qr2r5fjdmaf3lg93ai6s") (f (quote (("debug")))) (y #t)))

(define-public crate-gdnative_bindings_generator-0.9.3 (c (n "gdnative_bindings_generator") (v "0.9.3") (d (list (d (n "heck") (r "^0.3.0") (d #t) (k 0)) (d (n "miniserde") (r "=0.1.13") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0.6") (d #t) (k 0)) (d (n "quote") (r "^1.0.2") (d #t) (k 0)) (d (n "roxmltree") (r "^0.14.0") (d #t) (k 0)) (d (n "syn") (r "^1.0") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.7") (d #t) (k 0)))) (h "14cv97j27agy9w1g3djhf4rqdv91nc0qlgv3jic48n4yni503xhf") (f (quote (("debug"))))))

(define-public crate-gdnative_bindings_generator-0.10.0-rc.0 (c (n "gdnative_bindings_generator") (v "0.10.0-rc.0") (d (list (d (n "heck") (r "^0.4.0") (d #t) (k 0)) (d (n "memchr") (r "^2.4.1") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.15") (d #t) (k 0)) (d (n "proc-macro2") (r "^1.0.30") (d #t) (k 0)) (d (n "quote") (r "^1.0.10") (d #t) (k 0)) (d (n "regex") (r "^1.5.4") (d #t) (k 0)) (d (n "roxmltree") (r "^0.14.1") (d #t) (k 0)) (d (n "syn") (r "^1.0.80") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.7") (d #t) (k 0)) (d (n "which") (r "^4.2.2") (o #t) (d #t) (k 0)))) (h "05pkxfg03y0avkwqmgbz0wldkwc7rjdsp6624lqnzm81gcjc2sr9") (f (quote (("debug") ("custom-godot" "which"))))))

(define-public crate-gdnative_bindings_generator-0.10.0 (c (n "gdnative_bindings_generator") (v "0.10.0") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "memchr") (r "^2") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.10") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.14") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.5") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "1gljnz7c3vgciq12kcyx897158skc2r7cvg9xxcjnq9376vfp85h") (f (quote (("debug") ("custom-godot" "which")))) (r "1.56")))

(define-public crate-gdnative_bindings_generator-0.10.1 (c (n "gdnative_bindings_generator") (v "0.10.1") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.16") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.15") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.5") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "1w7jbvlni3nhinzmqx40ifbfgabp486cqxg7jjnb32870qzzghs5") (f (quote (("debug") ("custom-godot" "which")))) (r "1.56")))

(define-public crate-gdnative_bindings_generator-0.10.2 (c (n "gdnative_bindings_generator") (v "0.10.2") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.16") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.15") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.5") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "1zw4lnf6402hy7cj14c4qllk00m30a2rwwi66fqin54xas3mp4rl") (f (quote (("debug") ("custom-godot" "which")))) (r "1.56")))

(define-public crate-gdnative_bindings_generator-0.11.0 (c (n "gdnative_bindings_generator") (v "0.11.0") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.16") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.15") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.5") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "112fvjyzqrmc3my7gmn1m9745kgdhf9ldblz1cvf7zi8a44qhcsi") (f (quote (("debug") ("custom-godot" "which")))) (r "1.63")))

(define-public crate-gdnative_bindings_generator-0.11.1 (c (n "gdnative_bindings_generator") (v "0.11.1") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.16") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.16") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.5") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "02gv5d139drx1svjzrxf19vsbx1xzvrqqk47bd3hlkxhv31p9sac") (f (quote (("ptrcall") ("debug") ("custom-godot" "which")))) (r "1.63")))

(define-public crate-gdnative_bindings_generator-0.11.2 (c (n "gdnative_bindings_generator") (v "0.11.2") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.16") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.16") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.1.5") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "0prrnsgvywckrswy0gizh96p1x6w551lfabmvkcpsqm2qq0fj74x") (f (quote (("ptrcall") ("debug") ("custom-godot" "which")))) (r "1.63")))

(define-public crate-gdnative_bindings_generator-0.11.3 (c (n "gdnative_bindings_generator") (v "0.11.3") (d (list (d (n "heck") (r "^0.4") (d #t) (k 0)) (d (n "miniserde") (r "^0.1.16") (d #t) (k 0)) (d (n "proc-macro2") (r "^1") (d #t) (k 0)) (d (n "quote") (r "^1") (d #t) (k 0)) (d (n "regex") (r "^1.5.5") (f (quote ("std"))) (k 0)) (d (n "roxmltree") (r "^0.17") (d #t) (k 0)) (d (n "syn") (r "^1") (f (quote ("full" "extra-traits" "visit"))) (d #t) (k 0)) (d (n "unindent") (r "^0.2.0") (d #t) (k 0)) (d (n "which") (r "^4") (o #t) (d #t) (k 0)))) (h "18ip4yy73a7ng1d91np4cgbif2s6a430xsd1dw7pmy2xhsp0032z") (f (quote (("ptrcall") ("debug") ("custom-godot" "which")))) (r "1.63")))

